// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/yama6a/codarr/internal/promote"
	"sync"
)

// Ensure, that ProberMock does implement promote.Prober.
// If this is not the case, regenerate this file with moq.
var _ promote.Prober = &ProberMock{}

// ProberMock is a mock implementation of promote.Prober.
//
//	func TestSomethingThatUsesProber(t *testing.T) {
//
//		// make and configure a mocked promote.Prober
//		mockedProber := &ProberMock{
//			ProbeFunc: func(ctx context.Context, path string) (promote.Output, error) {
//				panic("mock out the Probe method")
//			},
//		}
//
//		// use mockedProber in code that requires promote.Prober
//		// and then make assertions.
//
//	}
type ProberMock struct {
	// ProbeFunc mocks the Probe method.
	ProbeFunc func(ctx context.Context, path string) (promote.Output, error)

	// calls tracks calls to the methods.
	calls struct {
		// Probe holds details about calls to the Probe method.
		Probe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
	}
	lockProbe sync.RWMutex
}

// Probe calls ProbeFunc.
func (mock *ProberMock) Probe(ctx context.Context, path string) (promote.Output, error) {
	if mock.ProbeFunc == nil {
		panic("ProberMock.ProbeFunc: method is nil but Prober.Probe was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockProbe.Lock()
	mock.calls.Probe = append(mock.calls.Probe, callInfo)
	mock.lockProbe.Unlock()
	return mock.ProbeFunc(ctx, path)
}

// ProbeCalls gets all the calls that were made to Probe.
// Check the length with:
//
//	len(mockedProber.ProbeCalls())
func (mock *ProberMock) ProbeCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockProbe.RLock()
	calls = mock.calls.Probe
	mock.lockProbe.RUnlock()
	return calls
}

// Ensure, that StreamGuardMock does implement promote.StreamGuard.
// If this is not the case, regenerate this file with moq.
var _ promote.StreamGuard = &StreamGuardMock{}

// StreamGuardMock is a mock implementation of promote.StreamGuard.
//
//	func TestSomethingThatUsesStreamGuard(t *testing.T) {
//
//		// make and configure a mocked promote.StreamGuard
//		mockedStreamGuard := &StreamGuardMock{
//			IsStreamingFunc: func(ctx context.Context, path string) (bool, string, error) {
//				panic("mock out the IsStreaming method")
//			},
//		}
//
//		// use mockedStreamGuard in code that requires promote.StreamGuard
//		// and then make assertions.
//
//	}
type StreamGuardMock struct {
	// IsStreamingFunc mocks the IsStreaming method.
	IsStreamingFunc func(ctx context.Context, path string) (bool, string, error)

	// calls tracks calls to the methods.
	calls struct {
		// IsStreaming holds details about calls to the IsStreaming method.
		IsStreaming []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
	}
	lockIsStreaming sync.RWMutex
}

// IsStreaming calls IsStreamingFunc.
func (mock *StreamGuardMock) IsStreaming(ctx context.Context, path string) (bool, string, error) {
	if mock.IsStreamingFunc == nil {
		panic("StreamGuardMock.IsStreamingFunc: method is nil but StreamGuard.IsStreaming was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockIsStreaming.Lock()
	mock.calls.IsStreaming = append(mock.calls.IsStreaming, callInfo)
	mock.lockIsStreaming.Unlock()
	return mock.IsStreamingFunc(ctx, path)
}

// IsStreamingCalls gets all the calls that were made to IsStreaming.
// Check the length with:
//
//	len(mockedStreamGuard.IsStreamingCalls())
func (mock *StreamGuardMock) IsStreamingCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockIsStreaming.RLock()
	calls = mock.calls.IsStreaming
	mock.lockIsStreaming.RUnlock()
	return calls
}

// Ensure, that FingerprinterMock does implement promote.Fingerprinter.
// If this is not the case, regenerate this file with moq.
var _ promote.Fingerprinter = &FingerprinterMock{}

// FingerprinterMock is a mock implementation of promote.Fingerprinter.
//
//	func TestSomethingThatUsesFingerprinter(t *testing.T) {
//
//		// make and configure a mocked promote.Fingerprinter
//		mockedFingerprinter := &FingerprinterMock{
//			FullFunc: func(path string) (string, error) {
//				panic("mock out the Full method")
//			},
//			SparseFunc: func(path string) (string, error) {
//				panic("mock out the Sparse method")
//			},
//		}
//
//		// use mockedFingerprinter in code that requires promote.Fingerprinter
//		// and then make assertions.
//
//	}
type FingerprinterMock struct {
	// FullFunc mocks the Full method.
	FullFunc func(path string) (string, error)

	// SparseFunc mocks the Sparse method.
	SparseFunc func(path string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Full holds details about calls to the Full method.
		Full []struct {
			// Path is the path argument value.
			Path string
		}
		// Sparse holds details about calls to the Sparse method.
		Sparse []struct {
			// Path is the path argument value.
			Path string
		}
	}
	lockFull   sync.RWMutex
	lockSparse sync.RWMutex
}

// Full calls FullFunc.
func (mock *FingerprinterMock) Full(path string) (string, error) {
	if mock.FullFunc == nil {
		panic("FingerprinterMock.FullFunc: method is nil but Fingerprinter.Full was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockFull.Lock()
	mock.calls.Full = append(mock.calls.Full, callInfo)
	mock.lockFull.Unlock()
	return mock.FullFunc(path)
}

// FullCalls gets all the calls that were made to Full.
// Check the length with:
//
//	len(mockedFingerprinter.FullCalls())
func (mock *FingerprinterMock) FullCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockFull.RLock()
	calls = mock.calls.Full
	mock.lockFull.RUnlock()
	return calls
}

// Sparse calls SparseFunc.
func (mock *FingerprinterMock) Sparse(path string) (string, error) {
	if mock.SparseFunc == nil {
		panic("FingerprinterMock.SparseFunc: method is nil but Fingerprinter.Sparse was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockSparse.Lock()
	mock.calls.Sparse = append(mock.calls.Sparse, callInfo)
	mock.lockSparse.Unlock()
	return mock.SparseFunc(path)
}

// SparseCalls gets all the calls that were made to Sparse.
// Check the length with:
//
//	len(mockedFingerprinter.SparseCalls())
func (mock *FingerprinterMock) SparseCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockSparse.RLock()
	calls = mock.calls.Sparse
	mock.lockSparse.RUnlock()
	return calls
}

// Ensure, that NotifierMock does implement promote.Notifier.
// If this is not the case, regenerate this file with moq.
var _ promote.Notifier = &NotifierMock{}

// NotifierMock is a mock implementation of promote.Notifier.
//
//	func TestSomethingThatUsesNotifier(t *testing.T) {
//
//		// make and configure a mocked promote.Notifier
//		mockedNotifier := &NotifierMock{
//			NotifyPromotedFunc: func(ctx context.Context, path string) error {
//				panic("mock out the NotifyPromoted method")
//			},
//		}
//
//		// use mockedNotifier in code that requires promote.Notifier
//		// and then make assertions.
//
//	}
type NotifierMock struct {
	// NotifyPromotedFunc mocks the NotifyPromoted method.
	NotifyPromotedFunc func(ctx context.Context, path string) error

	// calls tracks calls to the methods.
	calls struct {
		// NotifyPromoted holds details about calls to the NotifyPromoted method.
		NotifyPromoted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
	}
	lockNotifyPromoted sync.RWMutex
}

// NotifyPromoted calls NotifyPromotedFunc.
func (mock *NotifierMock) NotifyPromoted(ctx context.Context, path string) error {
	if mock.NotifyPromotedFunc == nil {
		panic("NotifierMock.NotifyPromotedFunc: method is nil but Notifier.NotifyPromoted was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockNotifyPromoted.Lock()
	mock.calls.NotifyPromoted = append(mock.calls.NotifyPromoted, callInfo)
	mock.lockNotifyPromoted.Unlock()
	return mock.NotifyPromotedFunc(ctx, path)
}

// NotifyPromotedCalls gets all the calls that were made to NotifyPromoted.
// Check the length with:
//
//	len(mockedNotifier.NotifyPromotedCalls())
func (mock *NotifierMock) NotifyPromotedCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockNotifyPromoted.RLock()
	calls = mock.calls.NotifyPromoted
	mock.lockNotifyPromoted.RUnlock()
	return calls
}

// Ensure, that CopierMock does implement promote.Copier.
// If this is not the case, regenerate this file with moq.
var _ promote.Copier = &CopierMock{}

// CopierMock is a mock implementation of promote.Copier.
//
//	func TestSomethingThatUsesCopier(t *testing.T) {
//
//		// make and configure a mocked promote.Copier
//		mockedCopier := &CopierMock{
//			CopyFunc: func(ctx context.Context, src string, dst string) (int64, error) {
//				panic("mock out the Copy method")
//			},
//		}
//
//		// use mockedCopier in code that requires promote.Copier
//		// and then make assertions.
//
//	}
type CopierMock struct {
	// CopyFunc mocks the Copy method.
	CopyFunc func(ctx context.Context, src string, dst string) (int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// Copy holds details about calls to the Copy method.
		Copy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Src is the src argument value.
			Src string
			// Dst is the dst argument value.
			Dst string
		}
	}
	lockCopy sync.RWMutex
}

// Copy calls CopyFunc.
func (mock *CopierMock) Copy(ctx context.Context, src string, dst string) (int64, error) {
	if mock.CopyFunc == nil {
		panic("CopierMock.CopyFunc: method is nil but Copier.Copy was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Src string
		Dst string
	}{
		Ctx: ctx,
		Src: src,
		Dst: dst,
	}
	mock.lockCopy.Lock()
	mock.calls.Copy = append(mock.calls.Copy, callInfo)
	mock.lockCopy.Unlock()
	return mock.CopyFunc(ctx, src, dst)
}

// CopyCalls gets all the calls that were made to Copy.
// Check the length with:
//
//	len(mockedCopier.CopyCalls())
func (mock *CopierMock) CopyCalls() []struct {
	Ctx context.Context
	Src string
	Dst string
} {
	var calls []struct {
		Ctx context.Context
		Src string
		Dst string
	}
	mock.lockCopy.RLock()
	calls = mock.calls.Copy
	mock.lockCopy.RUnlock()
	return calls
}
