// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/yama6a/codarr/internal/pkg/domain"
	"github.com/yama6a/codarr/internal/pkg/store"
	"sync"
	"time"
)

// Ensure, that StoreMock does implement store.Store.
// If this is not the case, regenerate this file with moq.
var _ store.Store = &StoreMock{}

// StoreMock is a mock implementation of store.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked store.Store
//		mockedStore := &StoreMock{
//			ActiveJobForMediaFunc: func(ctx context.Context, mediaFileID int64) (domain.Job, bool, error) {
//				panic("mock out the ActiveJobForMedia method")
//			},
//			AppendEventFunc: func(ctx context.Context, e domain.Event) (int64, error) {
//				panic("mock out the AppendEvent method")
//			},
//			CancelJobFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the CancelJob method")
//			},
//			ClaimNextJobFunc: func(ctx context.Context) (domain.Job, bool, error) {
//				panic("mock out the ClaimNextJob method")
//			},
//			CountJobsByStateFunc: func(ctx context.Context) (map[domain.JobState]int, error) {
//				panic("mock out the CountJobsByState method")
//			},
//			CountMediaByPlanKindFunc: func(ctx context.Context) (map[domain.Kind]int, error) {
//				panic("mock out the CountMediaByPlanKind method")
//			},
//			CountMediaByStatusFunc: func(ctx context.Context) (map[domain.MediaStatus]int, error) {
//				panic("mock out the CountMediaByStatus method")
//			},
//			CreateArrInstanceFunc: func(ctx context.Context, a domain.ArrInstance) (domain.ArrInstance, error) {
//				panic("mock out the CreateArrInstance method")
//			},
//			CreateRootFunc: func(ctx context.Context, r domain.Root) (domain.Root, error) {
//				panic("mock out the CreateRoot method")
//			},
//			DeleteArrInstanceFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the DeleteArrInstance method")
//			},
//			DeleteRootFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the DeleteRoot method")
//			},
//			EnqueueJobFunc: func(ctx context.Context, j domain.Job) (domain.Job, bool, error) {
//				panic("mock out the EnqueueJob method")
//			},
//			EnsureSettingsFunc: func(ctx context.Context, defaults domain.Settings) error {
//				panic("mock out the EnsureSettings method")
//			},
//			FailJobFunc: func(ctx context.Context, id int64, code domain.FailureCode, message string, stderrTail string) error {
//				panic("mock out the FailJob method")
//			},
//			GetArrInstanceFunc: func(ctx context.Context, id int64) (domain.ArrInstance, error) {
//				panic("mock out the GetArrInstance method")
//			},
//			GetArrInstanceByWebhookIDFunc: func(ctx context.Context, webhookID string) (domain.ArrInstance, error) {
//				panic("mock out the GetArrInstanceByWebhookID method")
//			},
//			GetJobFunc: func(ctx context.Context, id int64) (domain.Job, error) {
//				panic("mock out the GetJob method")
//			},
//			GetMediaFileFunc: func(ctx context.Context, id int64) (domain.MediaFile, error) {
//				panic("mock out the GetMediaFile method")
//			},
//			GetMediaFileByPathFunc: func(ctx context.Context, path string) (domain.MediaFile, error) {
//				panic("mock out the GetMediaFileByPath method")
//			},
//			GetPlexConfigFunc: func(ctx context.Context) (domain.PlexConfig, error) {
//				panic("mock out the GetPlexConfig method")
//			},
//			GetRootFunc: func(ctx context.Context, id int64) (domain.Root, error) {
//				panic("mock out the GetRoot method")
//			},
//			GetSettingsFunc: func(ctx context.Context) (domain.Settings, error) {
//				panic("mock out the GetSettings method")
//			},
//			GetThroughputStatFunc: func(ctx context.Context, kind domain.Kind, encoder string, resolution string) (domain.ThroughputStat, error) {
//				panic("mock out the GetThroughputStat method")
//			},
//			ListArrInstancesFunc: func(ctx context.Context) ([]domain.ArrInstance, error) {
//				panic("mock out the ListArrInstances method")
//			},
//			ListArrPathMappingsFunc: func(ctx context.Context, arrInstanceID int64) ([]domain.PathMapping, error) {
//				panic("mock out the ListArrPathMappings method")
//			},
//			ListEventsFunc: func(ctx context.Context, f store.EventFilter) ([]domain.Event, error) {
//				panic("mock out the ListEvents method")
//			},
//			ListHWCapabilitiesFunc: func(ctx context.Context) ([]domain.HWCapability, error) {
//				panic("mock out the ListHWCapabilities method")
//			},
//			ListJobsFunc: func(ctx context.Context, f store.JobFilter) ([]domain.Job, int, error) {
//				panic("mock out the ListJobs method")
//			},
//			ListMediaFilesFunc: func(ctx context.Context, f store.MediaFilter) ([]domain.MediaFile, int, error) {
//				panic("mock out the ListMediaFiles method")
//			},
//			ListMediaStatsByRootFunc: func(ctx context.Context, rootID int64) ([]store.MediaStat, error) {
//				panic("mock out the ListMediaStatsByRoot method")
//			},
//			ListPlexPathMappingsFunc: func(ctx context.Context) ([]domain.PathMapping, error) {
//				panic("mock out the ListPlexPathMappings method")
//			},
//			ListRootsFunc: func(ctx context.Context) ([]domain.Root, error) {
//				panic("mock out the ListRoots method")
//			},
//			ListThroughputStatsFunc: func(ctx context.Context) ([]domain.ThroughputStat, error) {
//				panic("mock out the ListThroughputStats method")
//			},
//			MarkMediaMissingFunc: func(ctx context.Context, ids []int64) (int64, error) {
//				panic("mock out the MarkMediaMissing method")
//			},
//			PruneEventsFunc: func(ctx context.Context, now time.Time) (int64, error) {
//				panic("mock out the PruneEvents method")
//			},
//			RecordPromotionFunc: func(ctx context.Context, u store.PromotionUpdate) error {
//				panic("mock out the RecordPromotion method")
//			},
//			ReplaceArrPathMappingsFunc: func(ctx context.Context, arrInstanceID int64, m []domain.PathMapping) error {
//				panic("mock out the ReplaceArrPathMappings method")
//			},
//			ReplaceHWCapabilitiesFunc: func(ctx context.Context, caps []domain.HWCapability) error {
//				panic("mock out the ReplaceHWCapabilities method")
//			},
//			ReplacePlexPathMappingsFunc: func(ctx context.Context, m []domain.PathMapping) error {
//				panic("mock out the ReplacePlexPathMappings method")
//			},
//			RequeueInterruptedJobFunc: func(ctx context.Context, id int64) (store.SweepResult, error) {
//				panic("mock out the RequeueInterruptedJob method")
//			},
//			RestartJobFunc: func(ctx context.Context, id int64) (domain.Job, error) {
//				panic("mock out the RestartJob method")
//			},
//			SetArrTestResultFunc: func(ctx context.Context, id int64, at time.Time, result string) error {
//				panic("mock out the SetArrTestResult method")
//			},
//			SetJobBlockedByFunc: func(ctx context.Context, id int64, blockedBy string) error {
//				panic("mock out the SetJobBlockedBy method")
//			},
//			SetJobStateFunc: func(ctx context.Context, id int64, state domain.JobState) error {
//				panic("mock out the SetJobState method")
//			},
//			SetMediaIgnoredFunc: func(ctx context.Context, id int64, ignored bool) error {
//				panic("mock out the SetMediaIgnored method")
//			},
//			SetMediaIntegrityFunc: func(ctx context.Context, id int64, fingerprint string, fullHash string, at time.Time) error {
//				panic("mock out the SetMediaIntegrity method")
//			},
//			SetMediaStatusFunc: func(ctx context.Context, id int64, status domain.MediaStatus, lastError string) error {
//				panic("mock out the SetMediaStatus method")
//			},
//			SetPlexTestResultFunc: func(ctx context.Context, at time.Time, result string) error {
//				panic("mock out the SetPlexTestResult method")
//			},
//			SetRootEnabledFunc: func(ctx context.Context, id int64, enabled bool) error {
//				panic("mock out the SetRootEnabled method")
//			},
//			StatsFunc: func(ctx context.Context) (store.Stats, error) {
//				panic("mock out the Stats method")
//			},
//			SweepInterruptedJobsFunc: func(ctx context.Context) ([]store.SweepResult, error) {
//				panic("mock out the SweepInterruptedJobs method")
//			},
//			UpdateArrInstanceFunc: func(ctx context.Context, a domain.ArrInstance) error {
//				panic("mock out the UpdateArrInstance method")
//			},
//			UpdateJobExecutionFunc: func(ctx context.Context, u store.ExecutionUpdate) error {
//				panic("mock out the UpdateJobExecution method")
//			},
//			UpdateJobProgressFunc: func(ctx context.Context, id int64, pct float64, speed float64, estimatedSeconds int) error {
//				panic("mock out the UpdateJobProgress method")
//			},
//			UpdateJobTransformFunc: func(ctx context.Context, id int64, t domain.TransformRecord) error {
//				panic("mock out the UpdateJobTransform method")
//			},
//			UpdateMediaAnalysisFunc: func(ctx context.Context, u store.AnalysisUpdate) error {
//				panic("mock out the UpdateMediaAnalysis method")
//			},
//			UpdatePlexConfigFunc: func(ctx context.Context, c domain.PlexConfig) error {
//				panic("mock out the UpdatePlexConfig method")
//			},
//			UpdateSettingsFunc: func(ctx context.Context, s domain.Settings) error {
//				panic("mock out the UpdateSettings method")
//			},
//			UpsertMediaFileFunc: func(ctx context.Context, m domain.MediaFile) (domain.MediaFile, error) {
//				panic("mock out the UpsertMediaFile method")
//			},
//			UpsertThroughputStatFunc: func(ctx context.Context, s domain.ThroughputStat) error {
//				panic("mock out the UpsertThroughputStat method")
//			},
//		}
//
//		// use mockedStore in code that requires store.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// ActiveJobForMediaFunc mocks the ActiveJobForMedia method.
	ActiveJobForMediaFunc func(ctx context.Context, mediaFileID int64) (domain.Job, bool, error)

	// AppendEventFunc mocks the AppendEvent method.
	AppendEventFunc func(ctx context.Context, e domain.Event) (int64, error)

	// CancelJobFunc mocks the CancelJob method.
	CancelJobFunc func(ctx context.Context, id int64) error

	// ClaimNextJobFunc mocks the ClaimNextJob method.
	ClaimNextJobFunc func(ctx context.Context) (domain.Job, bool, error)

	// CountJobsByStateFunc mocks the CountJobsByState method.
	CountJobsByStateFunc func(ctx context.Context) (map[domain.JobState]int, error)

	// CountMediaByPlanKindFunc mocks the CountMediaByPlanKind method.
	CountMediaByPlanKindFunc func(ctx context.Context) (map[domain.Kind]int, error)

	// CountMediaByStatusFunc mocks the CountMediaByStatus method.
	CountMediaByStatusFunc func(ctx context.Context) (map[domain.MediaStatus]int, error)

	// CreateArrInstanceFunc mocks the CreateArrInstance method.
	CreateArrInstanceFunc func(ctx context.Context, a domain.ArrInstance) (domain.ArrInstance, error)

	// CreateRootFunc mocks the CreateRoot method.
	CreateRootFunc func(ctx context.Context, r domain.Root) (domain.Root, error)

	// DeleteArrInstanceFunc mocks the DeleteArrInstance method.
	DeleteArrInstanceFunc func(ctx context.Context, id int64) error

	// DeleteRootFunc mocks the DeleteRoot method.
	DeleteRootFunc func(ctx context.Context, id int64) error

	// EnqueueJobFunc mocks the EnqueueJob method.
	EnqueueJobFunc func(ctx context.Context, j domain.Job) (domain.Job, bool, error)

	// EnsureSettingsFunc mocks the EnsureSettings method.
	EnsureSettingsFunc func(ctx context.Context, defaults domain.Settings) error

	// FailJobFunc mocks the FailJob method.
	FailJobFunc func(ctx context.Context, id int64, code domain.FailureCode, message string, stderrTail string) error

	// GetArrInstanceFunc mocks the GetArrInstance method.
	GetArrInstanceFunc func(ctx context.Context, id int64) (domain.ArrInstance, error)

	// GetArrInstanceByWebhookIDFunc mocks the GetArrInstanceByWebhookID method.
	GetArrInstanceByWebhookIDFunc func(ctx context.Context, webhookID string) (domain.ArrInstance, error)

	// GetJobFunc mocks the GetJob method.
	GetJobFunc func(ctx context.Context, id int64) (domain.Job, error)

	// GetMediaFileFunc mocks the GetMediaFile method.
	GetMediaFileFunc func(ctx context.Context, id int64) (domain.MediaFile, error)

	// GetMediaFileByPathFunc mocks the GetMediaFileByPath method.
	GetMediaFileByPathFunc func(ctx context.Context, path string) (domain.MediaFile, error)

	// GetPlexConfigFunc mocks the GetPlexConfig method.
	GetPlexConfigFunc func(ctx context.Context) (domain.PlexConfig, error)

	// GetRootFunc mocks the GetRoot method.
	GetRootFunc func(ctx context.Context, id int64) (domain.Root, error)

	// GetSettingsFunc mocks the GetSettings method.
	GetSettingsFunc func(ctx context.Context) (domain.Settings, error)

	// GetThroughputStatFunc mocks the GetThroughputStat method.
	GetThroughputStatFunc func(ctx context.Context, kind domain.Kind, encoder string, resolution string) (domain.ThroughputStat, error)

	// ListArrInstancesFunc mocks the ListArrInstances method.
	ListArrInstancesFunc func(ctx context.Context) ([]domain.ArrInstance, error)

	// ListArrPathMappingsFunc mocks the ListArrPathMappings method.
	ListArrPathMappingsFunc func(ctx context.Context, arrInstanceID int64) ([]domain.PathMapping, error)

	// ListEventsFunc mocks the ListEvents method.
	ListEventsFunc func(ctx context.Context, f store.EventFilter) ([]domain.Event, error)

	// ListHWCapabilitiesFunc mocks the ListHWCapabilities method.
	ListHWCapabilitiesFunc func(ctx context.Context) ([]domain.HWCapability, error)

	// ListJobsFunc mocks the ListJobs method.
	ListJobsFunc func(ctx context.Context, f store.JobFilter) ([]domain.Job, int, error)

	// ListMediaFilesFunc mocks the ListMediaFiles method.
	ListMediaFilesFunc func(ctx context.Context, f store.MediaFilter) ([]domain.MediaFile, int, error)

	// ListMediaStatsByRootFunc mocks the ListMediaStatsByRoot method.
	ListMediaStatsByRootFunc func(ctx context.Context, rootID int64) ([]store.MediaStat, error)

	// ListPlexPathMappingsFunc mocks the ListPlexPathMappings method.
	ListPlexPathMappingsFunc func(ctx context.Context) ([]domain.PathMapping, error)

	// ListRootsFunc mocks the ListRoots method.
	ListRootsFunc func(ctx context.Context) ([]domain.Root, error)

	// ListThroughputStatsFunc mocks the ListThroughputStats method.
	ListThroughputStatsFunc func(ctx context.Context) ([]domain.ThroughputStat, error)

	// MarkMediaMissingFunc mocks the MarkMediaMissing method.
	MarkMediaMissingFunc func(ctx context.Context, ids []int64) (int64, error)

	// PruneEventsFunc mocks the PruneEvents method.
	PruneEventsFunc func(ctx context.Context, now time.Time) (int64, error)

	// RecordPromotionFunc mocks the RecordPromotion method.
	RecordPromotionFunc func(ctx context.Context, u store.PromotionUpdate) error

	// ReplaceArrPathMappingsFunc mocks the ReplaceArrPathMappings method.
	ReplaceArrPathMappingsFunc func(ctx context.Context, arrInstanceID int64, m []domain.PathMapping) error

	// ReplaceHWCapabilitiesFunc mocks the ReplaceHWCapabilities method.
	ReplaceHWCapabilitiesFunc func(ctx context.Context, caps []domain.HWCapability) error

	// ReplacePlexPathMappingsFunc mocks the ReplacePlexPathMappings method.
	ReplacePlexPathMappingsFunc func(ctx context.Context, m []domain.PathMapping) error

	// RequeueInterruptedJobFunc mocks the RequeueInterruptedJob method.
	RequeueInterruptedJobFunc func(ctx context.Context, id int64) (store.SweepResult, error)

	// RestartJobFunc mocks the RestartJob method.
	RestartJobFunc func(ctx context.Context, id int64) (domain.Job, error)

	// SetArrTestResultFunc mocks the SetArrTestResult method.
	SetArrTestResultFunc func(ctx context.Context, id int64, at time.Time, result string) error

	// SetJobBlockedByFunc mocks the SetJobBlockedBy method.
	SetJobBlockedByFunc func(ctx context.Context, id int64, blockedBy string) error

	// SetJobStateFunc mocks the SetJobState method.
	SetJobStateFunc func(ctx context.Context, id int64, state domain.JobState) error

	// SetMediaIgnoredFunc mocks the SetMediaIgnored method.
	SetMediaIgnoredFunc func(ctx context.Context, id int64, ignored bool) error

	// SetMediaIntegrityFunc mocks the SetMediaIntegrity method.
	SetMediaIntegrityFunc func(ctx context.Context, id int64, fingerprint string, fullHash string, at time.Time) error

	// SetMediaStatusFunc mocks the SetMediaStatus method.
	SetMediaStatusFunc func(ctx context.Context, id int64, status domain.MediaStatus, lastError string) error

	// SetPlexTestResultFunc mocks the SetPlexTestResult method.
	SetPlexTestResultFunc func(ctx context.Context, at time.Time, result string) error

	// SetRootEnabledFunc mocks the SetRootEnabled method.
	SetRootEnabledFunc func(ctx context.Context, id int64, enabled bool) error

	// StatsFunc mocks the Stats method.
	StatsFunc func(ctx context.Context) (store.Stats, error)

	// SweepInterruptedJobsFunc mocks the SweepInterruptedJobs method.
	SweepInterruptedJobsFunc func(ctx context.Context) ([]store.SweepResult, error)

	// UpdateArrInstanceFunc mocks the UpdateArrInstance method.
	UpdateArrInstanceFunc func(ctx context.Context, a domain.ArrInstance) error

	// UpdateJobExecutionFunc mocks the UpdateJobExecution method.
	UpdateJobExecutionFunc func(ctx context.Context, u store.ExecutionUpdate) error

	// UpdateJobProgressFunc mocks the UpdateJobProgress method.
	UpdateJobProgressFunc func(ctx context.Context, id int64, pct float64, speed float64, estimatedSeconds int) error

	// UpdateJobTransformFunc mocks the UpdateJobTransform method.
	UpdateJobTransformFunc func(ctx context.Context, id int64, t domain.TransformRecord) error

	// UpdateMediaAnalysisFunc mocks the UpdateMediaAnalysis method.
	UpdateMediaAnalysisFunc func(ctx context.Context, u store.AnalysisUpdate) error

	// UpdatePlexConfigFunc mocks the UpdatePlexConfig method.
	UpdatePlexConfigFunc func(ctx context.Context, c domain.PlexConfig) error

	// UpdateSettingsFunc mocks the UpdateSettings method.
	UpdateSettingsFunc func(ctx context.Context, s domain.Settings) error

	// UpsertMediaFileFunc mocks the UpsertMediaFile method.
	UpsertMediaFileFunc func(ctx context.Context, m domain.MediaFile) (domain.MediaFile, error)

	// UpsertThroughputStatFunc mocks the UpsertThroughputStat method.
	UpsertThroughputStatFunc func(ctx context.Context, s domain.ThroughputStat) error

	// calls tracks calls to the methods.
	calls struct {
		// ActiveJobForMedia holds details about calls to the ActiveJobForMedia method.
		ActiveJobForMedia []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MediaFileID is the mediaFileID argument value.
			MediaFileID int64
		}
		// AppendEvent holds details about calls to the AppendEvent method.
		AppendEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// E is the e argument value.
			E domain.Event
		}
		// CancelJob holds details about calls to the CancelJob method.
		CancelJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// ClaimNextJob holds details about calls to the ClaimNextJob method.
		ClaimNextJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CountJobsByState holds details about calls to the CountJobsByState method.
		CountJobsByState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CountMediaByPlanKind holds details about calls to the CountMediaByPlanKind method.
		CountMediaByPlanKind []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CountMediaByStatus holds details about calls to the CountMediaByStatus method.
		CountMediaByStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CreateArrInstance holds details about calls to the CreateArrInstance method.
		CreateArrInstance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// A is the a argument value.
			A domain.ArrInstance
		}
		// CreateRoot holds details about calls to the CreateRoot method.
		CreateRoot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R domain.Root
		}
		// DeleteArrInstance holds details about calls to the DeleteArrInstance method.
		DeleteArrInstance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// DeleteRoot holds details about calls to the DeleteRoot method.
		DeleteRoot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// EnqueueJob holds details about calls to the EnqueueJob method.
		EnqueueJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// J is the j argument value.
			J domain.Job
		}
		// EnsureSettings holds details about calls to the EnsureSettings method.
		EnsureSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Defaults is the defaults argument value.
			Defaults domain.Settings
		}
		// FailJob holds details about calls to the FailJob method.
		FailJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Code is the code argument value.
			Code domain.FailureCode
			// Message is the message argument value.
			Message string
			// StderrTail is the stderrTail argument value.
			StderrTail string
		}
		// GetArrInstance holds details about calls to the GetArrInstance method.
		GetArrInstance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetArrInstanceByWebhookID holds details about calls to the GetArrInstanceByWebhookID method.
		GetArrInstanceByWebhookID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WebhookID is the webhookID argument value.
			WebhookID string
		}
		// GetJob holds details about calls to the GetJob method.
		GetJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetMediaFile holds details about calls to the GetMediaFile method.
		GetMediaFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetMediaFileByPath holds details about calls to the GetMediaFileByPath method.
		GetMediaFileByPath []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
		// GetPlexConfig holds details about calls to the GetPlexConfig method.
		GetPlexConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetRoot holds details about calls to the GetRoot method.
		GetRoot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetSettings holds details about calls to the GetSettings method.
		GetSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetThroughputStat holds details about calls to the GetThroughputStat method.
		GetThroughputStat []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Kind is the kind argument value.
			Kind domain.Kind
			// Encoder is the encoder argument value.
			Encoder string
			// Resolution is the resolution argument value.
			Resolution string
		}
		// ListArrInstances holds details about calls to the ListArrInstances method.
		ListArrInstances []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListArrPathMappings holds details about calls to the ListArrPathMappings method.
		ListArrPathMappings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ArrInstanceID is the arrInstanceID argument value.
			ArrInstanceID int64
		}
		// ListEvents holds details about calls to the ListEvents method.
		ListEvents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// F is the f argument value.
			F store.EventFilter
		}
		// ListHWCapabilities holds details about calls to the ListHWCapabilities method.
		ListHWCapabilities []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListJobs holds details about calls to the ListJobs method.
		ListJobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// F is the f argument value.
			F store.JobFilter
		}
		// ListMediaFiles holds details about calls to the ListMediaFiles method.
		ListMediaFiles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// F is the f argument value.
			F store.MediaFilter
		}
		// ListMediaStatsByRoot holds details about calls to the ListMediaStatsByRoot method.
		ListMediaStatsByRoot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RootID is the rootID argument value.
			RootID int64
		}
		// ListPlexPathMappings holds details about calls to the ListPlexPathMappings method.
		ListPlexPathMappings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListRoots holds details about calls to the ListRoots method.
		ListRoots []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListThroughputStats holds details about calls to the ListThroughputStats method.
		ListThroughputStats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// MarkMediaMissing holds details about calls to the MarkMediaMissing method.
		MarkMediaMissing []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ids is the ids argument value.
			Ids []int64
		}
		// PruneEvents holds details about calls to the PruneEvents method.
		PruneEvents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Now is the now argument value.
			Now time.Time
		}
		// RecordPromotion holds details about calls to the RecordPromotion method.
		RecordPromotion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// U is the u argument value.
			U store.PromotionUpdate
		}
		// ReplaceArrPathMappings holds details about calls to the ReplaceArrPathMappings method.
		ReplaceArrPathMappings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ArrInstanceID is the arrInstanceID argument value.
			ArrInstanceID int64
			// M is the m argument value.
			M []domain.PathMapping
		}
		// ReplaceHWCapabilities holds details about calls to the ReplaceHWCapabilities method.
		ReplaceHWCapabilities []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Caps is the caps argument value.
			Caps []domain.HWCapability
		}
		// ReplacePlexPathMappings holds details about calls to the ReplacePlexPathMappings method.
		ReplacePlexPathMappings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// M is the m argument value.
			M []domain.PathMapping
		}
		// RequeueInterruptedJob holds details about calls to the RequeueInterruptedJob method.
		RequeueInterruptedJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// RestartJob holds details about calls to the RestartJob method.
		RestartJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// SetArrTestResult holds details about calls to the SetArrTestResult method.
		SetArrTestResult []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// At is the at argument value.
			At time.Time
			// Result is the result argument value.
			Result string
		}
		// SetJobBlockedBy holds details about calls to the SetJobBlockedBy method.
		SetJobBlockedBy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// BlockedBy is the blockedBy argument value.
			BlockedBy string
		}
		// SetJobState holds details about calls to the SetJobState method.
		SetJobState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// State is the state argument value.
			State domain.JobState
		}
		// SetMediaIgnored holds details about calls to the SetMediaIgnored method.
		SetMediaIgnored []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Ignored is the ignored argument value.
			Ignored bool
		}
		// SetMediaIntegrity holds details about calls to the SetMediaIntegrity method.
		SetMediaIntegrity []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Fingerprint is the fingerprint argument value.
			Fingerprint string
			// FullHash is the fullHash argument value.
			FullHash string
			// At is the at argument value.
			At time.Time
		}
		// SetMediaStatus holds details about calls to the SetMediaStatus method.
		SetMediaStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Status is the status argument value.
			Status domain.MediaStatus
			// LastError is the lastError argument value.
			LastError string
		}
		// SetPlexTestResult holds details about calls to the SetPlexTestResult method.
		SetPlexTestResult []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// At is the at argument value.
			At time.Time
			// Result is the result argument value.
			Result string
		}
		// SetRootEnabled holds details about calls to the SetRootEnabled method.
		SetRootEnabled []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Enabled is the enabled argument value.
			Enabled bool
		}
		// Stats holds details about calls to the Stats method.
		Stats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// SweepInterruptedJobs holds details about calls to the SweepInterruptedJobs method.
		SweepInterruptedJobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdateArrInstance holds details about calls to the UpdateArrInstance method.
		UpdateArrInstance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// A is the a argument value.
			A domain.ArrInstance
		}
		// UpdateJobExecution holds details about calls to the UpdateJobExecution method.
		UpdateJobExecution []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// U is the u argument value.
			U store.ExecutionUpdate
		}
		// UpdateJobProgress holds details about calls to the UpdateJobProgress method.
		UpdateJobProgress []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Pct is the pct argument value.
			Pct float64
			// Speed is the speed argument value.
			Speed float64
			// EstimatedSeconds is the estimatedSeconds argument value.
			EstimatedSeconds int
		}
		// UpdateJobTransform holds details about calls to the UpdateJobTransform method.
		UpdateJobTransform []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// T is the t argument value.
			T domain.TransformRecord
		}
		// UpdateMediaAnalysis holds details about calls to the UpdateMediaAnalysis method.
		UpdateMediaAnalysis []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// U is the u argument value.
			U store.AnalysisUpdate
		}
		// UpdatePlexConfig holds details about calls to the UpdatePlexConfig method.
		UpdatePlexConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// C is the c argument value.
			C domain.PlexConfig
		}
		// UpdateSettings holds details about calls to the UpdateSettings method.
		UpdateSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S domain.Settings
		}
		// UpsertMediaFile holds details about calls to the UpsertMediaFile method.
		UpsertMediaFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// M is the m argument value.
			M domain.MediaFile
		}
		// UpsertThroughputStat holds details about calls to the UpsertThroughputStat method.
		UpsertThroughputStat []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S domain.ThroughputStat
		}
	}
	lockActiveJobForMedia         sync.RWMutex
	lockAppendEvent               sync.RWMutex
	lockCancelJob                 sync.RWMutex
	lockClaimNextJob              sync.RWMutex
	lockCountJobsByState          sync.RWMutex
	lockCountMediaByPlanKind      sync.RWMutex
	lockCountMediaByStatus        sync.RWMutex
	lockCreateArrInstance         sync.RWMutex
	lockCreateRoot                sync.RWMutex
	lockDeleteArrInstance         sync.RWMutex
	lockDeleteRoot                sync.RWMutex
	lockEnqueueJob                sync.RWMutex
	lockEnsureSettings            sync.RWMutex
	lockFailJob                   sync.RWMutex
	lockGetArrInstance            sync.RWMutex
	lockGetArrInstanceByWebhookID sync.RWMutex
	lockGetJob                    sync.RWMutex
	lockGetMediaFile              sync.RWMutex
	lockGetMediaFileByPath        sync.RWMutex
	lockGetPlexConfig             sync.RWMutex
	lockGetRoot                   sync.RWMutex
	lockGetSettings               sync.RWMutex
	lockGetThroughputStat         sync.RWMutex
	lockListArrInstances          sync.RWMutex
	lockListArrPathMappings       sync.RWMutex
	lockListEvents                sync.RWMutex
	lockListHWCapabilities        sync.RWMutex
	lockListJobs                  sync.RWMutex
	lockListMediaFiles            sync.RWMutex
	lockListMediaStatsByRoot      sync.RWMutex
	lockListPlexPathMappings      sync.RWMutex
	lockListRoots                 sync.RWMutex
	lockListThroughputStats       sync.RWMutex
	lockMarkMediaMissing          sync.RWMutex
	lockPruneEvents               sync.RWMutex
	lockRecordPromotion           sync.RWMutex
	lockReplaceArrPathMappings    sync.RWMutex
	lockReplaceHWCapabilities     sync.RWMutex
	lockReplacePlexPathMappings   sync.RWMutex
	lockRequeueInterruptedJob     sync.RWMutex
	lockRestartJob                sync.RWMutex
	lockSetArrTestResult          sync.RWMutex
	lockSetJobBlockedBy           sync.RWMutex
	lockSetJobState               sync.RWMutex
	lockSetMediaIgnored           sync.RWMutex
	lockSetMediaIntegrity         sync.RWMutex
	lockSetMediaStatus            sync.RWMutex
	lockSetPlexTestResult         sync.RWMutex
	lockSetRootEnabled            sync.RWMutex
	lockStats                     sync.RWMutex
	lockSweepInterruptedJobs      sync.RWMutex
	lockUpdateArrInstance         sync.RWMutex
	lockUpdateJobExecution        sync.RWMutex
	lockUpdateJobProgress         sync.RWMutex
	lockUpdateJobTransform        sync.RWMutex
	lockUpdateMediaAnalysis       sync.RWMutex
	lockUpdatePlexConfig          sync.RWMutex
	lockUpdateSettings            sync.RWMutex
	lockUpsertMediaFile           sync.RWMutex
	lockUpsertThroughputStat      sync.RWMutex
}

// ActiveJobForMedia calls ActiveJobForMediaFunc.
func (mock *StoreMock) ActiveJobForMedia(ctx context.Context, mediaFileID int64) (domain.Job, bool, error) {
	if mock.ActiveJobForMediaFunc == nil {
		panic("StoreMock.ActiveJobForMediaFunc: method is nil but Store.ActiveJobForMedia was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		MediaFileID int64
	}{
		Ctx:         ctx,
		MediaFileID: mediaFileID,
	}
	mock.lockActiveJobForMedia.Lock()
	mock.calls.ActiveJobForMedia = append(mock.calls.ActiveJobForMedia, callInfo)
	mock.lockActiveJobForMedia.Unlock()
	return mock.ActiveJobForMediaFunc(ctx, mediaFileID)
}

// ActiveJobForMediaCalls gets all the calls that were made to ActiveJobForMedia.
// Check the length with:
//
//	len(mockedStore.ActiveJobForMediaCalls())
func (mock *StoreMock) ActiveJobForMediaCalls() []struct {
	Ctx         context.Context
	MediaFileID int64
} {
	var calls []struct {
		Ctx         context.Context
		MediaFileID int64
	}
	mock.lockActiveJobForMedia.RLock()
	calls = mock.calls.ActiveJobForMedia
	mock.lockActiveJobForMedia.RUnlock()
	return calls
}

// AppendEvent calls AppendEventFunc.
func (mock *StoreMock) AppendEvent(ctx context.Context, e domain.Event) (int64, error) {
	if mock.AppendEventFunc == nil {
		panic("StoreMock.AppendEventFunc: method is nil but Store.AppendEvent was just called")
	}
	callInfo := struct {
		Ctx context.Context
		E   domain.Event
	}{
		Ctx: ctx,
		E:   e,
	}
	mock.lockAppendEvent.Lock()
	mock.calls.AppendEvent = append(mock.calls.AppendEvent, callInfo)
	mock.lockAppendEvent.Unlock()
	return mock.AppendEventFunc(ctx, e)
}

// AppendEventCalls gets all the calls that were made to AppendEvent.
// Check the length with:
//
//	len(mockedStore.AppendEventCalls())
func (mock *StoreMock) AppendEventCalls() []struct {
	Ctx context.Context
	E   domain.Event
} {
	var calls []struct {
		Ctx context.Context
		E   domain.Event
	}
	mock.lockAppendEvent.RLock()
	calls = mock.calls.AppendEvent
	mock.lockAppendEvent.RUnlock()
	return calls
}

// CancelJob calls CancelJobFunc.
func (mock *StoreMock) CancelJob(ctx context.Context, id int64) error {
	if mock.CancelJobFunc == nil {
		panic("StoreMock.CancelJobFunc: method is nil but Store.CancelJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockCancelJob.Lock()
	mock.calls.CancelJob = append(mock.calls.CancelJob, callInfo)
	mock.lockCancelJob.Unlock()
	return mock.CancelJobFunc(ctx, id)
}

// CancelJobCalls gets all the calls that were made to CancelJob.
// Check the length with:
//
//	len(mockedStore.CancelJobCalls())
func (mock *StoreMock) CancelJobCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockCancelJob.RLock()
	calls = mock.calls.CancelJob
	mock.lockCancelJob.RUnlock()
	return calls
}

// ClaimNextJob calls ClaimNextJobFunc.
func (mock *StoreMock) ClaimNextJob(ctx context.Context) (domain.Job, bool, error) {
	if mock.ClaimNextJobFunc == nil {
		panic("StoreMock.ClaimNextJobFunc: method is nil but Store.ClaimNextJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockClaimNextJob.Lock()
	mock.calls.ClaimNextJob = append(mock.calls.ClaimNextJob, callInfo)
	mock.lockClaimNextJob.Unlock()
	return mock.ClaimNextJobFunc(ctx)
}

// ClaimNextJobCalls gets all the calls that were made to ClaimNextJob.
// Check the length with:
//
//	len(mockedStore.ClaimNextJobCalls())
func (mock *StoreMock) ClaimNextJobCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockClaimNextJob.RLock()
	calls = mock.calls.ClaimNextJob
	mock.lockClaimNextJob.RUnlock()
	return calls
}

// CountJobsByState calls CountJobsByStateFunc.
func (mock *StoreMock) CountJobsByState(ctx context.Context) (map[domain.JobState]int, error) {
	if mock.CountJobsByStateFunc == nil {
		panic("StoreMock.CountJobsByStateFunc: method is nil but Store.CountJobsByState was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCountJobsByState.Lock()
	mock.calls.CountJobsByState = append(mock.calls.CountJobsByState, callInfo)
	mock.lockCountJobsByState.Unlock()
	return mock.CountJobsByStateFunc(ctx)
}

// CountJobsByStateCalls gets all the calls that were made to CountJobsByState.
// Check the length with:
//
//	len(mockedStore.CountJobsByStateCalls())
func (mock *StoreMock) CountJobsByStateCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCountJobsByState.RLock()
	calls = mock.calls.CountJobsByState
	mock.lockCountJobsByState.RUnlock()
	return calls
}

// CountMediaByPlanKind calls CountMediaByPlanKindFunc.
func (mock *StoreMock) CountMediaByPlanKind(ctx context.Context) (map[domain.Kind]int, error) {
	if mock.CountMediaByPlanKindFunc == nil {
		panic("StoreMock.CountMediaByPlanKindFunc: method is nil but Store.CountMediaByPlanKind was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCountMediaByPlanKind.Lock()
	mock.calls.CountMediaByPlanKind = append(mock.calls.CountMediaByPlanKind, callInfo)
	mock.lockCountMediaByPlanKind.Unlock()
	return mock.CountMediaByPlanKindFunc(ctx)
}

// CountMediaByPlanKindCalls gets all the calls that were made to CountMediaByPlanKind.
// Check the length with:
//
//	len(mockedStore.CountMediaByPlanKindCalls())
func (mock *StoreMock) CountMediaByPlanKindCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCountMediaByPlanKind.RLock()
	calls = mock.calls.CountMediaByPlanKind
	mock.lockCountMediaByPlanKind.RUnlock()
	return calls
}

// CountMediaByStatus calls CountMediaByStatusFunc.
func (mock *StoreMock) CountMediaByStatus(ctx context.Context) (map[domain.MediaStatus]int, error) {
	if mock.CountMediaByStatusFunc == nil {
		panic("StoreMock.CountMediaByStatusFunc: method is nil but Store.CountMediaByStatus was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCountMediaByStatus.Lock()
	mock.calls.CountMediaByStatus = append(mock.calls.CountMediaByStatus, callInfo)
	mock.lockCountMediaByStatus.Unlock()
	return mock.CountMediaByStatusFunc(ctx)
}

// CountMediaByStatusCalls gets all the calls that were made to CountMediaByStatus.
// Check the length with:
//
//	len(mockedStore.CountMediaByStatusCalls())
func (mock *StoreMock) CountMediaByStatusCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCountMediaByStatus.RLock()
	calls = mock.calls.CountMediaByStatus
	mock.lockCountMediaByStatus.RUnlock()
	return calls
}

// CreateArrInstance calls CreateArrInstanceFunc.
func (mock *StoreMock) CreateArrInstance(ctx context.Context, a domain.ArrInstance) (domain.ArrInstance, error) {
	if mock.CreateArrInstanceFunc == nil {
		panic("StoreMock.CreateArrInstanceFunc: method is nil but Store.CreateArrInstance was just called")
	}
	callInfo := struct {
		Ctx context.Context
		A   domain.ArrInstance
	}{
		Ctx: ctx,
		A:   a,
	}
	mock.lockCreateArrInstance.Lock()
	mock.calls.CreateArrInstance = append(mock.calls.CreateArrInstance, callInfo)
	mock.lockCreateArrInstance.Unlock()
	return mock.CreateArrInstanceFunc(ctx, a)
}

// CreateArrInstanceCalls gets all the calls that were made to CreateArrInstance.
// Check the length with:
//
//	len(mockedStore.CreateArrInstanceCalls())
func (mock *StoreMock) CreateArrInstanceCalls() []struct {
	Ctx context.Context
	A   domain.ArrInstance
} {
	var calls []struct {
		Ctx context.Context
		A   domain.ArrInstance
	}
	mock.lockCreateArrInstance.RLock()
	calls = mock.calls.CreateArrInstance
	mock.lockCreateArrInstance.RUnlock()
	return calls
}

// CreateRoot calls CreateRootFunc.
func (mock *StoreMock) CreateRoot(ctx context.Context, r domain.Root) (domain.Root, error) {
	if mock.CreateRootFunc == nil {
		panic("StoreMock.CreateRootFunc: method is nil but Store.CreateRoot was just called")
	}
	callInfo := struct {
		Ctx context.Context
		R   domain.Root
	}{
		Ctx: ctx,
		R:   r,
	}
	mock.lockCreateRoot.Lock()
	mock.calls.CreateRoot = append(mock.calls.CreateRoot, callInfo)
	mock.lockCreateRoot.Unlock()
	return mock.CreateRootFunc(ctx, r)
}

// CreateRootCalls gets all the calls that were made to CreateRoot.
// Check the length with:
//
//	len(mockedStore.CreateRootCalls())
func (mock *StoreMock) CreateRootCalls() []struct {
	Ctx context.Context
	R   domain.Root
} {
	var calls []struct {
		Ctx context.Context
		R   domain.Root
	}
	mock.lockCreateRoot.RLock()
	calls = mock.calls.CreateRoot
	mock.lockCreateRoot.RUnlock()
	return calls
}

// DeleteArrInstance calls DeleteArrInstanceFunc.
func (mock *StoreMock) DeleteArrInstance(ctx context.Context, id int64) error {
	if mock.DeleteArrInstanceFunc == nil {
		panic("StoreMock.DeleteArrInstanceFunc: method is nil but Store.DeleteArrInstance was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteArrInstance.Lock()
	mock.calls.DeleteArrInstance = append(mock.calls.DeleteArrInstance, callInfo)
	mock.lockDeleteArrInstance.Unlock()
	return mock.DeleteArrInstanceFunc(ctx, id)
}

// DeleteArrInstanceCalls gets all the calls that were made to DeleteArrInstance.
// Check the length with:
//
//	len(mockedStore.DeleteArrInstanceCalls())
func (mock *StoreMock) DeleteArrInstanceCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDeleteArrInstance.RLock()
	calls = mock.calls.DeleteArrInstance
	mock.lockDeleteArrInstance.RUnlock()
	return calls
}

// DeleteRoot calls DeleteRootFunc.
func (mock *StoreMock) DeleteRoot(ctx context.Context, id int64) error {
	if mock.DeleteRootFunc == nil {
		panic("StoreMock.DeleteRootFunc: method is nil but Store.DeleteRoot was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteRoot.Lock()
	mock.calls.DeleteRoot = append(mock.calls.DeleteRoot, callInfo)
	mock.lockDeleteRoot.Unlock()
	return mock.DeleteRootFunc(ctx, id)
}

// DeleteRootCalls gets all the calls that were made to DeleteRoot.
// Check the length with:
//
//	len(mockedStore.DeleteRootCalls())
func (mock *StoreMock) DeleteRootCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDeleteRoot.RLock()
	calls = mock.calls.DeleteRoot
	mock.lockDeleteRoot.RUnlock()
	return calls
}

// EnqueueJob calls EnqueueJobFunc.
func (mock *StoreMock) EnqueueJob(ctx context.Context, j domain.Job) (domain.Job, bool, error) {
	if mock.EnqueueJobFunc == nil {
		panic("StoreMock.EnqueueJobFunc: method is nil but Store.EnqueueJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		J   domain.Job
	}{
		Ctx: ctx,
		J:   j,
	}
	mock.lockEnqueueJob.Lock()
	mock.calls.EnqueueJob = append(mock.calls.EnqueueJob, callInfo)
	mock.lockEnqueueJob.Unlock()
	return mock.EnqueueJobFunc(ctx, j)
}

// EnqueueJobCalls gets all the calls that were made to EnqueueJob.
// Check the length with:
//
//	len(mockedStore.EnqueueJobCalls())
func (mock *StoreMock) EnqueueJobCalls() []struct {
	Ctx context.Context
	J   domain.Job
} {
	var calls []struct {
		Ctx context.Context
		J   domain.Job
	}
	mock.lockEnqueueJob.RLock()
	calls = mock.calls.EnqueueJob
	mock.lockEnqueueJob.RUnlock()
	return calls
}

// EnsureSettings calls EnsureSettingsFunc.
func (mock *StoreMock) EnsureSettings(ctx context.Context, defaults domain.Settings) error {
	if mock.EnsureSettingsFunc == nil {
		panic("StoreMock.EnsureSettingsFunc: method is nil but Store.EnsureSettings was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Defaults domain.Settings
	}{
		Ctx:      ctx,
		Defaults: defaults,
	}
	mock.lockEnsureSettings.Lock()
	mock.calls.EnsureSettings = append(mock.calls.EnsureSettings, callInfo)
	mock.lockEnsureSettings.Unlock()
	return mock.EnsureSettingsFunc(ctx, defaults)
}

// EnsureSettingsCalls gets all the calls that were made to EnsureSettings.
// Check the length with:
//
//	len(mockedStore.EnsureSettingsCalls())
func (mock *StoreMock) EnsureSettingsCalls() []struct {
	Ctx      context.Context
	Defaults domain.Settings
} {
	var calls []struct {
		Ctx      context.Context
		Defaults domain.Settings
	}
	mock.lockEnsureSettings.RLock()
	calls = mock.calls.EnsureSettings
	mock.lockEnsureSettings.RUnlock()
	return calls
}

// FailJob calls FailJobFunc.
func (mock *StoreMock) FailJob(ctx context.Context, id int64, code domain.FailureCode, message string, stderrTail string) error {
	if mock.FailJobFunc == nil {
		panic("StoreMock.FailJobFunc: method is nil but Store.FailJob was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ID         int64
		Code       domain.FailureCode
		Message    string
		StderrTail string
	}{
		Ctx:        ctx,
		ID:         id,
		Code:       code,
		Message:    message,
		StderrTail: stderrTail,
	}
	mock.lockFailJob.Lock()
	mock.calls.FailJob = append(mock.calls.FailJob, callInfo)
	mock.lockFailJob.Unlock()
	return mock.FailJobFunc(ctx, id, code, message, stderrTail)
}

// FailJobCalls gets all the calls that were made to FailJob.
// Check the length with:
//
//	len(mockedStore.FailJobCalls())
func (mock *StoreMock) FailJobCalls() []struct {
	Ctx        context.Context
	ID         int64
	Code       domain.FailureCode
	Message    string
	StderrTail string
} {
	var calls []struct {
		Ctx        context.Context
		ID         int64
		Code       domain.FailureCode
		Message    string
		StderrTail string
	}
	mock.lockFailJob.RLock()
	calls = mock.calls.FailJob
	mock.lockFailJob.RUnlock()
	return calls
}

// GetArrInstance calls GetArrInstanceFunc.
func (mock *StoreMock) GetArrInstance(ctx context.Context, id int64) (domain.ArrInstance, error) {
	if mock.GetArrInstanceFunc == nil {
		panic("StoreMock.GetArrInstanceFunc: method is nil but Store.GetArrInstance was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetArrInstance.Lock()
	mock.calls.GetArrInstance = append(mock.calls.GetArrInstance, callInfo)
	mock.lockGetArrInstance.Unlock()
	return mock.GetArrInstanceFunc(ctx, id)
}

// GetArrInstanceCalls gets all the calls that were made to GetArrInstance.
// Check the length with:
//
//	len(mockedStore.GetArrInstanceCalls())
func (mock *StoreMock) GetArrInstanceCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetArrInstance.RLock()
	calls = mock.calls.GetArrInstance
	mock.lockGetArrInstance.RUnlock()
	return calls
}

// GetArrInstanceByWebhookID calls GetArrInstanceByWebhookIDFunc.
func (mock *StoreMock) GetArrInstanceByWebhookID(ctx context.Context, webhookID string) (domain.ArrInstance, error) {
	if mock.GetArrInstanceByWebhookIDFunc == nil {
		panic("StoreMock.GetArrInstanceByWebhookIDFunc: method is nil but Store.GetArrInstanceByWebhookID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		WebhookID string
	}{
		Ctx:       ctx,
		WebhookID: webhookID,
	}
	mock.lockGetArrInstanceByWebhookID.Lock()
	mock.calls.GetArrInstanceByWebhookID = append(mock.calls.GetArrInstanceByWebhookID, callInfo)
	mock.lockGetArrInstanceByWebhookID.Unlock()
	return mock.GetArrInstanceByWebhookIDFunc(ctx, webhookID)
}

// GetArrInstanceByWebhookIDCalls gets all the calls that were made to GetArrInstanceByWebhookID.
// Check the length with:
//
//	len(mockedStore.GetArrInstanceByWebhookIDCalls())
func (mock *StoreMock) GetArrInstanceByWebhookIDCalls() []struct {
	Ctx       context.Context
	WebhookID string
} {
	var calls []struct {
		Ctx       context.Context
		WebhookID string
	}
	mock.lockGetArrInstanceByWebhookID.RLock()
	calls = mock.calls.GetArrInstanceByWebhookID
	mock.lockGetArrInstanceByWebhookID.RUnlock()
	return calls
}

// GetJob calls GetJobFunc.
func (mock *StoreMock) GetJob(ctx context.Context, id int64) (domain.Job, error) {
	if mock.GetJobFunc == nil {
		panic("StoreMock.GetJobFunc: method is nil but Store.GetJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetJob.Lock()
	mock.calls.GetJob = append(mock.calls.GetJob, callInfo)
	mock.lockGetJob.Unlock()
	return mock.GetJobFunc(ctx, id)
}

// GetJobCalls gets all the calls that were made to GetJob.
// Check the length with:
//
//	len(mockedStore.GetJobCalls())
func (mock *StoreMock) GetJobCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetJob.RLock()
	calls = mock.calls.GetJob
	mock.lockGetJob.RUnlock()
	return calls
}

// GetMediaFile calls GetMediaFileFunc.
func (mock *StoreMock) GetMediaFile(ctx context.Context, id int64) (domain.MediaFile, error) {
	if mock.GetMediaFileFunc == nil {
		panic("StoreMock.GetMediaFileFunc: method is nil but Store.GetMediaFile was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetMediaFile.Lock()
	mock.calls.GetMediaFile = append(mock.calls.GetMediaFile, callInfo)
	mock.lockGetMediaFile.Unlock()
	return mock.GetMediaFileFunc(ctx, id)
}

// GetMediaFileCalls gets all the calls that were made to GetMediaFile.
// Check the length with:
//
//	len(mockedStore.GetMediaFileCalls())
func (mock *StoreMock) GetMediaFileCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetMediaFile.RLock()
	calls = mock.calls.GetMediaFile
	mock.lockGetMediaFile.RUnlock()
	return calls
}

// GetMediaFileByPath calls GetMediaFileByPathFunc.
func (mock *StoreMock) GetMediaFileByPath(ctx context.Context, path string) (domain.MediaFile, error) {
	if mock.GetMediaFileByPathFunc == nil {
		panic("StoreMock.GetMediaFileByPathFunc: method is nil but Store.GetMediaFileByPath was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockGetMediaFileByPath.Lock()
	mock.calls.GetMediaFileByPath = append(mock.calls.GetMediaFileByPath, callInfo)
	mock.lockGetMediaFileByPath.Unlock()
	return mock.GetMediaFileByPathFunc(ctx, path)
}

// GetMediaFileByPathCalls gets all the calls that were made to GetMediaFileByPath.
// Check the length with:
//
//	len(mockedStore.GetMediaFileByPathCalls())
func (mock *StoreMock) GetMediaFileByPathCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockGetMediaFileByPath.RLock()
	calls = mock.calls.GetMediaFileByPath
	mock.lockGetMediaFileByPath.RUnlock()
	return calls
}

// GetPlexConfig calls GetPlexConfigFunc.
func (mock *StoreMock) GetPlexConfig(ctx context.Context) (domain.PlexConfig, error) {
	if mock.GetPlexConfigFunc == nil {
		panic("StoreMock.GetPlexConfigFunc: method is nil but Store.GetPlexConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetPlexConfig.Lock()
	mock.calls.GetPlexConfig = append(mock.calls.GetPlexConfig, callInfo)
	mock.lockGetPlexConfig.Unlock()
	return mock.GetPlexConfigFunc(ctx)
}

// GetPlexConfigCalls gets all the calls that were made to GetPlexConfig.
// Check the length with:
//
//	len(mockedStore.GetPlexConfigCalls())
func (mock *StoreMock) GetPlexConfigCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetPlexConfig.RLock()
	calls = mock.calls.GetPlexConfig
	mock.lockGetPlexConfig.RUnlock()
	return calls
}

// GetRoot calls GetRootFunc.
func (mock *StoreMock) GetRoot(ctx context.Context, id int64) (domain.Root, error) {
	if mock.GetRootFunc == nil {
		panic("StoreMock.GetRootFunc: method is nil but Store.GetRoot was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetRoot.Lock()
	mock.calls.GetRoot = append(mock.calls.GetRoot, callInfo)
	mock.lockGetRoot.Unlock()
	return mock.GetRootFunc(ctx, id)
}

// GetRootCalls gets all the calls that were made to GetRoot.
// Check the length with:
//
//	len(mockedStore.GetRootCalls())
func (mock *StoreMock) GetRootCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetRoot.RLock()
	calls = mock.calls.GetRoot
	mock.lockGetRoot.RUnlock()
	return calls
}

// GetSettings calls GetSettingsFunc.
func (mock *StoreMock) GetSettings(ctx context.Context) (domain.Settings, error) {
	if mock.GetSettingsFunc == nil {
		panic("StoreMock.GetSettingsFunc: method is nil but Store.GetSettings was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetSettings.Lock()
	mock.calls.GetSettings = append(mock.calls.GetSettings, callInfo)
	mock.lockGetSettings.Unlock()
	return mock.GetSettingsFunc(ctx)
}

// GetSettingsCalls gets all the calls that were made to GetSettings.
// Check the length with:
//
//	len(mockedStore.GetSettingsCalls())
func (mock *StoreMock) GetSettingsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetSettings.RLock()
	calls = mock.calls.GetSettings
	mock.lockGetSettings.RUnlock()
	return calls
}

// GetThroughputStat calls GetThroughputStatFunc.
func (mock *StoreMock) GetThroughputStat(ctx context.Context, kind domain.Kind, encoder string, resolution string) (domain.ThroughputStat, error) {
	if mock.GetThroughputStatFunc == nil {
		panic("StoreMock.GetThroughputStatFunc: method is nil but Store.GetThroughputStat was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Kind       domain.Kind
		Encoder    string
		Resolution string
	}{
		Ctx:        ctx,
		Kind:       kind,
		Encoder:    encoder,
		Resolution: resolution,
	}
	mock.lockGetThroughputStat.Lock()
	mock.calls.GetThroughputStat = append(mock.calls.GetThroughputStat, callInfo)
	mock.lockGetThroughputStat.Unlock()
	return mock.GetThroughputStatFunc(ctx, kind, encoder, resolution)
}

// GetThroughputStatCalls gets all the calls that were made to GetThroughputStat.
// Check the length with:
//
//	len(mockedStore.GetThroughputStatCalls())
func (mock *StoreMock) GetThroughputStatCalls() []struct {
	Ctx        context.Context
	Kind       domain.Kind
	Encoder    string
	Resolution string
} {
	var calls []struct {
		Ctx        context.Context
		Kind       domain.Kind
		Encoder    string
		Resolution string
	}
	mock.lockGetThroughputStat.RLock()
	calls = mock.calls.GetThroughputStat
	mock.lockGetThroughputStat.RUnlock()
	return calls
}

// ListArrInstances calls ListArrInstancesFunc.
func (mock *StoreMock) ListArrInstances(ctx context.Context) ([]domain.ArrInstance, error) {
	if mock.ListArrInstancesFunc == nil {
		panic("StoreMock.ListArrInstancesFunc: method is nil but Store.ListArrInstances was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListArrInstances.Lock()
	mock.calls.ListArrInstances = append(mock.calls.ListArrInstances, callInfo)
	mock.lockListArrInstances.Unlock()
	return mock.ListArrInstancesFunc(ctx)
}

// ListArrInstancesCalls gets all the calls that were made to ListArrInstances.
// Check the length with:
//
//	len(mockedStore.ListArrInstancesCalls())
func (mock *StoreMock) ListArrInstancesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListArrInstances.RLock()
	calls = mock.calls.ListArrInstances
	mock.lockListArrInstances.RUnlock()
	return calls
}

// ListArrPathMappings calls ListArrPathMappingsFunc.
func (mock *StoreMock) ListArrPathMappings(ctx context.Context, arrInstanceID int64) ([]domain.PathMapping, error) {
	if mock.ListArrPathMappingsFunc == nil {
		panic("StoreMock.ListArrPathMappingsFunc: method is nil but Store.ListArrPathMappings was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ArrInstanceID int64
	}{
		Ctx:           ctx,
		ArrInstanceID: arrInstanceID,
	}
	mock.lockListArrPathMappings.Lock()
	mock.calls.ListArrPathMappings = append(mock.calls.ListArrPathMappings, callInfo)
	mock.lockListArrPathMappings.Unlock()
	return mock.ListArrPathMappingsFunc(ctx, arrInstanceID)
}

// ListArrPathMappingsCalls gets all the calls that were made to ListArrPathMappings.
// Check the length with:
//
//	len(mockedStore.ListArrPathMappingsCalls())
func (mock *StoreMock) ListArrPathMappingsCalls() []struct {
	Ctx           context.Context
	ArrInstanceID int64
} {
	var calls []struct {
		Ctx           context.Context
		ArrInstanceID int64
	}
	mock.lockListArrPathMappings.RLock()
	calls = mock.calls.ListArrPathMappings
	mock.lockListArrPathMappings.RUnlock()
	return calls
}

// ListEvents calls ListEventsFunc.
func (mock *StoreMock) ListEvents(ctx context.Context, f store.EventFilter) ([]domain.Event, error) {
	if mock.ListEventsFunc == nil {
		panic("StoreMock.ListEventsFunc: method is nil but Store.ListEvents was just called")
	}
	callInfo := struct {
		Ctx context.Context
		F   store.EventFilter
	}{
		Ctx: ctx,
		F:   f,
	}
	mock.lockListEvents.Lock()
	mock.calls.ListEvents = append(mock.calls.ListEvents, callInfo)
	mock.lockListEvents.Unlock()
	return mock.ListEventsFunc(ctx, f)
}

// ListEventsCalls gets all the calls that were made to ListEvents.
// Check the length with:
//
//	len(mockedStore.ListEventsCalls())
func (mock *StoreMock) ListEventsCalls() []struct {
	Ctx context.Context
	F   store.EventFilter
} {
	var calls []struct {
		Ctx context.Context
		F   store.EventFilter
	}
	mock.lockListEvents.RLock()
	calls = mock.calls.ListEvents
	mock.lockListEvents.RUnlock()
	return calls
}

// ListHWCapabilities calls ListHWCapabilitiesFunc.
func (mock *StoreMock) ListHWCapabilities(ctx context.Context) ([]domain.HWCapability, error) {
	if mock.ListHWCapabilitiesFunc == nil {
		panic("StoreMock.ListHWCapabilitiesFunc: method is nil but Store.ListHWCapabilities was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListHWCapabilities.Lock()
	mock.calls.ListHWCapabilities = append(mock.calls.ListHWCapabilities, callInfo)
	mock.lockListHWCapabilities.Unlock()
	return mock.ListHWCapabilitiesFunc(ctx)
}

// ListHWCapabilitiesCalls gets all the calls that were made to ListHWCapabilities.
// Check the length with:
//
//	len(mockedStore.ListHWCapabilitiesCalls())
func (mock *StoreMock) ListHWCapabilitiesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListHWCapabilities.RLock()
	calls = mock.calls.ListHWCapabilities
	mock.lockListHWCapabilities.RUnlock()
	return calls
}

// ListJobs calls ListJobsFunc.
func (mock *StoreMock) ListJobs(ctx context.Context, f store.JobFilter) ([]domain.Job, int, error) {
	if mock.ListJobsFunc == nil {
		panic("StoreMock.ListJobsFunc: method is nil but Store.ListJobs was just called")
	}
	callInfo := struct {
		Ctx context.Context
		F   store.JobFilter
	}{
		Ctx: ctx,
		F:   f,
	}
	mock.lockListJobs.Lock()
	mock.calls.ListJobs = append(mock.calls.ListJobs, callInfo)
	mock.lockListJobs.Unlock()
	return mock.ListJobsFunc(ctx, f)
}

// ListJobsCalls gets all the calls that were made to ListJobs.
// Check the length with:
//
//	len(mockedStore.ListJobsCalls())
func (mock *StoreMock) ListJobsCalls() []struct {
	Ctx context.Context
	F   store.JobFilter
} {
	var calls []struct {
		Ctx context.Context
		F   store.JobFilter
	}
	mock.lockListJobs.RLock()
	calls = mock.calls.ListJobs
	mock.lockListJobs.RUnlock()
	return calls
}

// ListMediaFiles calls ListMediaFilesFunc.
func (mock *StoreMock) ListMediaFiles(ctx context.Context, f store.MediaFilter) ([]domain.MediaFile, int, error) {
	if mock.ListMediaFilesFunc == nil {
		panic("StoreMock.ListMediaFilesFunc: method is nil but Store.ListMediaFiles was just called")
	}
	callInfo := struct {
		Ctx context.Context
		F   store.MediaFilter
	}{
		Ctx: ctx,
		F:   f,
	}
	mock.lockListMediaFiles.Lock()
	mock.calls.ListMediaFiles = append(mock.calls.ListMediaFiles, callInfo)
	mock.lockListMediaFiles.Unlock()
	return mock.ListMediaFilesFunc(ctx, f)
}

// ListMediaFilesCalls gets all the calls that were made to ListMediaFiles.
// Check the length with:
//
//	len(mockedStore.ListMediaFilesCalls())
func (mock *StoreMock) ListMediaFilesCalls() []struct {
	Ctx context.Context
	F   store.MediaFilter
} {
	var calls []struct {
		Ctx context.Context
		F   store.MediaFilter
	}
	mock.lockListMediaFiles.RLock()
	calls = mock.calls.ListMediaFiles
	mock.lockListMediaFiles.RUnlock()
	return calls
}

// ListMediaStatsByRoot calls ListMediaStatsByRootFunc.
func (mock *StoreMock) ListMediaStatsByRoot(ctx context.Context, rootID int64) ([]store.MediaStat, error) {
	if mock.ListMediaStatsByRootFunc == nil {
		panic("StoreMock.ListMediaStatsByRootFunc: method is nil but Store.ListMediaStatsByRoot was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RootID int64
	}{
		Ctx:    ctx,
		RootID: rootID,
	}
	mock.lockListMediaStatsByRoot.Lock()
	mock.calls.ListMediaStatsByRoot = append(mock.calls.ListMediaStatsByRoot, callInfo)
	mock.lockListMediaStatsByRoot.Unlock()
	return mock.ListMediaStatsByRootFunc(ctx, rootID)
}

// ListMediaStatsByRootCalls gets all the calls that were made to ListMediaStatsByRoot.
// Check the length with:
//
//	len(mockedStore.ListMediaStatsByRootCalls())
func (mock *StoreMock) ListMediaStatsByRootCalls() []struct {
	Ctx    context.Context
	RootID int64
} {
	var calls []struct {
		Ctx    context.Context
		RootID int64
	}
	mock.lockListMediaStatsByRoot.RLock()
	calls = mock.calls.ListMediaStatsByRoot
	mock.lockListMediaStatsByRoot.RUnlock()
	return calls
}

// ListPlexPathMappings calls ListPlexPathMappingsFunc.
func (mock *StoreMock) ListPlexPathMappings(ctx context.Context) ([]domain.PathMapping, error) {
	if mock.ListPlexPathMappingsFunc == nil {
		panic("StoreMock.ListPlexPathMappingsFunc: method is nil but Store.ListPlexPathMappings was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListPlexPathMappings.Lock()
	mock.calls.ListPlexPathMappings = append(mock.calls.ListPlexPathMappings, callInfo)
	mock.lockListPlexPathMappings.Unlock()
	return mock.ListPlexPathMappingsFunc(ctx)
}

// ListPlexPathMappingsCalls gets all the calls that were made to ListPlexPathMappings.
// Check the length with:
//
//	len(mockedStore.ListPlexPathMappingsCalls())
func (mock *StoreMock) ListPlexPathMappingsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListPlexPathMappings.RLock()
	calls = mock.calls.ListPlexPathMappings
	mock.lockListPlexPathMappings.RUnlock()
	return calls
}

// ListRoots calls ListRootsFunc.
func (mock *StoreMock) ListRoots(ctx context.Context) ([]domain.Root, error) {
	if mock.ListRootsFunc == nil {
		panic("StoreMock.ListRootsFunc: method is nil but Store.ListRoots was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListRoots.Lock()
	mock.calls.ListRoots = append(mock.calls.ListRoots, callInfo)
	mock.lockListRoots.Unlock()
	return mock.ListRootsFunc(ctx)
}

// ListRootsCalls gets all the calls that were made to ListRoots.
// Check the length with:
//
//	len(mockedStore.ListRootsCalls())
func (mock *StoreMock) ListRootsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListRoots.RLock()
	calls = mock.calls.ListRoots
	mock.lockListRoots.RUnlock()
	return calls
}

// ListThroughputStats calls ListThroughputStatsFunc.
func (mock *StoreMock) ListThroughputStats(ctx context.Context) ([]domain.ThroughputStat, error) {
	if mock.ListThroughputStatsFunc == nil {
		panic("StoreMock.ListThroughputStatsFunc: method is nil but Store.ListThroughputStats was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListThroughputStats.Lock()
	mock.calls.ListThroughputStats = append(mock.calls.ListThroughputStats, callInfo)
	mock.lockListThroughputStats.Unlock()
	return mock.ListThroughputStatsFunc(ctx)
}

// ListThroughputStatsCalls gets all the calls that were made to ListThroughputStats.
// Check the length with:
//
//	len(mockedStore.ListThroughputStatsCalls())
func (mock *StoreMock) ListThroughputStatsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListThroughputStats.RLock()
	calls = mock.calls.ListThroughputStats
	mock.lockListThroughputStats.RUnlock()
	return calls
}

// MarkMediaMissing calls MarkMediaMissingFunc.
func (mock *StoreMock) MarkMediaMissing(ctx context.Context, ids []int64) (int64, error) {
	if mock.MarkMediaMissingFunc == nil {
		panic("StoreMock.MarkMediaMissingFunc: method is nil but Store.MarkMediaMissing was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ids []int64
	}{
		Ctx: ctx,
		Ids: ids,
	}
	mock.lockMarkMediaMissing.Lock()
	mock.calls.MarkMediaMissing = append(mock.calls.MarkMediaMissing, callInfo)
	mock.lockMarkMediaMissing.Unlock()
	return mock.MarkMediaMissingFunc(ctx, ids)
}

// MarkMediaMissingCalls gets all the calls that were made to MarkMediaMissing.
// Check the length with:
//
//	len(mockedStore.MarkMediaMissingCalls())
func (mock *StoreMock) MarkMediaMissingCalls() []struct {
	Ctx context.Context
	Ids []int64
} {
	var calls []struct {
		Ctx context.Context
		Ids []int64
	}
	mock.lockMarkMediaMissing.RLock()
	calls = mock.calls.MarkMediaMissing
	mock.lockMarkMediaMissing.RUnlock()
	return calls
}

// PruneEvents calls PruneEventsFunc.
func (mock *StoreMock) PruneEvents(ctx context.Context, now time.Time) (int64, error) {
	if mock.PruneEventsFunc == nil {
		panic("StoreMock.PruneEventsFunc: method is nil but Store.PruneEvents was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Now time.Time
	}{
		Ctx: ctx,
		Now: now,
	}
	mock.lockPruneEvents.Lock()
	mock.calls.PruneEvents = append(mock.calls.PruneEvents, callInfo)
	mock.lockPruneEvents.Unlock()
	return mock.PruneEventsFunc(ctx, now)
}

// PruneEventsCalls gets all the calls that were made to PruneEvents.
// Check the length with:
//
//	len(mockedStore.PruneEventsCalls())
func (mock *StoreMock) PruneEventsCalls() []struct {
	Ctx context.Context
	Now time.Time
} {
	var calls []struct {
		Ctx context.Context
		Now time.Time
	}
	mock.lockPruneEvents.RLock()
	calls = mock.calls.PruneEvents
	mock.lockPruneEvents.RUnlock()
	return calls
}

// RecordPromotion calls RecordPromotionFunc.
func (mock *StoreMock) RecordPromotion(ctx context.Context, u store.PromotionUpdate) error {
	if mock.RecordPromotionFunc == nil {
		panic("StoreMock.RecordPromotionFunc: method is nil but Store.RecordPromotion was just called")
	}
	callInfo := struct {
		Ctx context.Context
		U   store.PromotionUpdate
	}{
		Ctx: ctx,
		U:   u,
	}
	mock.lockRecordPromotion.Lock()
	mock.calls.RecordPromotion = append(mock.calls.RecordPromotion, callInfo)
	mock.lockRecordPromotion.Unlock()
	return mock.RecordPromotionFunc(ctx, u)
}

// RecordPromotionCalls gets all the calls that were made to RecordPromotion.
// Check the length with:
//
//	len(mockedStore.RecordPromotionCalls())
func (mock *StoreMock) RecordPromotionCalls() []struct {
	Ctx context.Context
	U   store.PromotionUpdate
} {
	var calls []struct {
		Ctx context.Context
		U   store.PromotionUpdate
	}
	mock.lockRecordPromotion.RLock()
	calls = mock.calls.RecordPromotion
	mock.lockRecordPromotion.RUnlock()
	return calls
}

// ReplaceArrPathMappings calls ReplaceArrPathMappingsFunc.
func (mock *StoreMock) ReplaceArrPathMappings(ctx context.Context, arrInstanceID int64, m []domain.PathMapping) error {
	if mock.ReplaceArrPathMappingsFunc == nil {
		panic("StoreMock.ReplaceArrPathMappingsFunc: method is nil but Store.ReplaceArrPathMappings was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ArrInstanceID int64
		M             []domain.PathMapping
	}{
		Ctx:           ctx,
		ArrInstanceID: arrInstanceID,
		M:             m,
	}
	mock.lockReplaceArrPathMappings.Lock()
	mock.calls.ReplaceArrPathMappings = append(mock.calls.ReplaceArrPathMappings, callInfo)
	mock.lockReplaceArrPathMappings.Unlock()
	return mock.ReplaceArrPathMappingsFunc(ctx, arrInstanceID, m)
}

// ReplaceArrPathMappingsCalls gets all the calls that were made to ReplaceArrPathMappings.
// Check the length with:
//
//	len(mockedStore.ReplaceArrPathMappingsCalls())
func (mock *StoreMock) ReplaceArrPathMappingsCalls() []struct {
	Ctx           context.Context
	ArrInstanceID int64
	M             []domain.PathMapping
} {
	var calls []struct {
		Ctx           context.Context
		ArrInstanceID int64
		M             []domain.PathMapping
	}
	mock.lockReplaceArrPathMappings.RLock()
	calls = mock.calls.ReplaceArrPathMappings
	mock.lockReplaceArrPathMappings.RUnlock()
	return calls
}

// ReplaceHWCapabilities calls ReplaceHWCapabilitiesFunc.
func (mock *StoreMock) ReplaceHWCapabilities(ctx context.Context, caps []domain.HWCapability) error {
	if mock.ReplaceHWCapabilitiesFunc == nil {
		panic("StoreMock.ReplaceHWCapabilitiesFunc: method is nil but Store.ReplaceHWCapabilities was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Caps []domain.HWCapability
	}{
		Ctx:  ctx,
		Caps: caps,
	}
	mock.lockReplaceHWCapabilities.Lock()
	mock.calls.ReplaceHWCapabilities = append(mock.calls.ReplaceHWCapabilities, callInfo)
	mock.lockReplaceHWCapabilities.Unlock()
	return mock.ReplaceHWCapabilitiesFunc(ctx, caps)
}

// ReplaceHWCapabilitiesCalls gets all the calls that were made to ReplaceHWCapabilities.
// Check the length with:
//
//	len(mockedStore.ReplaceHWCapabilitiesCalls())
func (mock *StoreMock) ReplaceHWCapabilitiesCalls() []struct {
	Ctx  context.Context
	Caps []domain.HWCapability
} {
	var calls []struct {
		Ctx  context.Context
		Caps []domain.HWCapability
	}
	mock.lockReplaceHWCapabilities.RLock()
	calls = mock.calls.ReplaceHWCapabilities
	mock.lockReplaceHWCapabilities.RUnlock()
	return calls
}

// ReplacePlexPathMappings calls ReplacePlexPathMappingsFunc.
func (mock *StoreMock) ReplacePlexPathMappings(ctx context.Context, m []domain.PathMapping) error {
	if mock.ReplacePlexPathMappingsFunc == nil {
		panic("StoreMock.ReplacePlexPathMappingsFunc: method is nil but Store.ReplacePlexPathMappings was just called")
	}
	callInfo := struct {
		Ctx context.Context
		M   []domain.PathMapping
	}{
		Ctx: ctx,
		M:   m,
	}
	mock.lockReplacePlexPathMappings.Lock()
	mock.calls.ReplacePlexPathMappings = append(mock.calls.ReplacePlexPathMappings, callInfo)
	mock.lockReplacePlexPathMappings.Unlock()
	return mock.ReplacePlexPathMappingsFunc(ctx, m)
}

// ReplacePlexPathMappingsCalls gets all the calls that were made to ReplacePlexPathMappings.
// Check the length with:
//
//	len(mockedStore.ReplacePlexPathMappingsCalls())
func (mock *StoreMock) ReplacePlexPathMappingsCalls() []struct {
	Ctx context.Context
	M   []domain.PathMapping
} {
	var calls []struct {
		Ctx context.Context
		M   []domain.PathMapping
	}
	mock.lockReplacePlexPathMappings.RLock()
	calls = mock.calls.ReplacePlexPathMappings
	mock.lockReplacePlexPathMappings.RUnlock()
	return calls
}

// RequeueInterruptedJob calls RequeueInterruptedJobFunc.
func (mock *StoreMock) RequeueInterruptedJob(ctx context.Context, id int64) (store.SweepResult, error) {
	if mock.RequeueInterruptedJobFunc == nil {
		panic("StoreMock.RequeueInterruptedJobFunc: method is nil but Store.RequeueInterruptedJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockRequeueInterruptedJob.Lock()
	mock.calls.RequeueInterruptedJob = append(mock.calls.RequeueInterruptedJob, callInfo)
	mock.lockRequeueInterruptedJob.Unlock()
	return mock.RequeueInterruptedJobFunc(ctx, id)
}

// RequeueInterruptedJobCalls gets all the calls that were made to RequeueInterruptedJob.
// Check the length with:
//
//	len(mockedStore.RequeueInterruptedJobCalls())
func (mock *StoreMock) RequeueInterruptedJobCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockRequeueInterruptedJob.RLock()
	calls = mock.calls.RequeueInterruptedJob
	mock.lockRequeueInterruptedJob.RUnlock()
	return calls
}

// RestartJob calls RestartJobFunc.
func (mock *StoreMock) RestartJob(ctx context.Context, id int64) (domain.Job, error) {
	if mock.RestartJobFunc == nil {
		panic("StoreMock.RestartJobFunc: method is nil but Store.RestartJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockRestartJob.Lock()
	mock.calls.RestartJob = append(mock.calls.RestartJob, callInfo)
	mock.lockRestartJob.Unlock()
	return mock.RestartJobFunc(ctx, id)
}

// RestartJobCalls gets all the calls that were made to RestartJob.
// Check the length with:
//
//	len(mockedStore.RestartJobCalls())
func (mock *StoreMock) RestartJobCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockRestartJob.RLock()
	calls = mock.calls.RestartJob
	mock.lockRestartJob.RUnlock()
	return calls
}

// SetArrTestResult calls SetArrTestResultFunc.
func (mock *StoreMock) SetArrTestResult(ctx context.Context, id int64, at time.Time, result string) error {
	if mock.SetArrTestResultFunc == nil {
		panic("StoreMock.SetArrTestResultFunc: method is nil but Store.SetArrTestResult was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     int64
		At     time.Time
		Result string
	}{
		Ctx:    ctx,
		ID:     id,
		At:     at,
		Result: result,
	}
	mock.lockSetArrTestResult.Lock()
	mock.calls.SetArrTestResult = append(mock.calls.SetArrTestResult, callInfo)
	mock.lockSetArrTestResult.Unlock()
	return mock.SetArrTestResultFunc(ctx, id, at, result)
}

// SetArrTestResultCalls gets all the calls that were made to SetArrTestResult.
// Check the length with:
//
//	len(mockedStore.SetArrTestResultCalls())
func (mock *StoreMock) SetArrTestResultCalls() []struct {
	Ctx    context.Context
	ID     int64
	At     time.Time
	Result string
} {
	var calls []struct {
		Ctx    context.Context
		ID     int64
		At     time.Time
		Result string
	}
	mock.lockSetArrTestResult.RLock()
	calls = mock.calls.SetArrTestResult
	mock.lockSetArrTestResult.RUnlock()
	return calls
}

// SetJobBlockedBy calls SetJobBlockedByFunc.
func (mock *StoreMock) SetJobBlockedBy(ctx context.Context, id int64, blockedBy string) error {
	if mock.SetJobBlockedByFunc == nil {
		panic("StoreMock.SetJobBlockedByFunc: method is nil but Store.SetJobBlockedBy was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ID        int64
		BlockedBy string
	}{
		Ctx:       ctx,
		ID:        id,
		BlockedBy: blockedBy,
	}
	mock.lockSetJobBlockedBy.Lock()
	mock.calls.SetJobBlockedBy = append(mock.calls.SetJobBlockedBy, callInfo)
	mock.lockSetJobBlockedBy.Unlock()
	return mock.SetJobBlockedByFunc(ctx, id, blockedBy)
}

// SetJobBlockedByCalls gets all the calls that were made to SetJobBlockedBy.
// Check the length with:
//
//	len(mockedStore.SetJobBlockedByCalls())
func (mock *StoreMock) SetJobBlockedByCalls() []struct {
	Ctx       context.Context
	ID        int64
	BlockedBy string
} {
	var calls []struct {
		Ctx       context.Context
		ID        int64
		BlockedBy string
	}
	mock.lockSetJobBlockedBy.RLock()
	calls = mock.calls.SetJobBlockedBy
	mock.lockSetJobBlockedBy.RUnlock()
	return calls
}

// SetJobState calls SetJobStateFunc.
func (mock *StoreMock) SetJobState(ctx context.Context, id int64, state domain.JobState) error {
	if mock.SetJobStateFunc == nil {
		panic("StoreMock.SetJobStateFunc: method is nil but Store.SetJobState was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		ID    int64
		State domain.JobState
	}{
		Ctx:   ctx,
		ID:    id,
		State: state,
	}
	mock.lockSetJobState.Lock()
	mock.calls.SetJobState = append(mock.calls.SetJobState, callInfo)
	mock.lockSetJobState.Unlock()
	return mock.SetJobStateFunc(ctx, id, state)
}

// SetJobStateCalls gets all the calls that were made to SetJobState.
// Check the length with:
//
//	len(mockedStore.SetJobStateCalls())
func (mock *StoreMock) SetJobStateCalls() []struct {
	Ctx   context.Context
	ID    int64
	State domain.JobState
} {
	var calls []struct {
		Ctx   context.Context
		ID    int64
		State domain.JobState
	}
	mock.lockSetJobState.RLock()
	calls = mock.calls.SetJobState
	mock.lockSetJobState.RUnlock()
	return calls
}

// SetMediaIgnored calls SetMediaIgnoredFunc.
func (mock *StoreMock) SetMediaIgnored(ctx context.Context, id int64, ignored bool) error {
	if mock.SetMediaIgnoredFunc == nil {
		panic("StoreMock.SetMediaIgnoredFunc: method is nil but Store.SetMediaIgnored was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ID      int64
		Ignored bool
	}{
		Ctx:     ctx,
		ID:      id,
		Ignored: ignored,
	}
	mock.lockSetMediaIgnored.Lock()
	mock.calls.SetMediaIgnored = append(mock.calls.SetMediaIgnored, callInfo)
	mock.lockSetMediaIgnored.Unlock()
	return mock.SetMediaIgnoredFunc(ctx, id, ignored)
}

// SetMediaIgnoredCalls gets all the calls that were made to SetMediaIgnored.
// Check the length with:
//
//	len(mockedStore.SetMediaIgnoredCalls())
func (mock *StoreMock) SetMediaIgnoredCalls() []struct {
	Ctx     context.Context
	ID      int64
	Ignored bool
} {
	var calls []struct {
		Ctx     context.Context
		ID      int64
		Ignored bool
	}
	mock.lockSetMediaIgnored.RLock()
	calls = mock.calls.SetMediaIgnored
	mock.lockSetMediaIgnored.RUnlock()
	return calls
}

// SetMediaIntegrity calls SetMediaIntegrityFunc.
func (mock *StoreMock) SetMediaIntegrity(ctx context.Context, id int64, fingerprint string, fullHash string, at time.Time) error {
	if mock.SetMediaIntegrityFunc == nil {
		panic("StoreMock.SetMediaIntegrityFunc: method is nil but Store.SetMediaIntegrity was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ID          int64
		Fingerprint string
		FullHash    string
		At          time.Time
	}{
		Ctx:         ctx,
		ID:          id,
		Fingerprint: fingerprint,
		FullHash:    fullHash,
		At:          at,
	}
	mock.lockSetMediaIntegrity.Lock()
	mock.calls.SetMediaIntegrity = append(mock.calls.SetMediaIntegrity, callInfo)
	mock.lockSetMediaIntegrity.Unlock()
	return mock.SetMediaIntegrityFunc(ctx, id, fingerprint, fullHash, at)
}

// SetMediaIntegrityCalls gets all the calls that were made to SetMediaIntegrity.
// Check the length with:
//
//	len(mockedStore.SetMediaIntegrityCalls())
func (mock *StoreMock) SetMediaIntegrityCalls() []struct {
	Ctx         context.Context
	ID          int64
	Fingerprint string
	FullHash    string
	At          time.Time
} {
	var calls []struct {
		Ctx         context.Context
		ID          int64
		Fingerprint string
		FullHash    string
		At          time.Time
	}
	mock.lockSetMediaIntegrity.RLock()
	calls = mock.calls.SetMediaIntegrity
	mock.lockSetMediaIntegrity.RUnlock()
	return calls
}

// SetMediaStatus calls SetMediaStatusFunc.
func (mock *StoreMock) SetMediaStatus(ctx context.Context, id int64, status domain.MediaStatus, lastError string) error {
	if mock.SetMediaStatusFunc == nil {
		panic("StoreMock.SetMediaStatusFunc: method is nil but Store.SetMediaStatus was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ID        int64
		Status    domain.MediaStatus
		LastError string
	}{
		Ctx:       ctx,
		ID:        id,
		Status:    status,
		LastError: lastError,
	}
	mock.lockSetMediaStatus.Lock()
	mock.calls.SetMediaStatus = append(mock.calls.SetMediaStatus, callInfo)
	mock.lockSetMediaStatus.Unlock()
	return mock.SetMediaStatusFunc(ctx, id, status, lastError)
}

// SetMediaStatusCalls gets all the calls that were made to SetMediaStatus.
// Check the length with:
//
//	len(mockedStore.SetMediaStatusCalls())
func (mock *StoreMock) SetMediaStatusCalls() []struct {
	Ctx       context.Context
	ID        int64
	Status    domain.MediaStatus
	LastError string
} {
	var calls []struct {
		Ctx       context.Context
		ID        int64
		Status    domain.MediaStatus
		LastError string
	}
	mock.lockSetMediaStatus.RLock()
	calls = mock.calls.SetMediaStatus
	mock.lockSetMediaStatus.RUnlock()
	return calls
}

// SetPlexTestResult calls SetPlexTestResultFunc.
func (mock *StoreMock) SetPlexTestResult(ctx context.Context, at time.Time, result string) error {
	if mock.SetPlexTestResultFunc == nil {
		panic("StoreMock.SetPlexTestResultFunc: method is nil but Store.SetPlexTestResult was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		At     time.Time
		Result string
	}{
		Ctx:    ctx,
		At:     at,
		Result: result,
	}
	mock.lockSetPlexTestResult.Lock()
	mock.calls.SetPlexTestResult = append(mock.calls.SetPlexTestResult, callInfo)
	mock.lockSetPlexTestResult.Unlock()
	return mock.SetPlexTestResultFunc(ctx, at, result)
}

// SetPlexTestResultCalls gets all the calls that were made to SetPlexTestResult.
// Check the length with:
//
//	len(mockedStore.SetPlexTestResultCalls())
func (mock *StoreMock) SetPlexTestResultCalls() []struct {
	Ctx    context.Context
	At     time.Time
	Result string
} {
	var calls []struct {
		Ctx    context.Context
		At     time.Time
		Result string
	}
	mock.lockSetPlexTestResult.RLock()
	calls = mock.calls.SetPlexTestResult
	mock.lockSetPlexTestResult.RUnlock()
	return calls
}

// SetRootEnabled calls SetRootEnabledFunc.
func (mock *StoreMock) SetRootEnabled(ctx context.Context, id int64, enabled bool) error {
	if mock.SetRootEnabledFunc == nil {
		panic("StoreMock.SetRootEnabledFunc: method is nil but Store.SetRootEnabled was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ID      int64
		Enabled bool
	}{
		Ctx:     ctx,
		ID:      id,
		Enabled: enabled,
	}
	mock.lockSetRootEnabled.Lock()
	mock.calls.SetRootEnabled = append(mock.calls.SetRootEnabled, callInfo)
	mock.lockSetRootEnabled.Unlock()
	return mock.SetRootEnabledFunc(ctx, id, enabled)
}

// SetRootEnabledCalls gets all the calls that were made to SetRootEnabled.
// Check the length with:
//
//	len(mockedStore.SetRootEnabledCalls())
func (mock *StoreMock) SetRootEnabledCalls() []struct {
	Ctx     context.Context
	ID      int64
	Enabled bool
} {
	var calls []struct {
		Ctx     context.Context
		ID      int64
		Enabled bool
	}
	mock.lockSetRootEnabled.RLock()
	calls = mock.calls.SetRootEnabled
	mock.lockSetRootEnabled.RUnlock()
	return calls
}

// Stats calls StatsFunc.
func (mock *StoreMock) Stats(ctx context.Context) (store.Stats, error) {
	if mock.StatsFunc == nil {
		panic("StoreMock.StatsFunc: method is nil but Store.Stats was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStats.Lock()
	mock.calls.Stats = append(mock.calls.Stats, callInfo)
	mock.lockStats.Unlock()
	return mock.StatsFunc(ctx)
}

// StatsCalls gets all the calls that were made to Stats.
// Check the length with:
//
//	len(mockedStore.StatsCalls())
func (mock *StoreMock) StatsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStats.RLock()
	calls = mock.calls.Stats
	mock.lockStats.RUnlock()
	return calls
}

// SweepInterruptedJobs calls SweepInterruptedJobsFunc.
func (mock *StoreMock) SweepInterruptedJobs(ctx context.Context) ([]store.SweepResult, error) {
	if mock.SweepInterruptedJobsFunc == nil {
		panic("StoreMock.SweepInterruptedJobsFunc: method is nil but Store.SweepInterruptedJobs was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockSweepInterruptedJobs.Lock()
	mock.calls.SweepInterruptedJobs = append(mock.calls.SweepInterruptedJobs, callInfo)
	mock.lockSweepInterruptedJobs.Unlock()
	return mock.SweepInterruptedJobsFunc(ctx)
}

// SweepInterruptedJobsCalls gets all the calls that were made to SweepInterruptedJobs.
// Check the length with:
//
//	len(mockedStore.SweepInterruptedJobsCalls())
func (mock *StoreMock) SweepInterruptedJobsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockSweepInterruptedJobs.RLock()
	calls = mock.calls.SweepInterruptedJobs
	mock.lockSweepInterruptedJobs.RUnlock()
	return calls
}

// UpdateArrInstance calls UpdateArrInstanceFunc.
func (mock *StoreMock) UpdateArrInstance(ctx context.Context, a domain.ArrInstance) error {
	if mock.UpdateArrInstanceFunc == nil {
		panic("StoreMock.UpdateArrInstanceFunc: method is nil but Store.UpdateArrInstance was just called")
	}
	callInfo := struct {
		Ctx context.Context
		A   domain.ArrInstance
	}{
		Ctx: ctx,
		A:   a,
	}
	mock.lockUpdateArrInstance.Lock()
	mock.calls.UpdateArrInstance = append(mock.calls.UpdateArrInstance, callInfo)
	mock.lockUpdateArrInstance.Unlock()
	return mock.UpdateArrInstanceFunc(ctx, a)
}

// UpdateArrInstanceCalls gets all the calls that were made to UpdateArrInstance.
// Check the length with:
//
//	len(mockedStore.UpdateArrInstanceCalls())
func (mock *StoreMock) UpdateArrInstanceCalls() []struct {
	Ctx context.Context
	A   domain.ArrInstance
} {
	var calls []struct {
		Ctx context.Context
		A   domain.ArrInstance
	}
	mock.lockUpdateArrInstance.RLock()
	calls = mock.calls.UpdateArrInstance
	mock.lockUpdateArrInstance.RUnlock()
	return calls
}

// UpdateJobExecution calls UpdateJobExecutionFunc.
func (mock *StoreMock) UpdateJobExecution(ctx context.Context, u store.ExecutionUpdate) error {
	if mock.UpdateJobExecutionFunc == nil {
		panic("StoreMock.UpdateJobExecutionFunc: method is nil but Store.UpdateJobExecution was just called")
	}
	callInfo := struct {
		Ctx context.Context
		U   store.ExecutionUpdate
	}{
		Ctx: ctx,
		U:   u,
	}
	mock.lockUpdateJobExecution.Lock()
	mock.calls.UpdateJobExecution = append(mock.calls.UpdateJobExecution, callInfo)
	mock.lockUpdateJobExecution.Unlock()
	return mock.UpdateJobExecutionFunc(ctx, u)
}

// UpdateJobExecutionCalls gets all the calls that were made to UpdateJobExecution.
// Check the length with:
//
//	len(mockedStore.UpdateJobExecutionCalls())
func (mock *StoreMock) UpdateJobExecutionCalls() []struct {
	Ctx context.Context
	U   store.ExecutionUpdate
} {
	var calls []struct {
		Ctx context.Context
		U   store.ExecutionUpdate
	}
	mock.lockUpdateJobExecution.RLock()
	calls = mock.calls.UpdateJobExecution
	mock.lockUpdateJobExecution.RUnlock()
	return calls
}

// UpdateJobProgress calls UpdateJobProgressFunc.
func (mock *StoreMock) UpdateJobProgress(ctx context.Context, id int64, pct float64, speed float64, estimatedSeconds int) error {
	if mock.UpdateJobProgressFunc == nil {
		panic("StoreMock.UpdateJobProgressFunc: method is nil but Store.UpdateJobProgress was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		ID               int64
		Pct              float64
		Speed            float64
		EstimatedSeconds int
	}{
		Ctx:              ctx,
		ID:               id,
		Pct:              pct,
		Speed:            speed,
		EstimatedSeconds: estimatedSeconds,
	}
	mock.lockUpdateJobProgress.Lock()
	mock.calls.UpdateJobProgress = append(mock.calls.UpdateJobProgress, callInfo)
	mock.lockUpdateJobProgress.Unlock()
	return mock.UpdateJobProgressFunc(ctx, id, pct, speed, estimatedSeconds)
}

// UpdateJobProgressCalls gets all the calls that were made to UpdateJobProgress.
// Check the length with:
//
//	len(mockedStore.UpdateJobProgressCalls())
func (mock *StoreMock) UpdateJobProgressCalls() []struct {
	Ctx              context.Context
	ID               int64
	Pct              float64
	Speed            float64
	EstimatedSeconds int
} {
	var calls []struct {
		Ctx              context.Context
		ID               int64
		Pct              float64
		Speed            float64
		EstimatedSeconds int
	}
	mock.lockUpdateJobProgress.RLock()
	calls = mock.calls.UpdateJobProgress
	mock.lockUpdateJobProgress.RUnlock()
	return calls
}

// UpdateJobTransform calls UpdateJobTransformFunc.
func (mock *StoreMock) UpdateJobTransform(ctx context.Context, id int64, t domain.TransformRecord) error {
	if mock.UpdateJobTransformFunc == nil {
		panic("StoreMock.UpdateJobTransformFunc: method is nil but Store.UpdateJobTransform was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
		T   domain.TransformRecord
	}{
		Ctx: ctx,
		ID:  id,
		T:   t,
	}
	mock.lockUpdateJobTransform.Lock()
	mock.calls.UpdateJobTransform = append(mock.calls.UpdateJobTransform, callInfo)
	mock.lockUpdateJobTransform.Unlock()
	return mock.UpdateJobTransformFunc(ctx, id, t)
}

// UpdateJobTransformCalls gets all the calls that were made to UpdateJobTransform.
// Check the length with:
//
//	len(mockedStore.UpdateJobTransformCalls())
func (mock *StoreMock) UpdateJobTransformCalls() []struct {
	Ctx context.Context
	ID  int64
	T   domain.TransformRecord
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
		T   domain.TransformRecord
	}
	mock.lockUpdateJobTransform.RLock()
	calls = mock.calls.UpdateJobTransform
	mock.lockUpdateJobTransform.RUnlock()
	return calls
}

// UpdateMediaAnalysis calls UpdateMediaAnalysisFunc.
func (mock *StoreMock) UpdateMediaAnalysis(ctx context.Context, u store.AnalysisUpdate) error {
	if mock.UpdateMediaAnalysisFunc == nil {
		panic("StoreMock.UpdateMediaAnalysisFunc: method is nil but Store.UpdateMediaAnalysis was just called")
	}
	callInfo := struct {
		Ctx context.Context
		U   store.AnalysisUpdate
	}{
		Ctx: ctx,
		U:   u,
	}
	mock.lockUpdateMediaAnalysis.Lock()
	mock.calls.UpdateMediaAnalysis = append(mock.calls.UpdateMediaAnalysis, callInfo)
	mock.lockUpdateMediaAnalysis.Unlock()
	return mock.UpdateMediaAnalysisFunc(ctx, u)
}

// UpdateMediaAnalysisCalls gets all the calls that were made to UpdateMediaAnalysis.
// Check the length with:
//
//	len(mockedStore.UpdateMediaAnalysisCalls())
func (mock *StoreMock) UpdateMediaAnalysisCalls() []struct {
	Ctx context.Context
	U   store.AnalysisUpdate
} {
	var calls []struct {
		Ctx context.Context
		U   store.AnalysisUpdate
	}
	mock.lockUpdateMediaAnalysis.RLock()
	calls = mock.calls.UpdateMediaAnalysis
	mock.lockUpdateMediaAnalysis.RUnlock()
	return calls
}

// UpdatePlexConfig calls UpdatePlexConfigFunc.
func (mock *StoreMock) UpdatePlexConfig(ctx context.Context, c domain.PlexConfig) error {
	if mock.UpdatePlexConfigFunc == nil {
		panic("StoreMock.UpdatePlexConfigFunc: method is nil but Store.UpdatePlexConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
		C   domain.PlexConfig
	}{
		Ctx: ctx,
		C:   c,
	}
	mock.lockUpdatePlexConfig.Lock()
	mock.calls.UpdatePlexConfig = append(mock.calls.UpdatePlexConfig, callInfo)
	mock.lockUpdatePlexConfig.Unlock()
	return mock.UpdatePlexConfigFunc(ctx, c)
}

// UpdatePlexConfigCalls gets all the calls that were made to UpdatePlexConfig.
// Check the length with:
//
//	len(mockedStore.UpdatePlexConfigCalls())
func (mock *StoreMock) UpdatePlexConfigCalls() []struct {
	Ctx context.Context
	C   domain.PlexConfig
} {
	var calls []struct {
		Ctx context.Context
		C   domain.PlexConfig
	}
	mock.lockUpdatePlexConfig.RLock()
	calls = mock.calls.UpdatePlexConfig
	mock.lockUpdatePlexConfig.RUnlock()
	return calls
}

// UpdateSettings calls UpdateSettingsFunc.
func (mock *StoreMock) UpdateSettings(ctx context.Context, s domain.Settings) error {
	if mock.UpdateSettingsFunc == nil {
		panic("StoreMock.UpdateSettingsFunc: method is nil but Store.UpdateSettings was just called")
	}
	callInfo := struct {
		Ctx context.Context
		S   domain.Settings
	}{
		Ctx: ctx,
		S:   s,
	}
	mock.lockUpdateSettings.Lock()
	mock.calls.UpdateSettings = append(mock.calls.UpdateSettings, callInfo)
	mock.lockUpdateSettings.Unlock()
	return mock.UpdateSettingsFunc(ctx, s)
}

// UpdateSettingsCalls gets all the calls that were made to UpdateSettings.
// Check the length with:
//
//	len(mockedStore.UpdateSettingsCalls())
func (mock *StoreMock) UpdateSettingsCalls() []struct {
	Ctx context.Context
	S   domain.Settings
} {
	var calls []struct {
		Ctx context.Context
		S   domain.Settings
	}
	mock.lockUpdateSettings.RLock()
	calls = mock.calls.UpdateSettings
	mock.lockUpdateSettings.RUnlock()
	return calls
}

// UpsertMediaFile calls UpsertMediaFileFunc.
func (mock *StoreMock) UpsertMediaFile(ctx context.Context, m domain.MediaFile) (domain.MediaFile, error) {
	if mock.UpsertMediaFileFunc == nil {
		panic("StoreMock.UpsertMediaFileFunc: method is nil but Store.UpsertMediaFile was just called")
	}
	callInfo := struct {
		Ctx context.Context
		M   domain.MediaFile
	}{
		Ctx: ctx,
		M:   m,
	}
	mock.lockUpsertMediaFile.Lock()
	mock.calls.UpsertMediaFile = append(mock.calls.UpsertMediaFile, callInfo)
	mock.lockUpsertMediaFile.Unlock()
	return mock.UpsertMediaFileFunc(ctx, m)
}

// UpsertMediaFileCalls gets all the calls that were made to UpsertMediaFile.
// Check the length with:
//
//	len(mockedStore.UpsertMediaFileCalls())
func (mock *StoreMock) UpsertMediaFileCalls() []struct {
	Ctx context.Context
	M   domain.MediaFile
} {
	var calls []struct {
		Ctx context.Context
		M   domain.MediaFile
	}
	mock.lockUpsertMediaFile.RLock()
	calls = mock.calls.UpsertMediaFile
	mock.lockUpsertMediaFile.RUnlock()
	return calls
}

// UpsertThroughputStat calls UpsertThroughputStatFunc.
func (mock *StoreMock) UpsertThroughputStat(ctx context.Context, s domain.ThroughputStat) error {
	if mock.UpsertThroughputStatFunc == nil {
		panic("StoreMock.UpsertThroughputStatFunc: method is nil but Store.UpsertThroughputStat was just called")
	}
	callInfo := struct {
		Ctx context.Context
		S   domain.ThroughputStat
	}{
		Ctx: ctx,
		S:   s,
	}
	mock.lockUpsertThroughputStat.Lock()
	mock.calls.UpsertThroughputStat = append(mock.calls.UpsertThroughputStat, callInfo)
	mock.lockUpsertThroughputStat.Unlock()
	return mock.UpsertThroughputStatFunc(ctx, s)
}

// UpsertThroughputStatCalls gets all the calls that were made to UpsertThroughputStat.
// Check the length with:
//
//	len(mockedStore.UpsertThroughputStatCalls())
func (mock *StoreMock) UpsertThroughputStatCalls() []struct {
	Ctx context.Context
	S   domain.ThroughputStat
} {
	var calls []struct {
		Ctx context.Context
		S   domain.ThroughputStat
	}
	mock.lockUpsertThroughputStat.RLock()
	calls = mock.calls.UpsertThroughputStat
	mock.lockUpsertThroughputStat.RUnlock()
	return calls
}
