import {
  AlertTriangle,
  AudioLines,
  Ban,
  Captions,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  Clock,
  Copy,
  Cpu,
  Database,
  ExternalLink,
  FileText,
  FileVideo,
  Film,
  Filter,
  Fingerprint,
  FolderOpen,
  Gauge,
  Gavel,
  HardDrive,
  Info,
  Inbox,
  KeyRound,
  LayoutDashboard,
  Library,
  ListChecks,
  Network,
  Pause,
  Pencil,
  Play,
  PlayCircle,
  Plus,
  RefreshCw,
  RotateCw,
  Save,
  ScanSearch,
  ScrollText,
  Search,
  ShieldAlert,
  SlidersHorizontal,
  Terminal,
  Trash2,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

// Named, so every icon the binary embeds is visible in one place. lucide tree-shakes on the named
// imports above; an icon font would have put its whole glyph set into the Go binary via go:embed.
const icons = {
  alert: AlertTriangle,
  audio: AudioLines,
  ban: Ban,
  check: Check,
  chevron_down: ChevronDown,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  chevron_up: ChevronUp,
  clock: Clock,
  close: X,
  copy: Copy,
  dashboard: LayoutDashboard,
  database: Database,
  disk: HardDrive,
  edit: Pencil,
  error: CircleAlert,
  external: ExternalLink,
  file: FileText,
  filter: Filter,
  fingerprint: Fingerprint,
  folder: FolderOpen,
  gauge: Gauge,
  gavel: Gavel,
  hardware: Cpu,
  hub: Network,
  inbox: Inbox,
  info: Info,
  key: KeyRound,
  library: Library,
  list: ListChecks,
  logo: Film,
  logs: ScrollText,
  pause: Pause,
  play: Play,
  plex: PlayCircle,
  plus: Plus,
  probe: ScanSearch,
  refresh: RefreshCw,
  retry: RotateCw,
  save: Save,
  search: Search,
  shield: ShieldAlert,
  subtitle: Captions,
  success: CircleCheck,
  terminal: Terminal,
  trash: Trash2,
  tune: SlidersHorizontal,
  video: FileVideo,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

interface IconProps {
  name: IconName;
  size?: number;
  className?: string;
}

export function Icon({ name, size = 20, className }: IconProps) {
  const Glyph = icons[name];

  return <Glyph size={size} strokeWidth={2} className={className} aria-hidden="true" />;
}
