// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/yama6a/codarr/internal/ffmpeg"
	"github.com/yama6a/codarr/internal/ffprobe"
	"github.com/yama6a/codarr/internal/hardware"
	"github.com/yama6a/codarr/internal/job"
	"github.com/yama6a/codarr/internal/pkg/domain"
	"github.com/yama6a/codarr/internal/pkg/fsx"
	"github.com/yama6a/codarr/internal/pkg/store"
	"github.com/yama6a/codarr/internal/promote"
	"os"
	"sync"
)

// Ensure, that StoreMock does implement job.Store.
// If this is not the case, regenerate this file with moq.
var _ job.Store = &StoreMock{}

// StoreMock is a mock implementation of job.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked job.Store
//		mockedStore := &StoreMock{
//			ActiveJobForMediaFunc: func(ctx context.Context, mediaFileID int64) (domain.Job, bool, error) {
//				panic("mock out the ActiveJobForMedia method")
//			},
//			CancelJobFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the CancelJob method")
//			},
//			ClaimNextJobFunc: func(ctx context.Context) (domain.Job, bool, error) {
//				panic("mock out the ClaimNextJob method")
//			},
//			CountJobsByStateFunc: func(ctx context.Context) (map[domain.JobState]int, error) {
//				panic("mock out the CountJobsByState method")
//			},
//			EnqueueJobFunc: func(ctx context.Context, j domain.Job) (domain.Job, bool, error) {
//				panic("mock out the EnqueueJob method")
//			},
//			FailJobFunc: func(ctx context.Context, id int64, code domain.FailureCode, message string, stderrTail string) error {
//				panic("mock out the FailJob method")
//			},
//			GetJobFunc: func(ctx context.Context, id int64) (domain.Job, error) {
//				panic("mock out the GetJob method")
//			},
//			GetMediaFileFunc: func(ctx context.Context, id int64) (domain.MediaFile, error) {
//				panic("mock out the GetMediaFile method")
//			},
//			GetSettingsFunc: func(ctx context.Context) (domain.Settings, error) {
//				panic("mock out the GetSettings method")
//			},
//			GetThroughputStatFunc: func(ctx context.Context, kind domain.Kind, encoder string, resolution string) (domain.ThroughputStat, error) {
//				panic("mock out the GetThroughputStat method")
//			},
//			ListMediaFilesFunc: func(ctx context.Context, f store.MediaFilter) ([]domain.MediaFile, int, error) {
//				panic("mock out the ListMediaFiles method")
//			},
//			ListRootsFunc: func(ctx context.Context) ([]domain.Root, error) {
//				panic("mock out the ListRoots method")
//			},
//			RecordPromotionFunc: func(ctx context.Context, u store.PromotionUpdate) error {
//				panic("mock out the RecordPromotion method")
//			},
//			RequeueInterruptedJobFunc: func(ctx context.Context, id int64) (store.SweepResult, error) {
//				panic("mock out the RequeueInterruptedJob method")
//			},
//			RestartJobFunc: func(ctx context.Context, id int64) (domain.Job, error) {
//				panic("mock out the RestartJob method")
//			},
//			SetJobBlockedByFunc: func(ctx context.Context, id int64, blockedBy string) error {
//				panic("mock out the SetJobBlockedBy method")
//			},
//			SetJobStateFunc: func(ctx context.Context, id int64, state domain.JobState) error {
//				panic("mock out the SetJobState method")
//			},
//			SetMediaStatusFunc: func(ctx context.Context, id int64, status domain.MediaStatus, lastError string) error {
//				panic("mock out the SetMediaStatus method")
//			},
//			SweepInterruptedJobsFunc: func(ctx context.Context) ([]store.SweepResult, error) {
//				panic("mock out the SweepInterruptedJobs method")
//			},
//			UpdateJobExecutionFunc: func(ctx context.Context, u store.ExecutionUpdate) error {
//				panic("mock out the UpdateJobExecution method")
//			},
//			UpdateJobProgressFunc: func(ctx context.Context, id int64, pct float64, speed float64, fps float64, estimatedSeconds int) error {
//				panic("mock out the UpdateJobProgress method")
//			},
//			UpdateJobTransformFunc: func(ctx context.Context, id int64, t domain.TransformRecord) error {
//				panic("mock out the UpdateJobTransform method")
//			},
//			UpdateSettingsFunc: func(ctx context.Context, s domain.Settings) error {
//				panic("mock out the UpdateSettings method")
//			},
//			UpsertThroughputStatFunc: func(ctx context.Context, s domain.ThroughputStat) error {
//				panic("mock out the UpsertThroughputStat method")
//			},
//		}
//
//		// use mockedStore in code that requires job.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// ActiveJobForMediaFunc mocks the ActiveJobForMedia method.
	ActiveJobForMediaFunc func(ctx context.Context, mediaFileID int64) (domain.Job, bool, error)

	// CancelJobFunc mocks the CancelJob method.
	CancelJobFunc func(ctx context.Context, id int64) error

	// ClaimNextJobFunc mocks the ClaimNextJob method.
	ClaimNextJobFunc func(ctx context.Context) (domain.Job, bool, error)

	// CountJobsByStateFunc mocks the CountJobsByState method.
	CountJobsByStateFunc func(ctx context.Context) (map[domain.JobState]int, error)

	// EnqueueJobFunc mocks the EnqueueJob method.
	EnqueueJobFunc func(ctx context.Context, j domain.Job) (domain.Job, bool, error)

	// FailJobFunc mocks the FailJob method.
	FailJobFunc func(ctx context.Context, id int64, code domain.FailureCode, message string, stderrTail string) error

	// GetJobFunc mocks the GetJob method.
	GetJobFunc func(ctx context.Context, id int64) (domain.Job, error)

	// GetMediaFileFunc mocks the GetMediaFile method.
	GetMediaFileFunc func(ctx context.Context, id int64) (domain.MediaFile, error)

	// GetSettingsFunc mocks the GetSettings method.
	GetSettingsFunc func(ctx context.Context) (domain.Settings, error)

	// GetThroughputStatFunc mocks the GetThroughputStat method.
	GetThroughputStatFunc func(ctx context.Context, kind domain.Kind, encoder string, resolution string) (domain.ThroughputStat, error)

	// ListMediaFilesFunc mocks the ListMediaFiles method.
	ListMediaFilesFunc func(ctx context.Context, f store.MediaFilter) ([]domain.MediaFile, int, error)

	// ListRootsFunc mocks the ListRoots method.
	ListRootsFunc func(ctx context.Context) ([]domain.Root, error)

	// RecordPromotionFunc mocks the RecordPromotion method.
	RecordPromotionFunc func(ctx context.Context, u store.PromotionUpdate) error

	// RequeueInterruptedJobFunc mocks the RequeueInterruptedJob method.
	RequeueInterruptedJobFunc func(ctx context.Context, id int64) (store.SweepResult, error)

	// RestartJobFunc mocks the RestartJob method.
	RestartJobFunc func(ctx context.Context, id int64) (domain.Job, error)

	// SetJobBlockedByFunc mocks the SetJobBlockedBy method.
	SetJobBlockedByFunc func(ctx context.Context, id int64, blockedBy string) error

	// SetJobStateFunc mocks the SetJobState method.
	SetJobStateFunc func(ctx context.Context, id int64, state domain.JobState) error

	// SetMediaStatusFunc mocks the SetMediaStatus method.
	SetMediaStatusFunc func(ctx context.Context, id int64, status domain.MediaStatus, lastError string) error

	// SweepInterruptedJobsFunc mocks the SweepInterruptedJobs method.
	SweepInterruptedJobsFunc func(ctx context.Context) ([]store.SweepResult, error)

	// UpdateJobExecutionFunc mocks the UpdateJobExecution method.
	UpdateJobExecutionFunc func(ctx context.Context, u store.ExecutionUpdate) error

	// UpdateJobProgressFunc mocks the UpdateJobProgress method.
	UpdateJobProgressFunc func(ctx context.Context, id int64, pct float64, speed float64, fps float64, estimatedSeconds int) error

	// UpdateJobTransformFunc mocks the UpdateJobTransform method.
	UpdateJobTransformFunc func(ctx context.Context, id int64, t domain.TransformRecord) error

	// UpdateSettingsFunc mocks the UpdateSettings method.
	UpdateSettingsFunc func(ctx context.Context, s domain.Settings) error

	// UpsertThroughputStatFunc mocks the UpsertThroughputStat method.
	UpsertThroughputStatFunc func(ctx context.Context, s domain.ThroughputStat) error

	// calls tracks calls to the methods.
	calls struct {
		// ActiveJobForMedia holds details about calls to the ActiveJobForMedia method.
		ActiveJobForMedia []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MediaFileID is the mediaFileID argument value.
			MediaFileID int64
		}
		// CancelJob holds details about calls to the CancelJob method.
		CancelJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// ClaimNextJob holds details about calls to the ClaimNextJob method.
		ClaimNextJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CountJobsByState holds details about calls to the CountJobsByState method.
		CountJobsByState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// EnqueueJob holds details about calls to the EnqueueJob method.
		EnqueueJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// J is the j argument value.
			J domain.Job
		}
		// FailJob holds details about calls to the FailJob method.
		FailJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Code is the code argument value.
			Code domain.FailureCode
			// Message is the message argument value.
			Message string
			// StderrTail is the stderrTail argument value.
			StderrTail string
		}
		// GetJob holds details about calls to the GetJob method.
		GetJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetMediaFile holds details about calls to the GetMediaFile method.
		GetMediaFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetSettings holds details about calls to the GetSettings method.
		GetSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetThroughputStat holds details about calls to the GetThroughputStat method.
		GetThroughputStat []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Kind is the kind argument value.
			Kind domain.Kind
			// Encoder is the encoder argument value.
			Encoder string
			// Resolution is the resolution argument value.
			Resolution string
		}
		// ListMediaFiles holds details about calls to the ListMediaFiles method.
		ListMediaFiles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// F is the f argument value.
			F store.MediaFilter
		}
		// ListRoots holds details about calls to the ListRoots method.
		ListRoots []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// RecordPromotion holds details about calls to the RecordPromotion method.
		RecordPromotion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// U is the u argument value.
			U store.PromotionUpdate
		}
		// RequeueInterruptedJob holds details about calls to the RequeueInterruptedJob method.
		RequeueInterruptedJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// RestartJob holds details about calls to the RestartJob method.
		RestartJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// SetJobBlockedBy holds details about calls to the SetJobBlockedBy method.
		SetJobBlockedBy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// BlockedBy is the blockedBy argument value.
			BlockedBy string
		}
		// SetJobState holds details about calls to the SetJobState method.
		SetJobState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// State is the state argument value.
			State domain.JobState
		}
		// SetMediaStatus holds details about calls to the SetMediaStatus method.
		SetMediaStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Status is the status argument value.
			Status domain.MediaStatus
			// LastError is the lastError argument value.
			LastError string
		}
		// SweepInterruptedJobs holds details about calls to the SweepInterruptedJobs method.
		SweepInterruptedJobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdateJobExecution holds details about calls to the UpdateJobExecution method.
		UpdateJobExecution []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// U is the u argument value.
			U store.ExecutionUpdate
		}
		// UpdateJobProgress holds details about calls to the UpdateJobProgress method.
		UpdateJobProgress []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Pct is the pct argument value.
			Pct float64
			// Speed is the speed argument value.
			Speed float64
			// Fps is the fps argument value.
			Fps float64
			// EstimatedSeconds is the estimatedSeconds argument value.
			EstimatedSeconds int
		}
		// UpdateJobTransform holds details about calls to the UpdateJobTransform method.
		UpdateJobTransform []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// T is the t argument value.
			T domain.TransformRecord
		}
		// UpdateSettings holds details about calls to the UpdateSettings method.
		UpdateSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S domain.Settings
		}
		// UpsertThroughputStat holds details about calls to the UpsertThroughputStat method.
		UpsertThroughputStat []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S domain.ThroughputStat
		}
	}
	lockActiveJobForMedia     sync.RWMutex
	lockCancelJob             sync.RWMutex
	lockClaimNextJob          sync.RWMutex
	lockCountJobsByState      sync.RWMutex
	lockEnqueueJob            sync.RWMutex
	lockFailJob               sync.RWMutex
	lockGetJob                sync.RWMutex
	lockGetMediaFile          sync.RWMutex
	lockGetSettings           sync.RWMutex
	lockGetThroughputStat     sync.RWMutex
	lockListMediaFiles        sync.RWMutex
	lockListRoots             sync.RWMutex
	lockRecordPromotion       sync.RWMutex
	lockRequeueInterruptedJob sync.RWMutex
	lockRestartJob            sync.RWMutex
	lockSetJobBlockedBy       sync.RWMutex
	lockSetJobState           sync.RWMutex
	lockSetMediaStatus        sync.RWMutex
	lockSweepInterruptedJobs  sync.RWMutex
	lockUpdateJobExecution    sync.RWMutex
	lockUpdateJobProgress     sync.RWMutex
	lockUpdateJobTransform    sync.RWMutex
	lockUpdateSettings        sync.RWMutex
	lockUpsertThroughputStat  sync.RWMutex
}

// ActiveJobForMedia calls ActiveJobForMediaFunc.
func (mock *StoreMock) ActiveJobForMedia(ctx context.Context, mediaFileID int64) (domain.Job, bool, error) {
	if mock.ActiveJobForMediaFunc == nil {
		panic("StoreMock.ActiveJobForMediaFunc: method is nil but Store.ActiveJobForMedia was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		MediaFileID int64
	}{
		Ctx:         ctx,
		MediaFileID: mediaFileID,
	}
	mock.lockActiveJobForMedia.Lock()
	mock.calls.ActiveJobForMedia = append(mock.calls.ActiveJobForMedia, callInfo)
	mock.lockActiveJobForMedia.Unlock()
	return mock.ActiveJobForMediaFunc(ctx, mediaFileID)
}

// ActiveJobForMediaCalls gets all the calls that were made to ActiveJobForMedia.
// Check the length with:
//
//	len(mockedStore.ActiveJobForMediaCalls())
func (mock *StoreMock) ActiveJobForMediaCalls() []struct {
	Ctx         context.Context
	MediaFileID int64
} {
	var calls []struct {
		Ctx         context.Context
		MediaFileID int64
	}
	mock.lockActiveJobForMedia.RLock()
	calls = mock.calls.ActiveJobForMedia
	mock.lockActiveJobForMedia.RUnlock()
	return calls
}

// CancelJob calls CancelJobFunc.
func (mock *StoreMock) CancelJob(ctx context.Context, id int64) error {
	if mock.CancelJobFunc == nil {
		panic("StoreMock.CancelJobFunc: method is nil but Store.CancelJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockCancelJob.Lock()
	mock.calls.CancelJob = append(mock.calls.CancelJob, callInfo)
	mock.lockCancelJob.Unlock()
	return mock.CancelJobFunc(ctx, id)
}

// CancelJobCalls gets all the calls that were made to CancelJob.
// Check the length with:
//
//	len(mockedStore.CancelJobCalls())
func (mock *StoreMock) CancelJobCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockCancelJob.RLock()
	calls = mock.calls.CancelJob
	mock.lockCancelJob.RUnlock()
	return calls
}

// ClaimNextJob calls ClaimNextJobFunc.
func (mock *StoreMock) ClaimNextJob(ctx context.Context) (domain.Job, bool, error) {
	if mock.ClaimNextJobFunc == nil {
		panic("StoreMock.ClaimNextJobFunc: method is nil but Store.ClaimNextJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockClaimNextJob.Lock()
	mock.calls.ClaimNextJob = append(mock.calls.ClaimNextJob, callInfo)
	mock.lockClaimNextJob.Unlock()
	return mock.ClaimNextJobFunc(ctx)
}

// ClaimNextJobCalls gets all the calls that were made to ClaimNextJob.
// Check the length with:
//
//	len(mockedStore.ClaimNextJobCalls())
func (mock *StoreMock) ClaimNextJobCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockClaimNextJob.RLock()
	calls = mock.calls.ClaimNextJob
	mock.lockClaimNextJob.RUnlock()
	return calls
}

// CountJobsByState calls CountJobsByStateFunc.
func (mock *StoreMock) CountJobsByState(ctx context.Context) (map[domain.JobState]int, error) {
	if mock.CountJobsByStateFunc == nil {
		panic("StoreMock.CountJobsByStateFunc: method is nil but Store.CountJobsByState was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCountJobsByState.Lock()
	mock.calls.CountJobsByState = append(mock.calls.CountJobsByState, callInfo)
	mock.lockCountJobsByState.Unlock()
	return mock.CountJobsByStateFunc(ctx)
}

// CountJobsByStateCalls gets all the calls that were made to CountJobsByState.
// Check the length with:
//
//	len(mockedStore.CountJobsByStateCalls())
func (mock *StoreMock) CountJobsByStateCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCountJobsByState.RLock()
	calls = mock.calls.CountJobsByState
	mock.lockCountJobsByState.RUnlock()
	return calls
}

// EnqueueJob calls EnqueueJobFunc.
func (mock *StoreMock) EnqueueJob(ctx context.Context, j domain.Job) (domain.Job, bool, error) {
	if mock.EnqueueJobFunc == nil {
		panic("StoreMock.EnqueueJobFunc: method is nil but Store.EnqueueJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		J   domain.Job
	}{
		Ctx: ctx,
		J:   j,
	}
	mock.lockEnqueueJob.Lock()
	mock.calls.EnqueueJob = append(mock.calls.EnqueueJob, callInfo)
	mock.lockEnqueueJob.Unlock()
	return mock.EnqueueJobFunc(ctx, j)
}

// EnqueueJobCalls gets all the calls that were made to EnqueueJob.
// Check the length with:
//
//	len(mockedStore.EnqueueJobCalls())
func (mock *StoreMock) EnqueueJobCalls() []struct {
	Ctx context.Context
	J   domain.Job
} {
	var calls []struct {
		Ctx context.Context
		J   domain.Job
	}
	mock.lockEnqueueJob.RLock()
	calls = mock.calls.EnqueueJob
	mock.lockEnqueueJob.RUnlock()
	return calls
}

// FailJob calls FailJobFunc.
func (mock *StoreMock) FailJob(ctx context.Context, id int64, code domain.FailureCode, message string, stderrTail string) error {
	if mock.FailJobFunc == nil {
		panic("StoreMock.FailJobFunc: method is nil but Store.FailJob was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ID         int64
		Code       domain.FailureCode
		Message    string
		StderrTail string
	}{
		Ctx:        ctx,
		ID:         id,
		Code:       code,
		Message:    message,
		StderrTail: stderrTail,
	}
	mock.lockFailJob.Lock()
	mock.calls.FailJob = append(mock.calls.FailJob, callInfo)
	mock.lockFailJob.Unlock()
	return mock.FailJobFunc(ctx, id, code, message, stderrTail)
}

// FailJobCalls gets all the calls that were made to FailJob.
// Check the length with:
//
//	len(mockedStore.FailJobCalls())
func (mock *StoreMock) FailJobCalls() []struct {
	Ctx        context.Context
	ID         int64
	Code       domain.FailureCode
	Message    string
	StderrTail string
} {
	var calls []struct {
		Ctx        context.Context
		ID         int64
		Code       domain.FailureCode
		Message    string
		StderrTail string
	}
	mock.lockFailJob.RLock()
	calls = mock.calls.FailJob
	mock.lockFailJob.RUnlock()
	return calls
}

// GetJob calls GetJobFunc.
func (mock *StoreMock) GetJob(ctx context.Context, id int64) (domain.Job, error) {
	if mock.GetJobFunc == nil {
		panic("StoreMock.GetJobFunc: method is nil but Store.GetJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetJob.Lock()
	mock.calls.GetJob = append(mock.calls.GetJob, callInfo)
	mock.lockGetJob.Unlock()
	return mock.GetJobFunc(ctx, id)
}

// GetJobCalls gets all the calls that were made to GetJob.
// Check the length with:
//
//	len(mockedStore.GetJobCalls())
func (mock *StoreMock) GetJobCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetJob.RLock()
	calls = mock.calls.GetJob
	mock.lockGetJob.RUnlock()
	return calls
}

// GetMediaFile calls GetMediaFileFunc.
func (mock *StoreMock) GetMediaFile(ctx context.Context, id int64) (domain.MediaFile, error) {
	if mock.GetMediaFileFunc == nil {
		panic("StoreMock.GetMediaFileFunc: method is nil but Store.GetMediaFile was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetMediaFile.Lock()
	mock.calls.GetMediaFile = append(mock.calls.GetMediaFile, callInfo)
	mock.lockGetMediaFile.Unlock()
	return mock.GetMediaFileFunc(ctx, id)
}

// GetMediaFileCalls gets all the calls that were made to GetMediaFile.
// Check the length with:
//
//	len(mockedStore.GetMediaFileCalls())
func (mock *StoreMock) GetMediaFileCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetMediaFile.RLock()
	calls = mock.calls.GetMediaFile
	mock.lockGetMediaFile.RUnlock()
	return calls
}

// GetSettings calls GetSettingsFunc.
func (mock *StoreMock) GetSettings(ctx context.Context) (domain.Settings, error) {
	if mock.GetSettingsFunc == nil {
		panic("StoreMock.GetSettingsFunc: method is nil but Store.GetSettings was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetSettings.Lock()
	mock.calls.GetSettings = append(mock.calls.GetSettings, callInfo)
	mock.lockGetSettings.Unlock()
	return mock.GetSettingsFunc(ctx)
}

// GetSettingsCalls gets all the calls that were made to GetSettings.
// Check the length with:
//
//	len(mockedStore.GetSettingsCalls())
func (mock *StoreMock) GetSettingsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetSettings.RLock()
	calls = mock.calls.GetSettings
	mock.lockGetSettings.RUnlock()
	return calls
}

// GetThroughputStat calls GetThroughputStatFunc.
func (mock *StoreMock) GetThroughputStat(ctx context.Context, kind domain.Kind, encoder string, resolution string) (domain.ThroughputStat, error) {
	if mock.GetThroughputStatFunc == nil {
		panic("StoreMock.GetThroughputStatFunc: method is nil but Store.GetThroughputStat was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Kind       domain.Kind
		Encoder    string
		Resolution string
	}{
		Ctx:        ctx,
		Kind:       kind,
		Encoder:    encoder,
		Resolution: resolution,
	}
	mock.lockGetThroughputStat.Lock()
	mock.calls.GetThroughputStat = append(mock.calls.GetThroughputStat, callInfo)
	mock.lockGetThroughputStat.Unlock()
	return mock.GetThroughputStatFunc(ctx, kind, encoder, resolution)
}

// GetThroughputStatCalls gets all the calls that were made to GetThroughputStat.
// Check the length with:
//
//	len(mockedStore.GetThroughputStatCalls())
func (mock *StoreMock) GetThroughputStatCalls() []struct {
	Ctx        context.Context
	Kind       domain.Kind
	Encoder    string
	Resolution string
} {
	var calls []struct {
		Ctx        context.Context
		Kind       domain.Kind
		Encoder    string
		Resolution string
	}
	mock.lockGetThroughputStat.RLock()
	calls = mock.calls.GetThroughputStat
	mock.lockGetThroughputStat.RUnlock()
	return calls
}

// ListMediaFiles calls ListMediaFilesFunc.
func (mock *StoreMock) ListMediaFiles(ctx context.Context, f store.MediaFilter) ([]domain.MediaFile, int, error) {
	if mock.ListMediaFilesFunc == nil {
		panic("StoreMock.ListMediaFilesFunc: method is nil but Store.ListMediaFiles was just called")
	}
	callInfo := struct {
		Ctx context.Context
		F   store.MediaFilter
	}{
		Ctx: ctx,
		F:   f,
	}
	mock.lockListMediaFiles.Lock()
	mock.calls.ListMediaFiles = append(mock.calls.ListMediaFiles, callInfo)
	mock.lockListMediaFiles.Unlock()
	return mock.ListMediaFilesFunc(ctx, f)
}

// ListMediaFilesCalls gets all the calls that were made to ListMediaFiles.
// Check the length with:
//
//	len(mockedStore.ListMediaFilesCalls())
func (mock *StoreMock) ListMediaFilesCalls() []struct {
	Ctx context.Context
	F   store.MediaFilter
} {
	var calls []struct {
		Ctx context.Context
		F   store.MediaFilter
	}
	mock.lockListMediaFiles.RLock()
	calls = mock.calls.ListMediaFiles
	mock.lockListMediaFiles.RUnlock()
	return calls
}

// ListRoots calls ListRootsFunc.
func (mock *StoreMock) ListRoots(ctx context.Context) ([]domain.Root, error) {
	if mock.ListRootsFunc == nil {
		panic("StoreMock.ListRootsFunc: method is nil but Store.ListRoots was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListRoots.Lock()
	mock.calls.ListRoots = append(mock.calls.ListRoots, callInfo)
	mock.lockListRoots.Unlock()
	return mock.ListRootsFunc(ctx)
}

// ListRootsCalls gets all the calls that were made to ListRoots.
// Check the length with:
//
//	len(mockedStore.ListRootsCalls())
func (mock *StoreMock) ListRootsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListRoots.RLock()
	calls = mock.calls.ListRoots
	mock.lockListRoots.RUnlock()
	return calls
}

// RecordPromotion calls RecordPromotionFunc.
func (mock *StoreMock) RecordPromotion(ctx context.Context, u store.PromotionUpdate) error {
	if mock.RecordPromotionFunc == nil {
		panic("StoreMock.RecordPromotionFunc: method is nil but Store.RecordPromotion was just called")
	}
	callInfo := struct {
		Ctx context.Context
		U   store.PromotionUpdate
	}{
		Ctx: ctx,
		U:   u,
	}
	mock.lockRecordPromotion.Lock()
	mock.calls.RecordPromotion = append(mock.calls.RecordPromotion, callInfo)
	mock.lockRecordPromotion.Unlock()
	return mock.RecordPromotionFunc(ctx, u)
}

// RecordPromotionCalls gets all the calls that were made to RecordPromotion.
// Check the length with:
//
//	len(mockedStore.RecordPromotionCalls())
func (mock *StoreMock) RecordPromotionCalls() []struct {
	Ctx context.Context
	U   store.PromotionUpdate
} {
	var calls []struct {
		Ctx context.Context
		U   store.PromotionUpdate
	}
	mock.lockRecordPromotion.RLock()
	calls = mock.calls.RecordPromotion
	mock.lockRecordPromotion.RUnlock()
	return calls
}

// RequeueInterruptedJob calls RequeueInterruptedJobFunc.
func (mock *StoreMock) RequeueInterruptedJob(ctx context.Context, id int64) (store.SweepResult, error) {
	if mock.RequeueInterruptedJobFunc == nil {
		panic("StoreMock.RequeueInterruptedJobFunc: method is nil but Store.RequeueInterruptedJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockRequeueInterruptedJob.Lock()
	mock.calls.RequeueInterruptedJob = append(mock.calls.RequeueInterruptedJob, callInfo)
	mock.lockRequeueInterruptedJob.Unlock()
	return mock.RequeueInterruptedJobFunc(ctx, id)
}

// RequeueInterruptedJobCalls gets all the calls that were made to RequeueInterruptedJob.
// Check the length with:
//
//	len(mockedStore.RequeueInterruptedJobCalls())
func (mock *StoreMock) RequeueInterruptedJobCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockRequeueInterruptedJob.RLock()
	calls = mock.calls.RequeueInterruptedJob
	mock.lockRequeueInterruptedJob.RUnlock()
	return calls
}

// RestartJob calls RestartJobFunc.
func (mock *StoreMock) RestartJob(ctx context.Context, id int64) (domain.Job, error) {
	if mock.RestartJobFunc == nil {
		panic("StoreMock.RestartJobFunc: method is nil but Store.RestartJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockRestartJob.Lock()
	mock.calls.RestartJob = append(mock.calls.RestartJob, callInfo)
	mock.lockRestartJob.Unlock()
	return mock.RestartJobFunc(ctx, id)
}

// RestartJobCalls gets all the calls that were made to RestartJob.
// Check the length with:
//
//	len(mockedStore.RestartJobCalls())
func (mock *StoreMock) RestartJobCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockRestartJob.RLock()
	calls = mock.calls.RestartJob
	mock.lockRestartJob.RUnlock()
	return calls
}

// SetJobBlockedBy calls SetJobBlockedByFunc.
func (mock *StoreMock) SetJobBlockedBy(ctx context.Context, id int64, blockedBy string) error {
	if mock.SetJobBlockedByFunc == nil {
		panic("StoreMock.SetJobBlockedByFunc: method is nil but Store.SetJobBlockedBy was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ID        int64
		BlockedBy string
	}{
		Ctx:       ctx,
		ID:        id,
		BlockedBy: blockedBy,
	}
	mock.lockSetJobBlockedBy.Lock()
	mock.calls.SetJobBlockedBy = append(mock.calls.SetJobBlockedBy, callInfo)
	mock.lockSetJobBlockedBy.Unlock()
	return mock.SetJobBlockedByFunc(ctx, id, blockedBy)
}

// SetJobBlockedByCalls gets all the calls that were made to SetJobBlockedBy.
// Check the length with:
//
//	len(mockedStore.SetJobBlockedByCalls())
func (mock *StoreMock) SetJobBlockedByCalls() []struct {
	Ctx       context.Context
	ID        int64
	BlockedBy string
} {
	var calls []struct {
		Ctx       context.Context
		ID        int64
		BlockedBy string
	}
	mock.lockSetJobBlockedBy.RLock()
	calls = mock.calls.SetJobBlockedBy
	mock.lockSetJobBlockedBy.RUnlock()
	return calls
}

// SetJobState calls SetJobStateFunc.
func (mock *StoreMock) SetJobState(ctx context.Context, id int64, state domain.JobState) error {
	if mock.SetJobStateFunc == nil {
		panic("StoreMock.SetJobStateFunc: method is nil but Store.SetJobState was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		ID    int64
		State domain.JobState
	}{
		Ctx:   ctx,
		ID:    id,
		State: state,
	}
	mock.lockSetJobState.Lock()
	mock.calls.SetJobState = append(mock.calls.SetJobState, callInfo)
	mock.lockSetJobState.Unlock()
	return mock.SetJobStateFunc(ctx, id, state)
}

// SetJobStateCalls gets all the calls that were made to SetJobState.
// Check the length with:
//
//	len(mockedStore.SetJobStateCalls())
func (mock *StoreMock) SetJobStateCalls() []struct {
	Ctx   context.Context
	ID    int64
	State domain.JobState
} {
	var calls []struct {
		Ctx   context.Context
		ID    int64
		State domain.JobState
	}
	mock.lockSetJobState.RLock()
	calls = mock.calls.SetJobState
	mock.lockSetJobState.RUnlock()
	return calls
}

// SetMediaStatus calls SetMediaStatusFunc.
func (mock *StoreMock) SetMediaStatus(ctx context.Context, id int64, status domain.MediaStatus, lastError string) error {
	if mock.SetMediaStatusFunc == nil {
		panic("StoreMock.SetMediaStatusFunc: method is nil but Store.SetMediaStatus was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ID        int64
		Status    domain.MediaStatus
		LastError string
	}{
		Ctx:       ctx,
		ID:        id,
		Status:    status,
		LastError: lastError,
	}
	mock.lockSetMediaStatus.Lock()
	mock.calls.SetMediaStatus = append(mock.calls.SetMediaStatus, callInfo)
	mock.lockSetMediaStatus.Unlock()
	return mock.SetMediaStatusFunc(ctx, id, status, lastError)
}

// SetMediaStatusCalls gets all the calls that were made to SetMediaStatus.
// Check the length with:
//
//	len(mockedStore.SetMediaStatusCalls())
func (mock *StoreMock) SetMediaStatusCalls() []struct {
	Ctx       context.Context
	ID        int64
	Status    domain.MediaStatus
	LastError string
} {
	var calls []struct {
		Ctx       context.Context
		ID        int64
		Status    domain.MediaStatus
		LastError string
	}
	mock.lockSetMediaStatus.RLock()
	calls = mock.calls.SetMediaStatus
	mock.lockSetMediaStatus.RUnlock()
	return calls
}

// SweepInterruptedJobs calls SweepInterruptedJobsFunc.
func (mock *StoreMock) SweepInterruptedJobs(ctx context.Context) ([]store.SweepResult, error) {
	if mock.SweepInterruptedJobsFunc == nil {
		panic("StoreMock.SweepInterruptedJobsFunc: method is nil but Store.SweepInterruptedJobs was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockSweepInterruptedJobs.Lock()
	mock.calls.SweepInterruptedJobs = append(mock.calls.SweepInterruptedJobs, callInfo)
	mock.lockSweepInterruptedJobs.Unlock()
	return mock.SweepInterruptedJobsFunc(ctx)
}

// SweepInterruptedJobsCalls gets all the calls that were made to SweepInterruptedJobs.
// Check the length with:
//
//	len(mockedStore.SweepInterruptedJobsCalls())
func (mock *StoreMock) SweepInterruptedJobsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockSweepInterruptedJobs.RLock()
	calls = mock.calls.SweepInterruptedJobs
	mock.lockSweepInterruptedJobs.RUnlock()
	return calls
}

// UpdateJobExecution calls UpdateJobExecutionFunc.
func (mock *StoreMock) UpdateJobExecution(ctx context.Context, u store.ExecutionUpdate) error {
	if mock.UpdateJobExecutionFunc == nil {
		panic("StoreMock.UpdateJobExecutionFunc: method is nil but Store.UpdateJobExecution was just called")
	}
	callInfo := struct {
		Ctx context.Context
		U   store.ExecutionUpdate
	}{
		Ctx: ctx,
		U:   u,
	}
	mock.lockUpdateJobExecution.Lock()
	mock.calls.UpdateJobExecution = append(mock.calls.UpdateJobExecution, callInfo)
	mock.lockUpdateJobExecution.Unlock()
	return mock.UpdateJobExecutionFunc(ctx, u)
}

// UpdateJobExecutionCalls gets all the calls that were made to UpdateJobExecution.
// Check the length with:
//
//	len(mockedStore.UpdateJobExecutionCalls())
func (mock *StoreMock) UpdateJobExecutionCalls() []struct {
	Ctx context.Context
	U   store.ExecutionUpdate
} {
	var calls []struct {
		Ctx context.Context
		U   store.ExecutionUpdate
	}
	mock.lockUpdateJobExecution.RLock()
	calls = mock.calls.UpdateJobExecution
	mock.lockUpdateJobExecution.RUnlock()
	return calls
}

// UpdateJobProgress calls UpdateJobProgressFunc.
func (mock *StoreMock) UpdateJobProgress(ctx context.Context, id int64, pct float64, speed float64, fps float64, estimatedSeconds int) error {
	if mock.UpdateJobProgressFunc == nil {
		panic("StoreMock.UpdateJobProgressFunc: method is nil but Store.UpdateJobProgress was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		ID               int64
		Pct              float64
		Speed            float64
		Fps              float64
		EstimatedSeconds int
	}{
		Ctx:              ctx,
		ID:               id,
		Pct:              pct,
		Speed:            speed,
		Fps:              fps,
		EstimatedSeconds: estimatedSeconds,
	}
	mock.lockUpdateJobProgress.Lock()
	mock.calls.UpdateJobProgress = append(mock.calls.UpdateJobProgress, callInfo)
	mock.lockUpdateJobProgress.Unlock()
	return mock.UpdateJobProgressFunc(ctx, id, pct, speed, fps, estimatedSeconds)
}

// UpdateJobProgressCalls gets all the calls that were made to UpdateJobProgress.
// Check the length with:
//
//	len(mockedStore.UpdateJobProgressCalls())
func (mock *StoreMock) UpdateJobProgressCalls() []struct {
	Ctx              context.Context
	ID               int64
	Pct              float64
	Speed            float64
	Fps              float64
	EstimatedSeconds int
} {
	var calls []struct {
		Ctx              context.Context
		ID               int64
		Pct              float64
		Speed            float64
		Fps              float64
		EstimatedSeconds int
	}
	mock.lockUpdateJobProgress.RLock()
	calls = mock.calls.UpdateJobProgress
	mock.lockUpdateJobProgress.RUnlock()
	return calls
}

// UpdateJobTransform calls UpdateJobTransformFunc.
func (mock *StoreMock) UpdateJobTransform(ctx context.Context, id int64, t domain.TransformRecord) error {
	if mock.UpdateJobTransformFunc == nil {
		panic("StoreMock.UpdateJobTransformFunc: method is nil but Store.UpdateJobTransform was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
		T   domain.TransformRecord
	}{
		Ctx: ctx,
		ID:  id,
		T:   t,
	}
	mock.lockUpdateJobTransform.Lock()
	mock.calls.UpdateJobTransform = append(mock.calls.UpdateJobTransform, callInfo)
	mock.lockUpdateJobTransform.Unlock()
	return mock.UpdateJobTransformFunc(ctx, id, t)
}

// UpdateJobTransformCalls gets all the calls that were made to UpdateJobTransform.
// Check the length with:
//
//	len(mockedStore.UpdateJobTransformCalls())
func (mock *StoreMock) UpdateJobTransformCalls() []struct {
	Ctx context.Context
	ID  int64
	T   domain.TransformRecord
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
		T   domain.TransformRecord
	}
	mock.lockUpdateJobTransform.RLock()
	calls = mock.calls.UpdateJobTransform
	mock.lockUpdateJobTransform.RUnlock()
	return calls
}

// UpdateSettings calls UpdateSettingsFunc.
func (mock *StoreMock) UpdateSettings(ctx context.Context, s domain.Settings) error {
	if mock.UpdateSettingsFunc == nil {
		panic("StoreMock.UpdateSettingsFunc: method is nil but Store.UpdateSettings was just called")
	}
	callInfo := struct {
		Ctx context.Context
		S   domain.Settings
	}{
		Ctx: ctx,
		S:   s,
	}
	mock.lockUpdateSettings.Lock()
	mock.calls.UpdateSettings = append(mock.calls.UpdateSettings, callInfo)
	mock.lockUpdateSettings.Unlock()
	return mock.UpdateSettingsFunc(ctx, s)
}

// UpdateSettingsCalls gets all the calls that were made to UpdateSettings.
// Check the length with:
//
//	len(mockedStore.UpdateSettingsCalls())
func (mock *StoreMock) UpdateSettingsCalls() []struct {
	Ctx context.Context
	S   domain.Settings
} {
	var calls []struct {
		Ctx context.Context
		S   domain.Settings
	}
	mock.lockUpdateSettings.RLock()
	calls = mock.calls.UpdateSettings
	mock.lockUpdateSettings.RUnlock()
	return calls
}

// UpsertThroughputStat calls UpsertThroughputStatFunc.
func (mock *StoreMock) UpsertThroughputStat(ctx context.Context, s domain.ThroughputStat) error {
	if mock.UpsertThroughputStatFunc == nil {
		panic("StoreMock.UpsertThroughputStatFunc: method is nil but Store.UpsertThroughputStat was just called")
	}
	callInfo := struct {
		Ctx context.Context
		S   domain.ThroughputStat
	}{
		Ctx: ctx,
		S:   s,
	}
	mock.lockUpsertThroughputStat.Lock()
	mock.calls.UpsertThroughputStat = append(mock.calls.UpsertThroughputStat, callInfo)
	mock.lockUpsertThroughputStat.Unlock()
	return mock.UpsertThroughputStatFunc(ctx, s)
}

// UpsertThroughputStatCalls gets all the calls that were made to UpsertThroughputStat.
// Check the length with:
//
//	len(mockedStore.UpsertThroughputStatCalls())
func (mock *StoreMock) UpsertThroughputStatCalls() []struct {
	Ctx context.Context
	S   domain.ThroughputStat
} {
	var calls []struct {
		Ctx context.Context
		S   domain.ThroughputStat
	}
	mock.lockUpsertThroughputStat.RLock()
	calls = mock.calls.UpsertThroughputStat
	mock.lockUpsertThroughputStat.RUnlock()
	return calls
}

// Ensure, that ProberMock does implement job.Prober.
// If this is not the case, regenerate this file with moq.
var _ job.Prober = &ProberMock{}

// ProberMock is a mock implementation of job.Prober.
//
//	func TestSomethingThatUsesProber(t *testing.T) {
//
//		// make and configure a mocked job.Prober
//		mockedProber := &ProberMock{
//			ProbeFunc: func(ctx context.Context, path string) (*ffprobe.Result, error) {
//				panic("mock out the Probe method")
//			},
//		}
//
//		// use mockedProber in code that requires job.Prober
//		// and then make assertions.
//
//	}
type ProberMock struct {
	// ProbeFunc mocks the Probe method.
	ProbeFunc func(ctx context.Context, path string) (*ffprobe.Result, error)

	// calls tracks calls to the methods.
	calls struct {
		// Probe holds details about calls to the Probe method.
		Probe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
	}
	lockProbe sync.RWMutex
}

// Probe calls ProbeFunc.
func (mock *ProberMock) Probe(ctx context.Context, path string) (*ffprobe.Result, error) {
	if mock.ProbeFunc == nil {
		panic("ProberMock.ProbeFunc: method is nil but Prober.Probe was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockProbe.Lock()
	mock.calls.Probe = append(mock.calls.Probe, callInfo)
	mock.lockProbe.Unlock()
	return mock.ProbeFunc(ctx, path)
}

// ProbeCalls gets all the calls that were made to Probe.
// Check the length with:
//
//	len(mockedProber.ProbeCalls())
func (mock *ProberMock) ProbeCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockProbe.RLock()
	calls = mock.calls.Probe
	mock.lockProbe.RUnlock()
	return calls
}

// Ensure, that EncoderMock does implement job.Encoder.
// If this is not the case, regenerate this file with moq.
var _ job.Encoder = &EncoderMock{}

// EncoderMock is a mock implementation of job.Encoder.
//
//	func TestSomethingThatUsesEncoder(t *testing.T) {
//
//		// make and configure a mocked job.Encoder
//		mockedEncoder := &EncoderMock{
//			RunFunc: func(ctx context.Context, args []string, progress func(p ffmpeg.Progress)) (ffmpeg.RunResult, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedEncoder in code that requires job.Encoder
//		// and then make assertions.
//
//	}
type EncoderMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, args []string, progress func(p ffmpeg.Progress)) (ffmpeg.RunResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args []string
			// Progress is the progress argument value.
			Progress func(p ffmpeg.Progress)
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *EncoderMock) Run(ctx context.Context, args []string, progress func(p ffmpeg.Progress)) (ffmpeg.RunResult, error) {
	if mock.RunFunc == nil {
		panic("EncoderMock.RunFunc: method is nil but Encoder.Run was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Args     []string
		Progress func(p ffmpeg.Progress)
	}{
		Ctx:      ctx,
		Args:     args,
		Progress: progress,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, args, progress)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedEncoder.RunCalls())
func (mock *EncoderMock) RunCalls() []struct {
	Ctx      context.Context
	Args     []string
	Progress func(p ffmpeg.Progress)
} {
	var calls []struct {
		Ctx      context.Context
		Args     []string
		Progress func(p ffmpeg.Progress)
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// Ensure, that PromoterMock does implement job.Promoter.
// If this is not the case, regenerate this file with moq.
var _ job.Promoter = &PromoterMock{}

// PromoterMock is a mock implementation of job.Promoter.
//
//	func TestSomethingThatUsesPromoter(t *testing.T) {
//
//		// make and configure a mocked job.Promoter
//		mockedPromoter := &PromoterMock{
//			PreflightFunc: func(req promote.PreflightRequest) (promote.Staging, error) {
//				panic("mock out the Preflight method")
//			},
//			PromoteFunc: func(ctx context.Context, req promote.Request) (promote.Result, error) {
//				panic("mock out the Promote method")
//			},
//			SweepFunc: func(ctx context.Context, roots []string, claimed []string) ([]string, error) {
//				panic("mock out the Sweep method")
//			},
//			VerifyFunc: func(ctx context.Context, req promote.Request) ([]string, error) {
//				panic("mock out the Verify method")
//			},
//		}
//
//		// use mockedPromoter in code that requires job.Promoter
//		// and then make assertions.
//
//	}
type PromoterMock struct {
	// PreflightFunc mocks the Preflight method.
	PreflightFunc func(req promote.PreflightRequest) (promote.Staging, error)

	// PromoteFunc mocks the Promote method.
	PromoteFunc func(ctx context.Context, req promote.Request) (promote.Result, error)

	// SweepFunc mocks the Sweep method.
	SweepFunc func(ctx context.Context, roots []string, claimed []string) ([]string, error)

	// VerifyFunc mocks the Verify method.
	VerifyFunc func(ctx context.Context, req promote.Request) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Preflight holds details about calls to the Preflight method.
		Preflight []struct {
			// Req is the req argument value.
			Req promote.PreflightRequest
		}
		// Promote holds details about calls to the Promote method.
		Promote []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req promote.Request
		}
		// Sweep holds details about calls to the Sweep method.
		Sweep []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Roots is the roots argument value.
			Roots []string
			// Claimed is the claimed argument value.
			Claimed []string
		}
		// Verify holds details about calls to the Verify method.
		Verify []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req promote.Request
		}
	}
	lockPreflight sync.RWMutex
	lockPromote   sync.RWMutex
	lockSweep     sync.RWMutex
	lockVerify    sync.RWMutex
}

// Preflight calls PreflightFunc.
func (mock *PromoterMock) Preflight(req promote.PreflightRequest) (promote.Staging, error) {
	if mock.PreflightFunc == nil {
		panic("PromoterMock.PreflightFunc: method is nil but Promoter.Preflight was just called")
	}
	callInfo := struct {
		Req promote.PreflightRequest
	}{
		Req: req,
	}
	mock.lockPreflight.Lock()
	mock.calls.Preflight = append(mock.calls.Preflight, callInfo)
	mock.lockPreflight.Unlock()
	return mock.PreflightFunc(req)
}

// PreflightCalls gets all the calls that were made to Preflight.
// Check the length with:
//
//	len(mockedPromoter.PreflightCalls())
func (mock *PromoterMock) PreflightCalls() []struct {
	Req promote.PreflightRequest
} {
	var calls []struct {
		Req promote.PreflightRequest
	}
	mock.lockPreflight.RLock()
	calls = mock.calls.Preflight
	mock.lockPreflight.RUnlock()
	return calls
}

// Promote calls PromoteFunc.
func (mock *PromoterMock) Promote(ctx context.Context, req promote.Request) (promote.Result, error) {
	if mock.PromoteFunc == nil {
		panic("PromoterMock.PromoteFunc: method is nil but Promoter.Promote was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req promote.Request
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockPromote.Lock()
	mock.calls.Promote = append(mock.calls.Promote, callInfo)
	mock.lockPromote.Unlock()
	return mock.PromoteFunc(ctx, req)
}

// PromoteCalls gets all the calls that were made to Promote.
// Check the length with:
//
//	len(mockedPromoter.PromoteCalls())
func (mock *PromoterMock) PromoteCalls() []struct {
	Ctx context.Context
	Req promote.Request
} {
	var calls []struct {
		Ctx context.Context
		Req promote.Request
	}
	mock.lockPromote.RLock()
	calls = mock.calls.Promote
	mock.lockPromote.RUnlock()
	return calls
}

// Sweep calls SweepFunc.
func (mock *PromoterMock) Sweep(ctx context.Context, roots []string, claimed []string) ([]string, error) {
	if mock.SweepFunc == nil {
		panic("PromoterMock.SweepFunc: method is nil but Promoter.Sweep was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Roots   []string
		Claimed []string
	}{
		Ctx:     ctx,
		Roots:   roots,
		Claimed: claimed,
	}
	mock.lockSweep.Lock()
	mock.calls.Sweep = append(mock.calls.Sweep, callInfo)
	mock.lockSweep.Unlock()
	return mock.SweepFunc(ctx, roots, claimed)
}

// SweepCalls gets all the calls that were made to Sweep.
// Check the length with:
//
//	len(mockedPromoter.SweepCalls())
func (mock *PromoterMock) SweepCalls() []struct {
	Ctx     context.Context
	Roots   []string
	Claimed []string
} {
	var calls []struct {
		Ctx     context.Context
		Roots   []string
		Claimed []string
	}
	mock.lockSweep.RLock()
	calls = mock.calls.Sweep
	mock.lockSweep.RUnlock()
	return calls
}

// Verify calls VerifyFunc.
func (mock *PromoterMock) Verify(ctx context.Context, req promote.Request) ([]string, error) {
	if mock.VerifyFunc == nil {
		panic("PromoterMock.VerifyFunc: method is nil but Promoter.Verify was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req promote.Request
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockVerify.Lock()
	mock.calls.Verify = append(mock.calls.Verify, callInfo)
	mock.lockVerify.Unlock()
	return mock.VerifyFunc(ctx, req)
}

// VerifyCalls gets all the calls that were made to Verify.
// Check the length with:
//
//	len(mockedPromoter.VerifyCalls())
func (mock *PromoterMock) VerifyCalls() []struct {
	Ctx context.Context
	Req promote.Request
} {
	var calls []struct {
		Ctx context.Context
		Req promote.Request
	}
	mock.lockVerify.RLock()
	calls = mock.calls.Verify
	mock.lockVerify.RUnlock()
	return calls
}

// Ensure, that FSMock does implement job.FS.
// If this is not the case, regenerate this file with moq.
var _ job.FS = &FSMock{}

// FSMock is a mock implementation of job.FS.
//
//	func TestSomethingThatUsesFS(t *testing.T) {
//
//		// make and configure a mocked job.FS
//		mockedFS := &FSMock{
//			MkdirAllFunc: func(path string, mode os.FileMode) error {
//				panic("mock out the MkdirAll method")
//			},
//			RemoveFunc: func(path string) error {
//				panic("mock out the Remove method")
//			},
//			StatFunc: func(path string) (fsx.FileInfo, error) {
//				panic("mock out the Stat method")
//			},
//		}
//
//		// use mockedFS in code that requires job.FS
//		// and then make assertions.
//
//	}
type FSMock struct {
	// MkdirAllFunc mocks the MkdirAll method.
	MkdirAllFunc func(path string, mode os.FileMode) error

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(path string) error

	// StatFunc mocks the Stat method.
	StatFunc func(path string) (fsx.FileInfo, error)

	// calls tracks calls to the methods.
	calls struct {
		// MkdirAll holds details about calls to the MkdirAll method.
		MkdirAll []struct {
			// Path is the path argument value.
			Path string
			// Mode is the mode argument value.
			Mode os.FileMode
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Path is the path argument value.
			Path string
		}
		// Stat holds details about calls to the Stat method.
		Stat []struct {
			// Path is the path argument value.
			Path string
		}
	}
	lockMkdirAll sync.RWMutex
	lockRemove   sync.RWMutex
	lockStat     sync.RWMutex
}

// MkdirAll calls MkdirAllFunc.
func (mock *FSMock) MkdirAll(path string, mode os.FileMode) error {
	if mock.MkdirAllFunc == nil {
		panic("FSMock.MkdirAllFunc: method is nil but FS.MkdirAll was just called")
	}
	callInfo := struct {
		Path string
		Mode os.FileMode
	}{
		Path: path,
		Mode: mode,
	}
	mock.lockMkdirAll.Lock()
	mock.calls.MkdirAll = append(mock.calls.MkdirAll, callInfo)
	mock.lockMkdirAll.Unlock()
	return mock.MkdirAllFunc(path, mode)
}

// MkdirAllCalls gets all the calls that were made to MkdirAll.
// Check the length with:
//
//	len(mockedFS.MkdirAllCalls())
func (mock *FSMock) MkdirAllCalls() []struct {
	Path string
	Mode os.FileMode
} {
	var calls []struct {
		Path string
		Mode os.FileMode
	}
	mock.lockMkdirAll.RLock()
	calls = mock.calls.MkdirAll
	mock.lockMkdirAll.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *FSMock) Remove(path string) error {
	if mock.RemoveFunc == nil {
		panic("FSMock.RemoveFunc: method is nil but FS.Remove was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(path)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedFS.RemoveCalls())
func (mock *FSMock) RemoveCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}

// Stat calls StatFunc.
func (mock *FSMock) Stat(path string) (fsx.FileInfo, error) {
	if mock.StatFunc == nil {
		panic("FSMock.StatFunc: method is nil but FS.Stat was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockStat.Lock()
	mock.calls.Stat = append(mock.calls.Stat, callInfo)
	mock.lockStat.Unlock()
	return mock.StatFunc(path)
}

// StatCalls gets all the calls that were made to Stat.
// Check the length with:
//
//	len(mockedFS.StatCalls())
func (mock *FSMock) StatCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockStat.RLock()
	calls = mock.calls.Stat
	mock.lockStat.RUnlock()
	return calls
}

// Ensure, that FingerprinterMock does implement job.Fingerprinter.
// If this is not the case, regenerate this file with moq.
var _ job.Fingerprinter = &FingerprinterMock{}

// FingerprinterMock is a mock implementation of job.Fingerprinter.
//
//	func TestSomethingThatUsesFingerprinter(t *testing.T) {
//
//		// make and configure a mocked job.Fingerprinter
//		mockedFingerprinter := &FingerprinterMock{
//			SparseFunc: func(path string) (string, error) {
//				panic("mock out the Sparse method")
//			},
//		}
//
//		// use mockedFingerprinter in code that requires job.Fingerprinter
//		// and then make assertions.
//
//	}
type FingerprinterMock struct {
	// SparseFunc mocks the Sparse method.
	SparseFunc func(path string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Sparse holds details about calls to the Sparse method.
		Sparse []struct {
			// Path is the path argument value.
			Path string
		}
	}
	lockSparse sync.RWMutex
}

// Sparse calls SparseFunc.
func (mock *FingerprinterMock) Sparse(path string) (string, error) {
	if mock.SparseFunc == nil {
		panic("FingerprinterMock.SparseFunc: method is nil but Fingerprinter.Sparse was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockSparse.Lock()
	mock.calls.Sparse = append(mock.calls.Sparse, callInfo)
	mock.lockSparse.Unlock()
	return mock.SparseFunc(path)
}

// SparseCalls gets all the calls that were made to Sparse.
// Check the length with:
//
//	len(mockedFingerprinter.SparseCalls())
func (mock *FingerprinterMock) SparseCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockSparse.RLock()
	calls = mock.calls.Sparse
	mock.lockSparse.RUnlock()
	return calls
}

// Ensure, that NotifierMock does implement job.Notifier.
// If this is not the case, regenerate this file with moq.
var _ job.Notifier = &NotifierMock{}

// NotifierMock is a mock implementation of job.Notifier.
//
//	func TestSomethingThatUsesNotifier(t *testing.T) {
//
//		// make and configure a mocked job.Notifier
//		mockedNotifier := &NotifierMock{
//			NotifyPromotedFunc: func(ctx context.Context, path string) error {
//				panic("mock out the NotifyPromoted method")
//			},
//		}
//
//		// use mockedNotifier in code that requires job.Notifier
//		// and then make assertions.
//
//	}
type NotifierMock struct {
	// NotifyPromotedFunc mocks the NotifyPromoted method.
	NotifyPromotedFunc func(ctx context.Context, path string) error

	// calls tracks calls to the methods.
	calls struct {
		// NotifyPromoted holds details about calls to the NotifyPromoted method.
		NotifyPromoted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
	}
	lockNotifyPromoted sync.RWMutex
}

// NotifyPromoted calls NotifyPromotedFunc.
func (mock *NotifierMock) NotifyPromoted(ctx context.Context, path string) error {
	if mock.NotifyPromotedFunc == nil {
		panic("NotifierMock.NotifyPromotedFunc: method is nil but Notifier.NotifyPromoted was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockNotifyPromoted.Lock()
	mock.calls.NotifyPromoted = append(mock.calls.NotifyPromoted, callInfo)
	mock.lockNotifyPromoted.Unlock()
	return mock.NotifyPromotedFunc(ctx, path)
}

// NotifyPromotedCalls gets all the calls that were made to NotifyPromoted.
// Check the length with:
//
//	len(mockedNotifier.NotifyPromotedCalls())
func (mock *NotifierMock) NotifyPromotedCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockNotifyPromoted.RLock()
	calls = mock.calls.NotifyPromoted
	mock.lockNotifyPromoted.RUnlock()
	return calls
}

// Ensure, that HardwareMock does implement job.Hardware.
// If this is not the case, regenerate this file with moq.
var _ job.Hardware = &HardwareMock{}

// HardwareMock is a mock implementation of job.Hardware.
//
//	func TestSomethingThatUsesHardware(t *testing.T) {
//
//		// make and configure a mocked job.Hardware
//		mockedHardware := &HardwareMock{
//			CapabilitiesFunc: func(ctx context.Context) (hardware.Capabilities, error) {
//				panic("mock out the Capabilities method")
//			},
//		}
//
//		// use mockedHardware in code that requires job.Hardware
//		// and then make assertions.
//
//	}
type HardwareMock struct {
	// CapabilitiesFunc mocks the Capabilities method.
	CapabilitiesFunc func(ctx context.Context) (hardware.Capabilities, error)

	// calls tracks calls to the methods.
	calls struct {
		// Capabilities holds details about calls to the Capabilities method.
		Capabilities []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockCapabilities sync.RWMutex
}

// Capabilities calls CapabilitiesFunc.
func (mock *HardwareMock) Capabilities(ctx context.Context) (hardware.Capabilities, error) {
	if mock.CapabilitiesFunc == nil {
		panic("HardwareMock.CapabilitiesFunc: method is nil but Hardware.Capabilities was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCapabilities.Lock()
	mock.calls.Capabilities = append(mock.calls.Capabilities, callInfo)
	mock.lockCapabilities.Unlock()
	return mock.CapabilitiesFunc(ctx)
}

// CapabilitiesCalls gets all the calls that were made to Capabilities.
// Check the length with:
//
//	len(mockedHardware.CapabilitiesCalls())
func (mock *HardwareMock) CapabilitiesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCapabilities.RLock()
	calls = mock.calls.Capabilities
	mock.lockCapabilities.RUnlock()
	return calls
}

// Ensure, that AnalyzerMock does implement job.Analyzer.
// If this is not the case, regenerate this file with moq.
var _ job.Analyzer = &AnalyzerMock{}

// AnalyzerMock is a mock implementation of job.Analyzer.
//
//	func TestSomethingThatUsesAnalyzer(t *testing.T) {
//
//		// make and configure a mocked job.Analyzer
//		mockedAnalyzer := &AnalyzerMock{
//			AnalyzeFunc: func(ctx context.Context, m domain.MediaFile) (domain.MediaFile, error) {
//				panic("mock out the Analyze method")
//			},
//		}
//
//		// use mockedAnalyzer in code that requires job.Analyzer
//		// and then make assertions.
//
//	}
type AnalyzerMock struct {
	// AnalyzeFunc mocks the Analyze method.
	AnalyzeFunc func(ctx context.Context, m domain.MediaFile) (domain.MediaFile, error)

	// calls tracks calls to the methods.
	calls struct {
		// Analyze holds details about calls to the Analyze method.
		Analyze []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// M is the m argument value.
			M domain.MediaFile
		}
	}
	lockAnalyze sync.RWMutex
}

// Analyze calls AnalyzeFunc.
func (mock *AnalyzerMock) Analyze(ctx context.Context, m domain.MediaFile) (domain.MediaFile, error) {
	if mock.AnalyzeFunc == nil {
		panic("AnalyzerMock.AnalyzeFunc: method is nil but Analyzer.Analyze was just called")
	}
	callInfo := struct {
		Ctx context.Context
		M   domain.MediaFile
	}{
		Ctx: ctx,
		M:   m,
	}
	mock.lockAnalyze.Lock()
	mock.calls.Analyze = append(mock.calls.Analyze, callInfo)
	mock.lockAnalyze.Unlock()
	return mock.AnalyzeFunc(ctx, m)
}

// AnalyzeCalls gets all the calls that were made to Analyze.
// Check the length with:
//
//	len(mockedAnalyzer.AnalyzeCalls())
func (mock *AnalyzerMock) AnalyzeCalls() []struct {
	Ctx context.Context
	M   domain.MediaFile
} {
	var calls []struct {
		Ctx context.Context
		M   domain.MediaFile
	}
	mock.lockAnalyze.RLock()
	calls = mock.calls.Analyze
	mock.lockAnalyze.RUnlock()
	return calls
}
