// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/yama6a/codarr/internal/pkg/fsx"
	"io"
	"os"
	"sync"
	"time"
)

// Ensure, that FSMock does implement fsx.FS.
// If this is not the case, regenerate this file with moq.
var _ fsx.FS = &FSMock{}

// FSMock is a mock implementation of fsx.FS.
//
//	func TestSomethingThatUsesFS(t *testing.T) {
//
//		// make and configure a mocked fsx.FS
//		mockedFS := &FSMock{
//			ChmodFunc: func(path string, mode os.FileMode) error {
//				panic("mock out the Chmod method")
//			},
//			ChownFunc: func(path string, uid int, gid int) error {
//				panic("mock out the Chown method")
//			},
//			ChtimesFunc: func(path string, atime time.Time, mtime time.Time) error {
//				panic("mock out the Chtimes method")
//			},
//			CopyFunc: func(ctx context.Context, src string, dst string) (int64, error) {
//				panic("mock out the Copy method")
//			},
//			CreateFunc: func(path string, mode os.FileMode) (fsx.WriteSyncCloser, error) {
//				panic("mock out the Create method")
//			},
//			GlobFunc: func(pattern string) ([]string, error) {
//				panic("mock out the Glob method")
//			},
//			MkdirAllFunc: func(path string, mode os.FileMode) error {
//				panic("mock out the MkdirAll method")
//			},
//			OpenFunc: func(path string) (io.ReadSeekCloser, error) {
//				panic("mock out the Open method")
//			},
//			RemoveFunc: func(path string) error {
//				panic("mock out the Remove method")
//			},
//			RenameFunc: func(oldpath string, newpath string) error {
//				panic("mock out the Rename method")
//			},
//			StatFunc: func(path string) (fsx.FileInfo, error) {
//				panic("mock out the Stat method")
//			},
//			StatfsFunc: func(path string) (fsx.SpaceInfo, error) {
//				panic("mock out the Statfs method")
//			},
//			SyncDirFunc: func(path string) error {
//				panic("mock out the SyncDir method")
//			},
//			SyncFileFunc: func(path string) error {
//				panic("mock out the SyncFile method")
//			},
//			WalkDirFunc: func(root string, fn func(path string, info fsx.FileInfo, err error) error) error {
//				panic("mock out the WalkDir method")
//			},
//		}
//
//		// use mockedFS in code that requires fsx.FS
//		// and then make assertions.
//
//	}
type FSMock struct {
	// ChmodFunc mocks the Chmod method.
	ChmodFunc func(path string, mode os.FileMode) error

	// ChownFunc mocks the Chown method.
	ChownFunc func(path string, uid int, gid int) error

	// ChtimesFunc mocks the Chtimes method.
	ChtimesFunc func(path string, atime time.Time, mtime time.Time) error

	// CopyFunc mocks the Copy method.
	CopyFunc func(ctx context.Context, src string, dst string) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(path string, mode os.FileMode) (fsx.WriteSyncCloser, error)

	// GlobFunc mocks the Glob method.
	GlobFunc func(pattern string) ([]string, error)

	// MkdirAllFunc mocks the MkdirAll method.
	MkdirAllFunc func(path string, mode os.FileMode) error

	// OpenFunc mocks the Open method.
	OpenFunc func(path string) (io.ReadSeekCloser, error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(path string) error

	// RenameFunc mocks the Rename method.
	RenameFunc func(oldpath string, newpath string) error

	// StatFunc mocks the Stat method.
	StatFunc func(path string) (fsx.FileInfo, error)

	// StatfsFunc mocks the Statfs method.
	StatfsFunc func(path string) (fsx.SpaceInfo, error)

	// SyncDirFunc mocks the SyncDir method.
	SyncDirFunc func(path string) error

	// SyncFileFunc mocks the SyncFile method.
	SyncFileFunc func(path string) error

	// WalkDirFunc mocks the WalkDir method.
	WalkDirFunc func(root string, fn func(path string, info fsx.FileInfo, err error) error) error

	// calls tracks calls to the methods.
	calls struct {
		// Chmod holds details about calls to the Chmod method.
		Chmod []struct {
			// Path is the path argument value.
			Path string
			// Mode is the mode argument value.
			Mode os.FileMode
		}
		// Chown holds details about calls to the Chown method.
		Chown []struct {
			// Path is the path argument value.
			Path string
			// UID is the uid argument value.
			UID int
			// Gid is the gid argument value.
			Gid int
		}
		// Chtimes holds details about calls to the Chtimes method.
		Chtimes []struct {
			// Path is the path argument value.
			Path string
			// Atime is the atime argument value.
			Atime time.Time
			// Mtime is the mtime argument value.
			Mtime time.Time
		}
		// Copy holds details about calls to the Copy method.
		Copy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Src is the src argument value.
			Src string
			// Dst is the dst argument value.
			Dst string
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Path is the path argument value.
			Path string
			// Mode is the mode argument value.
			Mode os.FileMode
		}
		// Glob holds details about calls to the Glob method.
		Glob []struct {
			// Pattern is the pattern argument value.
			Pattern string
		}
		// MkdirAll holds details about calls to the MkdirAll method.
		MkdirAll []struct {
			// Path is the path argument value.
			Path string
			// Mode is the mode argument value.
			Mode os.FileMode
		}
		// Open holds details about calls to the Open method.
		Open []struct {
			// Path is the path argument value.
			Path string
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Path is the path argument value.
			Path string
		}
		// Rename holds details about calls to the Rename method.
		Rename []struct {
			// Oldpath is the oldpath argument value.
			Oldpath string
			// Newpath is the newpath argument value.
			Newpath string
		}
		// Stat holds details about calls to the Stat method.
		Stat []struct {
			// Path is the path argument value.
			Path string
		}
		// Statfs holds details about calls to the Statfs method.
		Statfs []struct {
			// Path is the path argument value.
			Path string
		}
		// SyncDir holds details about calls to the SyncDir method.
		SyncDir []struct {
			// Path is the path argument value.
			Path string
		}
		// SyncFile holds details about calls to the SyncFile method.
		SyncFile []struct {
			// Path is the path argument value.
			Path string
		}
		// WalkDir holds details about calls to the WalkDir method.
		WalkDir []struct {
			// Root is the root argument value.
			Root string
			// Fn is the fn argument value.
			Fn func(path string, info fsx.FileInfo, err error) error
		}
	}
	lockChmod    sync.RWMutex
	lockChown    sync.RWMutex
	lockChtimes  sync.RWMutex
	lockCopy     sync.RWMutex
	lockCreate   sync.RWMutex
	lockGlob     sync.RWMutex
	lockMkdirAll sync.RWMutex
	lockOpen     sync.RWMutex
	lockRemove   sync.RWMutex
	lockRename   sync.RWMutex
	lockStat     sync.RWMutex
	lockStatfs   sync.RWMutex
	lockSyncDir  sync.RWMutex
	lockSyncFile sync.RWMutex
	lockWalkDir  sync.RWMutex
}

// Chmod calls ChmodFunc.
func (mock *FSMock) Chmod(path string, mode os.FileMode) error {
	if mock.ChmodFunc == nil {
		panic("FSMock.ChmodFunc: method is nil but FS.Chmod was just called")
	}
	callInfo := struct {
		Path string
		Mode os.FileMode
	}{
		Path: path,
		Mode: mode,
	}
	mock.lockChmod.Lock()
	mock.calls.Chmod = append(mock.calls.Chmod, callInfo)
	mock.lockChmod.Unlock()
	return mock.ChmodFunc(path, mode)
}

// ChmodCalls gets all the calls that were made to Chmod.
// Check the length with:
//
//	len(mockedFS.ChmodCalls())
func (mock *FSMock) ChmodCalls() []struct {
	Path string
	Mode os.FileMode
} {
	var calls []struct {
		Path string
		Mode os.FileMode
	}
	mock.lockChmod.RLock()
	calls = mock.calls.Chmod
	mock.lockChmod.RUnlock()
	return calls
}

// Chown calls ChownFunc.
func (mock *FSMock) Chown(path string, uid int, gid int) error {
	if mock.ChownFunc == nil {
		panic("FSMock.ChownFunc: method is nil but FS.Chown was just called")
	}
	callInfo := struct {
		Path string
		UID  int
		Gid  int
	}{
		Path: path,
		UID:  uid,
		Gid:  gid,
	}
	mock.lockChown.Lock()
	mock.calls.Chown = append(mock.calls.Chown, callInfo)
	mock.lockChown.Unlock()
	return mock.ChownFunc(path, uid, gid)
}

// ChownCalls gets all the calls that were made to Chown.
// Check the length with:
//
//	len(mockedFS.ChownCalls())
func (mock *FSMock) ChownCalls() []struct {
	Path string
	UID  int
	Gid  int
} {
	var calls []struct {
		Path string
		UID  int
		Gid  int
	}
	mock.lockChown.RLock()
	calls = mock.calls.Chown
	mock.lockChown.RUnlock()
	return calls
}

// Chtimes calls ChtimesFunc.
func (mock *FSMock) Chtimes(path string, atime time.Time, mtime time.Time) error {
	if mock.ChtimesFunc == nil {
		panic("FSMock.ChtimesFunc: method is nil but FS.Chtimes was just called")
	}
	callInfo := struct {
		Path  string
		Atime time.Time
		Mtime time.Time
	}{
		Path:  path,
		Atime: atime,
		Mtime: mtime,
	}
	mock.lockChtimes.Lock()
	mock.calls.Chtimes = append(mock.calls.Chtimes, callInfo)
	mock.lockChtimes.Unlock()
	return mock.ChtimesFunc(path, atime, mtime)
}

// ChtimesCalls gets all the calls that were made to Chtimes.
// Check the length with:
//
//	len(mockedFS.ChtimesCalls())
func (mock *FSMock) ChtimesCalls() []struct {
	Path  string
	Atime time.Time
	Mtime time.Time
} {
	var calls []struct {
		Path  string
		Atime time.Time
		Mtime time.Time
	}
	mock.lockChtimes.RLock()
	calls = mock.calls.Chtimes
	mock.lockChtimes.RUnlock()
	return calls
}

// Copy calls CopyFunc.
func (mock *FSMock) Copy(ctx context.Context, src string, dst string) (int64, error) {
	if mock.CopyFunc == nil {
		panic("FSMock.CopyFunc: method is nil but FS.Copy was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Src string
		Dst string
	}{
		Ctx: ctx,
		Src: src,
		Dst: dst,
	}
	mock.lockCopy.Lock()
	mock.calls.Copy = append(mock.calls.Copy, callInfo)
	mock.lockCopy.Unlock()
	return mock.CopyFunc(ctx, src, dst)
}

// CopyCalls gets all the calls that were made to Copy.
// Check the length with:
//
//	len(mockedFS.CopyCalls())
func (mock *FSMock) CopyCalls() []struct {
	Ctx context.Context
	Src string
	Dst string
} {
	var calls []struct {
		Ctx context.Context
		Src string
		Dst string
	}
	mock.lockCopy.RLock()
	calls = mock.calls.Copy
	mock.lockCopy.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *FSMock) Create(path string, mode os.FileMode) (fsx.WriteSyncCloser, error) {
	if mock.CreateFunc == nil {
		panic("FSMock.CreateFunc: method is nil but FS.Create was just called")
	}
	callInfo := struct {
		Path string
		Mode os.FileMode
	}{
		Path: path,
		Mode: mode,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(path, mode)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedFS.CreateCalls())
func (mock *FSMock) CreateCalls() []struct {
	Path string
	Mode os.FileMode
} {
	var calls []struct {
		Path string
		Mode os.FileMode
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Glob calls GlobFunc.
func (mock *FSMock) Glob(pattern string) ([]string, error) {
	if mock.GlobFunc == nil {
		panic("FSMock.GlobFunc: method is nil but FS.Glob was just called")
	}
	callInfo := struct {
		Pattern string
	}{
		Pattern: pattern,
	}
	mock.lockGlob.Lock()
	mock.calls.Glob = append(mock.calls.Glob, callInfo)
	mock.lockGlob.Unlock()
	return mock.GlobFunc(pattern)
}

// GlobCalls gets all the calls that were made to Glob.
// Check the length with:
//
//	len(mockedFS.GlobCalls())
func (mock *FSMock) GlobCalls() []struct {
	Pattern string
} {
	var calls []struct {
		Pattern string
	}
	mock.lockGlob.RLock()
	calls = mock.calls.Glob
	mock.lockGlob.RUnlock()
	return calls
}

// MkdirAll calls MkdirAllFunc.
func (mock *FSMock) MkdirAll(path string, mode os.FileMode) error {
	if mock.MkdirAllFunc == nil {
		panic("FSMock.MkdirAllFunc: method is nil but FS.MkdirAll was just called")
	}
	callInfo := struct {
		Path string
		Mode os.FileMode
	}{
		Path: path,
		Mode: mode,
	}
	mock.lockMkdirAll.Lock()
	mock.calls.MkdirAll = append(mock.calls.MkdirAll, callInfo)
	mock.lockMkdirAll.Unlock()
	return mock.MkdirAllFunc(path, mode)
}

// MkdirAllCalls gets all the calls that were made to MkdirAll.
// Check the length with:
//
//	len(mockedFS.MkdirAllCalls())
func (mock *FSMock) MkdirAllCalls() []struct {
	Path string
	Mode os.FileMode
} {
	var calls []struct {
		Path string
		Mode os.FileMode
	}
	mock.lockMkdirAll.RLock()
	calls = mock.calls.MkdirAll
	mock.lockMkdirAll.RUnlock()
	return calls
}

// Open calls OpenFunc.
func (mock *FSMock) Open(path string) (io.ReadSeekCloser, error) {
	if mock.OpenFunc == nil {
		panic("FSMock.OpenFunc: method is nil but FS.Open was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockOpen.Lock()
	mock.calls.Open = append(mock.calls.Open, callInfo)
	mock.lockOpen.Unlock()
	return mock.OpenFunc(path)
}

// OpenCalls gets all the calls that were made to Open.
// Check the length with:
//
//	len(mockedFS.OpenCalls())
func (mock *FSMock) OpenCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockOpen.RLock()
	calls = mock.calls.Open
	mock.lockOpen.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *FSMock) Remove(path string) error {
	if mock.RemoveFunc == nil {
		panic("FSMock.RemoveFunc: method is nil but FS.Remove was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(path)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedFS.RemoveCalls())
func (mock *FSMock) RemoveCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}

// Rename calls RenameFunc.
func (mock *FSMock) Rename(oldpath string, newpath string) error {
	if mock.RenameFunc == nil {
		panic("FSMock.RenameFunc: method is nil but FS.Rename was just called")
	}
	callInfo := struct {
		Oldpath string
		Newpath string
	}{
		Oldpath: oldpath,
		Newpath: newpath,
	}
	mock.lockRename.Lock()
	mock.calls.Rename = append(mock.calls.Rename, callInfo)
	mock.lockRename.Unlock()
	return mock.RenameFunc(oldpath, newpath)
}

// RenameCalls gets all the calls that were made to Rename.
// Check the length with:
//
//	len(mockedFS.RenameCalls())
func (mock *FSMock) RenameCalls() []struct {
	Oldpath string
	Newpath string
} {
	var calls []struct {
		Oldpath string
		Newpath string
	}
	mock.lockRename.RLock()
	calls = mock.calls.Rename
	mock.lockRename.RUnlock()
	return calls
}

// Stat calls StatFunc.
func (mock *FSMock) Stat(path string) (fsx.FileInfo, error) {
	if mock.StatFunc == nil {
		panic("FSMock.StatFunc: method is nil but FS.Stat was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockStat.Lock()
	mock.calls.Stat = append(mock.calls.Stat, callInfo)
	mock.lockStat.Unlock()
	return mock.StatFunc(path)
}

// StatCalls gets all the calls that were made to Stat.
// Check the length with:
//
//	len(mockedFS.StatCalls())
func (mock *FSMock) StatCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockStat.RLock()
	calls = mock.calls.Stat
	mock.lockStat.RUnlock()
	return calls
}

// Statfs calls StatfsFunc.
func (mock *FSMock) Statfs(path string) (fsx.SpaceInfo, error) {
	if mock.StatfsFunc == nil {
		panic("FSMock.StatfsFunc: method is nil but FS.Statfs was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockStatfs.Lock()
	mock.calls.Statfs = append(mock.calls.Statfs, callInfo)
	mock.lockStatfs.Unlock()
	return mock.StatfsFunc(path)
}

// StatfsCalls gets all the calls that were made to Statfs.
// Check the length with:
//
//	len(mockedFS.StatfsCalls())
func (mock *FSMock) StatfsCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockStatfs.RLock()
	calls = mock.calls.Statfs
	mock.lockStatfs.RUnlock()
	return calls
}

// SyncDir calls SyncDirFunc.
func (mock *FSMock) SyncDir(path string) error {
	if mock.SyncDirFunc == nil {
		panic("FSMock.SyncDirFunc: method is nil but FS.SyncDir was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockSyncDir.Lock()
	mock.calls.SyncDir = append(mock.calls.SyncDir, callInfo)
	mock.lockSyncDir.Unlock()
	return mock.SyncDirFunc(path)
}

// SyncDirCalls gets all the calls that were made to SyncDir.
// Check the length with:
//
//	len(mockedFS.SyncDirCalls())
func (mock *FSMock) SyncDirCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockSyncDir.RLock()
	calls = mock.calls.SyncDir
	mock.lockSyncDir.RUnlock()
	return calls
}

// SyncFile calls SyncFileFunc.
func (mock *FSMock) SyncFile(path string) error {
	if mock.SyncFileFunc == nil {
		panic("FSMock.SyncFileFunc: method is nil but FS.SyncFile was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockSyncFile.Lock()
	mock.calls.SyncFile = append(mock.calls.SyncFile, callInfo)
	mock.lockSyncFile.Unlock()
	return mock.SyncFileFunc(path)
}

// SyncFileCalls gets all the calls that were made to SyncFile.
// Check the length with:
//
//	len(mockedFS.SyncFileCalls())
func (mock *FSMock) SyncFileCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockSyncFile.RLock()
	calls = mock.calls.SyncFile
	mock.lockSyncFile.RUnlock()
	return calls
}

// WalkDir calls WalkDirFunc.
func (mock *FSMock) WalkDir(root string, fn func(path string, info fsx.FileInfo, err error) error) error {
	if mock.WalkDirFunc == nil {
		panic("FSMock.WalkDirFunc: method is nil but FS.WalkDir was just called")
	}
	callInfo := struct {
		Root string
		Fn   func(path string, info fsx.FileInfo, err error) error
	}{
		Root: root,
		Fn:   fn,
	}
	mock.lockWalkDir.Lock()
	mock.calls.WalkDir = append(mock.calls.WalkDir, callInfo)
	mock.lockWalkDir.Unlock()
	return mock.WalkDirFunc(root, fn)
}

// WalkDirCalls gets all the calls that were made to WalkDir.
// Check the length with:
//
//	len(mockedFS.WalkDirCalls())
func (mock *FSMock) WalkDirCalls() []struct {
	Root string
	Fn   func(path string, info fsx.FileInfo, err error) error
} {
	var calls []struct {
		Root string
		Fn   func(path string, info fsx.FileInfo, err error) error
	}
	mock.lockWalkDir.RLock()
	calls = mock.calls.WalkDir
	mock.lockWalkDir.RUnlock()
	return calls
}
