// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/yama6a/codarr/internal/ffmpeg"
	"sync"
)

// Ensure, that EncoderMock does implement ffmpeg.Encoder.
// If this is not the case, regenerate this file with moq.
var _ ffmpeg.Encoder = &EncoderMock{}

// EncoderMock is a mock implementation of ffmpeg.Encoder.
//
//	func TestSomethingThatUsesEncoder(t *testing.T) {
//
//		// make and configure a mocked ffmpeg.Encoder
//		mockedEncoder := &EncoderMock{
//			RunFunc: func(ctx context.Context, args []string, progress func(ffmpeg.Progress)) (ffmpeg.RunResult, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedEncoder in code that requires ffmpeg.Encoder
//		// and then make assertions.
//
//	}
type EncoderMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, args []string, progress func(ffmpeg.Progress)) (ffmpeg.RunResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args []string
			// Progress is the progress argument value.
			Progress func(ffmpeg.Progress)
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *EncoderMock) Run(ctx context.Context, args []string, progress func(ffmpeg.Progress)) (ffmpeg.RunResult, error) {
	if mock.RunFunc == nil {
		panic("EncoderMock.RunFunc: method is nil but Encoder.Run was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Args     []string
		Progress func(ffmpeg.Progress)
	}{
		Ctx:      ctx,
		Args:     args,
		Progress: progress,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, args, progress)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedEncoder.RunCalls())
func (mock *EncoderMock) RunCalls() []struct {
	Ctx      context.Context
	Args     []string
	Progress func(ffmpeg.Progress)
} {
	var calls []struct {
		Ctx      context.Context
		Args     []string
		Progress func(ffmpeg.Progress)
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
