// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/yama6a/codarr/internal/ffprobe"
	"sync"
)

// Ensure, that ProberMock does implement ffprobe.Prober.
// If this is not the case, regenerate this file with moq.
var _ ffprobe.Prober = &ProberMock{}

// ProberMock is a mock implementation of ffprobe.Prober.
//
//	func TestSomethingThatUsesProber(t *testing.T) {
//
//		// make and configure a mocked ffprobe.Prober
//		mockedProber := &ProberMock{
//			ProbeFunc: func(ctx context.Context, path string) (*ffprobe.Result, error) {
//				panic("mock out the Probe method")
//			},
//		}
//
//		// use mockedProber in code that requires ffprobe.Prober
//		// and then make assertions.
//
//	}
type ProberMock struct {
	// ProbeFunc mocks the Probe method.
	ProbeFunc func(ctx context.Context, path string) (*ffprobe.Result, error)

	// calls tracks calls to the methods.
	calls struct {
		// Probe holds details about calls to the Probe method.
		Probe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
	}
	lockProbe sync.RWMutex
}

// Probe calls ProbeFunc.
func (mock *ProberMock) Probe(ctx context.Context, path string) (*ffprobe.Result, error) {
	if mock.ProbeFunc == nil {
		panic("ProberMock.ProbeFunc: method is nil but Prober.Probe was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockProbe.Lock()
	mock.calls.Probe = append(mock.calls.Probe, callInfo)
	mock.lockProbe.Unlock()
	return mock.ProbeFunc(ctx, path)
}

// ProbeCalls gets all the calls that were made to Probe.
// Check the length with:
//
//	len(mockedProber.ProbeCalls())
func (mock *ProberMock) ProbeCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockProbe.RLock()
	calls = mock.calls.Probe
	mock.lockProbe.RUnlock()
	return calls
}
