// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/yama6a/codarr/internal/api"
	"github.com/yama6a/codarr/internal/arr"
	"github.com/yama6a/codarr/internal/hardware"
	"github.com/yama6a/codarr/internal/ingest"
	"github.com/yama6a/codarr/internal/job"
	"github.com/yama6a/codarr/internal/pkg/domain"
	"github.com/yama6a/codarr/internal/pkg/fsx"
	"github.com/yama6a/codarr/internal/pkg/store"
	"github.com/yama6a/codarr/internal/plex"
	"sync"
	"time"
)

// Ensure, that StoreMock does implement api.Store.
// If this is not the case, regenerate this file with moq.
var _ api.Store = &StoreMock{}

// StoreMock is a mock implementation of api.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked api.Store
//		mockedStore := &StoreMock{
//			CountJobsByStateFunc: func(ctx context.Context) (map[domain.JobState]int, error) {
//				panic("mock out the CountJobsByState method")
//			},
//			CountMediaByPlanKindFunc: func(ctx context.Context) (map[domain.Kind]int, error) {
//				panic("mock out the CountMediaByPlanKind method")
//			},
//			CountMediaByStatusFunc: func(ctx context.Context) (map[domain.MediaStatus]int, error) {
//				panic("mock out the CountMediaByStatus method")
//			},
//			CreateArrInstanceFunc: func(ctx context.Context, a domain.ArrInstance) (domain.ArrInstance, error) {
//				panic("mock out the CreateArrInstance method")
//			},
//			CreateRootFunc: func(ctx context.Context, r domain.Root) (domain.Root, error) {
//				panic("mock out the CreateRoot method")
//			},
//			DeleteArrInstanceFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the DeleteArrInstance method")
//			},
//			DeleteRootFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the DeleteRoot method")
//			},
//			GetArrInstanceFunc: func(ctx context.Context, id int64) (domain.ArrInstance, error) {
//				panic("mock out the GetArrInstance method")
//			},
//			GetArrInstanceByWebhookIDFunc: func(ctx context.Context, webhookID string) (domain.ArrInstance, error) {
//				panic("mock out the GetArrInstanceByWebhookID method")
//			},
//			GetJobFunc: func(ctx context.Context, id int64) (domain.Job, error) {
//				panic("mock out the GetJob method")
//			},
//			GetMediaFileFunc: func(ctx context.Context, id int64) (domain.MediaFile, error) {
//				panic("mock out the GetMediaFile method")
//			},
//			GetPlexConfigFunc: func(ctx context.Context) (domain.PlexConfig, error) {
//				panic("mock out the GetPlexConfig method")
//			},
//			GetRootFunc: func(ctx context.Context, id int64) (domain.Root, error) {
//				panic("mock out the GetRoot method")
//			},
//			GetSettingsFunc: func(ctx context.Context) (domain.Settings, error) {
//				panic("mock out the GetSettings method")
//			},
//			ListArrInstancesFunc: func(ctx context.Context) ([]domain.ArrInstance, error) {
//				panic("mock out the ListArrInstances method")
//			},
//			ListArrPathMappingsFunc: func(ctx context.Context, arrInstanceID int64) ([]domain.PathMapping, error) {
//				panic("mock out the ListArrPathMappings method")
//			},
//			ListEventsFunc: func(ctx context.Context, f store.EventFilter) ([]domain.Event, error) {
//				panic("mock out the ListEvents method")
//			},
//			ListHWCapabilitiesFunc: func(ctx context.Context) ([]domain.HWCapability, error) {
//				panic("mock out the ListHWCapabilities method")
//			},
//			ListJobsFunc: func(ctx context.Context, f store.JobFilter) ([]domain.Job, int, error) {
//				panic("mock out the ListJobs method")
//			},
//			ListMediaFilesFunc: func(ctx context.Context, f store.MediaFilter) ([]domain.MediaFile, int, error) {
//				panic("mock out the ListMediaFiles method")
//			},
//			ListPlexPathMappingsFunc: func(ctx context.Context) ([]domain.PathMapping, error) {
//				panic("mock out the ListPlexPathMappings method")
//			},
//			ListRootsFunc: func(ctx context.Context) ([]domain.Root, error) {
//				panic("mock out the ListRoots method")
//			},
//			ReplaceArrPathMappingsFunc: func(ctx context.Context, arrInstanceID int64, m []domain.PathMapping) error {
//				panic("mock out the ReplaceArrPathMappings method")
//			},
//			ReplacePlexPathMappingsFunc: func(ctx context.Context, m []domain.PathMapping) error {
//				panic("mock out the ReplacePlexPathMappings method")
//			},
//			SetArrTestResultFunc: func(ctx context.Context, id int64, at time.Time, result string) error {
//				panic("mock out the SetArrTestResult method")
//			},
//			SetMediaIgnoredFunc: func(ctx context.Context, id int64, ignored bool) error {
//				panic("mock out the SetMediaIgnored method")
//			},
//			SetMediaIntegrityFunc: func(ctx context.Context, id int64, fingerprint string, fullHash string, at time.Time) error {
//				panic("mock out the SetMediaIntegrity method")
//			},
//			SetPlexTestResultFunc: func(ctx context.Context, at time.Time, result string) error {
//				panic("mock out the SetPlexTestResult method")
//			},
//			StatsFunc: func(ctx context.Context) (store.Stats, error) {
//				panic("mock out the Stats method")
//			},
//			UpdateArrInstanceFunc: func(ctx context.Context, a domain.ArrInstance) error {
//				panic("mock out the UpdateArrInstance method")
//			},
//			UpdatePlexConfigFunc: func(ctx context.Context, c domain.PlexConfig) error {
//				panic("mock out the UpdatePlexConfig method")
//			},
//			UpdateSettingsFunc: func(ctx context.Context, s domain.Settings) error {
//				panic("mock out the UpdateSettings method")
//			},
//		}
//
//		// use mockedStore in code that requires api.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// CountJobsByStateFunc mocks the CountJobsByState method.
	CountJobsByStateFunc func(ctx context.Context) (map[domain.JobState]int, error)

	// CountMediaByPlanKindFunc mocks the CountMediaByPlanKind method.
	CountMediaByPlanKindFunc func(ctx context.Context) (map[domain.Kind]int, error)

	// CountMediaByStatusFunc mocks the CountMediaByStatus method.
	CountMediaByStatusFunc func(ctx context.Context) (map[domain.MediaStatus]int, error)

	// CreateArrInstanceFunc mocks the CreateArrInstance method.
	CreateArrInstanceFunc func(ctx context.Context, a domain.ArrInstance) (domain.ArrInstance, error)

	// CreateRootFunc mocks the CreateRoot method.
	CreateRootFunc func(ctx context.Context, r domain.Root) (domain.Root, error)

	// DeleteArrInstanceFunc mocks the DeleteArrInstance method.
	DeleteArrInstanceFunc func(ctx context.Context, id int64) error

	// DeleteRootFunc mocks the DeleteRoot method.
	DeleteRootFunc func(ctx context.Context, id int64) error

	// GetArrInstanceFunc mocks the GetArrInstance method.
	GetArrInstanceFunc func(ctx context.Context, id int64) (domain.ArrInstance, error)

	// GetArrInstanceByWebhookIDFunc mocks the GetArrInstanceByWebhookID method.
	GetArrInstanceByWebhookIDFunc func(ctx context.Context, webhookID string) (domain.ArrInstance, error)

	// GetJobFunc mocks the GetJob method.
	GetJobFunc func(ctx context.Context, id int64) (domain.Job, error)

	// GetMediaFileFunc mocks the GetMediaFile method.
	GetMediaFileFunc func(ctx context.Context, id int64) (domain.MediaFile, error)

	// GetPlexConfigFunc mocks the GetPlexConfig method.
	GetPlexConfigFunc func(ctx context.Context) (domain.PlexConfig, error)

	// GetRootFunc mocks the GetRoot method.
	GetRootFunc func(ctx context.Context, id int64) (domain.Root, error)

	// GetSettingsFunc mocks the GetSettings method.
	GetSettingsFunc func(ctx context.Context) (domain.Settings, error)

	// ListArrInstancesFunc mocks the ListArrInstances method.
	ListArrInstancesFunc func(ctx context.Context) ([]domain.ArrInstance, error)

	// ListArrPathMappingsFunc mocks the ListArrPathMappings method.
	ListArrPathMappingsFunc func(ctx context.Context, arrInstanceID int64) ([]domain.PathMapping, error)

	// ListEventsFunc mocks the ListEvents method.
	ListEventsFunc func(ctx context.Context, f store.EventFilter) ([]domain.Event, error)

	// ListHWCapabilitiesFunc mocks the ListHWCapabilities method.
	ListHWCapabilitiesFunc func(ctx context.Context) ([]domain.HWCapability, error)

	// ListJobsFunc mocks the ListJobs method.
	ListJobsFunc func(ctx context.Context, f store.JobFilter) ([]domain.Job, int, error)

	// ListMediaFilesFunc mocks the ListMediaFiles method.
	ListMediaFilesFunc func(ctx context.Context, f store.MediaFilter) ([]domain.MediaFile, int, error)

	// ListPlexPathMappingsFunc mocks the ListPlexPathMappings method.
	ListPlexPathMappingsFunc func(ctx context.Context) ([]domain.PathMapping, error)

	// ListRootsFunc mocks the ListRoots method.
	ListRootsFunc func(ctx context.Context) ([]domain.Root, error)

	// ReplaceArrPathMappingsFunc mocks the ReplaceArrPathMappings method.
	ReplaceArrPathMappingsFunc func(ctx context.Context, arrInstanceID int64, m []domain.PathMapping) error

	// ReplacePlexPathMappingsFunc mocks the ReplacePlexPathMappings method.
	ReplacePlexPathMappingsFunc func(ctx context.Context, m []domain.PathMapping) error

	// SetArrTestResultFunc mocks the SetArrTestResult method.
	SetArrTestResultFunc func(ctx context.Context, id int64, at time.Time, result string) error

	// SetMediaIgnoredFunc mocks the SetMediaIgnored method.
	SetMediaIgnoredFunc func(ctx context.Context, id int64, ignored bool) error

	// SetMediaIntegrityFunc mocks the SetMediaIntegrity method.
	SetMediaIntegrityFunc func(ctx context.Context, id int64, fingerprint string, fullHash string, at time.Time) error

	// SetPlexTestResultFunc mocks the SetPlexTestResult method.
	SetPlexTestResultFunc func(ctx context.Context, at time.Time, result string) error

	// StatsFunc mocks the Stats method.
	StatsFunc func(ctx context.Context) (store.Stats, error)

	// UpdateArrInstanceFunc mocks the UpdateArrInstance method.
	UpdateArrInstanceFunc func(ctx context.Context, a domain.ArrInstance) error

	// UpdatePlexConfigFunc mocks the UpdatePlexConfig method.
	UpdatePlexConfigFunc func(ctx context.Context, c domain.PlexConfig) error

	// UpdateSettingsFunc mocks the UpdateSettings method.
	UpdateSettingsFunc func(ctx context.Context, s domain.Settings) error

	// calls tracks calls to the methods.
	calls struct {
		// CountJobsByState holds details about calls to the CountJobsByState method.
		CountJobsByState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CountMediaByPlanKind holds details about calls to the CountMediaByPlanKind method.
		CountMediaByPlanKind []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CountMediaByStatus holds details about calls to the CountMediaByStatus method.
		CountMediaByStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CreateArrInstance holds details about calls to the CreateArrInstance method.
		CreateArrInstance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// A is the a argument value.
			A domain.ArrInstance
		}
		// CreateRoot holds details about calls to the CreateRoot method.
		CreateRoot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R domain.Root
		}
		// DeleteArrInstance holds details about calls to the DeleteArrInstance method.
		DeleteArrInstance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// DeleteRoot holds details about calls to the DeleteRoot method.
		DeleteRoot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetArrInstance holds details about calls to the GetArrInstance method.
		GetArrInstance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetArrInstanceByWebhookID holds details about calls to the GetArrInstanceByWebhookID method.
		GetArrInstanceByWebhookID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WebhookID is the webhookID argument value.
			WebhookID string
		}
		// GetJob holds details about calls to the GetJob method.
		GetJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetMediaFile holds details about calls to the GetMediaFile method.
		GetMediaFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetPlexConfig holds details about calls to the GetPlexConfig method.
		GetPlexConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetRoot holds details about calls to the GetRoot method.
		GetRoot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetSettings holds details about calls to the GetSettings method.
		GetSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListArrInstances holds details about calls to the ListArrInstances method.
		ListArrInstances []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListArrPathMappings holds details about calls to the ListArrPathMappings method.
		ListArrPathMappings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ArrInstanceID is the arrInstanceID argument value.
			ArrInstanceID int64
		}
		// ListEvents holds details about calls to the ListEvents method.
		ListEvents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// F is the f argument value.
			F store.EventFilter
		}
		// ListHWCapabilities holds details about calls to the ListHWCapabilities method.
		ListHWCapabilities []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListJobs holds details about calls to the ListJobs method.
		ListJobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// F is the f argument value.
			F store.JobFilter
		}
		// ListMediaFiles holds details about calls to the ListMediaFiles method.
		ListMediaFiles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// F is the f argument value.
			F store.MediaFilter
		}
		// ListPlexPathMappings holds details about calls to the ListPlexPathMappings method.
		ListPlexPathMappings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListRoots holds details about calls to the ListRoots method.
		ListRoots []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ReplaceArrPathMappings holds details about calls to the ReplaceArrPathMappings method.
		ReplaceArrPathMappings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ArrInstanceID is the arrInstanceID argument value.
			ArrInstanceID int64
			// M is the m argument value.
			M []domain.PathMapping
		}
		// ReplacePlexPathMappings holds details about calls to the ReplacePlexPathMappings method.
		ReplacePlexPathMappings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// M is the m argument value.
			M []domain.PathMapping
		}
		// SetArrTestResult holds details about calls to the SetArrTestResult method.
		SetArrTestResult []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// At is the at argument value.
			At time.Time
			// Result is the result argument value.
			Result string
		}
		// SetMediaIgnored holds details about calls to the SetMediaIgnored method.
		SetMediaIgnored []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Ignored is the ignored argument value.
			Ignored bool
		}
		// SetMediaIntegrity holds details about calls to the SetMediaIntegrity method.
		SetMediaIntegrity []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Fingerprint is the fingerprint argument value.
			Fingerprint string
			// FullHash is the fullHash argument value.
			FullHash string
			// At is the at argument value.
			At time.Time
		}
		// SetPlexTestResult holds details about calls to the SetPlexTestResult method.
		SetPlexTestResult []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// At is the at argument value.
			At time.Time
			// Result is the result argument value.
			Result string
		}
		// Stats holds details about calls to the Stats method.
		Stats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdateArrInstance holds details about calls to the UpdateArrInstance method.
		UpdateArrInstance []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// A is the a argument value.
			A domain.ArrInstance
		}
		// UpdatePlexConfig holds details about calls to the UpdatePlexConfig method.
		UpdatePlexConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// C is the c argument value.
			C domain.PlexConfig
		}
		// UpdateSettings holds details about calls to the UpdateSettings method.
		UpdateSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S domain.Settings
		}
	}
	lockCountJobsByState          sync.RWMutex
	lockCountMediaByPlanKind      sync.RWMutex
	lockCountMediaByStatus        sync.RWMutex
	lockCreateArrInstance         sync.RWMutex
	lockCreateRoot                sync.RWMutex
	lockDeleteArrInstance         sync.RWMutex
	lockDeleteRoot                sync.RWMutex
	lockGetArrInstance            sync.RWMutex
	lockGetArrInstanceByWebhookID sync.RWMutex
	lockGetJob                    sync.RWMutex
	lockGetMediaFile              sync.RWMutex
	lockGetPlexConfig             sync.RWMutex
	lockGetRoot                   sync.RWMutex
	lockGetSettings               sync.RWMutex
	lockListArrInstances          sync.RWMutex
	lockListArrPathMappings       sync.RWMutex
	lockListEvents                sync.RWMutex
	lockListHWCapabilities        sync.RWMutex
	lockListJobs                  sync.RWMutex
	lockListMediaFiles            sync.RWMutex
	lockListPlexPathMappings      sync.RWMutex
	lockListRoots                 sync.RWMutex
	lockReplaceArrPathMappings    sync.RWMutex
	lockReplacePlexPathMappings   sync.RWMutex
	lockSetArrTestResult          sync.RWMutex
	lockSetMediaIgnored           sync.RWMutex
	lockSetMediaIntegrity         sync.RWMutex
	lockSetPlexTestResult         sync.RWMutex
	lockStats                     sync.RWMutex
	lockUpdateArrInstance         sync.RWMutex
	lockUpdatePlexConfig          sync.RWMutex
	lockUpdateSettings            sync.RWMutex
}

// CountJobsByState calls CountJobsByStateFunc.
func (mock *StoreMock) CountJobsByState(ctx context.Context) (map[domain.JobState]int, error) {
	if mock.CountJobsByStateFunc == nil {
		panic("StoreMock.CountJobsByStateFunc: method is nil but Store.CountJobsByState was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCountJobsByState.Lock()
	mock.calls.CountJobsByState = append(mock.calls.CountJobsByState, callInfo)
	mock.lockCountJobsByState.Unlock()
	return mock.CountJobsByStateFunc(ctx)
}

// CountJobsByStateCalls gets all the calls that were made to CountJobsByState.
// Check the length with:
//
//	len(mockedStore.CountJobsByStateCalls())
func (mock *StoreMock) CountJobsByStateCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCountJobsByState.RLock()
	calls = mock.calls.CountJobsByState
	mock.lockCountJobsByState.RUnlock()
	return calls
}

// CountMediaByPlanKind calls CountMediaByPlanKindFunc.
func (mock *StoreMock) CountMediaByPlanKind(ctx context.Context) (map[domain.Kind]int, error) {
	if mock.CountMediaByPlanKindFunc == nil {
		panic("StoreMock.CountMediaByPlanKindFunc: method is nil but Store.CountMediaByPlanKind was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCountMediaByPlanKind.Lock()
	mock.calls.CountMediaByPlanKind = append(mock.calls.CountMediaByPlanKind, callInfo)
	mock.lockCountMediaByPlanKind.Unlock()
	return mock.CountMediaByPlanKindFunc(ctx)
}

// CountMediaByPlanKindCalls gets all the calls that were made to CountMediaByPlanKind.
// Check the length with:
//
//	len(mockedStore.CountMediaByPlanKindCalls())
func (mock *StoreMock) CountMediaByPlanKindCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCountMediaByPlanKind.RLock()
	calls = mock.calls.CountMediaByPlanKind
	mock.lockCountMediaByPlanKind.RUnlock()
	return calls
}

// CountMediaByStatus calls CountMediaByStatusFunc.
func (mock *StoreMock) CountMediaByStatus(ctx context.Context) (map[domain.MediaStatus]int, error) {
	if mock.CountMediaByStatusFunc == nil {
		panic("StoreMock.CountMediaByStatusFunc: method is nil but Store.CountMediaByStatus was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCountMediaByStatus.Lock()
	mock.calls.CountMediaByStatus = append(mock.calls.CountMediaByStatus, callInfo)
	mock.lockCountMediaByStatus.Unlock()
	return mock.CountMediaByStatusFunc(ctx)
}

// CountMediaByStatusCalls gets all the calls that were made to CountMediaByStatus.
// Check the length with:
//
//	len(mockedStore.CountMediaByStatusCalls())
func (mock *StoreMock) CountMediaByStatusCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCountMediaByStatus.RLock()
	calls = mock.calls.CountMediaByStatus
	mock.lockCountMediaByStatus.RUnlock()
	return calls
}

// CreateArrInstance calls CreateArrInstanceFunc.
func (mock *StoreMock) CreateArrInstance(ctx context.Context, a domain.ArrInstance) (domain.ArrInstance, error) {
	if mock.CreateArrInstanceFunc == nil {
		panic("StoreMock.CreateArrInstanceFunc: method is nil but Store.CreateArrInstance was just called")
	}
	callInfo := struct {
		Ctx context.Context
		A   domain.ArrInstance
	}{
		Ctx: ctx,
		A:   a,
	}
	mock.lockCreateArrInstance.Lock()
	mock.calls.CreateArrInstance = append(mock.calls.CreateArrInstance, callInfo)
	mock.lockCreateArrInstance.Unlock()
	return mock.CreateArrInstanceFunc(ctx, a)
}

// CreateArrInstanceCalls gets all the calls that were made to CreateArrInstance.
// Check the length with:
//
//	len(mockedStore.CreateArrInstanceCalls())
func (mock *StoreMock) CreateArrInstanceCalls() []struct {
	Ctx context.Context
	A   domain.ArrInstance
} {
	var calls []struct {
		Ctx context.Context
		A   domain.ArrInstance
	}
	mock.lockCreateArrInstance.RLock()
	calls = mock.calls.CreateArrInstance
	mock.lockCreateArrInstance.RUnlock()
	return calls
}

// CreateRoot calls CreateRootFunc.
func (mock *StoreMock) CreateRoot(ctx context.Context, r domain.Root) (domain.Root, error) {
	if mock.CreateRootFunc == nil {
		panic("StoreMock.CreateRootFunc: method is nil but Store.CreateRoot was just called")
	}
	callInfo := struct {
		Ctx context.Context
		R   domain.Root
	}{
		Ctx: ctx,
		R:   r,
	}
	mock.lockCreateRoot.Lock()
	mock.calls.CreateRoot = append(mock.calls.CreateRoot, callInfo)
	mock.lockCreateRoot.Unlock()
	return mock.CreateRootFunc(ctx, r)
}

// CreateRootCalls gets all the calls that were made to CreateRoot.
// Check the length with:
//
//	len(mockedStore.CreateRootCalls())
func (mock *StoreMock) CreateRootCalls() []struct {
	Ctx context.Context
	R   domain.Root
} {
	var calls []struct {
		Ctx context.Context
		R   domain.Root
	}
	mock.lockCreateRoot.RLock()
	calls = mock.calls.CreateRoot
	mock.lockCreateRoot.RUnlock()
	return calls
}

// DeleteArrInstance calls DeleteArrInstanceFunc.
func (mock *StoreMock) DeleteArrInstance(ctx context.Context, id int64) error {
	if mock.DeleteArrInstanceFunc == nil {
		panic("StoreMock.DeleteArrInstanceFunc: method is nil but Store.DeleteArrInstance was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteArrInstance.Lock()
	mock.calls.DeleteArrInstance = append(mock.calls.DeleteArrInstance, callInfo)
	mock.lockDeleteArrInstance.Unlock()
	return mock.DeleteArrInstanceFunc(ctx, id)
}

// DeleteArrInstanceCalls gets all the calls that were made to DeleteArrInstance.
// Check the length with:
//
//	len(mockedStore.DeleteArrInstanceCalls())
func (mock *StoreMock) DeleteArrInstanceCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDeleteArrInstance.RLock()
	calls = mock.calls.DeleteArrInstance
	mock.lockDeleteArrInstance.RUnlock()
	return calls
}

// DeleteRoot calls DeleteRootFunc.
func (mock *StoreMock) DeleteRoot(ctx context.Context, id int64) error {
	if mock.DeleteRootFunc == nil {
		panic("StoreMock.DeleteRootFunc: method is nil but Store.DeleteRoot was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteRoot.Lock()
	mock.calls.DeleteRoot = append(mock.calls.DeleteRoot, callInfo)
	mock.lockDeleteRoot.Unlock()
	return mock.DeleteRootFunc(ctx, id)
}

// DeleteRootCalls gets all the calls that were made to DeleteRoot.
// Check the length with:
//
//	len(mockedStore.DeleteRootCalls())
func (mock *StoreMock) DeleteRootCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDeleteRoot.RLock()
	calls = mock.calls.DeleteRoot
	mock.lockDeleteRoot.RUnlock()
	return calls
}

// GetArrInstance calls GetArrInstanceFunc.
func (mock *StoreMock) GetArrInstance(ctx context.Context, id int64) (domain.ArrInstance, error) {
	if mock.GetArrInstanceFunc == nil {
		panic("StoreMock.GetArrInstanceFunc: method is nil but Store.GetArrInstance was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetArrInstance.Lock()
	mock.calls.GetArrInstance = append(mock.calls.GetArrInstance, callInfo)
	mock.lockGetArrInstance.Unlock()
	return mock.GetArrInstanceFunc(ctx, id)
}

// GetArrInstanceCalls gets all the calls that were made to GetArrInstance.
// Check the length with:
//
//	len(mockedStore.GetArrInstanceCalls())
func (mock *StoreMock) GetArrInstanceCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetArrInstance.RLock()
	calls = mock.calls.GetArrInstance
	mock.lockGetArrInstance.RUnlock()
	return calls
}

// GetArrInstanceByWebhookID calls GetArrInstanceByWebhookIDFunc.
func (mock *StoreMock) GetArrInstanceByWebhookID(ctx context.Context, webhookID string) (domain.ArrInstance, error) {
	if mock.GetArrInstanceByWebhookIDFunc == nil {
		panic("StoreMock.GetArrInstanceByWebhookIDFunc: method is nil but Store.GetArrInstanceByWebhookID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		WebhookID string
	}{
		Ctx:       ctx,
		WebhookID: webhookID,
	}
	mock.lockGetArrInstanceByWebhookID.Lock()
	mock.calls.GetArrInstanceByWebhookID = append(mock.calls.GetArrInstanceByWebhookID, callInfo)
	mock.lockGetArrInstanceByWebhookID.Unlock()
	return mock.GetArrInstanceByWebhookIDFunc(ctx, webhookID)
}

// GetArrInstanceByWebhookIDCalls gets all the calls that were made to GetArrInstanceByWebhookID.
// Check the length with:
//
//	len(mockedStore.GetArrInstanceByWebhookIDCalls())
func (mock *StoreMock) GetArrInstanceByWebhookIDCalls() []struct {
	Ctx       context.Context
	WebhookID string
} {
	var calls []struct {
		Ctx       context.Context
		WebhookID string
	}
	mock.lockGetArrInstanceByWebhookID.RLock()
	calls = mock.calls.GetArrInstanceByWebhookID
	mock.lockGetArrInstanceByWebhookID.RUnlock()
	return calls
}

// GetJob calls GetJobFunc.
func (mock *StoreMock) GetJob(ctx context.Context, id int64) (domain.Job, error) {
	if mock.GetJobFunc == nil {
		panic("StoreMock.GetJobFunc: method is nil but Store.GetJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetJob.Lock()
	mock.calls.GetJob = append(mock.calls.GetJob, callInfo)
	mock.lockGetJob.Unlock()
	return mock.GetJobFunc(ctx, id)
}

// GetJobCalls gets all the calls that were made to GetJob.
// Check the length with:
//
//	len(mockedStore.GetJobCalls())
func (mock *StoreMock) GetJobCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetJob.RLock()
	calls = mock.calls.GetJob
	mock.lockGetJob.RUnlock()
	return calls
}

// GetMediaFile calls GetMediaFileFunc.
func (mock *StoreMock) GetMediaFile(ctx context.Context, id int64) (domain.MediaFile, error) {
	if mock.GetMediaFileFunc == nil {
		panic("StoreMock.GetMediaFileFunc: method is nil but Store.GetMediaFile was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetMediaFile.Lock()
	mock.calls.GetMediaFile = append(mock.calls.GetMediaFile, callInfo)
	mock.lockGetMediaFile.Unlock()
	return mock.GetMediaFileFunc(ctx, id)
}

// GetMediaFileCalls gets all the calls that were made to GetMediaFile.
// Check the length with:
//
//	len(mockedStore.GetMediaFileCalls())
func (mock *StoreMock) GetMediaFileCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetMediaFile.RLock()
	calls = mock.calls.GetMediaFile
	mock.lockGetMediaFile.RUnlock()
	return calls
}

// GetPlexConfig calls GetPlexConfigFunc.
func (mock *StoreMock) GetPlexConfig(ctx context.Context) (domain.PlexConfig, error) {
	if mock.GetPlexConfigFunc == nil {
		panic("StoreMock.GetPlexConfigFunc: method is nil but Store.GetPlexConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetPlexConfig.Lock()
	mock.calls.GetPlexConfig = append(mock.calls.GetPlexConfig, callInfo)
	mock.lockGetPlexConfig.Unlock()
	return mock.GetPlexConfigFunc(ctx)
}

// GetPlexConfigCalls gets all the calls that were made to GetPlexConfig.
// Check the length with:
//
//	len(mockedStore.GetPlexConfigCalls())
func (mock *StoreMock) GetPlexConfigCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetPlexConfig.RLock()
	calls = mock.calls.GetPlexConfig
	mock.lockGetPlexConfig.RUnlock()
	return calls
}

// GetRoot calls GetRootFunc.
func (mock *StoreMock) GetRoot(ctx context.Context, id int64) (domain.Root, error) {
	if mock.GetRootFunc == nil {
		panic("StoreMock.GetRootFunc: method is nil but Store.GetRoot was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetRoot.Lock()
	mock.calls.GetRoot = append(mock.calls.GetRoot, callInfo)
	mock.lockGetRoot.Unlock()
	return mock.GetRootFunc(ctx, id)
}

// GetRootCalls gets all the calls that were made to GetRoot.
// Check the length with:
//
//	len(mockedStore.GetRootCalls())
func (mock *StoreMock) GetRootCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetRoot.RLock()
	calls = mock.calls.GetRoot
	mock.lockGetRoot.RUnlock()
	return calls
}

// GetSettings calls GetSettingsFunc.
func (mock *StoreMock) GetSettings(ctx context.Context) (domain.Settings, error) {
	if mock.GetSettingsFunc == nil {
		panic("StoreMock.GetSettingsFunc: method is nil but Store.GetSettings was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetSettings.Lock()
	mock.calls.GetSettings = append(mock.calls.GetSettings, callInfo)
	mock.lockGetSettings.Unlock()
	return mock.GetSettingsFunc(ctx)
}

// GetSettingsCalls gets all the calls that were made to GetSettings.
// Check the length with:
//
//	len(mockedStore.GetSettingsCalls())
func (mock *StoreMock) GetSettingsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetSettings.RLock()
	calls = mock.calls.GetSettings
	mock.lockGetSettings.RUnlock()
	return calls
}

// ListArrInstances calls ListArrInstancesFunc.
func (mock *StoreMock) ListArrInstances(ctx context.Context) ([]domain.ArrInstance, error) {
	if mock.ListArrInstancesFunc == nil {
		panic("StoreMock.ListArrInstancesFunc: method is nil but Store.ListArrInstances was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListArrInstances.Lock()
	mock.calls.ListArrInstances = append(mock.calls.ListArrInstances, callInfo)
	mock.lockListArrInstances.Unlock()
	return mock.ListArrInstancesFunc(ctx)
}

// ListArrInstancesCalls gets all the calls that were made to ListArrInstances.
// Check the length with:
//
//	len(mockedStore.ListArrInstancesCalls())
func (mock *StoreMock) ListArrInstancesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListArrInstances.RLock()
	calls = mock.calls.ListArrInstances
	mock.lockListArrInstances.RUnlock()
	return calls
}

// ListArrPathMappings calls ListArrPathMappingsFunc.
func (mock *StoreMock) ListArrPathMappings(ctx context.Context, arrInstanceID int64) ([]domain.PathMapping, error) {
	if mock.ListArrPathMappingsFunc == nil {
		panic("StoreMock.ListArrPathMappingsFunc: method is nil but Store.ListArrPathMappings was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ArrInstanceID int64
	}{
		Ctx:           ctx,
		ArrInstanceID: arrInstanceID,
	}
	mock.lockListArrPathMappings.Lock()
	mock.calls.ListArrPathMappings = append(mock.calls.ListArrPathMappings, callInfo)
	mock.lockListArrPathMappings.Unlock()
	return mock.ListArrPathMappingsFunc(ctx, arrInstanceID)
}

// ListArrPathMappingsCalls gets all the calls that were made to ListArrPathMappings.
// Check the length with:
//
//	len(mockedStore.ListArrPathMappingsCalls())
func (mock *StoreMock) ListArrPathMappingsCalls() []struct {
	Ctx           context.Context
	ArrInstanceID int64
} {
	var calls []struct {
		Ctx           context.Context
		ArrInstanceID int64
	}
	mock.lockListArrPathMappings.RLock()
	calls = mock.calls.ListArrPathMappings
	mock.lockListArrPathMappings.RUnlock()
	return calls
}

// ListEvents calls ListEventsFunc.
func (mock *StoreMock) ListEvents(ctx context.Context, f store.EventFilter) ([]domain.Event, error) {
	if mock.ListEventsFunc == nil {
		panic("StoreMock.ListEventsFunc: method is nil but Store.ListEvents was just called")
	}
	callInfo := struct {
		Ctx context.Context
		F   store.EventFilter
	}{
		Ctx: ctx,
		F:   f,
	}
	mock.lockListEvents.Lock()
	mock.calls.ListEvents = append(mock.calls.ListEvents, callInfo)
	mock.lockListEvents.Unlock()
	return mock.ListEventsFunc(ctx, f)
}

// ListEventsCalls gets all the calls that were made to ListEvents.
// Check the length with:
//
//	len(mockedStore.ListEventsCalls())
func (mock *StoreMock) ListEventsCalls() []struct {
	Ctx context.Context
	F   store.EventFilter
} {
	var calls []struct {
		Ctx context.Context
		F   store.EventFilter
	}
	mock.lockListEvents.RLock()
	calls = mock.calls.ListEvents
	mock.lockListEvents.RUnlock()
	return calls
}

// ListHWCapabilities calls ListHWCapabilitiesFunc.
func (mock *StoreMock) ListHWCapabilities(ctx context.Context) ([]domain.HWCapability, error) {
	if mock.ListHWCapabilitiesFunc == nil {
		panic("StoreMock.ListHWCapabilitiesFunc: method is nil but Store.ListHWCapabilities was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListHWCapabilities.Lock()
	mock.calls.ListHWCapabilities = append(mock.calls.ListHWCapabilities, callInfo)
	mock.lockListHWCapabilities.Unlock()
	return mock.ListHWCapabilitiesFunc(ctx)
}

// ListHWCapabilitiesCalls gets all the calls that were made to ListHWCapabilities.
// Check the length with:
//
//	len(mockedStore.ListHWCapabilitiesCalls())
func (mock *StoreMock) ListHWCapabilitiesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListHWCapabilities.RLock()
	calls = mock.calls.ListHWCapabilities
	mock.lockListHWCapabilities.RUnlock()
	return calls
}

// ListJobs calls ListJobsFunc.
func (mock *StoreMock) ListJobs(ctx context.Context, f store.JobFilter) ([]domain.Job, int, error) {
	if mock.ListJobsFunc == nil {
		panic("StoreMock.ListJobsFunc: method is nil but Store.ListJobs was just called")
	}
	callInfo := struct {
		Ctx context.Context
		F   store.JobFilter
	}{
		Ctx: ctx,
		F:   f,
	}
	mock.lockListJobs.Lock()
	mock.calls.ListJobs = append(mock.calls.ListJobs, callInfo)
	mock.lockListJobs.Unlock()
	return mock.ListJobsFunc(ctx, f)
}

// ListJobsCalls gets all the calls that were made to ListJobs.
// Check the length with:
//
//	len(mockedStore.ListJobsCalls())
func (mock *StoreMock) ListJobsCalls() []struct {
	Ctx context.Context
	F   store.JobFilter
} {
	var calls []struct {
		Ctx context.Context
		F   store.JobFilter
	}
	mock.lockListJobs.RLock()
	calls = mock.calls.ListJobs
	mock.lockListJobs.RUnlock()
	return calls
}

// ListMediaFiles calls ListMediaFilesFunc.
func (mock *StoreMock) ListMediaFiles(ctx context.Context, f store.MediaFilter) ([]domain.MediaFile, int, error) {
	if mock.ListMediaFilesFunc == nil {
		panic("StoreMock.ListMediaFilesFunc: method is nil but Store.ListMediaFiles was just called")
	}
	callInfo := struct {
		Ctx context.Context
		F   store.MediaFilter
	}{
		Ctx: ctx,
		F:   f,
	}
	mock.lockListMediaFiles.Lock()
	mock.calls.ListMediaFiles = append(mock.calls.ListMediaFiles, callInfo)
	mock.lockListMediaFiles.Unlock()
	return mock.ListMediaFilesFunc(ctx, f)
}

// ListMediaFilesCalls gets all the calls that were made to ListMediaFiles.
// Check the length with:
//
//	len(mockedStore.ListMediaFilesCalls())
func (mock *StoreMock) ListMediaFilesCalls() []struct {
	Ctx context.Context
	F   store.MediaFilter
} {
	var calls []struct {
		Ctx context.Context
		F   store.MediaFilter
	}
	mock.lockListMediaFiles.RLock()
	calls = mock.calls.ListMediaFiles
	mock.lockListMediaFiles.RUnlock()
	return calls
}

// ListPlexPathMappings calls ListPlexPathMappingsFunc.
func (mock *StoreMock) ListPlexPathMappings(ctx context.Context) ([]domain.PathMapping, error) {
	if mock.ListPlexPathMappingsFunc == nil {
		panic("StoreMock.ListPlexPathMappingsFunc: method is nil but Store.ListPlexPathMappings was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListPlexPathMappings.Lock()
	mock.calls.ListPlexPathMappings = append(mock.calls.ListPlexPathMappings, callInfo)
	mock.lockListPlexPathMappings.Unlock()
	return mock.ListPlexPathMappingsFunc(ctx)
}

// ListPlexPathMappingsCalls gets all the calls that were made to ListPlexPathMappings.
// Check the length with:
//
//	len(mockedStore.ListPlexPathMappingsCalls())
func (mock *StoreMock) ListPlexPathMappingsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListPlexPathMappings.RLock()
	calls = mock.calls.ListPlexPathMappings
	mock.lockListPlexPathMappings.RUnlock()
	return calls
}

// ListRoots calls ListRootsFunc.
func (mock *StoreMock) ListRoots(ctx context.Context) ([]domain.Root, error) {
	if mock.ListRootsFunc == nil {
		panic("StoreMock.ListRootsFunc: method is nil but Store.ListRoots was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListRoots.Lock()
	mock.calls.ListRoots = append(mock.calls.ListRoots, callInfo)
	mock.lockListRoots.Unlock()
	return mock.ListRootsFunc(ctx)
}

// ListRootsCalls gets all the calls that were made to ListRoots.
// Check the length with:
//
//	len(mockedStore.ListRootsCalls())
func (mock *StoreMock) ListRootsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListRoots.RLock()
	calls = mock.calls.ListRoots
	mock.lockListRoots.RUnlock()
	return calls
}

// ReplaceArrPathMappings calls ReplaceArrPathMappingsFunc.
func (mock *StoreMock) ReplaceArrPathMappings(ctx context.Context, arrInstanceID int64, m []domain.PathMapping) error {
	if mock.ReplaceArrPathMappingsFunc == nil {
		panic("StoreMock.ReplaceArrPathMappingsFunc: method is nil but Store.ReplaceArrPathMappings was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ArrInstanceID int64
		M             []domain.PathMapping
	}{
		Ctx:           ctx,
		ArrInstanceID: arrInstanceID,
		M:             m,
	}
	mock.lockReplaceArrPathMappings.Lock()
	mock.calls.ReplaceArrPathMappings = append(mock.calls.ReplaceArrPathMappings, callInfo)
	mock.lockReplaceArrPathMappings.Unlock()
	return mock.ReplaceArrPathMappingsFunc(ctx, arrInstanceID, m)
}

// ReplaceArrPathMappingsCalls gets all the calls that were made to ReplaceArrPathMappings.
// Check the length with:
//
//	len(mockedStore.ReplaceArrPathMappingsCalls())
func (mock *StoreMock) ReplaceArrPathMappingsCalls() []struct {
	Ctx           context.Context
	ArrInstanceID int64
	M             []domain.PathMapping
} {
	var calls []struct {
		Ctx           context.Context
		ArrInstanceID int64
		M             []domain.PathMapping
	}
	mock.lockReplaceArrPathMappings.RLock()
	calls = mock.calls.ReplaceArrPathMappings
	mock.lockReplaceArrPathMappings.RUnlock()
	return calls
}

// ReplacePlexPathMappings calls ReplacePlexPathMappingsFunc.
func (mock *StoreMock) ReplacePlexPathMappings(ctx context.Context, m []domain.PathMapping) error {
	if mock.ReplacePlexPathMappingsFunc == nil {
		panic("StoreMock.ReplacePlexPathMappingsFunc: method is nil but Store.ReplacePlexPathMappings was just called")
	}
	callInfo := struct {
		Ctx context.Context
		M   []domain.PathMapping
	}{
		Ctx: ctx,
		M:   m,
	}
	mock.lockReplacePlexPathMappings.Lock()
	mock.calls.ReplacePlexPathMappings = append(mock.calls.ReplacePlexPathMappings, callInfo)
	mock.lockReplacePlexPathMappings.Unlock()
	return mock.ReplacePlexPathMappingsFunc(ctx, m)
}

// ReplacePlexPathMappingsCalls gets all the calls that were made to ReplacePlexPathMappings.
// Check the length with:
//
//	len(mockedStore.ReplacePlexPathMappingsCalls())
func (mock *StoreMock) ReplacePlexPathMappingsCalls() []struct {
	Ctx context.Context
	M   []domain.PathMapping
} {
	var calls []struct {
		Ctx context.Context
		M   []domain.PathMapping
	}
	mock.lockReplacePlexPathMappings.RLock()
	calls = mock.calls.ReplacePlexPathMappings
	mock.lockReplacePlexPathMappings.RUnlock()
	return calls
}

// SetArrTestResult calls SetArrTestResultFunc.
func (mock *StoreMock) SetArrTestResult(ctx context.Context, id int64, at time.Time, result string) error {
	if mock.SetArrTestResultFunc == nil {
		panic("StoreMock.SetArrTestResultFunc: method is nil but Store.SetArrTestResult was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     int64
		At     time.Time
		Result string
	}{
		Ctx:    ctx,
		ID:     id,
		At:     at,
		Result: result,
	}
	mock.lockSetArrTestResult.Lock()
	mock.calls.SetArrTestResult = append(mock.calls.SetArrTestResult, callInfo)
	mock.lockSetArrTestResult.Unlock()
	return mock.SetArrTestResultFunc(ctx, id, at, result)
}

// SetArrTestResultCalls gets all the calls that were made to SetArrTestResult.
// Check the length with:
//
//	len(mockedStore.SetArrTestResultCalls())
func (mock *StoreMock) SetArrTestResultCalls() []struct {
	Ctx    context.Context
	ID     int64
	At     time.Time
	Result string
} {
	var calls []struct {
		Ctx    context.Context
		ID     int64
		At     time.Time
		Result string
	}
	mock.lockSetArrTestResult.RLock()
	calls = mock.calls.SetArrTestResult
	mock.lockSetArrTestResult.RUnlock()
	return calls
}

// SetMediaIgnored calls SetMediaIgnoredFunc.
func (mock *StoreMock) SetMediaIgnored(ctx context.Context, id int64, ignored bool) error {
	if mock.SetMediaIgnoredFunc == nil {
		panic("StoreMock.SetMediaIgnoredFunc: method is nil but Store.SetMediaIgnored was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ID      int64
		Ignored bool
	}{
		Ctx:     ctx,
		ID:      id,
		Ignored: ignored,
	}
	mock.lockSetMediaIgnored.Lock()
	mock.calls.SetMediaIgnored = append(mock.calls.SetMediaIgnored, callInfo)
	mock.lockSetMediaIgnored.Unlock()
	return mock.SetMediaIgnoredFunc(ctx, id, ignored)
}

// SetMediaIgnoredCalls gets all the calls that were made to SetMediaIgnored.
// Check the length with:
//
//	len(mockedStore.SetMediaIgnoredCalls())
func (mock *StoreMock) SetMediaIgnoredCalls() []struct {
	Ctx     context.Context
	ID      int64
	Ignored bool
} {
	var calls []struct {
		Ctx     context.Context
		ID      int64
		Ignored bool
	}
	mock.lockSetMediaIgnored.RLock()
	calls = mock.calls.SetMediaIgnored
	mock.lockSetMediaIgnored.RUnlock()
	return calls
}

// SetMediaIntegrity calls SetMediaIntegrityFunc.
func (mock *StoreMock) SetMediaIntegrity(ctx context.Context, id int64, fingerprint string, fullHash string, at time.Time) error {
	if mock.SetMediaIntegrityFunc == nil {
		panic("StoreMock.SetMediaIntegrityFunc: method is nil but Store.SetMediaIntegrity was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ID          int64
		Fingerprint string
		FullHash    string
		At          time.Time
	}{
		Ctx:         ctx,
		ID:          id,
		Fingerprint: fingerprint,
		FullHash:    fullHash,
		At:          at,
	}
	mock.lockSetMediaIntegrity.Lock()
	mock.calls.SetMediaIntegrity = append(mock.calls.SetMediaIntegrity, callInfo)
	mock.lockSetMediaIntegrity.Unlock()
	return mock.SetMediaIntegrityFunc(ctx, id, fingerprint, fullHash, at)
}

// SetMediaIntegrityCalls gets all the calls that were made to SetMediaIntegrity.
// Check the length with:
//
//	len(mockedStore.SetMediaIntegrityCalls())
func (mock *StoreMock) SetMediaIntegrityCalls() []struct {
	Ctx         context.Context
	ID          int64
	Fingerprint string
	FullHash    string
	At          time.Time
} {
	var calls []struct {
		Ctx         context.Context
		ID          int64
		Fingerprint string
		FullHash    string
		At          time.Time
	}
	mock.lockSetMediaIntegrity.RLock()
	calls = mock.calls.SetMediaIntegrity
	mock.lockSetMediaIntegrity.RUnlock()
	return calls
}

// SetPlexTestResult calls SetPlexTestResultFunc.
func (mock *StoreMock) SetPlexTestResult(ctx context.Context, at time.Time, result string) error {
	if mock.SetPlexTestResultFunc == nil {
		panic("StoreMock.SetPlexTestResultFunc: method is nil but Store.SetPlexTestResult was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		At     time.Time
		Result string
	}{
		Ctx:    ctx,
		At:     at,
		Result: result,
	}
	mock.lockSetPlexTestResult.Lock()
	mock.calls.SetPlexTestResult = append(mock.calls.SetPlexTestResult, callInfo)
	mock.lockSetPlexTestResult.Unlock()
	return mock.SetPlexTestResultFunc(ctx, at, result)
}

// SetPlexTestResultCalls gets all the calls that were made to SetPlexTestResult.
// Check the length with:
//
//	len(mockedStore.SetPlexTestResultCalls())
func (mock *StoreMock) SetPlexTestResultCalls() []struct {
	Ctx    context.Context
	At     time.Time
	Result string
} {
	var calls []struct {
		Ctx    context.Context
		At     time.Time
		Result string
	}
	mock.lockSetPlexTestResult.RLock()
	calls = mock.calls.SetPlexTestResult
	mock.lockSetPlexTestResult.RUnlock()
	return calls
}

// Stats calls StatsFunc.
func (mock *StoreMock) Stats(ctx context.Context) (store.Stats, error) {
	if mock.StatsFunc == nil {
		panic("StoreMock.StatsFunc: method is nil but Store.Stats was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStats.Lock()
	mock.calls.Stats = append(mock.calls.Stats, callInfo)
	mock.lockStats.Unlock()
	return mock.StatsFunc(ctx)
}

// StatsCalls gets all the calls that were made to Stats.
// Check the length with:
//
//	len(mockedStore.StatsCalls())
func (mock *StoreMock) StatsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStats.RLock()
	calls = mock.calls.Stats
	mock.lockStats.RUnlock()
	return calls
}

// UpdateArrInstance calls UpdateArrInstanceFunc.
func (mock *StoreMock) UpdateArrInstance(ctx context.Context, a domain.ArrInstance) error {
	if mock.UpdateArrInstanceFunc == nil {
		panic("StoreMock.UpdateArrInstanceFunc: method is nil but Store.UpdateArrInstance was just called")
	}
	callInfo := struct {
		Ctx context.Context
		A   domain.ArrInstance
	}{
		Ctx: ctx,
		A:   a,
	}
	mock.lockUpdateArrInstance.Lock()
	mock.calls.UpdateArrInstance = append(mock.calls.UpdateArrInstance, callInfo)
	mock.lockUpdateArrInstance.Unlock()
	return mock.UpdateArrInstanceFunc(ctx, a)
}

// UpdateArrInstanceCalls gets all the calls that were made to UpdateArrInstance.
// Check the length with:
//
//	len(mockedStore.UpdateArrInstanceCalls())
func (mock *StoreMock) UpdateArrInstanceCalls() []struct {
	Ctx context.Context
	A   domain.ArrInstance
} {
	var calls []struct {
		Ctx context.Context
		A   domain.ArrInstance
	}
	mock.lockUpdateArrInstance.RLock()
	calls = mock.calls.UpdateArrInstance
	mock.lockUpdateArrInstance.RUnlock()
	return calls
}

// UpdatePlexConfig calls UpdatePlexConfigFunc.
func (mock *StoreMock) UpdatePlexConfig(ctx context.Context, c domain.PlexConfig) error {
	if mock.UpdatePlexConfigFunc == nil {
		panic("StoreMock.UpdatePlexConfigFunc: method is nil but Store.UpdatePlexConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
		C   domain.PlexConfig
	}{
		Ctx: ctx,
		C:   c,
	}
	mock.lockUpdatePlexConfig.Lock()
	mock.calls.UpdatePlexConfig = append(mock.calls.UpdatePlexConfig, callInfo)
	mock.lockUpdatePlexConfig.Unlock()
	return mock.UpdatePlexConfigFunc(ctx, c)
}

// UpdatePlexConfigCalls gets all the calls that were made to UpdatePlexConfig.
// Check the length with:
//
//	len(mockedStore.UpdatePlexConfigCalls())
func (mock *StoreMock) UpdatePlexConfigCalls() []struct {
	Ctx context.Context
	C   domain.PlexConfig
} {
	var calls []struct {
		Ctx context.Context
		C   domain.PlexConfig
	}
	mock.lockUpdatePlexConfig.RLock()
	calls = mock.calls.UpdatePlexConfig
	mock.lockUpdatePlexConfig.RUnlock()
	return calls
}

// UpdateSettings calls UpdateSettingsFunc.
func (mock *StoreMock) UpdateSettings(ctx context.Context, s domain.Settings) error {
	if mock.UpdateSettingsFunc == nil {
		panic("StoreMock.UpdateSettingsFunc: method is nil but Store.UpdateSettings was just called")
	}
	callInfo := struct {
		Ctx context.Context
		S   domain.Settings
	}{
		Ctx: ctx,
		S:   s,
	}
	mock.lockUpdateSettings.Lock()
	mock.calls.UpdateSettings = append(mock.calls.UpdateSettings, callInfo)
	mock.lockUpdateSettings.Unlock()
	return mock.UpdateSettingsFunc(ctx, s)
}

// UpdateSettingsCalls gets all the calls that were made to UpdateSettings.
// Check the length with:
//
//	len(mockedStore.UpdateSettingsCalls())
func (mock *StoreMock) UpdateSettingsCalls() []struct {
	Ctx context.Context
	S   domain.Settings
} {
	var calls []struct {
		Ctx context.Context
		S   domain.Settings
	}
	mock.lockUpdateSettings.RLock()
	calls = mock.calls.UpdateSettings
	mock.lockUpdateSettings.RUnlock()
	return calls
}

// Ensure, that QueueMock does implement api.Queue.
// If this is not the case, regenerate this file with moq.
var _ api.Queue = &QueueMock{}

// QueueMock is a mock implementation of api.Queue.
//
//	func TestSomethingThatUsesQueue(t *testing.T) {
//
//		// make and configure a mocked api.Queue
//		mockedQueue := &QueueMock{
//			CancelFunc: func(ctx context.Context, jobID int64) error {
//				panic("mock out the Cancel method")
//			},
//			EnqueueFunc: func(ctx context.Context, mediaFileID int64, origin domain.JobOrigin) (job.EnqueueResult, error) {
//				panic("mock out the Enqueue method")
//			},
//			PauseFunc: func(ctx context.Context) error {
//				panic("mock out the Pause method")
//			},
//			PausedFunc: func(ctx context.Context) (bool, error) {
//				panic("mock out the Paused method")
//			},
//			RecheckFunc: func(ctx context.Context, req job.Recheck) (job.RecheckResult, error) {
//				panic("mock out the Recheck method")
//			},
//			RecheckAllFunc: func(ctx context.Context, confirm bool) (job.RecheckResult, error) {
//				panic("mock out the RecheckAll method")
//			},
//			RestartFunc: func(ctx context.Context, jobID int64) (domain.Job, error) {
//				panic("mock out the Restart method")
//			},
//			ResumeFunc: func(ctx context.Context) error {
//				panic("mock out the Resume method")
//			},
//			SpaceSweepPreviewFunc: func(ctx context.Context) (job.SpaceSweepPreview, error) {
//				panic("mock out the SpaceSweepPreview method")
//			},
//			SpaceSweepRunFunc: func(ctx context.Context, ids []int64, confirm bool) (job.SpaceSweepPreview, error) {
//				panic("mock out the SpaceSweepRun method")
//			},
//		}
//
//		// use mockedQueue in code that requires api.Queue
//		// and then make assertions.
//
//	}
type QueueMock struct {
	// CancelFunc mocks the Cancel method.
	CancelFunc func(ctx context.Context, jobID int64) error

	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(ctx context.Context, mediaFileID int64, origin domain.JobOrigin) (job.EnqueueResult, error)

	// PauseFunc mocks the Pause method.
	PauseFunc func(ctx context.Context) error

	// PausedFunc mocks the Paused method.
	PausedFunc func(ctx context.Context) (bool, error)

	// RecheckFunc mocks the Recheck method.
	RecheckFunc func(ctx context.Context, req job.Recheck) (job.RecheckResult, error)

	// RecheckAllFunc mocks the RecheckAll method.
	RecheckAllFunc func(ctx context.Context, confirm bool) (job.RecheckResult, error)

	// RestartFunc mocks the Restart method.
	RestartFunc func(ctx context.Context, jobID int64) (domain.Job, error)

	// ResumeFunc mocks the Resume method.
	ResumeFunc func(ctx context.Context) error

	// SpaceSweepPreviewFunc mocks the SpaceSweepPreview method.
	SpaceSweepPreviewFunc func(ctx context.Context) (job.SpaceSweepPreview, error)

	// SpaceSweepRunFunc mocks the SpaceSweepRun method.
	SpaceSweepRunFunc func(ctx context.Context, ids []int64, confirm bool) (job.SpaceSweepPreview, error)

	// calls tracks calls to the methods.
	calls struct {
		// Cancel holds details about calls to the Cancel method.
		Cancel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID int64
		}
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MediaFileID is the mediaFileID argument value.
			MediaFileID int64
			// Origin is the origin argument value.
			Origin domain.JobOrigin
		}
		// Pause holds details about calls to the Pause method.
		Pause []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Paused holds details about calls to the Paused method.
		Paused []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Recheck holds details about calls to the Recheck method.
		Recheck []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req job.Recheck
		}
		// RecheckAll holds details about calls to the RecheckAll method.
		RecheckAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Confirm is the confirm argument value.
			Confirm bool
		}
		// Restart holds details about calls to the Restart method.
		Restart []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID int64
		}
		// Resume holds details about calls to the Resume method.
		Resume []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// SpaceSweepPreview holds details about calls to the SpaceSweepPreview method.
		SpaceSweepPreview []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// SpaceSweepRun holds details about calls to the SpaceSweepRun method.
		SpaceSweepRun []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ids is the ids argument value.
			Ids []int64
			// Confirm is the confirm argument value.
			Confirm bool
		}
	}
	lockCancel            sync.RWMutex
	lockEnqueue           sync.RWMutex
	lockPause             sync.RWMutex
	lockPaused            sync.RWMutex
	lockRecheck           sync.RWMutex
	lockRecheckAll        sync.RWMutex
	lockRestart           sync.RWMutex
	lockResume            sync.RWMutex
	lockSpaceSweepPreview sync.RWMutex
	lockSpaceSweepRun     sync.RWMutex
}

// Cancel calls CancelFunc.
func (mock *QueueMock) Cancel(ctx context.Context, jobID int64) error {
	if mock.CancelFunc == nil {
		panic("QueueMock.CancelFunc: method is nil but Queue.Cancel was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		JobID int64
	}{
		Ctx:   ctx,
		JobID: jobID,
	}
	mock.lockCancel.Lock()
	mock.calls.Cancel = append(mock.calls.Cancel, callInfo)
	mock.lockCancel.Unlock()
	return mock.CancelFunc(ctx, jobID)
}

// CancelCalls gets all the calls that were made to Cancel.
// Check the length with:
//
//	len(mockedQueue.CancelCalls())
func (mock *QueueMock) CancelCalls() []struct {
	Ctx   context.Context
	JobID int64
} {
	var calls []struct {
		Ctx   context.Context
		JobID int64
	}
	mock.lockCancel.RLock()
	calls = mock.calls.Cancel
	mock.lockCancel.RUnlock()
	return calls
}

// Enqueue calls EnqueueFunc.
func (mock *QueueMock) Enqueue(ctx context.Context, mediaFileID int64, origin domain.JobOrigin) (job.EnqueueResult, error) {
	if mock.EnqueueFunc == nil {
		panic("QueueMock.EnqueueFunc: method is nil but Queue.Enqueue was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		MediaFileID int64
		Origin      domain.JobOrigin
	}{
		Ctx:         ctx,
		MediaFileID: mediaFileID,
		Origin:      origin,
	}
	mock.lockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	mock.lockEnqueue.Unlock()
	return mock.EnqueueFunc(ctx, mediaFileID, origin)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//
//	len(mockedQueue.EnqueueCalls())
func (mock *QueueMock) EnqueueCalls() []struct {
	Ctx         context.Context
	MediaFileID int64
	Origin      domain.JobOrigin
} {
	var calls []struct {
		Ctx         context.Context
		MediaFileID int64
		Origin      domain.JobOrigin
	}
	mock.lockEnqueue.RLock()
	calls = mock.calls.Enqueue
	mock.lockEnqueue.RUnlock()
	return calls
}

// Pause calls PauseFunc.
func (mock *QueueMock) Pause(ctx context.Context) error {
	if mock.PauseFunc == nil {
		panic("QueueMock.PauseFunc: method is nil but Queue.Pause was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPause.Lock()
	mock.calls.Pause = append(mock.calls.Pause, callInfo)
	mock.lockPause.Unlock()
	return mock.PauseFunc(ctx)
}

// PauseCalls gets all the calls that were made to Pause.
// Check the length with:
//
//	len(mockedQueue.PauseCalls())
func (mock *QueueMock) PauseCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPause.RLock()
	calls = mock.calls.Pause
	mock.lockPause.RUnlock()
	return calls
}

// Paused calls PausedFunc.
func (mock *QueueMock) Paused(ctx context.Context) (bool, error) {
	if mock.PausedFunc == nil {
		panic("QueueMock.PausedFunc: method is nil but Queue.Paused was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPaused.Lock()
	mock.calls.Paused = append(mock.calls.Paused, callInfo)
	mock.lockPaused.Unlock()
	return mock.PausedFunc(ctx)
}

// PausedCalls gets all the calls that were made to Paused.
// Check the length with:
//
//	len(mockedQueue.PausedCalls())
func (mock *QueueMock) PausedCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPaused.RLock()
	calls = mock.calls.Paused
	mock.lockPaused.RUnlock()
	return calls
}

// Recheck calls RecheckFunc.
func (mock *QueueMock) Recheck(ctx context.Context, req job.Recheck) (job.RecheckResult, error) {
	if mock.RecheckFunc == nil {
		panic("QueueMock.RecheckFunc: method is nil but Queue.Recheck was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req job.Recheck
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockRecheck.Lock()
	mock.calls.Recheck = append(mock.calls.Recheck, callInfo)
	mock.lockRecheck.Unlock()
	return mock.RecheckFunc(ctx, req)
}

// RecheckCalls gets all the calls that were made to Recheck.
// Check the length with:
//
//	len(mockedQueue.RecheckCalls())
func (mock *QueueMock) RecheckCalls() []struct {
	Ctx context.Context
	Req job.Recheck
} {
	var calls []struct {
		Ctx context.Context
		Req job.Recheck
	}
	mock.lockRecheck.RLock()
	calls = mock.calls.Recheck
	mock.lockRecheck.RUnlock()
	return calls
}

// RecheckAll calls RecheckAllFunc.
func (mock *QueueMock) RecheckAll(ctx context.Context, confirm bool) (job.RecheckResult, error) {
	if mock.RecheckAllFunc == nil {
		panic("QueueMock.RecheckAllFunc: method is nil but Queue.RecheckAll was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Confirm bool
	}{
		Ctx:     ctx,
		Confirm: confirm,
	}
	mock.lockRecheckAll.Lock()
	mock.calls.RecheckAll = append(mock.calls.RecheckAll, callInfo)
	mock.lockRecheckAll.Unlock()
	return mock.RecheckAllFunc(ctx, confirm)
}

// RecheckAllCalls gets all the calls that were made to RecheckAll.
// Check the length with:
//
//	len(mockedQueue.RecheckAllCalls())
func (mock *QueueMock) RecheckAllCalls() []struct {
	Ctx     context.Context
	Confirm bool
} {
	var calls []struct {
		Ctx     context.Context
		Confirm bool
	}
	mock.lockRecheckAll.RLock()
	calls = mock.calls.RecheckAll
	mock.lockRecheckAll.RUnlock()
	return calls
}

// Restart calls RestartFunc.
func (mock *QueueMock) Restart(ctx context.Context, jobID int64) (domain.Job, error) {
	if mock.RestartFunc == nil {
		panic("QueueMock.RestartFunc: method is nil but Queue.Restart was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		JobID int64
	}{
		Ctx:   ctx,
		JobID: jobID,
	}
	mock.lockRestart.Lock()
	mock.calls.Restart = append(mock.calls.Restart, callInfo)
	mock.lockRestart.Unlock()
	return mock.RestartFunc(ctx, jobID)
}

// RestartCalls gets all the calls that were made to Restart.
// Check the length with:
//
//	len(mockedQueue.RestartCalls())
func (mock *QueueMock) RestartCalls() []struct {
	Ctx   context.Context
	JobID int64
} {
	var calls []struct {
		Ctx   context.Context
		JobID int64
	}
	mock.lockRestart.RLock()
	calls = mock.calls.Restart
	mock.lockRestart.RUnlock()
	return calls
}

// Resume calls ResumeFunc.
func (mock *QueueMock) Resume(ctx context.Context) error {
	if mock.ResumeFunc == nil {
		panic("QueueMock.ResumeFunc: method is nil but Queue.Resume was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockResume.Lock()
	mock.calls.Resume = append(mock.calls.Resume, callInfo)
	mock.lockResume.Unlock()
	return mock.ResumeFunc(ctx)
}

// ResumeCalls gets all the calls that were made to Resume.
// Check the length with:
//
//	len(mockedQueue.ResumeCalls())
func (mock *QueueMock) ResumeCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockResume.RLock()
	calls = mock.calls.Resume
	mock.lockResume.RUnlock()
	return calls
}

// SpaceSweepPreview calls SpaceSweepPreviewFunc.
func (mock *QueueMock) SpaceSweepPreview(ctx context.Context) (job.SpaceSweepPreview, error) {
	if mock.SpaceSweepPreviewFunc == nil {
		panic("QueueMock.SpaceSweepPreviewFunc: method is nil but Queue.SpaceSweepPreview was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockSpaceSweepPreview.Lock()
	mock.calls.SpaceSweepPreview = append(mock.calls.SpaceSweepPreview, callInfo)
	mock.lockSpaceSweepPreview.Unlock()
	return mock.SpaceSweepPreviewFunc(ctx)
}

// SpaceSweepPreviewCalls gets all the calls that were made to SpaceSweepPreview.
// Check the length with:
//
//	len(mockedQueue.SpaceSweepPreviewCalls())
func (mock *QueueMock) SpaceSweepPreviewCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockSpaceSweepPreview.RLock()
	calls = mock.calls.SpaceSweepPreview
	mock.lockSpaceSweepPreview.RUnlock()
	return calls
}

// SpaceSweepRun calls SpaceSweepRunFunc.
func (mock *QueueMock) SpaceSweepRun(ctx context.Context, ids []int64, confirm bool) (job.SpaceSweepPreview, error) {
	if mock.SpaceSweepRunFunc == nil {
		panic("QueueMock.SpaceSweepRunFunc: method is nil but Queue.SpaceSweepRun was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Ids     []int64
		Confirm bool
	}{
		Ctx:     ctx,
		Ids:     ids,
		Confirm: confirm,
	}
	mock.lockSpaceSweepRun.Lock()
	mock.calls.SpaceSweepRun = append(mock.calls.SpaceSweepRun, callInfo)
	mock.lockSpaceSweepRun.Unlock()
	return mock.SpaceSweepRunFunc(ctx, ids, confirm)
}

// SpaceSweepRunCalls gets all the calls that were made to SpaceSweepRun.
// Check the length with:
//
//	len(mockedQueue.SpaceSweepRunCalls())
func (mock *QueueMock) SpaceSweepRunCalls() []struct {
	Ctx     context.Context
	Ids     []int64
	Confirm bool
} {
	var calls []struct {
		Ctx     context.Context
		Ids     []int64
		Confirm bool
	}
	mock.lockSpaceSweepRun.RLock()
	calls = mock.calls.SpaceSweepRun
	mock.lockSpaceSweepRun.RUnlock()
	return calls
}

// Ensure, that AnalyzerMock does implement api.Analyzer.
// If this is not the case, regenerate this file with moq.
var _ api.Analyzer = &AnalyzerMock{}

// AnalyzerMock is a mock implementation of api.Analyzer.
//
//	func TestSomethingThatUsesAnalyzer(t *testing.T) {
//
//		// make and configure a mocked api.Analyzer
//		mockedAnalyzer := &AnalyzerMock{
//			AnalyzeFunc: func(ctx context.Context, path string, origin domain.JobOrigin) (ingest.Result, error) {
//				panic("mock out the Analyze method")
//			},
//		}
//
//		// use mockedAnalyzer in code that requires api.Analyzer
//		// and then make assertions.
//
//	}
type AnalyzerMock struct {
	// AnalyzeFunc mocks the Analyze method.
	AnalyzeFunc func(ctx context.Context, path string, origin domain.JobOrigin) (ingest.Result, error)

	// calls tracks calls to the methods.
	calls struct {
		// Analyze holds details about calls to the Analyze method.
		Analyze []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Origin is the origin argument value.
			Origin domain.JobOrigin
		}
	}
	lockAnalyze sync.RWMutex
}

// Analyze calls AnalyzeFunc.
func (mock *AnalyzerMock) Analyze(ctx context.Context, path string, origin domain.JobOrigin) (ingest.Result, error) {
	if mock.AnalyzeFunc == nil {
		panic("AnalyzerMock.AnalyzeFunc: method is nil but Analyzer.Analyze was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Path   string
		Origin domain.JobOrigin
	}{
		Ctx:    ctx,
		Path:   path,
		Origin: origin,
	}
	mock.lockAnalyze.Lock()
	mock.calls.Analyze = append(mock.calls.Analyze, callInfo)
	mock.lockAnalyze.Unlock()
	return mock.AnalyzeFunc(ctx, path, origin)
}

// AnalyzeCalls gets all the calls that were made to Analyze.
// Check the length with:
//
//	len(mockedAnalyzer.AnalyzeCalls())
func (mock *AnalyzerMock) AnalyzeCalls() []struct {
	Ctx    context.Context
	Path   string
	Origin domain.JobOrigin
} {
	var calls []struct {
		Ctx    context.Context
		Path   string
		Origin domain.JobOrigin
	}
	mock.lockAnalyze.RLock()
	calls = mock.calls.Analyze
	mock.lockAnalyze.RUnlock()
	return calls
}

// Ensure, that ScannerMock does implement api.Scanner.
// If this is not the case, regenerate this file with moq.
var _ api.Scanner = &ScannerMock{}

// ScannerMock is a mock implementation of api.Scanner.
//
//	func TestSomethingThatUsesScanner(t *testing.T) {
//
//		// make and configure a mocked api.Scanner
//		mockedScanner := &ScannerMock{
//			ScanRootFunc: func(ctx context.Context, rootID int64) (ingest.ScanReport, error) {
//				panic("mock out the ScanRoot method")
//			},
//		}
//
//		// use mockedScanner in code that requires api.Scanner
//		// and then make assertions.
//
//	}
type ScannerMock struct {
	// ScanRootFunc mocks the ScanRoot method.
	ScanRootFunc func(ctx context.Context, rootID int64) (ingest.ScanReport, error)

	// calls tracks calls to the methods.
	calls struct {
		// ScanRoot holds details about calls to the ScanRoot method.
		ScanRoot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RootID is the rootID argument value.
			RootID int64
		}
	}
	lockScanRoot sync.RWMutex
}

// ScanRoot calls ScanRootFunc.
func (mock *ScannerMock) ScanRoot(ctx context.Context, rootID int64) (ingest.ScanReport, error) {
	if mock.ScanRootFunc == nil {
		panic("ScannerMock.ScanRootFunc: method is nil but Scanner.ScanRoot was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RootID int64
	}{
		Ctx:    ctx,
		RootID: rootID,
	}
	mock.lockScanRoot.Lock()
	mock.calls.ScanRoot = append(mock.calls.ScanRoot, callInfo)
	mock.lockScanRoot.Unlock()
	return mock.ScanRootFunc(ctx, rootID)
}

// ScanRootCalls gets all the calls that were made to ScanRoot.
// Check the length with:
//
//	len(mockedScanner.ScanRootCalls())
func (mock *ScannerMock) ScanRootCalls() []struct {
	Ctx    context.Context
	RootID int64
} {
	var calls []struct {
		Ctx    context.Context
		RootID int64
	}
	mock.lockScanRoot.RLock()
	calls = mock.calls.ScanRoot
	mock.lockScanRoot.RUnlock()
	return calls
}

// Ensure, that WebhooksMock does implement api.Webhooks.
// If this is not the case, regenerate this file with moq.
var _ api.Webhooks = &WebhooksMock{}

// WebhooksMock is a mock implementation of api.Webhooks.
//
//	func TestSomethingThatUsesWebhooks(t *testing.T) {
//
//		// make and configure a mocked api.Webhooks
//		mockedWebhooks := &WebhooksMock{
//			HandleFunc: func(ctx context.Context, webhookID string, ev ingest.Event) (ingest.Ack, error) {
//				panic("mock out the Handle method")
//			},
//		}
//
//		// use mockedWebhooks in code that requires api.Webhooks
//		// and then make assertions.
//
//	}
type WebhooksMock struct {
	// HandleFunc mocks the Handle method.
	HandleFunc func(ctx context.Context, webhookID string, ev ingest.Event) (ingest.Ack, error)

	// calls tracks calls to the methods.
	calls struct {
		// Handle holds details about calls to the Handle method.
		Handle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WebhookID is the webhookID argument value.
			WebhookID string
			// Ev is the ev argument value.
			Ev ingest.Event
		}
	}
	lockHandle sync.RWMutex
}

// Handle calls HandleFunc.
func (mock *WebhooksMock) Handle(ctx context.Context, webhookID string, ev ingest.Event) (ingest.Ack, error) {
	if mock.HandleFunc == nil {
		panic("WebhooksMock.HandleFunc: method is nil but Webhooks.Handle was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		WebhookID string
		Ev        ingest.Event
	}{
		Ctx:       ctx,
		WebhookID: webhookID,
		Ev:        ev,
	}
	mock.lockHandle.Lock()
	mock.calls.Handle = append(mock.calls.Handle, callInfo)
	mock.lockHandle.Unlock()
	return mock.HandleFunc(ctx, webhookID, ev)
}

// HandleCalls gets all the calls that were made to Handle.
// Check the length with:
//
//	len(mockedWebhooks.HandleCalls())
func (mock *WebhooksMock) HandleCalls() []struct {
	Ctx       context.Context
	WebhookID string
	Ev        ingest.Event
} {
	var calls []struct {
		Ctx       context.Context
		WebhookID string
		Ev        ingest.Event
	}
	mock.lockHandle.RLock()
	calls = mock.calls.Handle
	mock.lockHandle.RUnlock()
	return calls
}

// Ensure, that HardwareMock does implement api.Hardware.
// If this is not the case, regenerate this file with moq.
var _ api.Hardware = &HardwareMock{}

// HardwareMock is a mock implementation of api.Hardware.
//
//	func TestSomethingThatUsesHardware(t *testing.T) {
//
//		// make and configure a mocked api.Hardware
//		mockedHardware := &HardwareMock{
//			CapabilitiesFunc: func(ctx context.Context) (hardware.Capabilities, error) {
//				panic("mock out the Capabilities method")
//			},
//			ProbeFunc: func(ctx context.Context) (hardware.Capabilities, error) {
//				panic("mock out the Probe method")
//			},
//		}
//
//		// use mockedHardware in code that requires api.Hardware
//		// and then make assertions.
//
//	}
type HardwareMock struct {
	// CapabilitiesFunc mocks the Capabilities method.
	CapabilitiesFunc func(ctx context.Context) (hardware.Capabilities, error)

	// ProbeFunc mocks the Probe method.
	ProbeFunc func(ctx context.Context) (hardware.Capabilities, error)

	// calls tracks calls to the methods.
	calls struct {
		// Capabilities holds details about calls to the Capabilities method.
		Capabilities []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Probe holds details about calls to the Probe method.
		Probe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockCapabilities sync.RWMutex
	lockProbe        sync.RWMutex
}

// Capabilities calls CapabilitiesFunc.
func (mock *HardwareMock) Capabilities(ctx context.Context) (hardware.Capabilities, error) {
	if mock.CapabilitiesFunc == nil {
		panic("HardwareMock.CapabilitiesFunc: method is nil but Hardware.Capabilities was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCapabilities.Lock()
	mock.calls.Capabilities = append(mock.calls.Capabilities, callInfo)
	mock.lockCapabilities.Unlock()
	return mock.CapabilitiesFunc(ctx)
}

// CapabilitiesCalls gets all the calls that were made to Capabilities.
// Check the length with:
//
//	len(mockedHardware.CapabilitiesCalls())
func (mock *HardwareMock) CapabilitiesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCapabilities.RLock()
	calls = mock.calls.Capabilities
	mock.lockCapabilities.RUnlock()
	return calls
}

// Probe calls ProbeFunc.
func (mock *HardwareMock) Probe(ctx context.Context) (hardware.Capabilities, error) {
	if mock.ProbeFunc == nil {
		panic("HardwareMock.ProbeFunc: method is nil but Hardware.Probe was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockProbe.Lock()
	mock.calls.Probe = append(mock.calls.Probe, callInfo)
	mock.lockProbe.Unlock()
	return mock.ProbeFunc(ctx)
}

// ProbeCalls gets all the calls that were made to Probe.
// Check the length with:
//
//	len(mockedHardware.ProbeCalls())
func (mock *HardwareMock) ProbeCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockProbe.RLock()
	calls = mock.calls.Probe
	mock.lockProbe.RUnlock()
	return calls
}

// Ensure, that FingerprinterMock does implement api.Fingerprinter.
// If this is not the case, regenerate this file with moq.
var _ api.Fingerprinter = &FingerprinterMock{}

// FingerprinterMock is a mock implementation of api.Fingerprinter.
//
//	func TestSomethingThatUsesFingerprinter(t *testing.T) {
//
//		// make and configure a mocked api.Fingerprinter
//		mockedFingerprinter := &FingerprinterMock{
//			FullFunc: func(path string) (string, error) {
//				panic("mock out the Full method")
//			},
//			SparseFunc: func(path string) (string, error) {
//				panic("mock out the Sparse method")
//			},
//		}
//
//		// use mockedFingerprinter in code that requires api.Fingerprinter
//		// and then make assertions.
//
//	}
type FingerprinterMock struct {
	// FullFunc mocks the Full method.
	FullFunc func(path string) (string, error)

	// SparseFunc mocks the Sparse method.
	SparseFunc func(path string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Full holds details about calls to the Full method.
		Full []struct {
			// Path is the path argument value.
			Path string
		}
		// Sparse holds details about calls to the Sparse method.
		Sparse []struct {
			// Path is the path argument value.
			Path string
		}
	}
	lockFull   sync.RWMutex
	lockSparse sync.RWMutex
}

// Full calls FullFunc.
func (mock *FingerprinterMock) Full(path string) (string, error) {
	if mock.FullFunc == nil {
		panic("FingerprinterMock.FullFunc: method is nil but Fingerprinter.Full was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockFull.Lock()
	mock.calls.Full = append(mock.calls.Full, callInfo)
	mock.lockFull.Unlock()
	return mock.FullFunc(path)
}

// FullCalls gets all the calls that were made to Full.
// Check the length with:
//
//	len(mockedFingerprinter.FullCalls())
func (mock *FingerprinterMock) FullCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockFull.RLock()
	calls = mock.calls.Full
	mock.lockFull.RUnlock()
	return calls
}

// Sparse calls SparseFunc.
func (mock *FingerprinterMock) Sparse(path string) (string, error) {
	if mock.SparseFunc == nil {
		panic("FingerprinterMock.SparseFunc: method is nil but Fingerprinter.Sparse was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockSparse.Lock()
	mock.calls.Sparse = append(mock.calls.Sparse, callInfo)
	mock.lockSparse.Unlock()
	return mock.SparseFunc(path)
}

// SparseCalls gets all the calls that were made to Sparse.
// Check the length with:
//
//	len(mockedFingerprinter.SparseCalls())
func (mock *FingerprinterMock) SparseCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockSparse.RLock()
	calls = mock.calls.Sparse
	mock.lockSparse.RUnlock()
	return calls
}

// Ensure, that FSMock does implement api.FS.
// If this is not the case, regenerate this file with moq.
var _ api.FS = &FSMock{}

// FSMock is a mock implementation of api.FS.
//
//	func TestSomethingThatUsesFS(t *testing.T) {
//
//		// make and configure a mocked api.FS
//		mockedFS := &FSMock{
//			StatFunc: func(path string) (fsx.FileInfo, error) {
//				panic("mock out the Stat method")
//			},
//		}
//
//		// use mockedFS in code that requires api.FS
//		// and then make assertions.
//
//	}
type FSMock struct {
	// StatFunc mocks the Stat method.
	StatFunc func(path string) (fsx.FileInfo, error)

	// calls tracks calls to the methods.
	calls struct {
		// Stat holds details about calls to the Stat method.
		Stat []struct {
			// Path is the path argument value.
			Path string
		}
	}
	lockStat sync.RWMutex
}

// Stat calls StatFunc.
func (mock *FSMock) Stat(path string) (fsx.FileInfo, error) {
	if mock.StatFunc == nil {
		panic("FSMock.StatFunc: method is nil but FS.Stat was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockStat.Lock()
	mock.calls.Stat = append(mock.calls.Stat, callInfo)
	mock.lockStat.Unlock()
	return mock.StatFunc(path)
}

// StatCalls gets all the calls that were made to Stat.
// Check the length with:
//
//	len(mockedFS.StatCalls())
func (mock *FSMock) StatCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockStat.RLock()
	calls = mock.calls.Stat
	mock.lockStat.RUnlock()
	return calls
}

// Ensure, that PingerMock does implement api.Pinger.
// If this is not the case, regenerate this file with moq.
var _ api.Pinger = &PingerMock{}

// PingerMock is a mock implementation of api.Pinger.
//
//	func TestSomethingThatUsesPinger(t *testing.T) {
//
//		// make and configure a mocked api.Pinger
//		mockedPinger := &PingerMock{
//			PingContextFunc: func(ctx context.Context) error {
//				panic("mock out the PingContext method")
//			},
//		}
//
//		// use mockedPinger in code that requires api.Pinger
//		// and then make assertions.
//
//	}
type PingerMock struct {
	// PingContextFunc mocks the PingContext method.
	PingContextFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// PingContext holds details about calls to the PingContext method.
		PingContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockPingContext sync.RWMutex
}

// PingContext calls PingContextFunc.
func (mock *PingerMock) PingContext(ctx context.Context) error {
	if mock.PingContextFunc == nil {
		panic("PingerMock.PingContextFunc: method is nil but Pinger.PingContext was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPingContext.Lock()
	mock.calls.PingContext = append(mock.calls.PingContext, callInfo)
	mock.lockPingContext.Unlock()
	return mock.PingContextFunc(ctx)
}

// PingContextCalls gets all the calls that were made to PingContext.
// Check the length with:
//
//	len(mockedPinger.PingContextCalls())
func (mock *PingerMock) PingContextCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPingContext.RLock()
	calls = mock.calls.PingContext
	mock.lockPingContext.RUnlock()
	return calls
}

// Ensure, that PlexAuthMock does implement api.PlexAuth.
// If this is not the case, regenerate this file with moq.
var _ api.PlexAuth = &PlexAuthMock{}

// PlexAuthMock is a mock implementation of api.PlexAuth.
//
//	func TestSomethingThatUsesPlexAuth(t *testing.T) {
//
//		// make and configure a mocked api.PlexAuth
//		mockedPlexAuth := &PlexAuthMock{
//			AuthURLFunc: func(clientIdentifier string, code string) string {
//				panic("mock out the AuthURL method")
//			},
//			CheckPinFunc: func(ctx context.Context, clientIdentifier string, id int64) (plex.Pin, error) {
//				panic("mock out the CheckPin method")
//			},
//			CreatePinFunc: func(ctx context.Context, clientIdentifier string) (plex.Pin, error) {
//				panic("mock out the CreatePin method")
//			},
//		}
//
//		// use mockedPlexAuth in code that requires api.PlexAuth
//		// and then make assertions.
//
//	}
type PlexAuthMock struct {
	// AuthURLFunc mocks the AuthURL method.
	AuthURLFunc func(clientIdentifier string, code string) string

	// CheckPinFunc mocks the CheckPin method.
	CheckPinFunc func(ctx context.Context, clientIdentifier string, id int64) (plex.Pin, error)

	// CreatePinFunc mocks the CreatePin method.
	CreatePinFunc func(ctx context.Context, clientIdentifier string) (plex.Pin, error)

	// calls tracks calls to the methods.
	calls struct {
		// AuthURL holds details about calls to the AuthURL method.
		AuthURL []struct {
			// ClientIdentifier is the clientIdentifier argument value.
			ClientIdentifier string
			// Code is the code argument value.
			Code string
		}
		// CheckPin holds details about calls to the CheckPin method.
		CheckPin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClientIdentifier is the clientIdentifier argument value.
			ClientIdentifier string
			// ID is the id argument value.
			ID int64
		}
		// CreatePin holds details about calls to the CreatePin method.
		CreatePin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ClientIdentifier is the clientIdentifier argument value.
			ClientIdentifier string
		}
	}
	lockAuthURL   sync.RWMutex
	lockCheckPin  sync.RWMutex
	lockCreatePin sync.RWMutex
}

// AuthURL calls AuthURLFunc.
func (mock *PlexAuthMock) AuthURL(clientIdentifier string, code string) string {
	if mock.AuthURLFunc == nil {
		panic("PlexAuthMock.AuthURLFunc: method is nil but PlexAuth.AuthURL was just called")
	}
	callInfo := struct {
		ClientIdentifier string
		Code             string
	}{
		ClientIdentifier: clientIdentifier,
		Code:             code,
	}
	mock.lockAuthURL.Lock()
	mock.calls.AuthURL = append(mock.calls.AuthURL, callInfo)
	mock.lockAuthURL.Unlock()
	return mock.AuthURLFunc(clientIdentifier, code)
}

// AuthURLCalls gets all the calls that were made to AuthURL.
// Check the length with:
//
//	len(mockedPlexAuth.AuthURLCalls())
func (mock *PlexAuthMock) AuthURLCalls() []struct {
	ClientIdentifier string
	Code             string
} {
	var calls []struct {
		ClientIdentifier string
		Code             string
	}
	mock.lockAuthURL.RLock()
	calls = mock.calls.AuthURL
	mock.lockAuthURL.RUnlock()
	return calls
}

// CheckPin calls CheckPinFunc.
func (mock *PlexAuthMock) CheckPin(ctx context.Context, clientIdentifier string, id int64) (plex.Pin, error) {
	if mock.CheckPinFunc == nil {
		panic("PlexAuthMock.CheckPinFunc: method is nil but PlexAuth.CheckPin was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		ClientIdentifier string
		ID               int64
	}{
		Ctx:              ctx,
		ClientIdentifier: clientIdentifier,
		ID:               id,
	}
	mock.lockCheckPin.Lock()
	mock.calls.CheckPin = append(mock.calls.CheckPin, callInfo)
	mock.lockCheckPin.Unlock()
	return mock.CheckPinFunc(ctx, clientIdentifier, id)
}

// CheckPinCalls gets all the calls that were made to CheckPin.
// Check the length with:
//
//	len(mockedPlexAuth.CheckPinCalls())
func (mock *PlexAuthMock) CheckPinCalls() []struct {
	Ctx              context.Context
	ClientIdentifier string
	ID               int64
} {
	var calls []struct {
		Ctx              context.Context
		ClientIdentifier string
		ID               int64
	}
	mock.lockCheckPin.RLock()
	calls = mock.calls.CheckPin
	mock.lockCheckPin.RUnlock()
	return calls
}

// CreatePin calls CreatePinFunc.
func (mock *PlexAuthMock) CreatePin(ctx context.Context, clientIdentifier string) (plex.Pin, error) {
	if mock.CreatePinFunc == nil {
		panic("PlexAuthMock.CreatePinFunc: method is nil but PlexAuth.CreatePin was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		ClientIdentifier string
	}{
		Ctx:              ctx,
		ClientIdentifier: clientIdentifier,
	}
	mock.lockCreatePin.Lock()
	mock.calls.CreatePin = append(mock.calls.CreatePin, callInfo)
	mock.lockCreatePin.Unlock()
	return mock.CreatePinFunc(ctx, clientIdentifier)
}

// CreatePinCalls gets all the calls that were made to CreatePin.
// Check the length with:
//
//	len(mockedPlexAuth.CreatePinCalls())
func (mock *PlexAuthMock) CreatePinCalls() []struct {
	Ctx              context.Context
	ClientIdentifier string
} {
	var calls []struct {
		Ctx              context.Context
		ClientIdentifier string
	}
	mock.lockCreatePin.RLock()
	calls = mock.calls.CreatePin
	mock.lockCreatePin.RUnlock()
	return calls
}

// Ensure, that PlexClientMock does implement api.PlexClient.
// If this is not the case, regenerate this file with moq.
var _ api.PlexClient = &PlexClientMock{}

// PlexClientMock is a mock implementation of api.PlexClient.
//
//	func TestSomethingThatUsesPlexClient(t *testing.T) {
//
//		// make and configure a mocked api.PlexClient
//		mockedPlexClient := &PlexClientMock{
//			ResolveFunc: func(ctx context.Context, localPath string) (plex.Target, error) {
//				panic("mock out the Resolve method")
//			},
//			SectionsFunc: func(ctx context.Context) ([]plex.Section, error) {
//				panic("mock out the Sections method")
//			},
//			TestFunc: func(ctx context.Context) plex.TestResult {
//				panic("mock out the Test method")
//			},
//		}
//
//		// use mockedPlexClient in code that requires api.PlexClient
//		// and then make assertions.
//
//	}
type PlexClientMock struct {
	// ResolveFunc mocks the Resolve method.
	ResolveFunc func(ctx context.Context, localPath string) (plex.Target, error)

	// SectionsFunc mocks the Sections method.
	SectionsFunc func(ctx context.Context) ([]plex.Section, error)

	// TestFunc mocks the Test method.
	TestFunc func(ctx context.Context) plex.TestResult

	// calls tracks calls to the methods.
	calls struct {
		// Resolve holds details about calls to the Resolve method.
		Resolve []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// LocalPath is the localPath argument value.
			LocalPath string
		}
		// Sections holds details about calls to the Sections method.
		Sections []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Test holds details about calls to the Test method.
		Test []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockResolve  sync.RWMutex
	lockSections sync.RWMutex
	lockTest     sync.RWMutex
}

// Resolve calls ResolveFunc.
func (mock *PlexClientMock) Resolve(ctx context.Context, localPath string) (plex.Target, error) {
	if mock.ResolveFunc == nil {
		panic("PlexClientMock.ResolveFunc: method is nil but PlexClient.Resolve was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		LocalPath string
	}{
		Ctx:       ctx,
		LocalPath: localPath,
	}
	mock.lockResolve.Lock()
	mock.calls.Resolve = append(mock.calls.Resolve, callInfo)
	mock.lockResolve.Unlock()
	return mock.ResolveFunc(ctx, localPath)
}

// ResolveCalls gets all the calls that were made to Resolve.
// Check the length with:
//
//	len(mockedPlexClient.ResolveCalls())
func (mock *PlexClientMock) ResolveCalls() []struct {
	Ctx       context.Context
	LocalPath string
} {
	var calls []struct {
		Ctx       context.Context
		LocalPath string
	}
	mock.lockResolve.RLock()
	calls = mock.calls.Resolve
	mock.lockResolve.RUnlock()
	return calls
}

// Sections calls SectionsFunc.
func (mock *PlexClientMock) Sections(ctx context.Context) ([]plex.Section, error) {
	if mock.SectionsFunc == nil {
		panic("PlexClientMock.SectionsFunc: method is nil but PlexClient.Sections was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockSections.Lock()
	mock.calls.Sections = append(mock.calls.Sections, callInfo)
	mock.lockSections.Unlock()
	return mock.SectionsFunc(ctx)
}

// SectionsCalls gets all the calls that were made to Sections.
// Check the length with:
//
//	len(mockedPlexClient.SectionsCalls())
func (mock *PlexClientMock) SectionsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockSections.RLock()
	calls = mock.calls.Sections
	mock.lockSections.RUnlock()
	return calls
}

// Test calls TestFunc.
func (mock *PlexClientMock) Test(ctx context.Context) plex.TestResult {
	if mock.TestFunc == nil {
		panic("PlexClientMock.TestFunc: method is nil but PlexClient.Test was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockTest.Lock()
	mock.calls.Test = append(mock.calls.Test, callInfo)
	mock.lockTest.Unlock()
	return mock.TestFunc(ctx)
}

// TestCalls gets all the calls that were made to Test.
// Check the length with:
//
//	len(mockedPlexClient.TestCalls())
func (mock *PlexClientMock) TestCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockTest.RLock()
	calls = mock.calls.Test
	mock.lockTest.RUnlock()
	return calls
}

// Ensure, that ArrClientMock does implement api.ArrClient.
// If this is not the case, regenerate this file with moq.
var _ api.ArrClient = &ArrClientMock{}

// ArrClientMock is a mock implementation of api.ArrClient.
//
//	func TestSomethingThatUsesArrClient(t *testing.T) {
//
//		// make and configure a mocked api.ArrClient
//		mockedArrClient := &ArrClientMock{
//			RootFoldersFunc: func(ctx context.Context) ([]arr.RootFolder, error) {
//				panic("mock out the RootFolders method")
//			},
//			TestFunc: func(ctx context.Context) arr.TestResult {
//				panic("mock out the Test method")
//			},
//		}
//
//		// use mockedArrClient in code that requires api.ArrClient
//		// and then make assertions.
//
//	}
type ArrClientMock struct {
	// RootFoldersFunc mocks the RootFolders method.
	RootFoldersFunc func(ctx context.Context) ([]arr.RootFolder, error)

	// TestFunc mocks the Test method.
	TestFunc func(ctx context.Context) arr.TestResult

	// calls tracks calls to the methods.
	calls struct {
		// RootFolders holds details about calls to the RootFolders method.
		RootFolders []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Test holds details about calls to the Test method.
		Test []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockRootFolders sync.RWMutex
	lockTest        sync.RWMutex
}

// RootFolders calls RootFoldersFunc.
func (mock *ArrClientMock) RootFolders(ctx context.Context) ([]arr.RootFolder, error) {
	if mock.RootFoldersFunc == nil {
		panic("ArrClientMock.RootFoldersFunc: method is nil but ArrClient.RootFolders was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRootFolders.Lock()
	mock.calls.RootFolders = append(mock.calls.RootFolders, callInfo)
	mock.lockRootFolders.Unlock()
	return mock.RootFoldersFunc(ctx)
}

// RootFoldersCalls gets all the calls that were made to RootFolders.
// Check the length with:
//
//	len(mockedArrClient.RootFoldersCalls())
func (mock *ArrClientMock) RootFoldersCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRootFolders.RLock()
	calls = mock.calls.RootFolders
	mock.lockRootFolders.RUnlock()
	return calls
}

// Test calls TestFunc.
func (mock *ArrClientMock) Test(ctx context.Context) arr.TestResult {
	if mock.TestFunc == nil {
		panic("ArrClientMock.TestFunc: method is nil but ArrClient.Test was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockTest.Lock()
	mock.calls.Test = append(mock.calls.Test, callInfo)
	mock.lockTest.Unlock()
	return mock.TestFunc(ctx)
}

// TestCalls gets all the calls that were made to Test.
// Check the length with:
//
//	len(mockedArrClient.TestCalls())
func (mock *ArrClientMock) TestCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockTest.RLock()
	calls = mock.calls.Test
	mock.lockTest.RUnlock()
	return calls
}

// Ensure, that MetricsMock does implement api.Metrics.
// If this is not the case, regenerate this file with moq.
var _ api.Metrics = &MetricsMock{}

// MetricsMock is a mock implementation of api.Metrics.
//
//	func TestSomethingThatUsesMetrics(t *testing.T) {
//
//		// make and configure a mocked api.Metrics
//		mockedMetrics := &MetricsMock{
//			ErrorFunc: func(category string)  {
//				panic("mock out the Error method")
//			},
//			JobObservedFunc: func(state domain.JobState, kind domain.Kind, origin domain.JobOrigin)  {
//				panic("mock out the JobObserved method")
//			},
//		}
//
//		// use mockedMetrics in code that requires api.Metrics
//		// and then make assertions.
//
//	}
type MetricsMock struct {
	// ErrorFunc mocks the Error method.
	ErrorFunc func(category string)

	// JobObservedFunc mocks the JobObserved method.
	JobObservedFunc func(state domain.JobState, kind domain.Kind, origin domain.JobOrigin)

	// calls tracks calls to the methods.
	calls struct {
		// Error holds details about calls to the Error method.
		Error []struct {
			// Category is the category argument value.
			Category string
		}
		// JobObserved holds details about calls to the JobObserved method.
		JobObserved []struct {
			// State is the state argument value.
			State domain.JobState
			// Kind is the kind argument value.
			Kind domain.Kind
			// Origin is the origin argument value.
			Origin domain.JobOrigin
		}
	}
	lockError       sync.RWMutex
	lockJobObserved sync.RWMutex
}

// Error calls ErrorFunc.
func (mock *MetricsMock) Error(category string) {
	if mock.ErrorFunc == nil {
		panic("MetricsMock.ErrorFunc: method is nil but Metrics.Error was just called")
	}
	callInfo := struct {
		Category string
	}{
		Category: category,
	}
	mock.lockError.Lock()
	mock.calls.Error = append(mock.calls.Error, callInfo)
	mock.lockError.Unlock()
	mock.ErrorFunc(category)
}

// ErrorCalls gets all the calls that were made to Error.
// Check the length with:
//
//	len(mockedMetrics.ErrorCalls())
func (mock *MetricsMock) ErrorCalls() []struct {
	Category string
} {
	var calls []struct {
		Category string
	}
	mock.lockError.RLock()
	calls = mock.calls.Error
	mock.lockError.RUnlock()
	return calls
}

// JobObserved calls JobObservedFunc.
func (mock *MetricsMock) JobObserved(state domain.JobState, kind domain.Kind, origin domain.JobOrigin) {
	if mock.JobObservedFunc == nil {
		panic("MetricsMock.JobObservedFunc: method is nil but Metrics.JobObserved was just called")
	}
	callInfo := struct {
		State  domain.JobState
		Kind   domain.Kind
		Origin domain.JobOrigin
	}{
		State:  state,
		Kind:   kind,
		Origin: origin,
	}
	mock.lockJobObserved.Lock()
	mock.calls.JobObserved = append(mock.calls.JobObserved, callInfo)
	mock.lockJobObserved.Unlock()
	mock.JobObservedFunc(state, kind, origin)
}

// JobObservedCalls gets all the calls that were made to JobObserved.
// Check the length with:
//
//	len(mockedMetrics.JobObservedCalls())
func (mock *MetricsMock) JobObservedCalls() []struct {
	State  domain.JobState
	Kind   domain.Kind
	Origin domain.JobOrigin
} {
	var calls []struct {
		State  domain.JobState
		Kind   domain.Kind
		Origin domain.JobOrigin
	}
	mock.lockJobObserved.RLock()
	calls = mock.calls.JobObserved
	mock.lockJobObserved.RUnlock()
	return calls
}
