// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/yama6a/codarr/internal/pkg/clock"
	"sync"
	"time"
)

// Ensure, that ClockMock does implement clock.Clock.
// If this is not the case, regenerate this file with moq.
var _ clock.Clock = &ClockMock{}

// ClockMock is a mock implementation of clock.Clock.
//
//	func TestSomethingThatUsesClock(t *testing.T) {
//
//		// make and configure a mocked clock.Clock
//		mockedClock := &ClockMock{
//			AfterFunc: func(d time.Duration) <-chan time.Time {
//				panic("mock out the After method")
//			},
//			NowFunc: func() time.Time {
//				panic("mock out the Now method")
//			},
//			SinceFunc: func(t time.Time) time.Duration {
//				panic("mock out the Since method")
//			},
//		}
//
//		// use mockedClock in code that requires clock.Clock
//		// and then make assertions.
//
//	}
type ClockMock struct {
	// AfterFunc mocks the After method.
	AfterFunc func(d time.Duration) <-chan time.Time

	// NowFunc mocks the Now method.
	NowFunc func() time.Time

	// SinceFunc mocks the Since method.
	SinceFunc func(t time.Time) time.Duration

	// calls tracks calls to the methods.
	calls struct {
		// After holds details about calls to the After method.
		After []struct {
			// D is the d argument value.
			D time.Duration
		}
		// Now holds details about calls to the Now method.
		Now []struct {
		}
		// Since holds details about calls to the Since method.
		Since []struct {
			// T is the t argument value.
			T time.Time
		}
	}
	lockAfter sync.RWMutex
	lockNow   sync.RWMutex
	lockSince sync.RWMutex
}

// After calls AfterFunc.
func (mock *ClockMock) After(d time.Duration) <-chan time.Time {
	if mock.AfterFunc == nil {
		panic("ClockMock.AfterFunc: method is nil but Clock.After was just called")
	}
	callInfo := struct {
		D time.Duration
	}{
		D: d,
	}
	mock.lockAfter.Lock()
	mock.calls.After = append(mock.calls.After, callInfo)
	mock.lockAfter.Unlock()
	return mock.AfterFunc(d)
}

// AfterCalls gets all the calls that were made to After.
// Check the length with:
//
//	len(mockedClock.AfterCalls())
func (mock *ClockMock) AfterCalls() []struct {
	D time.Duration
} {
	var calls []struct {
		D time.Duration
	}
	mock.lockAfter.RLock()
	calls = mock.calls.After
	mock.lockAfter.RUnlock()
	return calls
}

// Now calls NowFunc.
func (mock *ClockMock) Now() time.Time {
	if mock.NowFunc == nil {
		panic("ClockMock.NowFunc: method is nil but Clock.Now was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNow.Lock()
	mock.calls.Now = append(mock.calls.Now, callInfo)
	mock.lockNow.Unlock()
	return mock.NowFunc()
}

// NowCalls gets all the calls that were made to Now.
// Check the length with:
//
//	len(mockedClock.NowCalls())
func (mock *ClockMock) NowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNow.RLock()
	calls = mock.calls.Now
	mock.lockNow.RUnlock()
	return calls
}

// Since calls SinceFunc.
func (mock *ClockMock) Since(t time.Time) time.Duration {
	if mock.SinceFunc == nil {
		panic("ClockMock.SinceFunc: method is nil but Clock.Since was just called")
	}
	callInfo := struct {
		T time.Time
	}{
		T: t,
	}
	mock.lockSince.Lock()
	mock.calls.Since = append(mock.calls.Since, callInfo)
	mock.lockSince.Unlock()
	return mock.SinceFunc(t)
}

// SinceCalls gets all the calls that were made to Since.
// Check the length with:
//
//	len(mockedClock.SinceCalls())
func (mock *ClockMock) SinceCalls() []struct {
	T time.Time
} {
	var calls []struct {
		T time.Time
	}
	mock.lockSince.RLock()
	calls = mock.calls.Since
	mock.lockSince.RUnlock()
	return calls
}
