// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/yama6a/codarr/internal/ingest"
	"github.com/yama6a/codarr/internal/pkg/domain"
	"github.com/yama6a/codarr/internal/pkg/store"
	"sync"
)

// Ensure, that AnalysisStoreMock does implement ingest.AnalysisStore.
// If this is not the case, regenerate this file with moq.
var _ ingest.AnalysisStore = &AnalysisStoreMock{}

// AnalysisStoreMock is a mock implementation of ingest.AnalysisStore.
//
//	func TestSomethingThatUsesAnalysisStore(t *testing.T) {
//
//		// make and configure a mocked ingest.AnalysisStore
//		mockedAnalysisStore := &AnalysisStoreMock{
//			EnqueueJobFunc: func(ctx context.Context, j domain.Job) (domain.Job, bool, error) {
//				panic("mock out the EnqueueJob method")
//			},
//			GetMediaFileByPathFunc: func(ctx context.Context, path string) (domain.MediaFile, error) {
//				panic("mock out the GetMediaFileByPath method")
//			},
//			GetSettingsFunc: func(ctx context.Context) (domain.Settings, error) {
//				panic("mock out the GetSettings method")
//			},
//			ListRootsFunc: func(ctx context.Context) ([]domain.Root, error) {
//				panic("mock out the ListRoots method")
//			},
//			SetMediaStatusFunc: func(ctx context.Context, id int64, status domain.MediaStatus, lastError string) error {
//				panic("mock out the SetMediaStatus method")
//			},
//			UpdateMediaAnalysisFunc: func(ctx context.Context, u store.AnalysisUpdate) error {
//				panic("mock out the UpdateMediaAnalysis method")
//			},
//			UpsertMediaFileFunc: func(ctx context.Context, m domain.MediaFile) (domain.MediaFile, error) {
//				panic("mock out the UpsertMediaFile method")
//			},
//		}
//
//		// use mockedAnalysisStore in code that requires ingest.AnalysisStore
//		// and then make assertions.
//
//	}
type AnalysisStoreMock struct {
	// EnqueueJobFunc mocks the EnqueueJob method.
	EnqueueJobFunc func(ctx context.Context, j domain.Job) (domain.Job, bool, error)

	// GetMediaFileByPathFunc mocks the GetMediaFileByPath method.
	GetMediaFileByPathFunc func(ctx context.Context, path string) (domain.MediaFile, error)

	// GetSettingsFunc mocks the GetSettings method.
	GetSettingsFunc func(ctx context.Context) (domain.Settings, error)

	// ListRootsFunc mocks the ListRoots method.
	ListRootsFunc func(ctx context.Context) ([]domain.Root, error)

	// SetMediaStatusFunc mocks the SetMediaStatus method.
	SetMediaStatusFunc func(ctx context.Context, id int64, status domain.MediaStatus, lastError string) error

	// UpdateMediaAnalysisFunc mocks the UpdateMediaAnalysis method.
	UpdateMediaAnalysisFunc func(ctx context.Context, u store.AnalysisUpdate) error

	// UpsertMediaFileFunc mocks the UpsertMediaFile method.
	UpsertMediaFileFunc func(ctx context.Context, m domain.MediaFile) (domain.MediaFile, error)

	// calls tracks calls to the methods.
	calls struct {
		// EnqueueJob holds details about calls to the EnqueueJob method.
		EnqueueJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// J is the j argument value.
			J domain.Job
		}
		// GetMediaFileByPath holds details about calls to the GetMediaFileByPath method.
		GetMediaFileByPath []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
		// GetSettings holds details about calls to the GetSettings method.
		GetSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListRoots holds details about calls to the ListRoots method.
		ListRoots []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// SetMediaStatus holds details about calls to the SetMediaStatus method.
		SetMediaStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Status is the status argument value.
			Status domain.MediaStatus
			// LastError is the lastError argument value.
			LastError string
		}
		// UpdateMediaAnalysis holds details about calls to the UpdateMediaAnalysis method.
		UpdateMediaAnalysis []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// U is the u argument value.
			U store.AnalysisUpdate
		}
		// UpsertMediaFile holds details about calls to the UpsertMediaFile method.
		UpsertMediaFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// M is the m argument value.
			M domain.MediaFile
		}
	}
	lockEnqueueJob          sync.RWMutex
	lockGetMediaFileByPath  sync.RWMutex
	lockGetSettings         sync.RWMutex
	lockListRoots           sync.RWMutex
	lockSetMediaStatus      sync.RWMutex
	lockUpdateMediaAnalysis sync.RWMutex
	lockUpsertMediaFile     sync.RWMutex
}

// EnqueueJob calls EnqueueJobFunc.
func (mock *AnalysisStoreMock) EnqueueJob(ctx context.Context, j domain.Job) (domain.Job, bool, error) {
	if mock.EnqueueJobFunc == nil {
		panic("AnalysisStoreMock.EnqueueJobFunc: method is nil but AnalysisStore.EnqueueJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		J   domain.Job
	}{
		Ctx: ctx,
		J:   j,
	}
	mock.lockEnqueueJob.Lock()
	mock.calls.EnqueueJob = append(mock.calls.EnqueueJob, callInfo)
	mock.lockEnqueueJob.Unlock()
	return mock.EnqueueJobFunc(ctx, j)
}

// EnqueueJobCalls gets all the calls that were made to EnqueueJob.
// Check the length with:
//
//	len(mockedAnalysisStore.EnqueueJobCalls())
func (mock *AnalysisStoreMock) EnqueueJobCalls() []struct {
	Ctx context.Context
	J   domain.Job
} {
	var calls []struct {
		Ctx context.Context
		J   domain.Job
	}
	mock.lockEnqueueJob.RLock()
	calls = mock.calls.EnqueueJob
	mock.lockEnqueueJob.RUnlock()
	return calls
}

// GetMediaFileByPath calls GetMediaFileByPathFunc.
func (mock *AnalysisStoreMock) GetMediaFileByPath(ctx context.Context, path string) (domain.MediaFile, error) {
	if mock.GetMediaFileByPathFunc == nil {
		panic("AnalysisStoreMock.GetMediaFileByPathFunc: method is nil but AnalysisStore.GetMediaFileByPath was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockGetMediaFileByPath.Lock()
	mock.calls.GetMediaFileByPath = append(mock.calls.GetMediaFileByPath, callInfo)
	mock.lockGetMediaFileByPath.Unlock()
	return mock.GetMediaFileByPathFunc(ctx, path)
}

// GetMediaFileByPathCalls gets all the calls that were made to GetMediaFileByPath.
// Check the length with:
//
//	len(mockedAnalysisStore.GetMediaFileByPathCalls())
func (mock *AnalysisStoreMock) GetMediaFileByPathCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockGetMediaFileByPath.RLock()
	calls = mock.calls.GetMediaFileByPath
	mock.lockGetMediaFileByPath.RUnlock()
	return calls
}

// GetSettings calls GetSettingsFunc.
func (mock *AnalysisStoreMock) GetSettings(ctx context.Context) (domain.Settings, error) {
	if mock.GetSettingsFunc == nil {
		panic("AnalysisStoreMock.GetSettingsFunc: method is nil but AnalysisStore.GetSettings was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetSettings.Lock()
	mock.calls.GetSettings = append(mock.calls.GetSettings, callInfo)
	mock.lockGetSettings.Unlock()
	return mock.GetSettingsFunc(ctx)
}

// GetSettingsCalls gets all the calls that were made to GetSettings.
// Check the length with:
//
//	len(mockedAnalysisStore.GetSettingsCalls())
func (mock *AnalysisStoreMock) GetSettingsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetSettings.RLock()
	calls = mock.calls.GetSettings
	mock.lockGetSettings.RUnlock()
	return calls
}

// ListRoots calls ListRootsFunc.
func (mock *AnalysisStoreMock) ListRoots(ctx context.Context) ([]domain.Root, error) {
	if mock.ListRootsFunc == nil {
		panic("AnalysisStoreMock.ListRootsFunc: method is nil but AnalysisStore.ListRoots was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListRoots.Lock()
	mock.calls.ListRoots = append(mock.calls.ListRoots, callInfo)
	mock.lockListRoots.Unlock()
	return mock.ListRootsFunc(ctx)
}

// ListRootsCalls gets all the calls that were made to ListRoots.
// Check the length with:
//
//	len(mockedAnalysisStore.ListRootsCalls())
func (mock *AnalysisStoreMock) ListRootsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListRoots.RLock()
	calls = mock.calls.ListRoots
	mock.lockListRoots.RUnlock()
	return calls
}

// SetMediaStatus calls SetMediaStatusFunc.
func (mock *AnalysisStoreMock) SetMediaStatus(ctx context.Context, id int64, status domain.MediaStatus, lastError string) error {
	if mock.SetMediaStatusFunc == nil {
		panic("AnalysisStoreMock.SetMediaStatusFunc: method is nil but AnalysisStore.SetMediaStatus was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ID        int64
		Status    domain.MediaStatus
		LastError string
	}{
		Ctx:       ctx,
		ID:        id,
		Status:    status,
		LastError: lastError,
	}
	mock.lockSetMediaStatus.Lock()
	mock.calls.SetMediaStatus = append(mock.calls.SetMediaStatus, callInfo)
	mock.lockSetMediaStatus.Unlock()
	return mock.SetMediaStatusFunc(ctx, id, status, lastError)
}

// SetMediaStatusCalls gets all the calls that were made to SetMediaStatus.
// Check the length with:
//
//	len(mockedAnalysisStore.SetMediaStatusCalls())
func (mock *AnalysisStoreMock) SetMediaStatusCalls() []struct {
	Ctx       context.Context
	ID        int64
	Status    domain.MediaStatus
	LastError string
} {
	var calls []struct {
		Ctx       context.Context
		ID        int64
		Status    domain.MediaStatus
		LastError string
	}
	mock.lockSetMediaStatus.RLock()
	calls = mock.calls.SetMediaStatus
	mock.lockSetMediaStatus.RUnlock()
	return calls
}

// UpdateMediaAnalysis calls UpdateMediaAnalysisFunc.
func (mock *AnalysisStoreMock) UpdateMediaAnalysis(ctx context.Context, u store.AnalysisUpdate) error {
	if mock.UpdateMediaAnalysisFunc == nil {
		panic("AnalysisStoreMock.UpdateMediaAnalysisFunc: method is nil but AnalysisStore.UpdateMediaAnalysis was just called")
	}
	callInfo := struct {
		Ctx context.Context
		U   store.AnalysisUpdate
	}{
		Ctx: ctx,
		U:   u,
	}
	mock.lockUpdateMediaAnalysis.Lock()
	mock.calls.UpdateMediaAnalysis = append(mock.calls.UpdateMediaAnalysis, callInfo)
	mock.lockUpdateMediaAnalysis.Unlock()
	return mock.UpdateMediaAnalysisFunc(ctx, u)
}

// UpdateMediaAnalysisCalls gets all the calls that were made to UpdateMediaAnalysis.
// Check the length with:
//
//	len(mockedAnalysisStore.UpdateMediaAnalysisCalls())
func (mock *AnalysisStoreMock) UpdateMediaAnalysisCalls() []struct {
	Ctx context.Context
	U   store.AnalysisUpdate
} {
	var calls []struct {
		Ctx context.Context
		U   store.AnalysisUpdate
	}
	mock.lockUpdateMediaAnalysis.RLock()
	calls = mock.calls.UpdateMediaAnalysis
	mock.lockUpdateMediaAnalysis.RUnlock()
	return calls
}

// UpsertMediaFile calls UpsertMediaFileFunc.
func (mock *AnalysisStoreMock) UpsertMediaFile(ctx context.Context, m domain.MediaFile) (domain.MediaFile, error) {
	if mock.UpsertMediaFileFunc == nil {
		panic("AnalysisStoreMock.UpsertMediaFileFunc: method is nil but AnalysisStore.UpsertMediaFile was just called")
	}
	callInfo := struct {
		Ctx context.Context
		M   domain.MediaFile
	}{
		Ctx: ctx,
		M:   m,
	}
	mock.lockUpsertMediaFile.Lock()
	mock.calls.UpsertMediaFile = append(mock.calls.UpsertMediaFile, callInfo)
	mock.lockUpsertMediaFile.Unlock()
	return mock.UpsertMediaFileFunc(ctx, m)
}

// UpsertMediaFileCalls gets all the calls that were made to UpsertMediaFile.
// Check the length with:
//
//	len(mockedAnalysisStore.UpsertMediaFileCalls())
func (mock *AnalysisStoreMock) UpsertMediaFileCalls() []struct {
	Ctx context.Context
	M   domain.MediaFile
} {
	var calls []struct {
		Ctx context.Context
		M   domain.MediaFile
	}
	mock.lockUpsertMediaFile.RLock()
	calls = mock.calls.UpsertMediaFile
	mock.lockUpsertMediaFile.RUnlock()
	return calls
}
