// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/yama6a/codarr/internal/ingest"
	"sync"
)

// Ensure, that FileAnalyzerMock does implement ingest.FileAnalyzer.
// If this is not the case, regenerate this file with moq.
var _ ingest.FileAnalyzer = &FileAnalyzerMock{}

// FileAnalyzerMock is a mock implementation of ingest.FileAnalyzer.
//
//	func TestSomethingThatUsesFileAnalyzer(t *testing.T) {
//
//		// make and configure a mocked ingest.FileAnalyzer
//		mockedFileAnalyzer := &FileAnalyzerMock{
//			AnalyzeInFunc: func(ctx context.Context, path string, env ingest.Env) (ingest.Result, error) {
//				panic("mock out the AnalyzeIn method")
//			},
//		}
//
//		// use mockedFileAnalyzer in code that requires ingest.FileAnalyzer
//		// and then make assertions.
//
//	}
type FileAnalyzerMock struct {
	// AnalyzeInFunc mocks the AnalyzeIn method.
	AnalyzeInFunc func(ctx context.Context, path string, env ingest.Env) (ingest.Result, error)

	// calls tracks calls to the methods.
	calls struct {
		// AnalyzeIn holds details about calls to the AnalyzeIn method.
		AnalyzeIn []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Env is the env argument value.
			Env ingest.Env
		}
	}
	lockAnalyzeIn sync.RWMutex
}

// AnalyzeIn calls AnalyzeInFunc.
func (mock *FileAnalyzerMock) AnalyzeIn(ctx context.Context, path string, env ingest.Env) (ingest.Result, error) {
	if mock.AnalyzeInFunc == nil {
		panic("FileAnalyzerMock.AnalyzeInFunc: method is nil but FileAnalyzer.AnalyzeIn was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
		Env  ingest.Env
	}{
		Ctx:  ctx,
		Path: path,
		Env:  env,
	}
	mock.lockAnalyzeIn.Lock()
	mock.calls.AnalyzeIn = append(mock.calls.AnalyzeIn, callInfo)
	mock.lockAnalyzeIn.Unlock()
	return mock.AnalyzeInFunc(ctx, path, env)
}

// AnalyzeInCalls gets all the calls that were made to AnalyzeIn.
// Check the length with:
//
//	len(mockedFileAnalyzer.AnalyzeInCalls())
func (mock *FileAnalyzerMock) AnalyzeInCalls() []struct {
	Ctx  context.Context
	Path string
	Env  ingest.Env
} {
	var calls []struct {
		Ctx  context.Context
		Path string
		Env  ingest.Env
	}
	mock.lockAnalyzeIn.RLock()
	calls = mock.calls.AnalyzeIn
	mock.lockAnalyzeIn.RUnlock()
	return calls
}
