// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/yama6a/codarr/internal/ingest"
	"sync"
)

// Ensure, that FingerprinterMock does implement ingest.Fingerprinter.
// If this is not the case, regenerate this file with moq.
var _ ingest.Fingerprinter = &FingerprinterMock{}

// FingerprinterMock is a mock implementation of ingest.Fingerprinter.
//
//	func TestSomethingThatUsesFingerprinter(t *testing.T) {
//
//		// make and configure a mocked ingest.Fingerprinter
//		mockedFingerprinter := &FingerprinterMock{
//			SparseFunc: func(path string) (string, error) {
//				panic("mock out the Sparse method")
//			},
//		}
//
//		// use mockedFingerprinter in code that requires ingest.Fingerprinter
//		// and then make assertions.
//
//	}
type FingerprinterMock struct {
	// SparseFunc mocks the Sparse method.
	SparseFunc func(path string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Sparse holds details about calls to the Sparse method.
		Sparse []struct {
			// Path is the path argument value.
			Path string
		}
	}
	lockSparse sync.RWMutex
}

// Sparse calls SparseFunc.
func (mock *FingerprinterMock) Sparse(path string) (string, error) {
	if mock.SparseFunc == nil {
		panic("FingerprinterMock.SparseFunc: method is nil but Fingerprinter.Sparse was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockSparse.Lock()
	mock.calls.Sparse = append(mock.calls.Sparse, callInfo)
	mock.lockSparse.Unlock()
	return mock.SparseFunc(path)
}

// SparseCalls gets all the calls that were made to Sparse.
// Check the length with:
//
//	len(mockedFingerprinter.SparseCalls())
func (mock *FingerprinterMock) SparseCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockSparse.RLock()
	calls = mock.calls.Sparse
	mock.lockSparse.RUnlock()
	return calls
}
