// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/yama6a/codarr/internal/ingest"
	"github.com/yama6a/codarr/internal/pkg/fsx"
	"sync"
)

// Ensure, that FSMock does implement ingest.FS.
// If this is not the case, regenerate this file with moq.
var _ ingest.FS = &FSMock{}

// FSMock is a mock implementation of ingest.FS.
//
//	func TestSomethingThatUsesFS(t *testing.T) {
//
//		// make and configure a mocked ingest.FS
//		mockedFS := &FSMock{
//			StatFunc: func(path string) (fsx.FileInfo, error) {
//				panic("mock out the Stat method")
//			},
//			WalkDirFunc: func(root string, fn func(path string, info fsx.FileInfo, err error) error) error {
//				panic("mock out the WalkDir method")
//			},
//		}
//
//		// use mockedFS in code that requires ingest.FS
//		// and then make assertions.
//
//	}
type FSMock struct {
	// StatFunc mocks the Stat method.
	StatFunc func(path string) (fsx.FileInfo, error)

	// WalkDirFunc mocks the WalkDir method.
	WalkDirFunc func(root string, fn func(path string, info fsx.FileInfo, err error) error) error

	// calls tracks calls to the methods.
	calls struct {
		// Stat holds details about calls to the Stat method.
		Stat []struct {
			// Path is the path argument value.
			Path string
		}
		// WalkDir holds details about calls to the WalkDir method.
		WalkDir []struct {
			// Root is the root argument value.
			Root string
			// Fn is the fn argument value.
			Fn func(path string, info fsx.FileInfo, err error) error
		}
	}
	lockStat    sync.RWMutex
	lockWalkDir sync.RWMutex
}

// Stat calls StatFunc.
func (mock *FSMock) Stat(path string) (fsx.FileInfo, error) {
	if mock.StatFunc == nil {
		panic("FSMock.StatFunc: method is nil but FS.Stat was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockStat.Lock()
	mock.calls.Stat = append(mock.calls.Stat, callInfo)
	mock.lockStat.Unlock()
	return mock.StatFunc(path)
}

// StatCalls gets all the calls that were made to Stat.
// Check the length with:
//
//	len(mockedFS.StatCalls())
func (mock *FSMock) StatCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockStat.RLock()
	calls = mock.calls.Stat
	mock.lockStat.RUnlock()
	return calls
}

// WalkDir calls WalkDirFunc.
func (mock *FSMock) WalkDir(root string, fn func(path string, info fsx.FileInfo, err error) error) error {
	if mock.WalkDirFunc == nil {
		panic("FSMock.WalkDirFunc: method is nil but FS.WalkDir was just called")
	}
	callInfo := struct {
		Root string
		Fn   func(path string, info fsx.FileInfo, err error) error
	}{
		Root: root,
		Fn:   fn,
	}
	mock.lockWalkDir.Lock()
	mock.calls.WalkDir = append(mock.calls.WalkDir, callInfo)
	mock.lockWalkDir.Unlock()
	return mock.WalkDirFunc(root, fn)
}

// WalkDirCalls gets all the calls that were made to WalkDir.
// Check the length with:
//
//	len(mockedFS.WalkDirCalls())
func (mock *FSMock) WalkDirCalls() []struct {
	Root string
	Fn   func(path string, info fsx.FileInfo, err error) error
} {
	var calls []struct {
		Root string
		Fn   func(path string, info fsx.FileInfo, err error) error
	}
	mock.lockWalkDir.RLock()
	calls = mock.calls.WalkDir
	mock.lockWalkDir.RUnlock()
	return calls
}
