// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/yama6a/codarr/internal/ingest"
	"github.com/yama6a/codarr/internal/pkg/domain"
	"github.com/yama6a/codarr/internal/pkg/store"
	"sync"
)

// Ensure, that ScanStoreMock does implement ingest.ScanStore.
// If this is not the case, regenerate this file with moq.
var _ ingest.ScanStore = &ScanStoreMock{}

// ScanStoreMock is a mock implementation of ingest.ScanStore.
//
//	func TestSomethingThatUsesScanStore(t *testing.T) {
//
//		// make and configure a mocked ingest.ScanStore
//		mockedScanStore := &ScanStoreMock{
//			GetRootFunc: func(ctx context.Context, id int64) (domain.Root, error) {
//				panic("mock out the GetRoot method")
//			},
//			GetSettingsFunc: func(ctx context.Context) (domain.Settings, error) {
//				panic("mock out the GetSettings method")
//			},
//			ListMediaStatsByRootFunc: func(ctx context.Context, rootID int64) ([]store.MediaStat, error) {
//				panic("mock out the ListMediaStatsByRoot method")
//			},
//			ListRootsFunc: func(ctx context.Context) ([]domain.Root, error) {
//				panic("mock out the ListRoots method")
//			},
//			MarkMediaMissingFunc: func(ctx context.Context, ids []int64) (int64, error) {
//				panic("mock out the MarkMediaMissing method")
//			},
//		}
//
//		// use mockedScanStore in code that requires ingest.ScanStore
//		// and then make assertions.
//
//	}
type ScanStoreMock struct {
	// GetRootFunc mocks the GetRoot method.
	GetRootFunc func(ctx context.Context, id int64) (domain.Root, error)

	// GetSettingsFunc mocks the GetSettings method.
	GetSettingsFunc func(ctx context.Context) (domain.Settings, error)

	// ListMediaStatsByRootFunc mocks the ListMediaStatsByRoot method.
	ListMediaStatsByRootFunc func(ctx context.Context, rootID int64) ([]store.MediaStat, error)

	// ListRootsFunc mocks the ListRoots method.
	ListRootsFunc func(ctx context.Context) ([]domain.Root, error)

	// MarkMediaMissingFunc mocks the MarkMediaMissing method.
	MarkMediaMissingFunc func(ctx context.Context, ids []int64) (int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetRoot holds details about calls to the GetRoot method.
		GetRoot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetSettings holds details about calls to the GetSettings method.
		GetSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListMediaStatsByRoot holds details about calls to the ListMediaStatsByRoot method.
		ListMediaStatsByRoot []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RootID is the rootID argument value.
			RootID int64
		}
		// ListRoots holds details about calls to the ListRoots method.
		ListRoots []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// MarkMediaMissing holds details about calls to the MarkMediaMissing method.
		MarkMediaMissing []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ids is the ids argument value.
			Ids []int64
		}
	}
	lockGetRoot              sync.RWMutex
	lockGetSettings          sync.RWMutex
	lockListMediaStatsByRoot sync.RWMutex
	lockListRoots            sync.RWMutex
	lockMarkMediaMissing     sync.RWMutex
}

// GetRoot calls GetRootFunc.
func (mock *ScanStoreMock) GetRoot(ctx context.Context, id int64) (domain.Root, error) {
	if mock.GetRootFunc == nil {
		panic("ScanStoreMock.GetRootFunc: method is nil but ScanStore.GetRoot was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetRoot.Lock()
	mock.calls.GetRoot = append(mock.calls.GetRoot, callInfo)
	mock.lockGetRoot.Unlock()
	return mock.GetRootFunc(ctx, id)
}

// GetRootCalls gets all the calls that were made to GetRoot.
// Check the length with:
//
//	len(mockedScanStore.GetRootCalls())
func (mock *ScanStoreMock) GetRootCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetRoot.RLock()
	calls = mock.calls.GetRoot
	mock.lockGetRoot.RUnlock()
	return calls
}

// GetSettings calls GetSettingsFunc.
func (mock *ScanStoreMock) GetSettings(ctx context.Context) (domain.Settings, error) {
	if mock.GetSettingsFunc == nil {
		panic("ScanStoreMock.GetSettingsFunc: method is nil but ScanStore.GetSettings was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetSettings.Lock()
	mock.calls.GetSettings = append(mock.calls.GetSettings, callInfo)
	mock.lockGetSettings.Unlock()
	return mock.GetSettingsFunc(ctx)
}

// GetSettingsCalls gets all the calls that were made to GetSettings.
// Check the length with:
//
//	len(mockedScanStore.GetSettingsCalls())
func (mock *ScanStoreMock) GetSettingsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetSettings.RLock()
	calls = mock.calls.GetSettings
	mock.lockGetSettings.RUnlock()
	return calls
}

// ListMediaStatsByRoot calls ListMediaStatsByRootFunc.
func (mock *ScanStoreMock) ListMediaStatsByRoot(ctx context.Context, rootID int64) ([]store.MediaStat, error) {
	if mock.ListMediaStatsByRootFunc == nil {
		panic("ScanStoreMock.ListMediaStatsByRootFunc: method is nil but ScanStore.ListMediaStatsByRoot was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RootID int64
	}{
		Ctx:    ctx,
		RootID: rootID,
	}
	mock.lockListMediaStatsByRoot.Lock()
	mock.calls.ListMediaStatsByRoot = append(mock.calls.ListMediaStatsByRoot, callInfo)
	mock.lockListMediaStatsByRoot.Unlock()
	return mock.ListMediaStatsByRootFunc(ctx, rootID)
}

// ListMediaStatsByRootCalls gets all the calls that were made to ListMediaStatsByRoot.
// Check the length with:
//
//	len(mockedScanStore.ListMediaStatsByRootCalls())
func (mock *ScanStoreMock) ListMediaStatsByRootCalls() []struct {
	Ctx    context.Context
	RootID int64
} {
	var calls []struct {
		Ctx    context.Context
		RootID int64
	}
	mock.lockListMediaStatsByRoot.RLock()
	calls = mock.calls.ListMediaStatsByRoot
	mock.lockListMediaStatsByRoot.RUnlock()
	return calls
}

// ListRoots calls ListRootsFunc.
func (mock *ScanStoreMock) ListRoots(ctx context.Context) ([]domain.Root, error) {
	if mock.ListRootsFunc == nil {
		panic("ScanStoreMock.ListRootsFunc: method is nil but ScanStore.ListRoots was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListRoots.Lock()
	mock.calls.ListRoots = append(mock.calls.ListRoots, callInfo)
	mock.lockListRoots.Unlock()
	return mock.ListRootsFunc(ctx)
}

// ListRootsCalls gets all the calls that were made to ListRoots.
// Check the length with:
//
//	len(mockedScanStore.ListRootsCalls())
func (mock *ScanStoreMock) ListRootsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListRoots.RLock()
	calls = mock.calls.ListRoots
	mock.lockListRoots.RUnlock()
	return calls
}

// MarkMediaMissing calls MarkMediaMissingFunc.
func (mock *ScanStoreMock) MarkMediaMissing(ctx context.Context, ids []int64) (int64, error) {
	if mock.MarkMediaMissingFunc == nil {
		panic("ScanStoreMock.MarkMediaMissingFunc: method is nil but ScanStore.MarkMediaMissing was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ids []int64
	}{
		Ctx: ctx,
		Ids: ids,
	}
	mock.lockMarkMediaMissing.Lock()
	mock.calls.MarkMediaMissing = append(mock.calls.MarkMediaMissing, callInfo)
	mock.lockMarkMediaMissing.Unlock()
	return mock.MarkMediaMissingFunc(ctx, ids)
}

// MarkMediaMissingCalls gets all the calls that were made to MarkMediaMissing.
// Check the length with:
//
//	len(mockedScanStore.MarkMediaMissingCalls())
func (mock *ScanStoreMock) MarkMediaMissingCalls() []struct {
	Ctx context.Context
	Ids []int64
} {
	var calls []struct {
		Ctx context.Context
		Ids []int64
	}
	mock.lockMarkMediaMissing.RLock()
	calls = mock.calls.MarkMediaMissing
	mock.lockMarkMediaMissing.RUnlock()
	return calls
}
