// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/yama6a/codarr/internal/ingest"
	"github.com/yama6a/codarr/internal/pkg/domain"
	"sync"
)

// Ensure, that WebhookStoreMock does implement ingest.WebhookStore.
// If this is not the case, regenerate this file with moq.
var _ ingest.WebhookStore = &WebhookStoreMock{}

// WebhookStoreMock is a mock implementation of ingest.WebhookStore.
//
//	func TestSomethingThatUsesWebhookStore(t *testing.T) {
//
//		// make and configure a mocked ingest.WebhookStore
//		mockedWebhookStore := &WebhookStoreMock{
//			GetArrInstanceByWebhookIDFunc: func(ctx context.Context, webhookID string) (domain.ArrInstance, error) {
//				panic("mock out the GetArrInstanceByWebhookID method")
//			},
//			GetMediaFileByPathFunc: func(ctx context.Context, path string) (domain.MediaFile, error) {
//				panic("mock out the GetMediaFileByPath method")
//			},
//			GetSettingsFunc: func(ctx context.Context) (domain.Settings, error) {
//				panic("mock out the GetSettings method")
//			},
//			ListArrPathMappingsFunc: func(ctx context.Context, arrInstanceID int64) ([]domain.PathMapping, error) {
//				panic("mock out the ListArrPathMappings method")
//			},
//			ListRootsFunc: func(ctx context.Context) ([]domain.Root, error) {
//				panic("mock out the ListRoots method")
//			},
//			MarkMediaMissingFunc: func(ctx context.Context, ids []int64) (int64, error) {
//				panic("mock out the MarkMediaMissing method")
//			},
//		}
//
//		// use mockedWebhookStore in code that requires ingest.WebhookStore
//		// and then make assertions.
//
//	}
type WebhookStoreMock struct {
	// GetArrInstanceByWebhookIDFunc mocks the GetArrInstanceByWebhookID method.
	GetArrInstanceByWebhookIDFunc func(ctx context.Context, webhookID string) (domain.ArrInstance, error)

	// GetMediaFileByPathFunc mocks the GetMediaFileByPath method.
	GetMediaFileByPathFunc func(ctx context.Context, path string) (domain.MediaFile, error)

	// GetSettingsFunc mocks the GetSettings method.
	GetSettingsFunc func(ctx context.Context) (domain.Settings, error)

	// ListArrPathMappingsFunc mocks the ListArrPathMappings method.
	ListArrPathMappingsFunc func(ctx context.Context, arrInstanceID int64) ([]domain.PathMapping, error)

	// ListRootsFunc mocks the ListRoots method.
	ListRootsFunc func(ctx context.Context) ([]domain.Root, error)

	// MarkMediaMissingFunc mocks the MarkMediaMissing method.
	MarkMediaMissingFunc func(ctx context.Context, ids []int64) (int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetArrInstanceByWebhookID holds details about calls to the GetArrInstanceByWebhookID method.
		GetArrInstanceByWebhookID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WebhookID is the webhookID argument value.
			WebhookID string
		}
		// GetMediaFileByPath holds details about calls to the GetMediaFileByPath method.
		GetMediaFileByPath []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
		// GetSettings holds details about calls to the GetSettings method.
		GetSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListArrPathMappings holds details about calls to the ListArrPathMappings method.
		ListArrPathMappings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ArrInstanceID is the arrInstanceID argument value.
			ArrInstanceID int64
		}
		// ListRoots holds details about calls to the ListRoots method.
		ListRoots []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// MarkMediaMissing holds details about calls to the MarkMediaMissing method.
		MarkMediaMissing []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ids is the ids argument value.
			Ids []int64
		}
	}
	lockGetArrInstanceByWebhookID sync.RWMutex
	lockGetMediaFileByPath        sync.RWMutex
	lockGetSettings               sync.RWMutex
	lockListArrPathMappings       sync.RWMutex
	lockListRoots                 sync.RWMutex
	lockMarkMediaMissing          sync.RWMutex
}

// GetArrInstanceByWebhookID calls GetArrInstanceByWebhookIDFunc.
func (mock *WebhookStoreMock) GetArrInstanceByWebhookID(ctx context.Context, webhookID string) (domain.ArrInstance, error) {
	if mock.GetArrInstanceByWebhookIDFunc == nil {
		panic("WebhookStoreMock.GetArrInstanceByWebhookIDFunc: method is nil but WebhookStore.GetArrInstanceByWebhookID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		WebhookID string
	}{
		Ctx:       ctx,
		WebhookID: webhookID,
	}
	mock.lockGetArrInstanceByWebhookID.Lock()
	mock.calls.GetArrInstanceByWebhookID = append(mock.calls.GetArrInstanceByWebhookID, callInfo)
	mock.lockGetArrInstanceByWebhookID.Unlock()
	return mock.GetArrInstanceByWebhookIDFunc(ctx, webhookID)
}

// GetArrInstanceByWebhookIDCalls gets all the calls that were made to GetArrInstanceByWebhookID.
// Check the length with:
//
//	len(mockedWebhookStore.GetArrInstanceByWebhookIDCalls())
func (mock *WebhookStoreMock) GetArrInstanceByWebhookIDCalls() []struct {
	Ctx       context.Context
	WebhookID string
} {
	var calls []struct {
		Ctx       context.Context
		WebhookID string
	}
	mock.lockGetArrInstanceByWebhookID.RLock()
	calls = mock.calls.GetArrInstanceByWebhookID
	mock.lockGetArrInstanceByWebhookID.RUnlock()
	return calls
}

// GetMediaFileByPath calls GetMediaFileByPathFunc.
func (mock *WebhookStoreMock) GetMediaFileByPath(ctx context.Context, path string) (domain.MediaFile, error) {
	if mock.GetMediaFileByPathFunc == nil {
		panic("WebhookStoreMock.GetMediaFileByPathFunc: method is nil but WebhookStore.GetMediaFileByPath was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockGetMediaFileByPath.Lock()
	mock.calls.GetMediaFileByPath = append(mock.calls.GetMediaFileByPath, callInfo)
	mock.lockGetMediaFileByPath.Unlock()
	return mock.GetMediaFileByPathFunc(ctx, path)
}

// GetMediaFileByPathCalls gets all the calls that were made to GetMediaFileByPath.
// Check the length with:
//
//	len(mockedWebhookStore.GetMediaFileByPathCalls())
func (mock *WebhookStoreMock) GetMediaFileByPathCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockGetMediaFileByPath.RLock()
	calls = mock.calls.GetMediaFileByPath
	mock.lockGetMediaFileByPath.RUnlock()
	return calls
}

// GetSettings calls GetSettingsFunc.
func (mock *WebhookStoreMock) GetSettings(ctx context.Context) (domain.Settings, error) {
	if mock.GetSettingsFunc == nil {
		panic("WebhookStoreMock.GetSettingsFunc: method is nil but WebhookStore.GetSettings was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetSettings.Lock()
	mock.calls.GetSettings = append(mock.calls.GetSettings, callInfo)
	mock.lockGetSettings.Unlock()
	return mock.GetSettingsFunc(ctx)
}

// GetSettingsCalls gets all the calls that were made to GetSettings.
// Check the length with:
//
//	len(mockedWebhookStore.GetSettingsCalls())
func (mock *WebhookStoreMock) GetSettingsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetSettings.RLock()
	calls = mock.calls.GetSettings
	mock.lockGetSettings.RUnlock()
	return calls
}

// ListArrPathMappings calls ListArrPathMappingsFunc.
func (mock *WebhookStoreMock) ListArrPathMappings(ctx context.Context, arrInstanceID int64) ([]domain.PathMapping, error) {
	if mock.ListArrPathMappingsFunc == nil {
		panic("WebhookStoreMock.ListArrPathMappingsFunc: method is nil but WebhookStore.ListArrPathMappings was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ArrInstanceID int64
	}{
		Ctx:           ctx,
		ArrInstanceID: arrInstanceID,
	}
	mock.lockListArrPathMappings.Lock()
	mock.calls.ListArrPathMappings = append(mock.calls.ListArrPathMappings, callInfo)
	mock.lockListArrPathMappings.Unlock()
	return mock.ListArrPathMappingsFunc(ctx, arrInstanceID)
}

// ListArrPathMappingsCalls gets all the calls that were made to ListArrPathMappings.
// Check the length with:
//
//	len(mockedWebhookStore.ListArrPathMappingsCalls())
func (mock *WebhookStoreMock) ListArrPathMappingsCalls() []struct {
	Ctx           context.Context
	ArrInstanceID int64
} {
	var calls []struct {
		Ctx           context.Context
		ArrInstanceID int64
	}
	mock.lockListArrPathMappings.RLock()
	calls = mock.calls.ListArrPathMappings
	mock.lockListArrPathMappings.RUnlock()
	return calls
}

// ListRoots calls ListRootsFunc.
func (mock *WebhookStoreMock) ListRoots(ctx context.Context) ([]domain.Root, error) {
	if mock.ListRootsFunc == nil {
		panic("WebhookStoreMock.ListRootsFunc: method is nil but WebhookStore.ListRoots was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListRoots.Lock()
	mock.calls.ListRoots = append(mock.calls.ListRoots, callInfo)
	mock.lockListRoots.Unlock()
	return mock.ListRootsFunc(ctx)
}

// ListRootsCalls gets all the calls that were made to ListRoots.
// Check the length with:
//
//	len(mockedWebhookStore.ListRootsCalls())
func (mock *WebhookStoreMock) ListRootsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListRoots.RLock()
	calls = mock.calls.ListRoots
	mock.lockListRoots.RUnlock()
	return calls
}

// MarkMediaMissing calls MarkMediaMissingFunc.
func (mock *WebhookStoreMock) MarkMediaMissing(ctx context.Context, ids []int64) (int64, error) {
	if mock.MarkMediaMissingFunc == nil {
		panic("WebhookStoreMock.MarkMediaMissingFunc: method is nil but WebhookStore.MarkMediaMissing was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ids []int64
	}{
		Ctx: ctx,
		Ids: ids,
	}
	mock.lockMarkMediaMissing.Lock()
	mock.calls.MarkMediaMissing = append(mock.calls.MarkMediaMissing, callInfo)
	mock.lockMarkMediaMissing.Unlock()
	return mock.MarkMediaMissingFunc(ctx, ids)
}

// MarkMediaMissingCalls gets all the calls that were made to MarkMediaMissing.
// Check the length with:
//
//	len(mockedWebhookStore.MarkMediaMissingCalls())
func (mock *WebhookStoreMock) MarkMediaMissingCalls() []struct {
	Ctx context.Context
	Ids []int64
} {
	var calls []struct {
		Ctx context.Context
		Ids []int64
	}
	mock.lockMarkMediaMissing.RLock()
	calls = mock.calls.MarkMediaMissing
	mock.lockMarkMediaMissing.RUnlock()
	return calls
}
