// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/yama6a/codarr/internal/arr"
	"sync"
)

// Ensure, that ClientMock does implement arr.Client.
// If this is not the case, regenerate this file with moq.
var _ arr.Client = &ClientMock{}

// ClientMock is a mock implementation of arr.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked arr.Client
//		mockedClient := &ClientMock{
//			IdentityFunc: func() arr.Identity {
//				panic("mock out the Identity method")
//			},
//			RescanFunc: func(ctx context.Context, item arr.ItemRef) error {
//				panic("mock out the Rescan method")
//			},
//			RootFoldersFunc: func(ctx context.Context) ([]arr.RootFolder, error) {
//				panic("mock out the RootFolders method")
//			},
//			TestFunc: func(ctx context.Context) arr.TestResult {
//				panic("mock out the Test method")
//			},
//			UnmonitorFunc: func(ctx context.Context, item arr.ItemRef) error {
//				panic("mock out the Unmonitor method")
//			},
//		}
//
//		// use mockedClient in code that requires arr.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// IdentityFunc mocks the Identity method.
	IdentityFunc func() arr.Identity

	// RescanFunc mocks the Rescan method.
	RescanFunc func(ctx context.Context, item arr.ItemRef) error

	// RootFoldersFunc mocks the RootFolders method.
	RootFoldersFunc func(ctx context.Context) ([]arr.RootFolder, error)

	// TestFunc mocks the Test method.
	TestFunc func(ctx context.Context) arr.TestResult

	// UnmonitorFunc mocks the Unmonitor method.
	UnmonitorFunc func(ctx context.Context, item arr.ItemRef) error

	// calls tracks calls to the methods.
	calls struct {
		// Identity holds details about calls to the Identity method.
		Identity []struct {
		}
		// Rescan holds details about calls to the Rescan method.
		Rescan []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Item is the item argument value.
			Item arr.ItemRef
		}
		// RootFolders holds details about calls to the RootFolders method.
		RootFolders []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Test holds details about calls to the Test method.
		Test []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Unmonitor holds details about calls to the Unmonitor method.
		Unmonitor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Item is the item argument value.
			Item arr.ItemRef
		}
	}
	lockIdentity    sync.RWMutex
	lockRescan      sync.RWMutex
	lockRootFolders sync.RWMutex
	lockTest        sync.RWMutex
	lockUnmonitor   sync.RWMutex
}

// Identity calls IdentityFunc.
func (mock *ClientMock) Identity() arr.Identity {
	if mock.IdentityFunc == nil {
		panic("ClientMock.IdentityFunc: method is nil but Client.Identity was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIdentity.Lock()
	mock.calls.Identity = append(mock.calls.Identity, callInfo)
	mock.lockIdentity.Unlock()
	return mock.IdentityFunc()
}

// IdentityCalls gets all the calls that were made to Identity.
// Check the length with:
//
//	len(mockedClient.IdentityCalls())
func (mock *ClientMock) IdentityCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIdentity.RLock()
	calls = mock.calls.Identity
	mock.lockIdentity.RUnlock()
	return calls
}

// Rescan calls RescanFunc.
func (mock *ClientMock) Rescan(ctx context.Context, item arr.ItemRef) error {
	if mock.RescanFunc == nil {
		panic("ClientMock.RescanFunc: method is nil but Client.Rescan was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Item arr.ItemRef
	}{
		Ctx:  ctx,
		Item: item,
	}
	mock.lockRescan.Lock()
	mock.calls.Rescan = append(mock.calls.Rescan, callInfo)
	mock.lockRescan.Unlock()
	return mock.RescanFunc(ctx, item)
}

// RescanCalls gets all the calls that were made to Rescan.
// Check the length with:
//
//	len(mockedClient.RescanCalls())
func (mock *ClientMock) RescanCalls() []struct {
	Ctx  context.Context
	Item arr.ItemRef
} {
	var calls []struct {
		Ctx  context.Context
		Item arr.ItemRef
	}
	mock.lockRescan.RLock()
	calls = mock.calls.Rescan
	mock.lockRescan.RUnlock()
	return calls
}

// RootFolders calls RootFoldersFunc.
func (mock *ClientMock) RootFolders(ctx context.Context) ([]arr.RootFolder, error) {
	if mock.RootFoldersFunc == nil {
		panic("ClientMock.RootFoldersFunc: method is nil but Client.RootFolders was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRootFolders.Lock()
	mock.calls.RootFolders = append(mock.calls.RootFolders, callInfo)
	mock.lockRootFolders.Unlock()
	return mock.RootFoldersFunc(ctx)
}

// RootFoldersCalls gets all the calls that were made to RootFolders.
// Check the length with:
//
//	len(mockedClient.RootFoldersCalls())
func (mock *ClientMock) RootFoldersCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRootFolders.RLock()
	calls = mock.calls.RootFolders
	mock.lockRootFolders.RUnlock()
	return calls
}

// Test calls TestFunc.
func (mock *ClientMock) Test(ctx context.Context) arr.TestResult {
	if mock.TestFunc == nil {
		panic("ClientMock.TestFunc: method is nil but Client.Test was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockTest.Lock()
	mock.calls.Test = append(mock.calls.Test, callInfo)
	mock.lockTest.Unlock()
	return mock.TestFunc(ctx)
}

// TestCalls gets all the calls that were made to Test.
// Check the length with:
//
//	len(mockedClient.TestCalls())
func (mock *ClientMock) TestCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockTest.RLock()
	calls = mock.calls.Test
	mock.lockTest.RUnlock()
	return calls
}

// Unmonitor calls UnmonitorFunc.
func (mock *ClientMock) Unmonitor(ctx context.Context, item arr.ItemRef) error {
	if mock.UnmonitorFunc == nil {
		panic("ClientMock.UnmonitorFunc: method is nil but Client.Unmonitor was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Item arr.ItemRef
	}{
		Ctx:  ctx,
		Item: item,
	}
	mock.lockUnmonitor.Lock()
	mock.calls.Unmonitor = append(mock.calls.Unmonitor, callInfo)
	mock.lockUnmonitor.Unlock()
	return mock.UnmonitorFunc(ctx, item)
}

// UnmonitorCalls gets all the calls that were made to Unmonitor.
// Check the length with:
//
//	len(mockedClient.UnmonitorCalls())
func (mock *ClientMock) UnmonitorCalls() []struct {
	Ctx  context.Context
	Item arr.ItemRef
} {
	var calls []struct {
		Ctx  context.Context
		Item arr.ItemRef
	}
	mock.lockUnmonitor.RLock()
	calls = mock.calls.Unmonitor
	mock.lockUnmonitor.RUnlock()
	return calls
}

// Ensure, that MediaServerMock does implement arr.MediaServer.
// If this is not the case, regenerate this file with moq.
var _ arr.MediaServer = &MediaServerMock{}

// MediaServerMock is a mock implementation of arr.MediaServer.
//
//	func TestSomethingThatUsesMediaServer(t *testing.T) {
//
//		// make and configure a mocked arr.MediaServer
//		mockedMediaServer := &MediaServerMock{
//			NotifyPromotedFunc: func(ctx context.Context, path string) error {
//				panic("mock out the NotifyPromoted method")
//			},
//		}
//
//		// use mockedMediaServer in code that requires arr.MediaServer
//		// and then make assertions.
//
//	}
type MediaServerMock struct {
	// NotifyPromotedFunc mocks the NotifyPromoted method.
	NotifyPromotedFunc func(ctx context.Context, path string) error

	// calls tracks calls to the methods.
	calls struct {
		// NotifyPromoted holds details about calls to the NotifyPromoted method.
		NotifyPromoted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
	}
	lockNotifyPromoted sync.RWMutex
}

// NotifyPromoted calls NotifyPromotedFunc.
func (mock *MediaServerMock) NotifyPromoted(ctx context.Context, path string) error {
	if mock.NotifyPromotedFunc == nil {
		panic("MediaServerMock.NotifyPromotedFunc: method is nil but MediaServer.NotifyPromoted was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockNotifyPromoted.Lock()
	mock.calls.NotifyPromoted = append(mock.calls.NotifyPromoted, callInfo)
	mock.lockNotifyPromoted.Unlock()
	return mock.NotifyPromotedFunc(ctx, path)
}

// NotifyPromotedCalls gets all the calls that were made to NotifyPromoted.
// Check the length with:
//
//	len(mockedMediaServer.NotifyPromotedCalls())
func (mock *MediaServerMock) NotifyPromotedCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockNotifyPromoted.RLock()
	calls = mock.calls.NotifyPromoted
	mock.lockNotifyPromoted.RUnlock()
	return calls
}

// Ensure, that OwnerResolverMock does implement arr.OwnerResolver.
// If this is not the case, regenerate this file with moq.
var _ arr.OwnerResolver = &OwnerResolverMock{}

// OwnerResolverMock is a mock implementation of arr.OwnerResolver.
//
//	func TestSomethingThatUsesOwnerResolver(t *testing.T) {
//
//		// make and configure a mocked arr.OwnerResolver
//		mockedOwnerResolver := &OwnerResolverMock{
//			ResolveOwnerFunc: func(ctx context.Context, path string) (arr.Owner, bool, error) {
//				panic("mock out the ResolveOwner method")
//			},
//		}
//
//		// use mockedOwnerResolver in code that requires arr.OwnerResolver
//		// and then make assertions.
//
//	}
type OwnerResolverMock struct {
	// ResolveOwnerFunc mocks the ResolveOwner method.
	ResolveOwnerFunc func(ctx context.Context, path string) (arr.Owner, bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// ResolveOwner holds details about calls to the ResolveOwner method.
		ResolveOwner []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
	}
	lockResolveOwner sync.RWMutex
}

// ResolveOwner calls ResolveOwnerFunc.
func (mock *OwnerResolverMock) ResolveOwner(ctx context.Context, path string) (arr.Owner, bool, error) {
	if mock.ResolveOwnerFunc == nil {
		panic("OwnerResolverMock.ResolveOwnerFunc: method is nil but OwnerResolver.ResolveOwner was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockResolveOwner.Lock()
	mock.calls.ResolveOwner = append(mock.calls.ResolveOwner, callInfo)
	mock.lockResolveOwner.Unlock()
	return mock.ResolveOwnerFunc(ctx, path)
}

// ResolveOwnerCalls gets all the calls that were made to ResolveOwner.
// Check the length with:
//
//	len(mockedOwnerResolver.ResolveOwnerCalls())
func (mock *OwnerResolverMock) ResolveOwnerCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockResolveOwner.RLock()
	calls = mock.calls.ResolveOwner
	mock.lockResolveOwner.RUnlock()
	return calls
}
