// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/yama6a/codarr/internal/hardware"
	"sync"
)

// Ensure, that FSMock does implement hardware.FS.
// If this is not the case, regenerate this file with moq.
var _ hardware.FS = &FSMock{}

// FSMock is a mock implementation of hardware.FS.
//
//	func TestSomethingThatUsesFS(t *testing.T) {
//
//		// make and configure a mocked hardware.FS
//		mockedFS := &FSMock{
//			RemoveFunc: func(path string) error {
//				panic("mock out the Remove method")
//			},
//		}
//
//		// use mockedFS in code that requires hardware.FS
//		// and then make assertions.
//
//	}
type FSMock struct {
	// RemoveFunc mocks the Remove method.
	RemoveFunc func(path string) error

	// calls tracks calls to the methods.
	calls struct {
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Path is the path argument value.
			Path string
		}
	}
	lockRemove sync.RWMutex
}

// Remove calls RemoveFunc.
func (mock *FSMock) Remove(path string) error {
	if mock.RemoveFunc == nil {
		panic("FSMock.RemoveFunc: method is nil but FS.Remove was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(path)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedFS.RemoveCalls())
func (mock *FSMock) RemoveCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}
