// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/yama6a/codarr/internal/hardware"
	"sync"
)

// Ensure, that RunnerMock does implement hardware.Runner.
// If this is not the case, regenerate this file with moq.
var _ hardware.Runner = &RunnerMock{}

// RunnerMock is a mock implementation of hardware.Runner.
//
//	func TestSomethingThatUsesRunner(t *testing.T) {
//
//		// make and configure a mocked hardware.Runner
//		mockedRunner := &RunnerMock{
//			RunFunc: func(ctx context.Context, args []string) (string, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedRunner in code that requires hardware.Runner
//		// and then make assertions.
//
//	}
type RunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, args []string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args []string
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *RunnerMock) Run(ctx context.Context, args []string) (string, error) {
	if mock.RunFunc == nil {
		panic("RunnerMock.RunFunc: method is nil but Runner.Run was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Args []string
	}{
		Ctx:  ctx,
		Args: args,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, args)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedRunner.RunCalls())
func (mock *RunnerMock) RunCalls() []struct {
	Ctx  context.Context
	Args []string
} {
	var calls []struct {
		Ctx  context.Context
		Args []string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
