// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/yama6a/codarr/internal/hardware"
	"github.com/yama6a/codarr/internal/pkg/domain"
	"sync"
)

// Ensure, that StoreMock does implement hardware.Store.
// If this is not the case, regenerate this file with moq.
var _ hardware.Store = &StoreMock{}

// StoreMock is a mock implementation of hardware.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked hardware.Store
//		mockedStore := &StoreMock{
//			ListHWCapabilitiesFunc: func(ctx context.Context) ([]domain.HWCapability, error) {
//				panic("mock out the ListHWCapabilities method")
//			},
//			ReplaceHWCapabilitiesFunc: func(ctx context.Context, caps []domain.HWCapability) error {
//				panic("mock out the ReplaceHWCapabilities method")
//			},
//		}
//
//		// use mockedStore in code that requires hardware.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// ListHWCapabilitiesFunc mocks the ListHWCapabilities method.
	ListHWCapabilitiesFunc func(ctx context.Context) ([]domain.HWCapability, error)

	// ReplaceHWCapabilitiesFunc mocks the ReplaceHWCapabilities method.
	ReplaceHWCapabilitiesFunc func(ctx context.Context, caps []domain.HWCapability) error

	// calls tracks calls to the methods.
	calls struct {
		// ListHWCapabilities holds details about calls to the ListHWCapabilities method.
		ListHWCapabilities []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ReplaceHWCapabilities holds details about calls to the ReplaceHWCapabilities method.
		ReplaceHWCapabilities []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Caps is the caps argument value.
			Caps []domain.HWCapability
		}
	}
	lockListHWCapabilities    sync.RWMutex
	lockReplaceHWCapabilities sync.RWMutex
}

// ListHWCapabilities calls ListHWCapabilitiesFunc.
func (mock *StoreMock) ListHWCapabilities(ctx context.Context) ([]domain.HWCapability, error) {
	if mock.ListHWCapabilitiesFunc == nil {
		panic("StoreMock.ListHWCapabilitiesFunc: method is nil but Store.ListHWCapabilities was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListHWCapabilities.Lock()
	mock.calls.ListHWCapabilities = append(mock.calls.ListHWCapabilities, callInfo)
	mock.lockListHWCapabilities.Unlock()
	return mock.ListHWCapabilitiesFunc(ctx)
}

// ListHWCapabilitiesCalls gets all the calls that were made to ListHWCapabilities.
// Check the length with:
//
//	len(mockedStore.ListHWCapabilitiesCalls())
func (mock *StoreMock) ListHWCapabilitiesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListHWCapabilities.RLock()
	calls = mock.calls.ListHWCapabilities
	mock.lockListHWCapabilities.RUnlock()
	return calls
}

// ReplaceHWCapabilities calls ReplaceHWCapabilitiesFunc.
func (mock *StoreMock) ReplaceHWCapabilities(ctx context.Context, caps []domain.HWCapability) error {
	if mock.ReplaceHWCapabilitiesFunc == nil {
		panic("StoreMock.ReplaceHWCapabilitiesFunc: method is nil but Store.ReplaceHWCapabilities was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Caps []domain.HWCapability
	}{
		Ctx:  ctx,
		Caps: caps,
	}
	mock.lockReplaceHWCapabilities.Lock()
	mock.calls.ReplaceHWCapabilities = append(mock.calls.ReplaceHWCapabilities, callInfo)
	mock.lockReplaceHWCapabilities.Unlock()
	return mock.ReplaceHWCapabilitiesFunc(ctx, caps)
}

// ReplaceHWCapabilitiesCalls gets all the calls that were made to ReplaceHWCapabilities.
// Check the length with:
//
//	len(mockedStore.ReplaceHWCapabilitiesCalls())
func (mock *StoreMock) ReplaceHWCapabilitiesCalls() []struct {
	Ctx  context.Context
	Caps []domain.HWCapability
} {
	var calls []struct {
		Ctx  context.Context
		Caps []domain.HWCapability
	}
	mock.lockReplaceHWCapabilities.RLock()
	calls = mock.calls.ReplaceHWCapabilities
	mock.lockReplaceHWCapabilities.RUnlock()
	return calls
}
