// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for BitrateSource.
const (
	BitrateSourceBpsTag     BitrateSource = "bps_tag"
	BitrateSourceComputed   BitrateSource = "computed"
	BitrateSourceFormat     BitrateSource = "format"
	BitrateSourceStream     BitrateSource = "stream"
	BitrateSourceUnresolved BitrateSource = "unresolved"
)

// Valid indicates whether the value is a known member of the BitrateSource enum.
func (e BitrateSource) Valid() bool {
	switch e {
	case BitrateSourceBpsTag:
		return true
	case BitrateSourceComputed:
		return true
	case BitrateSourceFormat:
		return true
	case BitrateSourceStream:
		return true
	case BitrateSourceUnresolved:
		return true
	default:
		return false
	}
}

// Defines values for ContainerFamily.
const (
	ContainerFamilyMatroska ContainerFamily = "matroska"
	ContainerFamilyMp4      ContainerFamily = "mp4"
)

// Valid indicates whether the value is a known member of the ContainerFamily enum.
func (e ContainerFamily) Valid() bool {
	switch e {
	case ContainerFamilyMatroska:
		return true
	case ContainerFamilyMp4:
		return true
	default:
		return false
	}
}

// Defines values for Decision.
const (
	DecisionConvert Decision = "convert"
	DecisionCopy    Decision = "copy"
	DecisionDrop    Decision = "drop"
	DecisionEncode  Decision = "encode"
)

// Valid indicates whether the value is a known member of the Decision enum.
func (e Decision) Valid() bool {
	switch e {
	case DecisionConvert:
		return true
	case DecisionCopy:
		return true
	case DecisionDrop:
		return true
	case DecisionEncode:
		return true
	default:
		return false
	}
}

// Defines values for DecodePath.
const (
	DecodePathHardware DecodePath = "hardware"
	DecodePathSoftware DecodePath = "software"
)

// Valid indicates whether the value is a known member of the DecodePath enum.
func (e DecodePath) Valid() bool {
	switch e {
	case DecodePathHardware:
		return true
	case DecodePathSoftware:
		return true
	default:
		return false
	}
}

// Defines values for Encoder.
const (
	EncoderHevcQsv   Encoder = "hevc_qsv"
	EncoderHevcVaapi Encoder = "hevc_vaapi"
	EncoderLibx265   Encoder = "libx265"
)

// Valid indicates whether the value is a known member of the Encoder enum.
func (e Encoder) Valid() bool {
	switch e {
	case EncoderHevcQsv:
		return true
	case EncoderHevcVaapi:
		return true
	case EncoderLibx265:
		return true
	default:
		return false
	}
}

// Defines values for EventLevel.
const (
	EventLevelDebug EventLevel = "debug"
	EventLevelError EventLevel = "error"
	EventLevelInfo  EventLevel = "info"
	EventLevelWarn  EventLevel = "warn"
)

// Valid indicates whether the value is a known member of the EventLevel enum.
func (e EventLevel) Valid() bool {
	switch e {
	case EventLevelDebug:
		return true
	case EventLevelError:
		return true
	case EventLevelInfo:
		return true
	case EventLevelWarn:
		return true
	default:
		return false
	}
}

// Defines values for FailureCode.
const (
	FailureCodeFfmpegFailed       FailureCode = "ffmpeg_failed"
	FailureCodeInternalError      FailureCode = "internal_error"
	FailureCodeInterrupted        FailureCode = "interrupted"
	FailureCodePreflightFailed    FailureCode = "preflight_failed"
	FailureCodeProbeFailed        FailureCode = "probe_failed"
	FailureCodePromoteFailed      FailureCode = "promote_failed"
	FailureCodeVerificationFailed FailureCode = "verification_failed"
)

// Valid indicates whether the value is a known member of the FailureCode enum.
func (e FailureCode) Valid() bool {
	switch e {
	case FailureCodeFfmpegFailed:
		return true
	case FailureCodeInternalError:
		return true
	case FailureCodeInterrupted:
		return true
	case FailureCodePreflightFailed:
		return true
	case FailureCodeProbeFailed:
		return true
	case FailureCodePromoteFailed:
		return true
	case FailureCodeVerificationFailed:
		return true
	default:
		return false
	}
}

// Defines values for Flavour.
const (
	FlavourRadarr Flavour = "radarr"
	FlavourSonarr Flavour = "sonarr"
)

// Valid indicates whether the value is a known member of the Flavour enum.
func (e Flavour) Valid() bool {
	switch e {
	case FlavourRadarr:
		return true
	case FlavourSonarr:
		return true
	default:
		return false
	}
}

// Defines values for HWCapabilityDirection.
const (
	HWCapabilityDirectionDecode HWCapabilityDirection = "decode"
	HWCapabilityDirectionEncode HWCapabilityDirection = "encode"
)

// Valid indicates whether the value is a known member of the HWCapabilityDirection enum.
func (e HWCapabilityDirection) Valid() bool {
	switch e {
	case HWCapabilityDirectionDecode:
		return true
	case HWCapabilityDirectionEncode:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for JobOrigin.
const (
	JobOriginIngest     JobOrigin = "ingest"
	JobOriginManual     JobOrigin = "manual"
	JobOriginRecheck    JobOrigin = "recheck"
	JobOriginSpaceSweep JobOrigin = "space_sweep"
)

// Valid indicates whether the value is a known member of the JobOrigin enum.
func (e JobOrigin) Valid() bool {
	switch e {
	case JobOriginIngest:
		return true
	case JobOriginManual:
		return true
	case JobOriginRecheck:
		return true
	case JobOriginSpaceSweep:
		return true
	default:
		return false
	}
}

// Defines values for JobState.
const (
	JobStateAwaitingStreamEnd JobState = "awaiting_stream_end"
	JobStateCancelled         JobState = "cancelled"
	JobStateDone              JobState = "done"
	JobStateFailed            JobState = "failed"
	JobStatePromoting         JobState = "promoting"
	JobStateQueued            JobState = "queued"
	JobStateRunning           JobState = "running"
	JobStateVerifying         JobState = "verifying"
)

// Valid indicates whether the value is a known member of the JobState enum.
func (e JobState) Valid() bool {
	switch e {
	case JobStateAwaitingStreamEnd:
		return true
	case JobStateCancelled:
		return true
	case JobStateDone:
		return true
	case JobStateFailed:
		return true
	case JobStatePromoting:
		return true
	case JobStateQueued:
		return true
	case JobStateRunning:
		return true
	case JobStateVerifying:
		return true
	default:
		return false
	}
}

// Defines values for MediaSort.
const (
	MediaSortMinusPath         MediaSort = "-path"
	MediaSortMinusPlanKind     MediaSort = "-plan_kind"
	MediaSortMinusProvenance   MediaSort = "-provenance"
	MediaSortMinusSizeBytes    MediaSort = "-size_bytes"
	MediaSortMinusStatus       MediaSort = "-status"
	MediaSortMinusUpdatedAt    MediaSort = "-updated_at"
	MediaSortMinusVideoBitrate MediaSort = "-video_bitrate"
	MediaSortPath              MediaSort = "path"
	MediaSortPlanKind          MediaSort = "plan_kind"
	MediaSortProvenance        MediaSort = "provenance"
	MediaSortSizeBytes         MediaSort = "size_bytes"
	MediaSortStatus            MediaSort = "status"
	MediaSortUpdatedAt         MediaSort = "updated_at"
	MediaSortVideoBitrate      MediaSort = "video_bitrate"
)

// Valid indicates whether the value is a known member of the MediaSort enum.
func (e MediaSort) Valid() bool {
	switch e {
	case MediaSortMinusPath:
		return true
	case MediaSortMinusPlanKind:
		return true
	case MediaSortMinusProvenance:
		return true
	case MediaSortMinusSizeBytes:
		return true
	case MediaSortMinusStatus:
		return true
	case MediaSortMinusUpdatedAt:
		return true
	case MediaSortMinusVideoBitrate:
		return true
	case MediaSortPath:
		return true
	case MediaSortPlanKind:
		return true
	case MediaSortProvenance:
		return true
	case MediaSortSizeBytes:
		return true
	case MediaSortStatus:
		return true
	case MediaSortUpdatedAt:
		return true
	case MediaSortVideoBitrate:
		return true
	default:
		return false
	}
}

// Defines values for MediaStatus.
const (
	MediaStatusAnalyzed   MediaStatus = "analyzed"
	MediaStatusDone       MediaStatus = "done"
	MediaStatusFailed     MediaStatus = "failed"
	MediaStatusIgnored    MediaStatus = "ignored"
	MediaStatusMissing    MediaStatus = "missing"
	MediaStatusNew        MediaStatus = "new"
	MediaStatusProcessing MediaStatus = "processing"
	MediaStatusQueued     MediaStatus = "queued"
	MediaStatusSkipped    MediaStatus = "skipped"
)

// Valid indicates whether the value is a known member of the MediaStatus enum.
func (e MediaStatus) Valid() bool {
	switch e {
	case MediaStatusAnalyzed:
		return true
	case MediaStatusDone:
		return true
	case MediaStatusFailed:
		return true
	case MediaStatusIgnored:
		return true
	case MediaStatusMissing:
		return true
	case MediaStatusNew:
		return true
	case MediaStatusProcessing:
		return true
	case MediaStatusQueued:
		return true
	case MediaStatusSkipped:
		return true
	default:
		return false
	}
}

// Defines values for PlanKind.
const (
	PlanKindAudioOnly PlanKind = "audio_only"
	PlanKindFull      PlanKind = "full"
	PlanKindRemux     PlanKind = "remux"
	PlanKindSkip      PlanKind = "skip"
)

// Valid indicates whether the value is a known member of the PlanKind enum.
func (e PlanKind) Valid() bool {
	switch e {
	case PlanKindAudioOnly:
		return true
	case PlanKindFull:
		return true
	case PlanKindRemux:
		return true
	case PlanKindSkip:
		return true
	default:
		return false
	}
}

// Defines values for Provenance.
const (
	ProvenanceCodarrOutput           Provenance = "codarr_output"
	ProvenanceModifiedSinceTranscode Provenance = "modified_since_transcode"
	ProvenanceUntouched              Provenance = "untouched"
)

// Valid indicates whether the value is a known member of the Provenance enum.
func (e Provenance) Valid() bool {
	switch e {
	case ProvenanceCodarrOutput:
		return true
	case ProvenanceModifiedSinceTranscode:
		return true
	case ProvenanceUntouched:
		return true
	default:
		return false
	}
}

// Defines values for ScanType.
const (
	ScanTypeInterlaced  ScanType = "interlaced"
	ScanTypeProgressive ScanType = "progressive"
)

// Valid indicates whether the value is a known member of the ScanType enum.
func (e ScanType) Valid() bool {
	switch e {
	case ScanTypeInterlaced:
		return true
	case ScanTypeProgressive:
		return true
	default:
		return false
	}
}

// Defines values for StreamType.
const (
	StreamTypeAudio    StreamType = "audio"
	StreamTypeSubtitle StreamType = "subtitle"
	StreamTypeVideo    StreamType = "video"
)

// Valid indicates whether the value is a known member of the StreamType enum.
func (e StreamType) Valid() bool {
	switch e {
	case StreamTypeAudio:
		return true
	case StreamTypeSubtitle:
		return true
	case StreamTypeVideo:
		return true
	default:
		return false
	}
}

// ArrInstance defines model for ArrInstance.
type ArrInstance struct {
	// ApiKey Always the masked placeholder `********` on read. The real key is
	// never returned and never logged.
	//
	//
	// Example: ********
	ApiKey         string        `json:"api_key"`
	BaseUrl        string        `json:"base_url"`
	CreatedAt      time.Time     `json:"created_at"`
	Enabled        bool          `json:"enabled"`
	Flavour        Flavour       `json:"flavour"`
	Id             int64         `json:"id"`
	LastTestResult *string       `json:"last_test_result,omitempty"`
	LastTestedAt   *time.Time    `json:"last_tested_at,omitempty"`
	Name           string        `json:"name"`
	PathMappings   []PathMapping `json:"path_mappings"`

	// RescanAfter RescanMovie or RescanSeries after a replacement.
	RescanAfter bool `json:"rescan_after"`

	// UnmonitorAfter Unmonitor the item after a successful full job. Off by default.
	UnmonitorAfter bool      `json:"unmonitor_after"`
	UpdatedAt      time.Time `json:"updated_at"`

	// WebhookId Unguessable, generated server-side. The instance's webhook URL is
	// this server's external base plus `/api/webhook/{webhook_id}`.
	WebhookId string `json:"webhook_id"`
}

// ArrInstanceCreate defines model for ArrInstanceCreate.
type ArrInstanceCreate struct {
	ApiKey         string         `json:"api_key"`
	BaseUrl        string         `json:"base_url"`
	Enabled        *bool          `json:"enabled,omitempty"`
	Flavour        Flavour        `json:"flavour"`
	Name           string         `json:"name"`
	PathMappings   *[]PathMapping `json:"path_mappings,omitempty"`
	RescanAfter    *bool          `json:"rescan_after,omitempty"`
	UnmonitorAfter *bool          `json:"unmonitor_after,omitempty"`
}

// ArrInstanceUpdate defines model for ArrInstanceUpdate.
type ArrInstanceUpdate struct {
	// ApiKey Send the masked placeholder `********` to keep the stored key. Any
	// other value replaces it.
	ApiKey  string  `json:"api_key"`
	BaseUrl string  `json:"base_url"`
	Enabled bool    `json:"enabled"`
	Flavour Flavour `json:"flavour"`
	Name    string  `json:"name"`

	// PathMappings Replaces the whole mapping list.
	PathMappings   []PathMapping `json:"path_mappings"`
	RescanAfter    bool          `json:"rescan_after"`
	UnmonitorAfter bool          `json:"unmonitor_after"`
}

// ArrRootFolder defines model for ArrRootFolder.
type ArrRootFolder struct {
	Accessible      bool   `json:"accessible"`
	AlreadyImported *bool  `json:"already_imported,omitempty"`
	FreeSpace       *int64 `json:"free_space,omitempty"`

	// Id The id on the *arr instance.
	Id int64 `json:"id"`

	// LocalPath The same path through that instance's mappings.
	LocalPath string `json:"local_path"`

	// Path The instance's view of the path.
	Path string `json:"path"`
}

// ArrWebhookEpisode defines model for ArrWebhookEpisode.
type ArrWebhookEpisode struct {
	EpisodeNumber        *int                   `json:"episodeNumber,omitempty"`
	Id                   *int64                 `json:"id,omitempty"`
	SeasonNumber         *int                   `json:"seasonNumber,omitempty"`
	Title                *string                `json:"title,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ArrWebhookEpisodeFile defines model for ArrWebhookEpisodeFile.
type ArrWebhookEpisodeFile struct {
	Id                   *int64                 `json:"id,omitempty"`
	Path                 *string                `json:"path,omitempty"`
	RelativePath         *string                `json:"relativePath,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ArrWebhookMovie defines model for ArrWebhookMovie.
type ArrWebhookMovie struct {
	FolderPath           *string                `json:"folderPath,omitempty"`
	Id                   *int64                 `json:"id,omitempty"`
	Title                *string                `json:"title,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ArrWebhookMovieFile defines model for ArrWebhookMovieFile.
type ArrWebhookMovieFile struct {
	Id                   *int64                 `json:"id,omitempty"`
	Path                 *string                `json:"path,omitempty"`
	RelativePath         *string                `json:"relativePath,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ArrWebhookPayload Modelled loosely on purpose. Radarr and Sonarr payloads vary by event
// type and by *arr version, so only the fields Codarr actually reads are
// declared and `additionalProperties: true` lets everything else through
// untouched. Mirroring the *arr schemas exactly creates breakage on every
// *arr release (plan.md 2.1 and 13.1).
//
// `path` is the sending instance's view of the filesystem and is remapped
// through that instance's own path mappings.
type ArrWebhookPayload struct {
	EpisodeFile *ArrWebhookEpisodeFile `json:"episodeFile,omitempty"`
	Episodes    *[]ArrWebhookEpisode   `json:"episodes,omitempty"`

	// EventType Handled: Download, Rename, Test, MovieFileDelete, EpisodeFileDelete.
	// Anything else is acknowledged and ignored.
	//
	//
	// Example: Download
	EventType            string                 `json:"eventType"`
	IsUpgrade            *bool                  `json:"isUpgrade,omitempty"`
	Movie                *ArrWebhookMovie       `json:"movie,omitempty"`
	MovieFile            *ArrWebhookMovieFile   `json:"movieFile,omitempty"`
	Series               *ArrWebhookSeries      `json:"series,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ArrWebhookSeries defines model for ArrWebhookSeries.
type ArrWebhookSeries struct {
	Id                   *int64                 `json:"id,omitempty"`
	Path                 *string                `json:"path,omitempty"`
	Title                *string                `json:"title,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// AudioState defines model for AudioState.
type AudioState struct {
	BitrateKbps *int    `json:"bitrate_kbps"`
	Channels    int     `json:"channels"`
	Codec       string  `json:"codec"`
	Layout      string  `json:"layout"`
	Profile     *string `json:"profile,omitempty"`
}

// AudioSummary defines model for AudioSummary.
type AudioSummary struct {
	Channels int    `json:"channels"`
	Codec    string `json:"codec"`

	// Language Example: eng
	Language string `json:"language"`

	// Layout Example: 5.1
	Layout string `json:"layout"`
}

// AudioTransform defines model for AudioTransform.
type AudioTransform struct {
	// Action What happens to one stream. `convert` is subtitles only.
	Action   Decision    `json:"action"`
	After    *AudioState `json:"after"`
	Before   *AudioState `json:"before"`
	Language string      `json:"language"`

	// OutputIndex Null for a dropped stream.
	OutputIndex *int    `json:"output_index"`
	Reason      *string `json:"reason,omitempty"`
	SourceIndex int     `json:"source_index"`
	Title       *string `json:"title"`
}

// AwaitingStreamEnd defines model for AwaitingStreamEnd.
type AwaitingStreamEnd struct {
	Filename       string    `json:"filename"`
	JobId          int64     `json:"job_id"`
	MediaFileId    int64     `json:"media_file_id"`
	Path           string    `json:"path"`
	SessionKey     *string   `json:"session_key,omitempty"`
	SessionPlayer  *string   `json:"session_player,omitempty"`
	SessionUser    *string   `json:"session_user,omitempty"`
	WaitingSeconds int       `json:"waiting_seconds"`
	WaitingSince   time.Time `json:"waiting_since"`
}

// BeforeAfterInt defines model for BeforeAfterInt.
type BeforeAfterInt struct {
	After  int `json:"after"`
	Before int `json:"before"`
}

// BeforeAfterString defines model for BeforeAfterString.
type BeforeAfterString struct {
	After  string `json:"after"`
	Before string `json:"before"`
}

// BitrateSource Which rung of the resolution chain in plan.md 8.4 produced the video bitrate.
type BitrateSource string

// CompatibilityReasons A file can need work for more than one reason, so these overlap.
type CompatibilityReasons struct {
	Audio     int `json:"audio"`
	Container int `json:"container"`
	Subtitles int `json:"subtitles"`
	Video     int `json:"video"`
}

// CompatibilitySummary How many files still force playback transcoding, and why. This is the
// number that tracks progress toward the primary goal.
type CompatibilitySummary struct {
	ByPlanKind PlanKindBreakdown `json:"by_plan_kind"`

	// ByReason A file can need work for more than one reason, so these overlap.
	ByReason         CompatibilityReasons `json:"by_reason"`
	FilesAnalyzed    int                  `json:"files_analyzed"`
	FilesCompatible  int                  `json:"files_compatible"`
	FilesNeedingWork int                  `json:"files_needing_work"`
	FilesUnanalyzed  int                  `json:"files_unanalyzed"`
}

// ContainerFamily The output muxer family. Codarr only ever writes these two.
type ContainerFamily string

// Dashboard defines model for Dashboard.
type Dashboard struct {
	AwaitingStreamEnd []AwaitingStreamEnd `json:"awaiting_stream_end"`

	// Compatibility How many files still force playback transcoding, and why. This is the
	// number that tracks progress toward the primary goal.
	Compatibility CompatibilitySummary `json:"compatibility"`
	CurrentJob    *JobSummary          `json:"current_job,omitempty"`

	// Failures Failed jobs needing attention, newest first.
	Failures    []JobSummary `json:"failures"`
	GeneratedAt time.Time    `json:"generated_at"`

	// Queue In execution order.
	Queue             []JobSummary `json:"queue"`
	QueueDepth        int          `json:"queue_depth"`
	QueuePaused       bool         `json:"queue_paused"`
	RecentCompletions []JobSummary `json:"recent_completions"`
	Stats             Stats        `json:"stats"`
}

// Decision What happens to one stream. `convert` is subtitles only.
type Decision string

// DecodePath defines model for DecodePath.
type DecodePath string

// DurationTransform defines model for DurationTransform.
type DurationTransform struct {
	// Actual Null until the job finishes.
	Actual    *int `json:"actual"`
	Estimated int  `json:"estimated"`
}

// Encoder defines model for Encoder.
type Encoder string

// EnqueueResult defines model for EnqueueResult.
type EnqueueResult struct {
	Enqueued bool `json:"enqueued"`

	// JobId The existing job when the enqueue was a no-op.
	JobId       *int64 `json:"job_id,omitempty"`
	MediaFileId int64  `json:"media_file_id"`

	// PlanKind The shape of the work a file needs.
	PlanKind *PlanKind `json:"plan_kind,omitempty"`
	Reason   string    `json:"reason"`
}

// Error defines model for Error.
type Error struct {
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Stable machine-readable code, snake_case.
	//
	// Example: not_found
	Error string `json:"error"`

	// Message Human-readable detail, specific enough to act on.
	Message string `json:"message"`
}

// Event defines model for Event.
type Event struct {
	Category    string     `json:"category"`
	CreatedAt   time.Time  `json:"created_at"`
	Id          int64      `json:"id"`
	JobId       *int64     `json:"job_id,omitempty"`
	Level       EventLevel `json:"level"`
	MediaFileId *int64     `json:"media_file_id,omitempty"`
	Message     string     `json:"message"`
}

// EventLevel defines model for EventLevel.
type EventLevel string

// EventPage defines model for EventPage.
type EventPage struct {
	// HasMore More events matched than the limit allowed.
	HasMore bool `json:"has_more"`

	// Items Ascending by id.
	Items []Event `json:"items"`

	// NextSinceId Pass as `since_id` on the next poll.
	NextSinceId int64 `json:"next_since_id"`
}

// FailureCode A failed job without one is a bug (plan.md 19.1).
type FailureCode string

// Flavour defines model for Flavour.
type Flavour string

// HWCapability defines model for HWCapability.
type HWCapability struct {
	// Backend Example: qsv
	Backend string `json:"backend"`

	// Codec Example: hevc
	Codec         string                `json:"codec"`
	Direction     HWCapabilityDirection `json:"direction"`
	Error         *string               `json:"error,omitempty"`
	FfmpegVersion *string               `json:"ffmpeg_version,omitempty"`
	ProbedAt      time.Time             `json:"probed_at"`

	// Profile Example: main10
	Profile string `json:"profile"`
	Works   bool   `json:"works"`
}

// HWCapabilityDirection defines model for HWCapability.Direction.
type HWCapabilityDirection string

// Hardware defines model for Hardware.
type Hardware struct {
	Capabilities  []HWCapability `json:"capabilities"`
	FfmpegVersion *string        `json:"ffmpeg_version,omitempty"`

	// HardwareDecodeCodecs The hard-coded Gen 9.5 decode set. Anything else decodes in software.
	HardwareDecodeCodecs []string   `json:"hardware_decode_codecs"`
	ProbedAt             *time.Time `json:"probed_at,omitempty"`
	QsvDevice            string     `json:"qsv_device"`

	// Remediation What to do when a probe failed; a Main10 failure is almost always the driver stack.
	Remediation     *string  `json:"remediation,omitempty"`
	SelectedEncoder *Encoder `json:"selected_encoder,omitempty"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ImportRootsResult defines model for ImportRootsResult.
type ImportRootsResult struct {
	// Conflicts Paths another enabled instance already claims. Codarr never guesses
	// an owner, so these are skipped and surfaced (plan.md 16.2).
	Conflicts []RootConflict `json:"conflicts"`
	Imported  int            `json:"imported"`
	Roots     []Root         `json:"roots"`

	// Skipped Already present and owned by this instance.
	Skipped int `json:"skipped"`
}

// IntegrityBulkResult defines model for IntegrityBulkResult.
type IntegrityBulkResult struct {
	Checked    int               `json:"checked"`
	Mismatched int               `json:"mismatched"`
	Results    []IntegrityResult `json:"results"`
}

// IntegrityResult defines model for IntegrityResult.
type IntegrityResult struct {
	CheckedAt          time.Time `json:"checked_at"`
	CurrentFingerprint *string   `json:"current_fingerprint,omitempty"`
	CurrentFullHash    *string   `json:"current_full_hash,omitempty"`
	CurrentSizeBytes   *int64    `json:"current_size_bytes,omitempty"`

	// FullHashChecked Only true when a whole-file hash was recorded at promotion.
	FullHashChecked bool    `json:"full_hash_checked"`
	MediaFileId     int64   `json:"media_file_id"`
	Message         *string `json:"message,omitempty"`

	// Ok The file still matches what was recorded at promotion. A file Codarr
	// never wrote reports ok with provenance `untouched`.
	Ok   bool   `json:"ok"`
	Path string `json:"path"`

	// Provenance Derived on every analysis, never set by a user. `modified_since_transcode`
	// means something rewrote a file Codarr produced.
	Provenance          Provenance `json:"provenance"`
	RecordedFingerprint *string    `json:"recorded_fingerprint,omitempty"`
	RecordedFullHash    *string    `json:"recorded_full_hash,omitempty"`
	RecordedSizeBytes   *int64     `json:"recorded_size_bytes,omitempty"`
}

// Job defines model for Job.
type Job struct {
	ActualSeconds    *int        `json:"actual_seconds,omitempty"`
	ArrInstanceId    *int64      `json:"arr_instance_id,omitempty"`
	ArrInstanceName  *string     `json:"arr_instance_name,omitempty"`
	Attempt          int         `json:"attempt"`
	BlockedBy        *string     `json:"blocked_by,omitempty"`
	DecodePath       *DecodePath `json:"decode_path,omitempty"`
	EncoderUsed      *Encoder    `json:"encoder_used,omitempty"`
	EstimatedSeconds *int        `json:"estimated_seconds,omitempty"`

	// FailureCode A failed job without one is a bug (plan.md 19.1).
	FailureCode    *FailureCode `json:"failure_code,omitempty"`
	FailureMessage *string      `json:"failure_message,omitempty"`
	FallbackReason *string      `json:"fallback_reason,omitempty"`
	FellBack       bool         `json:"fell_back"`
	FfmpegArgv     *[]string    `json:"ffmpeg_argv,omitempty"`
	FinishedAt     *time.Time   `json:"finished_at,omitempty"`
	Id             int64        `json:"id"`

	// Kind The shape of the work a file needs.
	Kind              PlanKind  `json:"kind"`
	MediaFileId       int64     `json:"media_file_id"`
	MediaFilename     string    `json:"media_filename"`
	MediaPath         string    `json:"media_path"`
	Origin            JobOrigin `json:"origin"`
	OutputFingerprint *string   `json:"output_fingerprint,omitempty"`
	OutputFullHash    *string   `json:"output_full_hash,omitempty"`
	OutputSize        *int64    `json:"output_size,omitempty"`
	Priority          int       `json:"priority"`

	// ProbeResult Raw ffprobe output of the staged result, when one was taken.
	ProbeResult   *string    `json:"probe_result,omitempty"`
	ProgressPct   *float64   `json:"progress_pct,omitempty"`
	ProgressSpeed *float64   `json:"progress_speed,omitempty"`
	QueuedAt      time.Time  `json:"queued_at"`
	SourceSize    *int64     `json:"source_size,omitempty"`
	StagingPath   *string    `json:"staging_path,omitempty"`
	StartedAt     *time.Time `json:"started_at,omitempty"`
	State         JobState   `json:"state"`

	// StderrTail Included on ffmpeg_failed.
	StderrTail *string `json:"stderr_tail,omitempty"`

	// Transform The before/after history for one job (plan.md 17.2). Written at enqueue
	// with `after` holding the plan, updated at completion with `after` holding
	// what an ffprobe of the real output measured. One schema serves both,
	// which is what lets the UI render queued and completed items with the same
	// component. Never deleted.
	Transform   TransformRecord `json:"transform"`
	UsedTempDir bool            `json:"used_temp_dir"`
}

// JobOrigin defines model for JobOrigin.
type JobOrigin string

// JobPage defines model for JobPage.
type JobPage struct {
	Items    []JobSummary `json:"items"`
	Page     int          `json:"page"`
	PageSize int          `json:"page_size"`
	Total    int          `json:"total"`
}

// JobState defines model for JobState.
type JobState string

// JobSummary defines model for JobSummary.
type JobSummary struct {
	ActualSeconds *int `json:"actual_seconds,omitempty"`

	// Attempt Automatic re-queues after an interruption; caps at 3.
	Attempt int `json:"attempt"`

	// BlockedBy What is holding the job in awaiting_stream_end.
	BlockedBy        *string     `json:"blocked_by,omitempty"`
	DecodePath       *DecodePath `json:"decode_path,omitempty"`
	EncoderUsed      *Encoder    `json:"encoder_used,omitempty"`
	EstimatedSeconds *int        `json:"estimated_seconds,omitempty"`

	// FailureCode A failed job without one is a bug (plan.md 19.1).
	FailureCode *FailureCode `json:"failure_code,omitempty"`

	// FailureMessage Always populated on failure, and specific enough to act on.
	FailureMessage *string `json:"failure_message,omitempty"`
	FallbackReason *string `json:"fallback_reason,omitempty"`

	// FellBack A software-encoder fallback turns a 20-minute job into a 4-hour one; the UI shouts about it.
	FellBack   bool       `json:"fell_back"`
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	Id         int64      `json:"id"`

	// Kind The shape of the work a file needs.
	Kind          PlanKind  `json:"kind"`
	MediaFileId   int64     `json:"media_file_id"`
	MediaFilename string    `json:"media_filename"`
	MediaPath     string    `json:"media_path"`
	Origin        JobOrigin `json:"origin"`
	OutputSize    *int64    `json:"output_size,omitempty"`

	// Priority Lower runs first.
	Priority    int      `json:"priority"`
	ProgressPct *float64 `json:"progress_pct,omitempty"`

	// ProgressSpeed ffmpeg's speed multiplier relative to realtime.
	ProgressSpeed *float64   `json:"progress_speed,omitempty"`
	QueuedAt      time.Time  `json:"queued_at"`
	SourceSize    *int64     `json:"source_size,omitempty"`
	StartedAt     *time.Time `json:"started_at,omitempty"`
	State         JobState   `json:"state"`
}

// MediaDetail defines model for MediaDetail.
type MediaDetail struct {
	AnalyzedAt      *time.Time     `json:"analyzed_at,omitempty"`
	ArrEntityId     *int64         `json:"arr_entity_id,omitempty"`
	ArrInstanceId   *int64         `json:"arr_instance_id,omitempty"`
	ArrInstanceName *string        `json:"arr_instance_name,omitempty"`
	Audio           []AudioSummary `json:"audio"`
	CodarrJobId     *int64         `json:"codarr_job_id,omitempty"`

	// CodarrOutputFingerprint Empty means Codarr has never written this file.
	CodarrOutputFingerprint *string    `json:"codarr_output_fingerprint,omitempty"`
	CodarrOutputFullHash    *string    `json:"codarr_output_full_hash,omitempty"`
	CodarrOutputMtime       *int64     `json:"codarr_output_mtime,omitempty"`
	CodarrOutputSize        *int64     `json:"codarr_output_size,omitempty"`
	CodarrPolicyHash        *string    `json:"codarr_policy_hash,omitempty"`
	CodarrProcessedAt       *time.Time `json:"codarr_processed_at,omitempty"`
	CodarrTagged            bool       `json:"codarr_tagged"`
	Container               *string    `json:"container,omitempty"`
	CreatedAt               time.Time  `json:"created_at"`
	Filename                string     `json:"filename"`
	Fingerprint             *string    `json:"fingerprint,omitempty"`

	// FingerprintAlgo Example: xxh3-128
	FingerprintAlgo    *string    `json:"fingerprint_algo,omitempty"`
	Height             *int       `json:"height,omitempty"`
	Id                 int64      `json:"id"`
	Ignored            bool       `json:"ignored"`
	IntegrityCheckedAt *time.Time `json:"integrity_checked_at,omitempty"`
	IsHdr              bool       `json:"is_hdr"`
	LastError          *string    `json:"last_error,omitempty"`
	LatestJobId        *int64     `json:"latest_job_id,omitempty"`

	// MediaInfo The parsed summary the detail modal renders. Deliberately not a full
	// probe dump; `probe_json` carries that.
	MediaInfo *MediaInfo `json:"media_info,omitempty"`
	Mtime     int64      `json:"mtime"`

	// Nlink Greater than one fails preflight; a hardlinked file is never replaced.
	Nlink *int   `json:"nlink,omitempty"`
	Path  string `json:"path"`

	// Plan Derived purely from an ffprobe result plus the hard-coded policy, so it
	// is deterministic (plan.md section 7).
	Plan *Plan `json:"plan,omitempty"`

	// PlanKind The shape of the work a file needs.
	PlanKind    *PlanKind `json:"plan_kind,omitempty"`
	PlanReasons []string  `json:"plan_reasons"`

	// ProbeJson Raw ffprobe output, for the collapsed technical section of the modal.
	ProbeJson *string `json:"probe_json,omitempty"`

	// Provenance Derived on every analysis, never set by a user. `modified_since_transcode`
	// means something rewrote a file Codarr produced.
	Provenance       Provenance        `json:"provenance"`
	RootId           *int64            `json:"root_id,omitempty"`
	SizeBytes        int64             `json:"size_bytes"`
	Status           MediaStatus       `json:"status"`
	Subtitles        []SubtitleSummary `json:"subtitles"`
	UpdatedAt        time.Time         `json:"updated_at"`
	VideoBitrateKbps *int              `json:"video_bitrate_kbps,omitempty"`

	// VideoBitrateSource Which rung of the resolution chain in plan.md 8.4 produced the video bitrate.
	VideoBitrateSource *BitrateSource `json:"video_bitrate_source,omitempty"`
	VideoCodec         *string        `json:"video_codec,omitempty"`
	VideoLevel         *string        `json:"video_level,omitempty"`
	VideoProfile       *string        `json:"video_profile,omitempty"`
	Width              *int           `json:"width,omitempty"`
}

// MediaFilter The same filter the library table applies, so "select all matching filter" (plan.md 18.2) does not mean shipping every matching id over the wire. A 40k-file selection is one filter object, not 40k integers.
type MediaFilter struct {
	ArrInstanceId *int64 `json:"arr_instance_id,omitempty"`

	// PlanKind The shape of the work a file needs.
	PlanKind *PlanKind `json:"plan_kind,omitempty"`

	// Provenance Derived on every analysis, never set by a user. `modified_since_transcode`
	// means something rewrote a file Codarr produced.
	Provenance *Provenance  `json:"provenance,omitempty"`
	Q          *string      `json:"q,omitempty"`
	Status     *MediaStatus `json:"status,omitempty"`
	VideoCodec *string      `json:"video_codec,omitempty"`
}

// MediaInfo The parsed summary the detail modal renders. Deliberately not a full
// probe dump; `probe_json` carries that.
type MediaInfo struct {
	Attachments     int                 `json:"attachments"`
	Audio           []MediaInfoAudio    `json:"audio"`
	Chapters        int                 `json:"chapters"`
	Container       string              `json:"container"`
	DurationSeconds *float64            `json:"duration_seconds,omitempty"`
	Subtitles       []MediaInfoSubtitle `json:"subtitles"`
	Video           *VideoState         `json:"video"`
}

// MediaInfoAudio defines model for MediaInfoAudio.
type MediaInfoAudio struct {
	BitrateKbps *int   `json:"bitrate_kbps,omitempty"`
	Channels    int    `json:"channels"`
	Codec       string `json:"codec"`
	Comment     bool   `json:"comment"`
	Default     bool   `json:"default"`
	Forced      bool   `json:"forced"`

	// Index Source stream index.
	Index          int     `json:"index"`
	Language       string  `json:"language"`
	Layout         string  `json:"layout"`
	Profile        *string `json:"profile,omitempty"`
	Title          *string `json:"title,omitempty"`
	VisualImpaired bool    `json:"visual_impaired"`
}

// MediaInfoSubtitle defines model for MediaInfoSubtitle.
type MediaInfoSubtitle struct {
	Codec    string  `json:"codec"`
	Default  bool    `json:"default"`
	Forced   bool    `json:"forced"`
	Index    int     `json:"index"`
	Language string  `json:"language"`
	Title    *string `json:"title,omitempty"`
}

// MediaListItem defines model for MediaListItem.
type MediaListItem struct {
	AnalyzedAt      *time.Time     `json:"analyzed_at,omitempty"`
	ArrInstanceId   *int64         `json:"arr_instance_id,omitempty"`
	ArrInstanceName *string        `json:"arr_instance_name,omitempty"`
	Audio           []AudioSummary `json:"audio"`
	CodarrTagged    bool           `json:"codarr_tagged"`
	Container       *string        `json:"container,omitempty"`
	Filename        string         `json:"filename"`
	Height          *int           `json:"height,omitempty"`
	Id              int64          `json:"id"`
	Ignored         bool           `json:"ignored"`
	IsHdr           bool           `json:"is_hdr"`
	Path            string         `json:"path"`

	// PlanKind The shape of the work a file needs.
	PlanKind *PlanKind `json:"plan_kind,omitempty"`

	// Provenance Derived on every analysis, never set by a user. `modified_since_transcode`
	// means something rewrote a file Codarr produced.
	Provenance       Provenance        `json:"provenance"`
	RootId           *int64            `json:"root_id,omitempty"`
	SizeBytes        int64             `json:"size_bytes"`
	Status           MediaStatus       `json:"status"`
	Subtitles        []SubtitleSummary `json:"subtitles"`
	UpdatedAt        time.Time         `json:"updated_at"`
	VideoBitrateKbps *int              `json:"video_bitrate_kbps,omitempty"`

	// VideoBitrateSource Which rung of the resolution chain in plan.md 8.4 produced the video bitrate.
	VideoBitrateSource *BitrateSource `json:"video_bitrate_source,omitempty"`
	VideoCodec         *string        `json:"video_codec,omitempty"`
	VideoLevel         *string        `json:"video_level,omitempty"`
	VideoProfile       *string        `json:"video_profile,omitempty"`
	Width              *int           `json:"width,omitempty"`
}

// MediaPage defines model for MediaPage.
type MediaPage struct {
	Items    []MediaListItem `json:"items"`
	Page     int             `json:"page"`
	PageSize int             `json:"page_size"`

	// Total Rows matching the filter, ignoring pagination.
	Total int `json:"total"`
}

// MediaSort defines model for MediaSort.
type MediaSort string

// MediaStatus defines model for MediaStatus.
type MediaStatus string

// OutputIdentity Written at promotion, after the mtime restore. The immutable record of
// what Codarr actually produced; the media row's copy is the mutable
// current-state view, and the two diverging is the signal that something
// rewrote the file.
type OutputIdentity struct {
	// Fingerprint Example: xxh3-128:9f2c
	Fingerprint string `json:"fingerprint"`

	// FullHash Only when full_hash_enabled was on.
	FullHash   *string   `json:"full_hash"`
	Mtime      int64     `json:"mtime"`
	PolicyHash string    `json:"policy_hash"`
	RecordedAt time.Time `json:"recorded_at"`
	SizeBytes  int64     `json:"size_bytes"`
}

// PathMapping defines model for PathMapping.
type PathMapping struct {
	// Id Absent when creating.
	Id *int64 `json:"id,omitempty"`

	// Local Codarr's view of the path.
	Local string `json:"local"`

	// Remote The other service's view of the same path.
	Remote string `json:"remote"`

	// Sort Lower is tried first.
	Sort int `json:"sort"`
}

// Plan Derived purely from an ffprobe result plus the hard-coded policy, so it
// is deterministic (plan.md section 7).
type Plan struct {
	Deinterlace        bool `json:"deinterlace"`
	DolbyVision        bool `json:"dolby_vision"`
	DolbyVisionProfile *int `json:"dolby_vision_profile,omitempty"`
	Hdr                bool `json:"hdr"`

	// Kind The shape of the work a file needs.
	Kind PlanKind `json:"kind"`

	// LevelRewrite The stream is still copied; only the H.264 level flag is rewritten
	// to 4.2 by a bitstream filter (plan.md 6.2).
	LevelRewrite bool `json:"level_rewrite"`

	// OutputContainer The output muxer family. Codarr only ever writes these two.
	OutputContainer ContainerFamily `json:"output_container"`
	PolicyHash      string          `json:"policy_hash"`
	Reasons         []string        `json:"reasons"`
	SourceContainer string          `json:"source_container"`
	Streams         []StreamPlan    `json:"streams"`

	// TargetVideoBitrateBps Zero until the sample probe has run, which is the first phase of a
	// full job rather than something that happens at enqueue.
	TargetVideoBitrateBps *int `json:"target_video_bitrate_bps,omitempty"`
}

// PlanKind The shape of the work a file needs.
type PlanKind string

// PlanKindBreakdown defines model for PlanKindBreakdown.
type PlanKindBreakdown struct {
	AudioOnly int `json:"audio_only"`
	Full      int `json:"full"`
	Remux     int `json:"remux"`
	Skip      int `json:"skip"`
}

// PlexAuthPoll defines model for PlexAuthPoll.
type PlexAuthPoll struct {
	Authorized bool    `json:"authorized"`
	Message    *string `json:"message,omitempty"`

	// TokenStored True once the claimed token has been persisted. The token itself is
	// never returned by this API.
	TokenStored bool `json:"token_stored"`
}

// PlexAuthStart defines model for PlexAuthStart.
type PlexAuthStart struct {
	// AuthUrl Open this in a browser to claim the PIN.
	AuthUrl          string     `json:"auth_url"`
	ClientIdentifier string     `json:"client_identifier"`
	Code             string     `json:"code"`
	ExpiresAt        *time.Time `json:"expires_at,omitempty"`
	PinId            int64      `json:"pin_id"`
}

// PlexConfig defines model for PlexConfig.
type PlexConfig struct {
	// AnalyzeAfter PUT /library/metadata/{ratingKey}/analyze after a replacement.
	AnalyzeAfter bool   `json:"analyze_after"`
	BaseUrl      string `json:"base_url"`

	// ClientIdentifier Stable X-Plex-Client-Identifier, generated once and persisted.
	ClientIdentifier string `json:"client_identifier"`

	// GuardActiveStreams Never replace a file Plex is streaming right now. This defers a job,
	// it never skips it, and it is unrelated to resource contention.
	GuardActiveStreams bool          `json:"guard_active_streams"`
	LastTestResult     *string       `json:"last_test_result,omitempty"`
	LastTestedAt       *time.Time    `json:"last_tested_at,omitempty"`
	PathMappings       []PathMapping `json:"path_mappings"`

	// RefreshAfter Partial scan of the containing directory after a replacement.
	RefreshAfter bool `json:"refresh_after"`

	// Token Always the masked placeholder `********` on read. The real token is
	// never returned and never logged. On PUT, this exact value leaves the
	// stored token untouched; anything else overwrites it.
	//
	//
	// Example: ********
	Token     string    `json:"token"`
	UpdatedAt time.Time `json:"updated_at"`
}

// PlexConfigUpdate defines model for PlexConfigUpdate.
type PlexConfigUpdate struct {
	AnalyzeAfter       bool   `json:"analyze_after"`
	BaseUrl            string `json:"base_url"`
	GuardActiveStreams bool   `json:"guard_active_streams"`

	// PathMappings Replaces the whole mapping list.
	PathMappings []PathMapping `json:"path_mappings"`
	RefreshAfter bool          `json:"refresh_after"`

	// Token Send the masked placeholder `********` to keep the stored token.
	// Any other value replaces it.
	Token string `json:"token"`
}

// PlexLibrary defines model for PlexLibrary.
type PlexLibrary struct {
	// Key The section key used in /library/sections/{key}/refresh.
	Key string `json:"key"`

	// Locations Plex-side directories for the section.
	Locations []string `json:"locations"`
	Title     string   `json:"title"`

	// Type Example: movie
	Type string `json:"type"`
}

// Policy Compiled into the binary and displayed read-only. Nothing in this API
// changes what gets transcoded or to what (plan.md section 6). Changing the
// policy and rebuilding changes `policy_hash`, which is what makes
// previously-tagged files eligible for a re-check again.
type Policy struct {
	Audio      PolicyAudio      `json:"audio"`
	Bitrate    PolicyBitrate    `json:"bitrate"`
	Container  PolicyContainer  `json:"container"`
	Exclusions PolicyExclusions `json:"exclusions"`
	PolicyHash string           `json:"policy_hash"`
	SpaceSweep PolicySpaceSweep `json:"space_sweep"`
	Subtitles  PolicySubtitles  `json:"subtitles"`

	// TagKeys Written into every output. The tag alone is never sufficient to skip
	// a file; the skip rule is a conjunction with the policy hash and the
	// recorded output fingerprint (plan.md section 12).
	TagKeys []string    `json:"tag_keys"`
	Video   PolicyVideo `json:"video"`
}

// PolicyAudio defines model for PolicyAudio.
type PolicyAudio struct {
	CopyList          []PolicyAudioCopyRule     `json:"copy_list"`
	EncodeTargets     []PolicyAudioEncodeTarget `json:"encode_targets"`
	KeepAllLanguages  bool                      `json:"keep_all_languages"`
	Mp4KbpsPerChannel int                       `json:"mp4_kbps_per_channel"`

	// Mp4MultichannelCodec AC3 in MP4 is legal but patchily supported, so multichannel MP4 audio goes to AAC.
	Mp4MultichannelCodec string `json:"mp4_multichannel_codec"`

	// NeverZeroAudioStreams A mapping that would produce no audio fails the job instead.
	NeverZeroAudioStreams bool `json:"never_zero_audio_streams"`
}

// PolicyAudioCopyRule defines model for PolicyAudioCopyRule.
type PolicyAudioCopyRule struct {
	Codecs []string `json:"codecs"`

	// MaxChannels Zero means unbounded.
	MaxChannels int `json:"max_channels"`
	MinChannels int `json:"min_channels"`
}

// PolicyAudioEncodeTarget defines model for PolicyAudioEncodeTarget.
type PolicyAudioEncodeTarget struct {
	BitrateKbps int    `json:"bitrate_kbps"`
	Codec       string `json:"codec"`

	// DownmixChannels Set for 7 or more channels, which downmix to 5.1.
	DownmixChannels *int `json:"downmix_channels,omitempty"`

	// MaxChannels Zero means unbounded.
	MaxChannels int `json:"max_channels"`
	MinChannels int `json:"min_channels"`
}

// PolicyBitrate defines model for PolicyBitrate.
type PolicyBitrate struct {
	// AppliesTo Only full jobs and the manual space sweep compute a bitrate.
	AppliesTo     string             `json:"applies_to"`
	BufsizeFactor float64            `json:"bufsize_factor"`
	FpsScaleCap   float64            `json:"fps_scale_cap"`
	HdrUpliftPct  float64            `json:"hdr_uplift_pct"`
	MaxrateFactor float64            `json:"maxrate_factor"`
	SampleProbe   PolicySampleProbe  `json:"sample_probe"`
	Table         []PolicyBitrateRow `json:"table"`
}

// PolicyBitrateRow defines model for PolicyBitrateRow.
type PolicyBitrateRow struct {
	// Bpp Bits per pixel for the fallback formula when the sample probe fails.
	Bpp         float64 `json:"bpp"`
	CeilingKbps int     `json:"ceiling_kbps"`
	FloorKbps   int     `json:"floor_kbps"`

	// Resolution Example: 1080p
	Resolution string `json:"resolution"`
}

// PolicyContainer defines model for PolicyContainer.
type PolicyContainer struct {
	// LegacyExtensions Containers always rewritten to Matroska, even when every stream copies.
	LegacyExtensions []string `json:"legacy_extensions"`

	// Mp4Movflags faststart moves the moov atom to the front; use_metadata_tags carries the loop-prevention tag.
	Mp4Movflags []string `json:"mp4_movflags"`

	// PreserveExtensions Containers kept as they are, so the path never changes.
	PreserveExtensions []string `json:"preserve_extensions"`
}

// PolicyEncodeTarget defines model for PolicyEncodeTarget.
type PolicyEncodeTarget struct {
	BitDepth int    `json:"bit_depth"`
	Codec    string `json:"codec"`

	// Mp4Tag hvc1 rather than ffmpeg's default hev1, which Apple-derived players refuse.
	Mp4Tag  *string `json:"mp4_tag,omitempty"`
	Profile string  `json:"profile"`

	// Source Example: SDR
	Source string `json:"source"`
}

// PolicyExclusions defines model for PolicyExclusions.
type PolicyExclusions struct {
	ExtrasDirectories []string `json:"extras_directories"`
	FilenamePatterns  []string `json:"filename_patterns"`
	MinSizeBytes      int64    `json:"min_size_bytes"`
	PartialExtensions []string `json:"partial_extensions"`

	// StabilityGuardSeconds Files whose mtime is newer than this are left for the next scan.
	StabilityGuardSeconds int `json:"stability_guard_seconds"`
}

// PolicyLevelRewrite A stream failing only the level test is still copied; the flag is
// rewritten in-stream during the container rebuild. The refs guard is
// load-bearing, not a safety margin.
type PolicyLevelRewrite struct {
	// BitstreamFilter Example: h264_metadata=level=4.2
	BitstreamFilter string  `json:"bitstream_filter"`
	MaxFps          float64 `json:"max_fps"`
	MaxHeight       int     `json:"max_height"`
	MaxRefs         int     `json:"max_refs"`
	MaxWidth        int     `json:"max_width"`
	TargetLevel     string  `json:"target_level"`
}

// PolicySampleProbe defines model for PolicySampleProbe.
type PolicySampleProbe struct {
	Crf     int    `json:"crf"`
	Encoder string `json:"encoder"`

	// HardwareCorrection The fixed-function encoder is less efficient than x265 at equal bitrate.
	HardwareCorrection float64 `json:"hardware_correction"`
	Preset             string  `json:"preset"`
	SegmentSeconds     int     `json:"segment_seconds"`
	Segments           int     `json:"segments"`
	SkipHeadPct        float64 `json:"skip_head_pct"`
	SkipTailPct        float64 `json:"skip_tail_pct"`

	// SourceClamp Target is capped at this fraction of the resolved source bitrate.
	SourceClamp float64 `json:"source_clamp"`
}

// PolicySpaceSweep defines model for PolicySpaceSweep.
type PolicySpaceSweep struct {
	// ManualOnly Never runs automatically and is never triggered by ingest.
	ManualOnly            bool    `json:"manual_only"`
	MinProjectedSavingPct float64 `json:"min_projected_saving_pct"`
	MinVideoBitrateKbps   int     `json:"min_video_bitrate_kbps"`
	SourceCodec           string  `json:"source_codec"`
}

// PolicySubtitleTarget defines model for PolicySubtitleTarget.
type PolicySubtitleTarget struct {
	Codec string `json:"codec"`

	// Container The output muxer family. Codarr only ever writes these two.
	Container ContainerFamily `json:"container"`
}

// PolicySubtitles defines model for PolicySubtitles.
type PolicySubtitles struct {
	// DropAttachments Converting ASS to SRT removes the dependency on embedded fonts.
	DropAttachments     bool     `json:"drop_attachments"`
	DropBroadcastCodecs []string `json:"drop_broadcast_codecs"`

	// DropForcedImageSubtitles Keeping forced PGS would reintroduce the burn-in transcode this policy exists to remove.
	DropForcedImageSubtitles bool `json:"drop_forced_image_subtitles"`

	// DropImageCodecs Bitmaps. A client that cannot render them makes the server burn them in, forcing a full playback transcode.
	DropImageCodecs  []string               `json:"drop_image_codecs"`
	KeepAllLanguages bool                   `json:"keep_all_languages"`
	Targets          []PolicySubtitleTarget `json:"targets"`

	// TextCodecs Never dropped for format reasons; converted to the container's target.
	TextCodecs []string `json:"text_codecs"`
}

// PolicyVideo defines model for PolicyVideo.
type PolicyVideo struct {
	CopyRule             PolicyVideoCopyRule  `json:"copy_rule"`
	DropAttachedPictures bool                 `json:"drop_attached_pictures"`
	EncodeTargets        []PolicyEncodeTarget `json:"encode_targets"`
	HardwareDecodeCodecs []string             `json:"hardware_decode_codecs"`

	// LevelRewrite A stream failing only the level test is still copied; the flag is
	// rewritten in-stream during the container rebuild. The refs guard is
	// load-bearing, not a safety margin.
	LevelRewrite PolicyLevelRewrite `json:"level_rewrite"`
}

// PolicyVideoCopyRule defines model for PolicyVideoCopyRule.
type PolicyVideoCopyRule struct {
	// ChromaSubsampling A subsampling test, not a pix_fmt string compare. Any bit depth passes.
	//
	// Example: 4:2:0
	ChromaSubsampling string   `json:"chroma_subsampling"`
	Codecs            []string `json:"codecs"`

	// H264MaxLevel Example: 4.2
	H264MaxLevel string `json:"h264_max_level"`

	// H264Profiles ffprobe's exact strings. Constrained Baseline is distinct from Baseline.
	H264Profiles             []string `json:"h264_profiles"`
	HevcProfiles             []string `json:"hevc_profiles"`
	ProgressiveOnly          bool     `json:"progressive_only"`
	UnknownScanIsProgressive bool     `json:"unknown_scan_is_progressive"`
}

// Provenance Derived on every analysis, never set by a user. `modified_since_transcode`
// means something rewrote a file Codarr produced.
type Provenance string

// QueueState defines model for QueueState.
type QueueState struct {
	AwaitingStreamEnd []AwaitingStreamEnd `json:"awaiting_stream_end"`

	// Depth Jobs in queued.
	Depth  int  `json:"depth"`
	Paused bool `json:"paused"`

	// Queued In execution order.
	Queued  []JobSummary `json:"queued"`
	Running *JobSummary  `json:"running,omitempty"`
}

// Readiness defines model for Readiness.
type Readiness struct {
	Checks []ReadinessCheck `json:"checks"`
	Ready  bool             `json:"ready"`
}

// ReadinessCheck defines model for ReadinessCheck.
type ReadinessCheck struct {
	Message *string `json:"message,omitempty"`

	// Name Example: database
	Name string `json:"name"`
	Ok   bool   `json:"ok"`
}

// RecheckAllRequest defines model for RecheckAllRequest.
type RecheckAllRequest struct {
	// Confirm False re-probes and re-plans but queues nothing.
	Confirm bool `json:"confirm"`
}

// RecheckResult defines model for RecheckResult.
type RecheckResult struct {
	ByPlanKind PlanKindBreakdown `json:"by_plan_kind"`

	// Count Files that no longer match the current policy, so would be queued.
	Count int `json:"count"`

	// DryRun True when confirm was false; nothing was queued.
	DryRun bool `json:"dry_run"`

	// Examined Files re-probed and re-planned.
	Examined int `json:"examined"`

	// MediaFileIds The files behind `count`, so the confirmation can name them.
	MediaFileIds *[]int64 `json:"media_file_ids,omitempty"`

	// QueuedJobIds Empty on a dry run.
	QueuedJobIds []int64 `json:"queued_job_ids"`
}

// RecheckSelectedRequest Supply either ids or filter, never both. An empty body selects nothing rather than everything, so a mis-sent request cannot queue the library.
type RecheckSelectedRequest struct {
	Confirm bool `json:"confirm"`

	// Filter The same filter the library table applies, so "select all matching filter" (plan.md 18.2) does not mean shipping every matching id over the wire. A 40k-file selection is one filter object, not 40k integers.
	Filter *MediaFilter `json:"filter,omitempty"`
	Ids    *[]int64     `json:"ids,omitempty"`
}

// ResolvePathRequest defines model for ResolvePathRequest.
type ResolvePathRequest struct {
	// Path A local path as Codarr sees it.
	Path string `json:"path"`
}

// ResolvePathResult defines model for ResolvePathResult.
type ResolvePathResult struct {
	LocalPath string `json:"local_path"`
	MappingId *int64 `json:"mapping_id,omitempty"`
	Matched   bool   `json:"matched"`

	// RemotePath Equal to local_path when no mapping matched.
	RemotePath string `json:"remote_path"`
}

// Root defines model for Root.
type Root struct {
	// ArrInstanceId Null means files here are processed but nothing is notified.
	ArrInstanceId   *int64    `json:"arr_instance_id,omitempty"`
	ArrInstanceName *string   `json:"arr_instance_name,omitempty"`
	CreatedAt       time.Time `json:"created_at"`
	Enabled         bool      `json:"enabled"`
	Id              int64     `json:"id"`

	// Imported Created by import-roots rather than by hand.
	Imported       bool   `json:"imported"`
	MediaFileCount *int   `json:"media_file_count,omitempty"`
	Path           string `json:"path"`
}

// RootConflict defines model for RootConflict.
type RootConflict struct {
	OwningArrInstanceId   int64  `json:"owning_arr_instance_id"`
	OwningArrInstanceName string `json:"owning_arr_instance_name"`
	Path                  string `json:"path"`
}

// RootCreate defines model for RootCreate.
type RootCreate struct {
	ArrInstanceId *int64 `json:"arr_instance_id,omitempty"`
	Enabled       *bool  `json:"enabled,omitempty"`
	Path          string `json:"path"`
}

// ScanStarted defines model for ScanStarted.
type ScanStarted struct {
	RootId    int64     `json:"root_id"`
	StartedAt time.Time `json:"started_at"`
}

// ScanType Unknown or absent field_order counts as progressive.
type ScanType string

// Settings defines model for Settings.
type Settings struct {
	// FullHashEnabled Compute a whole-file hash at promotion as well (plan.md 12.2).
	FullHashEnabled bool `json:"full_hash_enabled"`

	// PrioritiseQuickJobs Give remux and audio_only a better default priority than full.
	PrioritiseQuickJobs bool `json:"prioritise_quick_jobs"`

	// QsvDevice Example: /dev/dri/renderD128
	QsvDevice   string `json:"qsv_device"`
	QueuePaused bool   `json:"queue_paused"`

	// ScanCron Example: 0 4 * * *
	ScanCron    string `json:"scan_cron"`
	ScanEnabled bool   `json:"scan_enabled"`

	// ScanRateLimitFps Files per second the scheduled walk is allowed to stat.
	ScanRateLimitFps int `json:"scan_rate_limit_fps"`

	// TempDir Staging fallback when the destination filesystem cannot hold the output.
	TempDir   string    `json:"temp_dir"`
	UpdatedAt time.Time `json:"updated_at"`
}

// SettingsUpdate defines model for SettingsUpdate.
type SettingsUpdate struct {
	FullHashEnabled     bool   `json:"full_hash_enabled"`
	PrioritiseQuickJobs bool   `json:"prioritise_quick_jobs"`
	QsvDevice           string `json:"qsv_device"`
	ScanCron            string `json:"scan_cron"`
	ScanEnabled         bool   `json:"scan_enabled"`
	ScanRateLimitFps    int    `json:"scan_rate_limit_fps"`
	TempDir             string `json:"temp_dir"`
}

// SizeTransform defines model for SizeTransform.
type SizeTransform struct {
	AfterBytes  int64 `json:"after_bytes"`
	BeforeBytes int64 `json:"before_bytes"`
}

// SpaceSweepCandidate defines model for SpaceSweepCandidate.
type SpaceSweepCandidate struct {
	CurrentBytes            int64   `json:"current_bytes"`
	CurrentVideoBitrateKbps *int    `json:"current_video_bitrate_kbps,omitempty"`
	Filename                string  `json:"filename"`
	MediaFileId             int64   `json:"media_file_id"`
	Path                    string  `json:"path"`
	ProjectedBytes          int64   `json:"projected_bytes"`
	ProjectedSavingBytes    int64   `json:"projected_saving_bytes"`
	ProjectedSavingPct      float64 `json:"projected_saving_pct"`
	TargetVideoBitrateKbps  *int    `json:"target_video_bitrate_kbps,omitempty"`
	VideoCodec              *string `json:"video_codec,omitempty"`
}

// SpaceSweepPreview defines model for SpaceSweepPreview.
type SpaceSweepPreview struct {
	ByPlanKind PlanKindBreakdown     `json:"by_plan_kind"`
	Candidates []SpaceSweepCandidate `json:"candidates"`

	// Count Files that clear the policy saving threshold.
	Count        int   `json:"count"`
	CurrentBytes int64 `json:"current_bytes"`

	// Examined Files that matched the bitrate filter and were sample-probed.
	Examined int `json:"examined"`

	// Irreversible Always true. The confirmation must say so plainly.
	Irreversible         bool    `json:"irreversible"`
	ProjectedBytes       int64   `json:"projected_bytes"`
	ProjectedSavingBytes int64   `json:"projected_saving_bytes"`
	ProjectedSavingPct   float64 `json:"projected_saving_pct"`
}

// SpaceSweepRunRequest defines model for SpaceSweepRunRequest.
type SpaceSweepRunRequest struct {
	// Confirm Must be true. False is rejected with 400.
	Confirm bool `json:"confirm"`

	// MediaFileIds Restricts the run to these files, which is how the UI runs exactly
	// what the preview showed. Omitted means every current candidate.
	MediaFileIds *[]int64 `json:"media_file_ids,omitempty"`
}

// SpaceSweepRunResult defines model for SpaceSweepRunResult.
type SpaceSweepRunResult struct {
	ByPlanKind           PlanKindBreakdown `json:"by_plan_kind"`
	Count                int               `json:"count"`
	ProjectedSavingBytes int64             `json:"projected_saving_bytes"`
	QueuedJobIds         []int64           `json:"queued_job_ids"`
}

// Stats defines model for Stats.
type Stats struct {
	AvgSavingPct *float64 `json:"avg_saving_pct,omitempty"`
	BytesIn      int64    `json:"bytes_in"`
	BytesOut     int64    `json:"bytes_out"`

	// BytesSaved Can be negative; an AV1 source re-encoded to HEVC usually grows.
	BytesSaved    int64 `json:"bytes_saved"`
	EncodeSeconds int64 `json:"encode_seconds"`
	FilesDone     int   `json:"files_done"`
	FilesFailed   int   `json:"files_failed"`
	FilesIgnored  int   `json:"files_ignored"`
	FilesMissing  int   `json:"files_missing"`
	FilesPending  int   `json:"files_pending"`
	FilesSkipped  int   `json:"files_skipped"`
	FilesTotal    int   `json:"files_total"`
	JobsDone      int   `json:"jobs_done"`
	JobsFailed    int   `json:"jobs_failed"`
}

// StreamPlan The decision for one source stream plus where it lands in the output.
// Both indices are carried on purpose: ffmpeg's -c:a:N, -b:a:N,
// -disposition:a:N and -bsf:v:N all address the OUTPUT position
// (plan.md 14.2).
type StreamPlan struct {
	Comment bool `json:"comment"`

	// Decision What happens to one stream. `convert` is subtitles only.
	Decision Decision `json:"decision"`
	Default  bool     `json:"default"`
	Forced   bool     `json:"forced"`
	Language *string  `json:"language,omitempty"`

	// OutputIndex Null for a dropped stream.
	OutputIndex      *int       `json:"output_index"`
	Reason           string     `json:"reason"`
	SourceIndex      int        `json:"source_index"`
	TargetBitrateBps *int       `json:"target_bitrate_bps,omitempty"`
	TargetChannels   *int       `json:"target_channels,omitempty"`
	TargetCodec      *string    `json:"target_codec,omitempty"`
	Title            *string    `json:"title,omitempty"`
	Type             StreamType `json:"type"`
	VisualImpaired   bool       `json:"visual_impaired"`
}

// StreamType defines model for StreamType.
type StreamType string

// SubtitleState defines model for SubtitleState.
type SubtitleState struct {
	Codec  string `json:"codec"`
	Forced bool   `json:"forced"`
}

// SubtitleSummary defines model for SubtitleSummary.
type SubtitleSummary struct {
	Codec    string `json:"codec"`
	Forced   bool   `json:"forced"`
	Language string `json:"language"`
}

// SubtitleTransform defines model for SubtitleTransform.
type SubtitleTransform struct {
	// Action What happens to one stream. `convert` is subtitles only.
	Action   Decision       `json:"action"`
	After    *SubtitleState `json:"after"`
	Before   *SubtitleState `json:"before"`
	Language string         `json:"language"`

	// OutputIndex Null for a dropped stream.
	OutputIndex *int    `json:"output_index"`
	Reason      *string `json:"reason,omitempty"`
	SourceIndex int     `json:"source_index"`
}

// TestResult defines model for TestResult.
type TestResult struct {
	Message       string    `json:"message"`
	Ok            bool      `json:"ok"`
	ServerName    *string   `json:"server_name,omitempty"`
	ServerVersion *string   `json:"server_version,omitempty"`
	TestedAt      time.Time `json:"tested_at"`
}

// TransformRecord The before/after history for one job (plan.md 17.2). Written at enqueue
// with `after` holding the plan, updated at completion with `after` holding
// what an ffprobe of the real output measured. One schema serves both,
// which is what lets the UI render queued and completed items with the same
// component. Never deleted.
type TransformRecord struct {
	Attachments     BeforeAfterInt    `json:"attachments"`
	Audio           []AudioTransform  `json:"audio"`
	Chapters        BeforeAfterInt    `json:"chapters"`
	Container       BeforeAfterString `json:"container"`
	DurationSeconds DurationTransform `json:"duration_seconds"`

	// OutputIdentity Written at promotion, after the mtime restore. The immutable record of
	// what Codarr actually produced; the media row's copy is the mutable
	// current-state view, and the two diverging is the signal that something
	// rewrote the file.
	OutputIdentity *OutputIdentity     `json:"output_identity"`
	Size           SizeTransform       `json:"size"`
	Subtitles      []SubtitleTransform `json:"subtitles"`
	Video          VideoTransform      `json:"video"`
}

// VerifyIntegrityRequest defines model for VerifyIntegrityRequest.
type VerifyIntegrityRequest struct {
	Ids []int64 `json:"ids"`
}

// Version defines model for Version.
type Version struct {
	BuiltAt       time.Time `json:"built_at"`
	Commit        string    `json:"commit"`
	FfmpegVersion *string   `json:"ffmpeg_version,omitempty"`
	GoVersion     string    `json:"go_version"`

	// PolicyHash Hash of the compiled-in policy; changing it makes tagged files eligible again.
	PolicyHash *string `json:"policy_hash,omitempty"`
	Version    string  `json:"version"`
}

// VideoState defines model for VideoState.
type VideoState struct {
	// BitrateKbps Null on the predicted side of a full job until the sample probe has
	// run; the UI shows "calculating" (plan.md 17.2).
	BitrateKbps *int    `json:"bitrate_kbps"`
	Codec       string  `json:"codec"`
	Fps         float64 `json:"fps"`
	Hdr         bool    `json:"hdr"`
	Height      int     `json:"height"`
	Level       string  `json:"level"`
	PixFmt      string  `json:"pix_fmt"`
	Profile     string  `json:"profile"`

	// Scan Unknown or absent field_order counts as progressive.
	Scan  ScanType `json:"scan"`
	Width int      `json:"width"`
}

// VideoTransform defines model for VideoTransform.
type VideoTransform struct {
	// Action What happens to one stream. `convert` is subtitles only.
	Action Decision    `json:"action"`
	After  *VideoState `json:"after"`
	Before *VideoState `json:"before"`
	Reason string      `json:"reason"`
}

// WebhookAck defines model for WebhookAck.
type WebhookAck struct {
	JobId       *int64 `json:"job_id,omitempty"`
	MediaFileId *int64 `json:"media_file_id,omitempty"`
	Message     string `json:"message"`
	Received    bool   `json:"received"`
}

// ID defines model for ID.
type ID = int64

// PinID defines model for PinID.
type PinID = int64

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	// Level Minimum level, inclusive.
	Level    *EventLevel `form:"level,omitempty" json:"level,omitempty"`
	Category *string     `form:"category,omitempty" json:"category,omitempty"`

	// SinceId Return events with a strictly greater id.
	SinceId *int64 `form:"since_id,omitempty" json:"since_id,omitempty"`
	Limit   *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	State       *JobState `form:"state,omitempty" json:"state,omitempty"`
	MediaFileId *int64    `form:"media_file_id,omitempty" json:"media_file_id,omitempty"`

	// Page One-based.
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListMediaParams defines parameters for ListMedia.
type ListMediaParams struct {
	// Q Substring match on the path.
	Q        *string      `form:"q,omitempty" json:"q,omitempty"`
	Status   *MediaStatus `form:"status,omitempty" json:"status,omitempty"`
	PlanKind *PlanKind    `form:"plan_kind,omitempty" json:"plan_kind,omitempty"`

	// VideoCodec ffprobe codec name, matched exactly.
	VideoCodec    *string     `form:"video_codec,omitempty" json:"video_codec,omitempty"`
	ArrInstanceId *int64      `form:"arr_instance_id,omitempty" json:"arr_instance_id,omitempty"`
	Provenance    *Provenance `form:"provenance,omitempty" json:"provenance,omitempty"`

	// Sort A `-` prefix reverses the order.
	Sort *MediaSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page One-based.
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// CreateArrInstanceJSONRequestBody defines body for CreateArrInstance for application/json ContentType.
type CreateArrInstanceJSONRequestBody = ArrInstanceCreate

// UpdateArrInstanceJSONRequestBody defines body for UpdateArrInstance for application/json ContentType.
type UpdateArrInstanceJSONRequestBody = ArrInstanceUpdate

// RecheckAllMediaJSONRequestBody defines body for RecheckAllMedia for application/json ContentType.
type RecheckAllMediaJSONRequestBody = RecheckAllRequest

// RecheckSelectedMediaJSONRequestBody defines body for RecheckSelectedMedia for application/json ContentType.
type RecheckSelectedMediaJSONRequestBody = RecheckSelectedRequest

// VerifyMediaIntegrityBulkJSONRequestBody defines body for VerifyMediaIntegrityBulk for application/json ContentType.
type VerifyMediaIntegrityBulkJSONRequestBody = VerifyIntegrityRequest

// UpdatePlexJSONRequestBody defines body for UpdatePlex for application/json ContentType.
type UpdatePlexJSONRequestBody = PlexConfigUpdate

// ResolvePlexPathJSONRequestBody defines body for ResolvePlexPath for application/json ContentType.
type ResolvePlexPathJSONRequestBody = ResolvePathRequest

// CreateRootJSONRequestBody defines body for CreateRoot for application/json ContentType.
type CreateRootJSONRequestBody = RootCreate

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = SettingsUpdate

// RunSpaceSweepJSONRequestBody defines body for RunSpaceSweep for application/json ContentType.
type RunSpaceSweepJSONRequestBody = SpaceSweepRunRequest

// ReceiveArrWebhookJSONRequestBody defines body for ReceiveArrWebhook for application/json ContentType.
type ReceiveArrWebhookJSONRequestBody = ArrWebhookPayload

// Getter for additional properties for ArrWebhookEpisode. Returns the specified
// element and whether it was found
func (a ArrWebhookEpisode) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ArrWebhookEpisode
func (a *ArrWebhookEpisode) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ArrWebhookEpisode to handle AdditionalProperties
func (a *ArrWebhookEpisode) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["episodeNumber"]; found {
		err = json.Unmarshal(raw, &a.EpisodeNumber)
		if err != nil {
			return fmt.Errorf("error reading 'episodeNumber': %w", err)
		}
		delete(object, "episodeNumber")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["seasonNumber"]; found {
		err = json.Unmarshal(raw, &a.SeasonNumber)
		if err != nil {
			return fmt.Errorf("error reading 'seasonNumber': %w", err)
		}
		delete(object, "seasonNumber")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ArrWebhookEpisode to handle AdditionalProperties
func (a ArrWebhookEpisode) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.EpisodeNumber != nil {
		object["episodeNumber"], err = json.Marshal(a.EpisodeNumber)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'episodeNumber': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.SeasonNumber != nil {
		object["seasonNumber"], err = json.Marshal(a.SeasonNumber)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'seasonNumber': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ArrWebhookEpisodeFile. Returns the specified
// element and whether it was found
func (a ArrWebhookEpisodeFile) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ArrWebhookEpisodeFile
func (a *ArrWebhookEpisodeFile) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ArrWebhookEpisodeFile to handle AdditionalProperties
func (a *ArrWebhookEpisodeFile) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["path"]; found {
		err = json.Unmarshal(raw, &a.Path)
		if err != nil {
			return fmt.Errorf("error reading 'path': %w", err)
		}
		delete(object, "path")
	}

	if raw, found := object["relativePath"]; found {
		err = json.Unmarshal(raw, &a.RelativePath)
		if err != nil {
			return fmt.Errorf("error reading 'relativePath': %w", err)
		}
		delete(object, "relativePath")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ArrWebhookEpisodeFile to handle AdditionalProperties
func (a ArrWebhookEpisodeFile) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Path != nil {
		object["path"], err = json.Marshal(a.Path)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'path': %w", err)
		}
	}

	if a.RelativePath != nil {
		object["relativePath"], err = json.Marshal(a.RelativePath)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'relativePath': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ArrWebhookMovie. Returns the specified
// element and whether it was found
func (a ArrWebhookMovie) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ArrWebhookMovie
func (a *ArrWebhookMovie) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ArrWebhookMovie to handle AdditionalProperties
func (a *ArrWebhookMovie) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["folderPath"]; found {
		err = json.Unmarshal(raw, &a.FolderPath)
		if err != nil {
			return fmt.Errorf("error reading 'folderPath': %w", err)
		}
		delete(object, "folderPath")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ArrWebhookMovie to handle AdditionalProperties
func (a ArrWebhookMovie) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.FolderPath != nil {
		object["folderPath"], err = json.Marshal(a.FolderPath)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'folderPath': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ArrWebhookMovieFile. Returns the specified
// element and whether it was found
func (a ArrWebhookMovieFile) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ArrWebhookMovieFile
func (a *ArrWebhookMovieFile) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ArrWebhookMovieFile to handle AdditionalProperties
func (a *ArrWebhookMovieFile) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["path"]; found {
		err = json.Unmarshal(raw, &a.Path)
		if err != nil {
			return fmt.Errorf("error reading 'path': %w", err)
		}
		delete(object, "path")
	}

	if raw, found := object["relativePath"]; found {
		err = json.Unmarshal(raw, &a.RelativePath)
		if err != nil {
			return fmt.Errorf("error reading 'relativePath': %w", err)
		}
		delete(object, "relativePath")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ArrWebhookMovieFile to handle AdditionalProperties
func (a ArrWebhookMovieFile) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Path != nil {
		object["path"], err = json.Marshal(a.Path)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'path': %w", err)
		}
	}

	if a.RelativePath != nil {
		object["relativePath"], err = json.Marshal(a.RelativePath)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'relativePath': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ArrWebhookPayload. Returns the specified
// element and whether it was found
func (a ArrWebhookPayload) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ArrWebhookPayload
func (a *ArrWebhookPayload) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ArrWebhookPayload to handle AdditionalProperties
func (a *ArrWebhookPayload) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["episodeFile"]; found {
		err = json.Unmarshal(raw, &a.EpisodeFile)
		if err != nil {
			return fmt.Errorf("error reading 'episodeFile': %w", err)
		}
		delete(object, "episodeFile")
	}

	if raw, found := object["episodes"]; found {
		err = json.Unmarshal(raw, &a.Episodes)
		if err != nil {
			return fmt.Errorf("error reading 'episodes': %w", err)
		}
		delete(object, "episodes")
	}

	if raw, found := object["eventType"]; found {
		err = json.Unmarshal(raw, &a.EventType)
		if err != nil {
			return fmt.Errorf("error reading 'eventType': %w", err)
		}
		delete(object, "eventType")
	}

	if raw, found := object["isUpgrade"]; found {
		err = json.Unmarshal(raw, &a.IsUpgrade)
		if err != nil {
			return fmt.Errorf("error reading 'isUpgrade': %w", err)
		}
		delete(object, "isUpgrade")
	}

	if raw, found := object["movie"]; found {
		err = json.Unmarshal(raw, &a.Movie)
		if err != nil {
			return fmt.Errorf("error reading 'movie': %w", err)
		}
		delete(object, "movie")
	}

	if raw, found := object["movieFile"]; found {
		err = json.Unmarshal(raw, &a.MovieFile)
		if err != nil {
			return fmt.Errorf("error reading 'movieFile': %w", err)
		}
		delete(object, "movieFile")
	}

	if raw, found := object["series"]; found {
		err = json.Unmarshal(raw, &a.Series)
		if err != nil {
			return fmt.Errorf("error reading 'series': %w", err)
		}
		delete(object, "series")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ArrWebhookPayload to handle AdditionalProperties
func (a ArrWebhookPayload) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.EpisodeFile != nil {
		object["episodeFile"], err = json.Marshal(a.EpisodeFile)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'episodeFile': %w", err)
		}
	}

	if a.Episodes != nil {
		object["episodes"], err = json.Marshal(a.Episodes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'episodes': %w", err)
		}
	}

	object["eventType"], err = json.Marshal(a.EventType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'eventType': %w", err)
	}

	if a.IsUpgrade != nil {
		object["isUpgrade"], err = json.Marshal(a.IsUpgrade)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isUpgrade': %w", err)
		}
	}

	if a.Movie != nil {
		object["movie"], err = json.Marshal(a.Movie)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'movie': %w", err)
		}
	}

	if a.MovieFile != nil {
		object["movieFile"], err = json.Marshal(a.MovieFile)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'movieFile': %w", err)
		}
	}

	if a.Series != nil {
		object["series"], err = json.Marshal(a.Series)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'series': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ArrWebhookSeries. Returns the specified
// element and whether it was found
func (a ArrWebhookSeries) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ArrWebhookSeries
func (a *ArrWebhookSeries) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ArrWebhookSeries to handle AdditionalProperties
func (a *ArrWebhookSeries) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["path"]; found {
		err = json.Unmarshal(raw, &a.Path)
		if err != nil {
			return fmt.Errorf("error reading 'path': %w", err)
		}
		delete(object, "path")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ArrWebhookSeries to handle AdditionalProperties
func (a ArrWebhookSeries) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Path != nil {
		object["path"], err = json.Marshal(a.Path)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'path': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
